#![allow(improper_ctypes_definitions)]
#![allow(unused)]

use std::{
    any::Any,
    cell::RefCell,
    collections::HashMap,
    ops::{Deref, DerefMut},
    rc::Rc,
    str::FromStr,
};

use num_bigint::BigInt;
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use smallvec::{smallvec, SmallVec};
use uuid::Uuid;

use perro_core::prelude::*;

//=======================================;
// Auto Generated by Perro Transpiler [Any further edits to this file will be overwritten on next transile];
//=======================================;

// ========================================================================
// ScriptsCamPup - Main Script Structure
// ========================================================================

pub struct ScriptsCamPupScript {
    node: Camera3D,
}

// ========================================================================
// ScriptsCamPup - Creator Function (FFI Entry Point)
// ========================================================================

#[unsafe(no_mangle)]
pub extern "C" fn scripts_cam_pup_create_script() -> *mut dyn ScriptObject {
    let node = Camera3D::new("ScriptsCamPup");

    Box::into_raw(Box::new(ScriptsCamPupScript {
        node,
    })) as *mut dyn ScriptObject
}

// ========================================================================
// ScriptsCamPup - Script Init & Update Implementation
// ========================================================================

impl Script for ScriptsCamPupScript {
    fn init(&mut self, api: &mut ScriptApi<'_>) {
    }

    fn update(&mut self, api: &mut ScriptApi<'_>) {
        self.node = api.get_node_clone::<Camera3D>(self.node.id);
        self.node.transform.position.x += (1f32 * api.Time.get_delta());

        api.merge_nodes(vec![self.node.clone().to_scene_node()]);
    }

}


impl ScriptObject for ScriptsCamPupScript {
    fn set_node_id(&mut self, id: Uuid) {
        self.node.id = id;
    }

    fn get_node_id(&self) -> Uuid {
        self.node.id
    }

    fn get_var(&self, var_id: u64) -> Option<Value> {
            VAR_GET_TABLE.get(&var_id).and_then(|f| f(self))
    }

    fn set_var(&mut self, var_id: u64, val: Value) -> Option<()> {
        VAR_SET_TABLE.get(&var_id).and_then(|f| f(self, val))
    }

    fn apply_exposed(&mut self, hashmap: &HashMap<u64, Value>) {
        for (var_id, val) in hashmap.iter() {
            if let Some(f) = VAR_APPLY_TABLE.get(var_id) {
                f(self, val);
            }
        }
    }

    fn call_function(&mut self, id: u64, api: &mut ScriptApi<'_>, params: &SmallVec<[Value; 3]>) {
        if let Some(f) = DISPATCH_TABLE.get(&id) {
            f(self, params, api);
        }
    }
}

// =========================== Static PHF Dispatch Tables ===========================

static VAR_GET_TABLE: phf::Map<u64, fn(&ScriptsCamPupScript) -> Option<Value>> = phf::phf_map! {
};

static VAR_SET_TABLE: phf::Map<u64, fn(&mut ScriptsCamPupScript, Value) -> Option<()>> = phf::phf_map! {
};

static VAR_APPLY_TABLE: phf::Map<u64, fn(&mut ScriptsCamPupScript, &Value)> = phf::phf_map! {
};

static DISPATCH_TABLE: phf::Map<u64, fn(&mut ScriptsCamPupScript, &[Value], &mut ScriptApi<'_>)> = phf::phf_map! {
};