#![allow(improper_ctypes_definitions)]
#![allow(unused)]

use std::{
    any::Any,
    cell::RefCell,
    collections::HashMap,
    ops::{Deref, DerefMut},
    rc::Rc,
    str::FromStr,
};

use num_bigint::BigInt;
use phf::{phf_map, Map};
use rust_decimal::Decimal;
use rust_decimal::prelude::{FromPrimitive, ToPrimitive};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use smallvec::{smallvec, SmallVec};
use uuid::Uuid;

use perro_core::prelude::*;

//=======================================;
// Auto Generated by Perro Transpiler [Any further edits to this file will be overwritten on next transile];
//=======================================;

// ========================================================================
// ScriptsCsCs - Main Script Structure
// ========================================================================

static MEMBER_TO_ATTRIBUTES_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
    "speed" => &["ThisIsAnAttribute"],
    "TakeDamage()" => &["DamageFunc"],
};

static ATTRIBUTE_TO_MEMBERS_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
    "ThisIsAnAttribute" => &["speed"],
    "DamageFunc" => &["TakeDamage()"],
};

pub struct ScriptsCsCsScript {
    id: Uuid,
    t_var_speed: f32,
    t_var_health: i32,
}

// ========================================================================
// ScriptsCsCs - Creator Function (FFI Entry Point)
// ========================================================================

#[unsafe(no_mangle)]
pub extern "C" fn scripts_cs_cs_create_script() -> *mut dyn ScriptObject {
    let id = Uuid::nil(); // Will be set when attached to node
    let speed = 0.0f32;
    let health = 0i32;

    Box::into_raw(Box::new(ScriptsCsCsScript {
        id,
        t_var_speed,
        t_var_health,
    })) as *mut dyn ScriptObject
}

// ========================================================================
// ScriptsCsCs - Script Init & Update Implementation
// ========================================================================

impl Script for ScriptsCsCsScript {
    fn init(&mut self, api: &mut ScriptApi<'_>) {
        self.t_var_speed = 10.0f32;
        api.print("Player initialized!");
    }

    fn update(&mut self, api: &mut ScriptApi<'_>) {
        self.TakeDamage(24i32, api);
    }

}

// ========================================================================
// ScriptsCsCs - Script-Defined Methods
// ========================================================================

impl ScriptsCsCsScript {
    fn TakeDamage(&mut self, mut amount: i32, api: &mut ScriptApi<'_>) {
        self.health -= t_var_amount;
        api.print("Took damage!");
    }

}


impl ScriptObject for ScriptsCsCsScript {
    fn set_id(&mut self, id: Uuid) {
        self.id = id;
    }

    fn get_id(&self) -> Uuid {
        self.id
    }

    fn get_var(&self, var_id: u64) -> Option<Value> {
        VAR_GET_TABLE.get(&var_id).and_then(|f| f(self))
    }

    fn set_var(&mut self, var_id: u64, val: Value) -> Option<()> {
        VAR_SET_TABLE.get(&var_id).and_then(|f| f(self, val))
    }

    fn apply_exposed(&mut self, hashmap: &HashMap<u64, Value>) {
        for (var_id, val) in hashmap.iter() {
            if let Some(f) = VAR_APPLY_TABLE.get(var_id) {
                f(self, val);
            }
        }
    }

    fn call_function(
        &mut self,
        id: u64,
        api: &mut ScriptApi<'_>,
        params: &[Value],
    ) {
        if let Some(f) = DISPATCH_TABLE.get(&id) {
            f(self, params, api);
        }
    }

    // Attributes

    fn attributes_of(&self, member: &str) -> Vec<String> {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn members_with(&self, attribute: &str) -> Vec<String> {
        ATTRIBUTE_TO_MEMBERS_MAP
            .get(attribute)
            .map(|members| members.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn has_attribute(&self, member: &str, attribute: &str) -> bool {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().any(|a| *a == attribute))
            .unwrap_or(false)
    }
    
    fn script_flags(&self) -> ScriptFlags {
        ScriptFlags::new(3)
    }
}

// =========================== Static PHF Dispatch Tables ===========================

static VAR_GET_TABLE: phf::Map<u64, fn(&ScriptsCsCsScript) -> Option<Value>> =
    phf::phf_map! {
        2486349329025994304u64 => |script: &ScriptsCsCsScript| -> Option<Value> {
                        Some(json!(script.speed))
                    },
        9181103189905877455u64 => |script: &ScriptsCsCsScript| -> Option<Value> {
                        Some(json!(script.health))
                    },

    };

static VAR_SET_TABLE: phf::Map<u64, fn(&mut ScriptsCsCsScript, Value) -> Option<()>> =
    phf::phf_map! {
        2486349329025994304u64 => |script: &mut ScriptsCsCsScript, val: Value| -> Option<()> {
                            if let Some(v) = val.as_f64() {
                                script.speed = v as f32;
                                return Some(());
                            }
                            None
                        },
        9181103189905877455u64 => |script: &mut ScriptsCsCsScript, val: Value| -> Option<()> {
                            if let Some(v) = val.as_i64() {
                                script.health = v as i32;
                                return Some(());
                            }
                            None
                        },

    };

static VAR_APPLY_TABLE: phf::Map<u64, fn(&mut ScriptsCsCsScript, &Value)> =
    phf::phf_map! {

    };

static DISPATCH_TABLE: phf::Map<
    u64,
    fn(&mut ScriptsCsCsScript, &[Value], &mut ScriptApi<'_>),
> = phf::phf_map! {
        1329396982928406835u64 => | script: &mut ScriptsCsCsScript, params: &[Value], api: &mut ScriptApi<'_>| {
let t_var_amount = params.get(0)
                            .and_then(|v| v.as_i64().or_else(|| v.as_f64().map(|f| f as i64)))
                            .unwrap_or_default() as i32;
            script.TakeDamage(t_var_amount, api);
        },

    };
