#![allow(improper_ctypes_definitions)]
#![allow(unused)]

use std::any::Any;
use std::collections::HashMap;
use smallvec::{SmallVec, smallvec};
use serde_json::{Value, json};
use serde::{Serialize, Deserialize};
use uuid::Uuid;
use std::ops::{Deref, DerefMut};
use rust_decimal::{Decimal, prelude::*};
use num_bigint::BigInt;
use std::str::FromStr;
use std::{rc::Rc, cell::RefCell};

use perro_core::prelude::*;

//=======================================;
// Auto Generated by Perro Transpiler [Any further edits to this file will be overwritten on next transile];
//=======================================;

// ========================================================================
// ScriptsTestPup - Main Script Structure
// ========================================================================

pub struct ScriptsTestPupScript {
    node: Node2D,
}

// ========================================================================
// ScriptsTestPup - Creator Function (FFI Entry Point)
// ========================================================================

#[unsafe(no_mangle)]
pub extern "C" fn scripts_test_pup_create_script() -> *mut dyn ScriptObject {
    let node = Node2D::new("ScriptsTestPup");

    Box::into_raw(Box::new(ScriptsTestPupScript {
        node,
    })) as *mut dyn ScriptObject
}

// ========================================================================
// ScriptsTestPup - Script Init & Update Implementation
// ========================================================================

impl Script for ScriptsTestPupScript {
    fn init(&mut self, api: &mut ScriptApi<'_>) {
        self.bob(2f32, api, false);
    }

    fn update(&mut self, api: &mut ScriptApi<'_>) {
    }

}

// ========================================================================
// ScriptsTestPup - Script-Defined Methods
// ========================================================================

impl ScriptsTestPupScript {
    fn bob(&mut self, mut i: i32, api: &mut ScriptApi<'_>, external_call: bool) {
        api.print(&i);
    }

}


impl ScriptObject for ScriptsTestPupScript {
    fn set_node_id(&mut self, id: Uuid) {
        self.node.id = id;
    }

    fn get_node_id(&self) -> Uuid {
        self.node.id
    }

    fn get_var(&self, var_id: u64) -> Option<Value> {
            VAR_GET_TABLE.get(&var_id).and_then(|f| f(self))
    }

    fn set_var(&mut self, var_id: u64, val: Value) -> Option<()> {
        VAR_SET_TABLE.get(&var_id).and_then(|f| f(self, val))
    }

    fn apply_exposed(&mut self, hashmap: &HashMap<u64, Value>) {
        for (var_id, val) in hashmap.iter() {
            if let Some(f) = VAR_APPLY_TABLE.get(var_id) {
                f(self, val);
            }
        }
    }

    fn call_function(&mut self, id: u64, api: &mut ScriptApi<'_>, params: &SmallVec<[Value; 3]>) {
        if let Some(f) = DISPATCH_TABLE.get(&id) {
            f(self, params, api);
        }
    }
}

// =========================== Static PHF Dispatch Tables ===========================

static VAR_GET_TABLE: phf::Map<u64, fn(&ScriptsTestPupScript) -> Option<Value>> = phf::phf_map! {
};

static VAR_SET_TABLE: phf::Map<u64, fn(&mut ScriptsTestPupScript, Value) -> Option<()>> = phf::phf_map! {
};

static VAR_APPLY_TABLE: phf::Map<u64, fn(&mut ScriptsTestPupScript, &Value)> = phf::phf_map! {
};

static DISPATCH_TABLE: phf::Map<u64, fn(&mut ScriptsTestPupScript, &[Value], &mut ScriptApi<'_>)> = phf::phf_map! {
        21748447695211092u64 => | script: &mut ScriptsTestPupScript, params: &[Value], api: &mut ScriptApi<'_>| {
let i = params.get(0)
                            .and_then(|v| v.as_i64().or_else(|| v.as_f64().map(|f| f as i64)))
                            .unwrap_or_default() as i32;
            script.bob(i, api, true);
        },
};