// AUTO-GENERATED by perro_compiler. Do not edit by hand.

#[path = "scripts/script.rs"]
pub mod scripts_script_rs;

pub static SCRIPT_REGISTRY: &[(&str, &str)] = &[
    ("res://scripts/script.rs", "scripts_script_rs"),
];
