// Auto-generated by perro_compiler. Do not edit.
use phf::phf_map;
use perro_scene::{StaticNodeData, StaticNodeEntry, StaticScene, StaticSceneKey, StaticSceneValue};

const CHILDREN_RES___MAIN_SCN_0: &[StaticSceneKey] = &[
    StaticSceneKey("cube"),
    StaticSceneKey("camera"),
];
const FIELDS_RES___MAIN_SCN_0: &[(&str, StaticSceneValue)] = &[
    ("position", StaticSceneValue::Vec3 { x: 0.0, y: 0.0, z: 0.0 }),
];
const DATA_RES___MAIN_SCN_0: StaticNodeData = StaticNodeData { ty: "Node3D", fields: FIELDS_RES___MAIN_SCN_0, base: None };
const CHILDREN_RES___MAIN_SCN_1: &[StaticSceneKey] = &[
];
const FIELDS_RES___MAIN_SCN_1: &[(&str, StaticSceneValue)] = &[
    ("mesh", StaticSceneValue::Str("__cube__")),
];
const FIELDS_RES___MAIN_SCN_2: &[(&str, StaticSceneValue)] = &[
    ("position", StaticSceneValue::Vec3 { x: 0.0, y: 0.0, z: 0.0 }),
    ("rotation", StaticSceneValue::Vec4 { x: 0.0, y: 0.2826834, z: 0.1, w: 0.9238795 }),
];
const DATA_RES___MAIN_SCN_2: StaticNodeData = StaticNodeData { ty: "Node3D", fields: FIELDS_RES___MAIN_SCN_2, base: None };
const DATA_RES___MAIN_SCN_1: StaticNodeData = StaticNodeData { ty: "MeshInstance3D", fields: FIELDS_RES___MAIN_SCN_1, base: Some(&DATA_RES___MAIN_SCN_2) };
const CHILDREN_RES___MAIN_SCN_2: &[StaticSceneKey] = &[
];
const FIELDS_RES___MAIN_SCN_3: &[(&str, StaticSceneValue)] = &[
    ("active", StaticSceneValue::Bool(true)),
    ("zoom", StaticSceneValue::F32(1.0)),
];
const FIELDS_RES___MAIN_SCN_4: &[(&str, StaticSceneValue)] = &[
    ("position", StaticSceneValue::Vec3 { x: 0.0, y: 0.0, z: 5.0 }),
];
const DATA_RES___MAIN_SCN_4: StaticNodeData = StaticNodeData { ty: "Node3D", fields: FIELDS_RES___MAIN_SCN_4, base: None };
const DATA_RES___MAIN_SCN_3: StaticNodeData = StaticNodeData { ty: "Camera3D", fields: FIELDS_RES___MAIN_SCN_3, base: Some(&DATA_RES___MAIN_SCN_4) };
const NODES_RES___MAIN_SCN: &[StaticNodeEntry] = &[
    StaticNodeEntry { key: StaticSceneKey("main"), name: Some("Wod"), children: CHILDREN_RES___MAIN_SCN_0, parent: None, script: None, data: DATA_RES___MAIN_SCN_0 },
    StaticNodeEntry { key: StaticSceneKey("cube"), name: Some("Cube"), children: CHILDREN_RES___MAIN_SCN_1, parent: Some(StaticSceneKey("main")), script: None, data: DATA_RES___MAIN_SCN_1 },
    StaticNodeEntry { key: StaticSceneKey("camera"), name: Some("Camera"), children: CHILDREN_RES___MAIN_SCN_2, parent: Some(StaticSceneKey("main")), script: None, data: DATA_RES___MAIN_SCN_3 },
];

pub static SCENE_RES___MAIN_SCN: StaticScene = StaticScene { nodes: NODES_RES___MAIN_SCN, root: Some(StaticSceneKey("main")) };


pub static SCENE_MAP: phf::Map<&'static str, &'static StaticScene> = phf_map! {
    "res://main.scn" => &SCENE_RES___MAIN_SCN,
};

pub fn lookup_scene(path: &str) -> Option<&'static StaticScene> {
    SCENE_MAP.get(path).copied()
}
