#![allow(improper_ctypes_definitions)]
#![allow(unused)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]

use std::{
    any::Any,
    borrow::Cow,
    cell::RefCell,
    collections::HashMap,
    ops::{Deref, DerefMut},
    rc::Rc,
    str::FromStr,
};

use num_bigint::BigInt;
use phf::{phf_map, Map};
use rust_decimal::Decimal;
use rust_decimal::prelude::{FromPrimitive, ToPrimitive};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use smallvec::{smallvec, SmallVec};
use perro_core::{TextureID, NodeID, MaterialID, MeshID, LightID, UIElementID};

use perro_core::prelude::*;

//=======================================;
// Auto Generated by Perro Transpiler [Any further edits to this file will be overwritten on next transile];
//=======================================;

const __PERRO_SOURCE_FILE: &str = "test_syntax_edge.pup";

// ========================================================================
// PuptestsTypeTestsTestSyntaxEdgePup - Main Script Structure
// ========================================================================

static MEMBER_TO_ATTRIBUTES_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
};

static ATTRIBUTE_TO_MEMBERS_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
};

pub struct PuptestsTypeTestsTestSyntaxEdgePupScript {
    id: NodeID,
    __t_some_var: i32,
}

// ========================================================================
// PuptestsTypeTestsTestSyntaxEdgePup - Creator Function (FFI Entry Point)
// ========================================================================

#[unsafe(no_mangle)]
pub extern "C" fn puptests_type_tests_test_syntax_edge_pup_create_script() -> *mut dyn ScriptObject {
    let id = NodeID::nil(); // Will be set when attached to node
    let some_var = 42i32;

    Box::into_raw(Box::new(PuptestsTypeTestsTestSyntaxEdgePupScript {
        id,
        __t_some_var: some_var,
    })) as *mut dyn ScriptObject
}

// ========================================================================
// PuptestsTypeTestsTestSyntaxEdgePup - Script Init & Update Implementation
// ========================================================================

impl Script for PuptestsTypeTestsTestSyntaxEdgePupScript {
    fn init(&mut self, api: &mut ScriptApi<'_>) {
        let mut __t_a: i32 = 10i32;
        let mut __t_b: f32 = (__t_a as f32);
        let mut __t_c: i32 = (__t_b.round() as i32);
        let mut __t_s: String = __t_a.to_string();
        let mut __t_d: Decimal = (Decimal::from_str("123.456789").unwrap() as Decimal);
        let mut __t_bi: BigInt = (BigInt::from_str("1000000000000").unwrap() as BigInt);
        let mut __t_i64: i64 = (2_000_000i64 as i64);
        let mut __t_v: i32 = self.__t_some_var;
        let mut __t_r: i32 = self.__t_get_my_int(api);;
        self.__t_some_var = 99i32;
        let mut child_id: Option<NodeID> = api.get_child_by_name(self.id, String::from("Child").as_str());
        let mut __t_cv: Value = api.get_script_var_id(child_id.expect("Child node not found"), 17819110315924748471u64);
        let mut __t_cr: Value = api.call_function_id(child_id.expect("Child node not found"), 2789383857360210807u64, &[(json!(1.0f32) as Value)]);
    }

}

// ========================================================================
// PuptestsTypeTestsTestSyntaxEdgePup - Script-Defined Methods
// ========================================================================

impl PuptestsTypeTestsTestSyntaxEdgePupScript {
    fn __t_get_my_int(&mut self, api: &mut ScriptApi<'_>) -> i32 {
return 100i32;    0i32
    }

}


impl ScriptObject for PuptestsTypeTestsTestSyntaxEdgePupScript {
    fn set_id(&mut self, id: NodeID) {
        self.id = id;
    }

    fn get_id(&self) -> NodeID {
        self.id
    }

    fn get_var(&self, var_id: u64) -> Option<Value> {
        VAR_GET_TABLE.get(&var_id).and_then(|f| f(self))
    }

    fn set_var(&mut self, var_id: u64, val: Value) -> Option<()> {
        VAR_SET_TABLE.get(&var_id).and_then(|f| f(self, val))
    }

    fn apply_exposed(&mut self, hashmap: &HashMap<u64, Value>) {
        for (var_id, val) in hashmap.iter() {
            if let Some(f) = VAR_APPLY_TABLE.get(var_id) {
                f(self, val);
            }
        }
    }

    fn call_function(
        &mut self,
        id: u64,
        api: &mut ScriptApi<'_>,
        params: &[Value],
    ) -> Value {
        DISPATCH_TABLE.get(&id).map_or(Value::Null, |f| f(self, params, api))
    }

    // Attributes

    fn attributes_of(&self, member: &str) -> Vec<String> {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn members_with(&self, attribute: &str) -> Vec<String> {
        ATTRIBUTE_TO_MEMBERS_MAP
            .get(attribute)
            .map(|members| members.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn has_attribute(&self, member: &str, attribute: &str) -> bool {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().any(|a| *a == attribute))
            .unwrap_or(false)
    }
    
    fn script_flags(&self) -> ScriptFlags {
        ScriptFlags::new(1)
    }
}

// =========================== Static PHF Dispatch Tables ===========================

static VAR_GET_TABLE: phf::Map<u64, fn(&PuptestsTypeTestsTestSyntaxEdgePupScript) -> Option<Value>> =
    phf::phf_map! {
        71936255744524551u64 => |script: &PuptestsTypeTestsTestSyntaxEdgePupScript| -> Option<Value> {
                        Some(json!(script.__t_some_var))
                    },

    };

static VAR_SET_TABLE: phf::Map<u64, fn(&mut PuptestsTypeTestsTestSyntaxEdgePupScript, Value) -> Option<()>> =
    phf::phf_map! {
        71936255744524551u64 => |script: &mut PuptestsTypeTestsTestSyntaxEdgePupScript, val: Value| -> Option<()> {
                            if let Some(v) = val.as_i64() {
                                script.__t_some_var = v as i32;
                                return Some(());
                            }
                            None
                        },

    };

static VAR_APPLY_TABLE: phf::Map<u64, fn(&mut PuptestsTypeTestsTestSyntaxEdgePupScript, &Value)> =
    phf::phf_map! {

    };

static DISPATCH_TABLE: phf::Map<
    u64,
    fn(&mut PuptestsTypeTestsTestSyntaxEdgePupScript, &[Value], &mut ScriptApi<'_>) -> Value,
> = phf::phf_map! {
        3111815040097353864u64 => | script: &mut PuptestsTypeTestsTestSyntaxEdgePupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            json!(script.__t_get_my_int(api))
        },

    };
