#![allow(improper_ctypes_definitions)]
#![allow(unused)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]

use std::{
    any::Any,
    borrow::Cow,
    cell::RefCell,
    collections::HashMap,
    ops::{Deref, DerefMut},
    rc::Rc,
    str::FromStr,
};

use num_bigint::BigInt;
use phf::{phf_map, Map};
use rust_decimal::Decimal;
use rust_decimal::prelude::{FromPrimitive, ToPrimitive};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use smallvec::{smallvec, SmallVec};
use perro_core::{TextureID, NodeID, MaterialID, MeshID, LightID, UIElementID};

use perro_core::prelude::*;

//=======================================;
// Auto Generated by Perro Transpiler [Any further edits to this file will be overwritten on next transile];
//=======================================;

const __PERRO_SOURCE_FILE: &str = "test_resource_api.pup";

// ========================================================================
// PuptestsResourceTestsTestResourceApiPup - Main Script Structure
// ========================================================================

static MEMBER_TO_ATTRIBUTES_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
};

static ATTRIBUTE_TO_MEMBERS_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
};

pub struct PuptestsResourceTestsTestResourceApiPupScript {
    id: NodeID,
    __t_emit_count: i32,
}

// ========================================================================
// PuptestsResourceTestsTestResourceApiPup - Creator Function (FFI Entry Point)
// ========================================================================

#[unsafe(no_mangle)]
pub extern "C" fn puptests_resource_tests_test_resource_api_pup_create_script() -> *mut dyn ScriptObject {
    let id = NodeID::nil(); // Will be set when attached to node
    let emit_count = 0i32;

    Box::into_raw(Box::new(PuptestsResourceTestsTestResourceApiPupScript {
        id,
        __t_emit_count: emit_count,
    })) as *mut dyn ScriptObject
}

// ========================================================================
// PuptestsResourceTestsTestResourceApiPup - Script Init & Update Implementation
// ========================================================================

impl Script for PuptestsResourceTestsTestResourceApiPupScript {
    fn init(&mut self, api: &mut ScriptApi<'_>) {
        self.__t_test_texture(api);
        self.__t_test_mesh(api);
        self.__t_test_quaternion(api);
        self.__t_test_shape2d(api);
        self.__t_test_signal_new_connect_emit(api);
        self.__t_test_signal_emit_deferred(api);
        self.__t_test_array(api);
        self.__t_test_map(api);
    }

}

// ========================================================================
// PuptestsResourceTestsTestResourceApiPup - Script-Defined Methods
// ========================================================================

impl PuptestsResourceTestsTestResourceApiPupScript {
    fn __t_test_texture(&mut self, api: &mut ScriptApi<'_>) {
        let mut tex_id: Option<TextureID> = api.Texture.load("res://icon.png");
        let mut tex2_id: Option<TextureID> = api.Texture.preload("res://icon.png");
        let mut __t_w: u32 = api.Texture.get_width(tex_id);
        let mut __t_h: u32 = api.Texture.get_height(tex_id);
        let mut __t_sz: Vector2 = api.Texture.get_size(tex_id);
    }

    fn __t_test_mesh(&mut self, api: &mut ScriptApi<'_>) {
        let mut __t_mesh: Option<MeshID> = api.Mesh.load("res://mesh.obj");
        let mut __t_mesh2: Option<MeshID> = api.Mesh.preload("res://mesh.obj");
    }

    fn __t_test_quaternion(&mut self, api: &mut ScriptApi<'_>) {
        let mut __t_q: Quaternion = Quaternion::identity();
        let mut __t_q2: Quaternion = Quaternion::from_euler_degrees(0.0f32, 90.0f32, 0.0f32);
        let mut __t_euler: Vector3 = (__t_q2).as_euler();
        let mut __t_q3: Quaternion = (__t_q).rotate_x(45.0f32);
        let mut __t_q4: Quaternion = (__t_q).rotate_y(10.0f32);
        let mut __t_q5: Quaternion = (__t_q).rotate_z(5.0f32);
        let mut __t_q6: Quaternion = (__t_q).rotate_euler_degrees(1.0f32, 2.0f32, 3.0f32);
    }

    fn __t_test_shape2d(&mut self, api: &mut ScriptApi<'_>) {
        let mut __t_rect: Shape2D = Shape2D::Rectangle { width: 10.0f32, height: 20.0f32 };
        let mut __t_circle: Shape2D = Shape2D::Circle { radius: 5.0f32 };
        let mut __t_square: Shape2D = Shape2D::Square { size: 8.0f32 };
        let mut __t_tri: Shape2D = Shape2D::Triangle { base: 4.0f32, height: 6.0f32 };
    }

    fn __t_test_signal_new_connect_emit(&mut self, api: &mut ScriptApi<'_>) {
        let mut __t_sig: u64 = 12863628130621643238u64;
        api.connect_signal_id(12863628130621643238u64, self.id, 15891415482422161649u64);
        api.emit_signal_id(__t_sig, &[]);
        api.emit_signal_id(__t_sig, &[]);
    }

    fn __t_test_signal_emit_deferred(&mut self, api: &mut ScriptApi<'_>) {
        let mut __t_sig2: u64 = 6252300950692974454u64;
        api.connect_signal_id(6252300950692974454u64, self.id, 8539718162271983822u64);
        api.emit_signal_id_deferred(__t_sig2, &[]);
        api.emit_signal_id_deferred(__t_sig2, &[]);
    }

    fn __t_test_array(&mut self, api: &mut ScriptApi<'_>) {
        let mut __t_arr: Vec<Value> = Vec::new();
        __t_arr.push(json!(1f32));
        __t_arr.push(json!(String::from("two")));
        let mut __t_len = __t_arr.len();
        let mut __t_elem: Value = __t_arr.get(0u32 as usize).cloned().unwrap_or_default();
    }

    fn __t_test_map(&mut self, api: &mut ScriptApi<'_>) {
        let mut __t_m: HashMap<String, Value> = HashMap::new();
        __t_m.insert(String::from("key"), json!(String::from("value")));
        let mut __t_v: Value = __t_m.get(String::from("key").as_str()).cloned().unwrap_or_default();
        let mut __t_has: bool = __t_m.contains_key(String::from("key").as_str());
        let mut __t_mlen = __t_m["len"].clone();
    }

    fn __t_on_signal(&mut self, api: &mut ScriptApi<'_>) {
        self.__t_emit_count = (self.__t_emit_count + 1i32);
        api.print(String::from("signal received"));
    }

    fn __t_on_other_signal(&mut self, api: &mut ScriptApi<'_>) {
        api.print(String::from("other_signal received"));
    }

}


impl ScriptObject for PuptestsResourceTestsTestResourceApiPupScript {
    fn set_id(&mut self, id: NodeID) {
        self.id = id;
    }

    fn get_id(&self) -> NodeID {
        self.id
    }

    fn get_var(&self, var_id: u64) -> Option<Value> {
        VAR_GET_TABLE.get(&var_id).and_then(|f| f(self))
    }

    fn set_var(&mut self, var_id: u64, val: Value) -> Option<()> {
        VAR_SET_TABLE.get(&var_id).and_then(|f| f(self, val))
    }

    fn apply_exposed(&mut self, hashmap: &HashMap<u64, Value>) {
        for (var_id, val) in hashmap.iter() {
            if let Some(f) = VAR_APPLY_TABLE.get(var_id) {
                f(self, val);
            }
        }
    }

    fn call_function(
        &mut self,
        id: u64,
        api: &mut ScriptApi<'_>,
        params: &[Value],
    ) -> Value {
        DISPATCH_TABLE.get(&id).map_or(Value::Null, |f| f(self, params, api))
    }

    // Attributes

    fn attributes_of(&self, member: &str) -> Vec<String> {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn members_with(&self, attribute: &str) -> Vec<String> {
        ATTRIBUTE_TO_MEMBERS_MAP
            .get(attribute)
            .map(|members| members.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn has_attribute(&self, member: &str, attribute: &str) -> bool {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().any(|a| *a == attribute))
            .unwrap_or(false)
    }
    
    fn script_flags(&self) -> ScriptFlags {
        ScriptFlags::new(1)
    }
}

// =========================== Static PHF Dispatch Tables ===========================

static VAR_GET_TABLE: phf::Map<u64, fn(&PuptestsResourceTestsTestResourceApiPupScript) -> Option<Value>> =
    phf::phf_map! {
        9332267950230239222u64 => |script: &PuptestsResourceTestsTestResourceApiPupScript| -> Option<Value> {
                        Some(json!(script.__t_emit_count))
                    },

    };

static VAR_SET_TABLE: phf::Map<u64, fn(&mut PuptestsResourceTestsTestResourceApiPupScript, Value) -> Option<()>> =
    phf::phf_map! {
        9332267950230239222u64 => |script: &mut PuptestsResourceTestsTestResourceApiPupScript, val: Value| -> Option<()> {
                            if let Some(v) = val.as_i64() {
                                script.__t_emit_count = v as i32;
                                return Some(());
                            }
                            None
                        },

    };

static VAR_APPLY_TABLE: phf::Map<u64, fn(&mut PuptestsResourceTestsTestResourceApiPupScript, &Value)> =
    phf::phf_map! {

    };

static DISPATCH_TABLE: phf::Map<
    u64,
    fn(&mut PuptestsResourceTestsTestResourceApiPupScript, &[Value], &mut ScriptApi<'_>) -> Value,
> = phf::phf_map! {
        7880464646272170321u64 => | script: &mut PuptestsResourceTestsTestResourceApiPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_test_texture(api);
            Value::Null
        },
        14801928087785011895u64 => | script: &mut PuptestsResourceTestsTestResourceApiPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_test_mesh(api);
            Value::Null
        },
        659671514298471190u64 => | script: &mut PuptestsResourceTestsTestResourceApiPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_test_quaternion(api);
            Value::Null
        },
        17657417272605923597u64 => | script: &mut PuptestsResourceTestsTestResourceApiPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_test_shape2d(api);
            Value::Null
        },
        3497552624715609828u64 => | script: &mut PuptestsResourceTestsTestResourceApiPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_test_signal_new_connect_emit(api);
            Value::Null
        },
        7935796306813564562u64 => | script: &mut PuptestsResourceTestsTestResourceApiPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_test_signal_emit_deferred(api);
            Value::Null
        },
        17460559410220403735u64 => | script: &mut PuptestsResourceTestsTestResourceApiPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_test_array(api);
            Value::Null
        },
        4461473229972980648u64 => | script: &mut PuptestsResourceTestsTestResourceApiPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_test_map(api);
            Value::Null
        },
        15891415482422161649u64 => | script: &mut PuptestsResourceTestsTestResourceApiPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_on_signal(api);
            Value::Null
        },
        8539718162271983822u64 => | script: &mut PuptestsResourceTestsTestResourceApiPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_on_other_signal(api);
            Value::Null
        },

    };
