// Auto-generated by Perro compiler
const PART1: [u8; 8] = [0xFA, 0x59, 0x78, 0xF7, 0xE8, 0xE4, 0xF5, 0x43];
const PART2: [u8; 8] = [0x0A, 0xC5, 0x5B, 0xC5, 0x4A, 0xFB, 0xFE, 0x89];
const PART3: [u8; 8] = [0x31, 0xEE, 0x9C, 0x83, 0x79, 0x82, 0x2F, 0xBA];
const PART4: [u8; 8] = [0x83, 0x10, 0x63, 0xB0, 0x07, 0x46, 0xA1, 0x94];
const CONST1: u32 = 0x2CF34E28;
const CONST2: u32 = 0x4B0366F7;
const CONST3: u32 = 0x720E390F;
const CONST4: u32 = 0x6F33ECA8;
const CONST5: u32 = 0x9C77F560;
const CONST6: u32 = 0xB169425A;
const CONST7: u32 = 0x9058D65D;
const CONST8: u32 = 0x84A2C12C;
pub fn get_aes_key() -> [u8; 32] {
    let mut key = [0u8; 32];
    for i in 0..8 {
        key[i]      = PART1[i] ^ (((CONST7 as u8).wrapping_sub(CONST1 as u8)));
        key[i + 8]  = PART2[i] ^ (((CONST7 as u8).wrapping_sub(CONST1 as u8)));
        key[i + 16] = PART3[i] ^ (((CONST8 >> 8) as u8) ^ (CONST6 as u8));
        key[i + 24] = PART4[i] ^ (((CONST3 as u8).wrapping_add(CONST5 as u8)));
    }
    key
}
