#![allow(unused_imports, unused_variables, dead_code)]
// AUTO-GENERATED by Perro Compiler. Do not edit by hand.

use perro::runtime::{Runtime, RuntimeInputApi, RuntimeResourceApi};
use perro::scripting::ScriptConstructor;

pub static SCRIPT_REGISTRY: &[(u64, ScriptConstructor<Runtime, RuntimeResourceApi, RuntimeInputApi>)] = &[
];

#[unsafe(no_mangle)]
pub extern "C" fn perro_scripts_set_project_root(
root_ptr: *const u8,
root_len: usize,
name_ptr: *const u8,
name_len: usize,
) -> bool {
if root_ptr.is_null() || name_ptr.is_null() {
return false;
}
let root_bytes = unsafe { std::slice::from_raw_parts(root_ptr, root_len) };
let name_bytes = unsafe { std::slice::from_raw_parts(name_ptr, name_len) };
let Ok(root) = std::str::from_utf8(root_bytes) else {
return false;
};
let Ok(name) = std::str::from_utf8(name_bytes) else {
return false;
};
perro::modules::file::set_project_root_disk(root, name);
true
}

#[unsafe(no_mangle)]
pub extern "C" fn perro_script_registry_len() -> usize {
SCRIPT_REGISTRY.len()
}

#[allow(improper_ctypes_definitions)]
#[unsafe(no_mangle)]
pub extern "C" fn perro_script_registry_get(
index: usize,
path_hash_out: *mut u64,
ctor_out: *mut ScriptConstructor<Runtime, RuntimeResourceApi, RuntimeInputApi>,
) -> bool {
if path_hash_out.is_null() || ctor_out.is_null() {
return false;
}
let Some((path_hash, ctor)) = SCRIPT_REGISTRY.get(index) else {
return false;
};
unsafe {
*path_hash_out = *path_hash;
*ctor_out = *ctor;
}
true
}
