use super::*;

pub(super) fn water_gpu_2d(
    node: NodeID,
    water: &Water2DState,
    resolution: WaterGridResolution,
    cell_offset: u32,
    cell_count: u32,
    ripple_blend: f32,
) -> WaterGpu {
    water_gpu_common(
        node,
        2,
        water.idle_mode,
        water.size,
        water.depth,
        water.flow,
        water.wind,
        water.shape,
        resolution,
        water.wave_speed,
        water.wave_scale,
        water.wave_length,
        water.simulation_time,
        water.simulation_delta,
        water.damping,
        water.wake_strength,
        water.foam_strength,
        water.collision_layers.bits(),
        water.collision_mask.bits(),
        water.coastline_foam_color.into(),
        water.deep_color.into(),
        water.shallow_color.into(),
        water.shallow_depth,
        [0.0, 0.0, 0.0, 0.0],
        water.foam_color.into(),
        [
            water.transparency,
            water.reflectivity,
            water.roughness,
            water.fresnel_power,
        ],
        [
            water.normal_strength,
            water.ripple_scale,
            water.foam_amount,
            water.crest_foam_threshold,
        ],
        [
            water.caustic_strength,
            water.refraction_strength,
            water.scattering_strength,
            water.distance_fog_strength,
        ],
        [
            water.coastline_foam_strength,
            water.coastline_foam_width,
            water.coastline_cutoff_softness,
            water.coastline_wave_damping,
        ],
        water.coastline_wave_reflection,
        water.coastline_edge_noise,
        water.debug,
        water.paused,
        water.model,
        [0.0, 0.0, 0.0, 1.0],
        water.z_index,
        cell_offset,
        cell_count,
        ripple_blend,
    )
}

pub(super) fn water_gpu_3d(
    node: NodeID,
    water: &Water3DState,
    resolution: WaterGridResolution,
    cell_offset: u32,
    cell_count: u32,
    ripple_blend: f32,
    sky_color: [f32; 3],
) -> WaterGpu {
    water_gpu_common(
        node,
        3,
        water.idle_mode,
        water.size,
        water.depth,
        water.flow,
        water.wind,
        water.shape,
        resolution,
        water.wave_speed,
        water.wave_scale,
        water.wave_length,
        water.simulation_time,
        water.simulation_delta,
        water.damping,
        water.wake_strength,
        water.foam_strength,
        water.collision_layers.bits(),
        water.collision_mask.bits(),
        water.coastline_foam_color.into(),
        water.deep_color.into(),
        water.shallow_color.into(),
        water.shallow_depth,
        [
            sky_color[0],
            sky_color[1],
            sky_color[2],
            water.sky_bias_ratio.clamp(0.0, 1.0),
        ],
        water.foam_color.into(),
        [
            water.transparency,
            water.reflectivity,
            water.roughness,
            water.fresnel_power,
        ],
        [
            water.normal_strength,
            water.ripple_scale,
            water.foam_amount,
            water.crest_foam_threshold,
        ],
        [
            water.caustic_strength,
            water.refraction_strength,
            water.scattering_strength,
            water.distance_fog_strength,
        ],
        [
            water.coastline_foam_strength,
            water.coastline_foam_width,
            water.coastline_cutoff_softness,
            water.coastline_wave_damping,
        ],
        water.coastline_wave_reflection,
        water.coastline_edge_noise,
        water.debug,
        water.paused,
        [
            [water.model[0][0], water.model[0][1], water.model[0][2]],
            [water.model[1][0], water.model[1][1], water.model[1][2]],
            [water.model[2][0], water.model[2][1], water.model[2][2]],
        ],
        water.model[3],
        0,
        cell_offset,
        cell_count,
        ripple_blend,
    )
}

#[allow(clippy::too_many_arguments)]
pub(super) fn water_gpu_common(
    node: NodeID,
    kind: u32,
    idle_mode: WaterIdleModeState,
    size: [f32; 2],
    depth: f32,
    flow: [f32; 2],
    wind: [f32; 2],
    shape: WaterShapeState,
    resolution: WaterGridResolution,
    wave_speed: f32,
    wave_scale: f32,
    wave_length: f32,
    simulation_time: f32,
    simulation_delta: f32,
    damping: f32,
    wake_strength: f32,
    foam_strength: f32,
    _collision_layers: u32,
    _collision_mask: u32,
    coastline_foam_color: [f32; 4],
    deep_color: [f32; 4],
    shallow_color: [f32; 4],
    shallow_depth: f32,
    sky_color_bias: [f32; 4],
    foam_color: [f32; 4],
    visual0: [f32; 4],
    visual1: [f32; 4],
    visual2: [f32; 4],
    coastline: [f32; 4],
    coastline_wave_reflection: f32,
    coastline_edge_noise: f32,
    debug: bool,
    paused: bool,
    model: [[f32; 3]; 3],
    model_w: [f32; 4],
    z_index: i32,
    cell_offset: u32,
    cell_count: u32,
    ripple_blend: f32,
) -> WaterGpu {
    WaterGpu {
        node: node.index(),
        kind,
        idle_mode: idle_mode as u32,
        z_index,
        size_depth_time: [size[0], size[1], depth, shallow_depth.max(-1.0)],
        flow_wind: [flow[0], flow[1], wind[0], wind[1]],
        wave: [wave_speed, wave_scale, damping, wake_strength],
        flags: [
            resolution.render[0].clamp(1, WATER_MAX_RENDER_RESOLUTION),
            resolution.render[1].clamp(1, WATER_MAX_RENDER_RESOLUTION),
            (u32::from(debug) * WATER_FLAG_DEBUG) | (u32::from(paused) * WATER_FLAG_PAUSED),
            foam_strength.to_bits(),
        ],
        deep_color,
        shallow_color,
        sky_color_bias,
        foam_color,
        visual0,
        visual1,
        visual2,
        wave_profile: [
            wave_length.max(0.001),
            simulation_time.max(0.0),
            simulation_delta.clamp(0.0, 0.050),
            0.0,
        ],
        coastline_foam_color,
        coastline,
        shape: water_shape_gpu(shape, size, depth),
        sim: [
            cell_offset,
            cell_count,
            resolution.sim[0].clamp(1, 256),
            resolution.sim[1].clamp(1, 256),
        ],
        model_x: [
            model[0][0],
            model[0][1],
            model[0][2],
            ripple_blend.clamp(0.0, 1.0),
        ],
        model_y: [
            model[1][0],
            model[1][1],
            model[1][2],
            coastline_wave_reflection.clamp(0.0, 2.0),
        ],
        model_z: [
            model[2][0],
            model[2][1],
            model[2][2],
            coastline_edge_noise.clamp(0.0, 1.0),
        ],
        model_w,
    }
}

pub(super) fn water_shape_gpu(shape: WaterShapeState, size: [f32; 2], depth: f32) -> [f32; 4] {
    match shape {
        WaterShapeState::Rect => [0.0, size[0], size[1], depth],
        WaterShapeState::Circle { radius } => [1.0, radius, depth, 0.0],
        WaterShapeState::Cylinder {
            radius,
            half_height,
        } => [2.0, radius, half_height, 0.0],
    }
}

pub(super) const WATER_WGSL: &str =
    perro_macros::include_str_stripped!("water_shaders/water_compute.wgsl");
pub(super) const WATER_3D_RENDER_WGSL: &str =
    perro_macros::include_str_stripped!("water_shaders/water_3d_render.wgsl");
