use crate::{StaticPipelineError, ensure_unique_hashes, res_dir, static_dir};
use perro_animation::{
    AnimationBoneSelector, AnimationEase, AnimationEvent, AnimationEventScope, AnimationInterpolation,
    AnimationObjectKey, AnimationObjectTrack, AnimationParam, AnimationTrackValue,
};
use perro_io::walkdir::collect_file_paths;
use perro_scene::NodeField;
use rayon::prelude::*;
use std::{borrow::Cow, fmt::Write as _, fs, io, path::Path};

#[derive(Clone)]
struct ParsedAnimation {
    lookup_key: String,
    clip: perro_animation::AnimationClip,
}

pub fn generate_static_animations(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    fs::create_dir_all(&static_dir)?;

    let mut anim_paths = Vec::<String>::new();
    if res_dir.exists() {
        anim_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| ext.eq_ignore_ascii_case("panim"))
            })
            .collect();
    }
    anim_paths.sort();

    let mut parsed = anim_paths
        .par_iter()
        .map(|rel| -> io::Result<ParsedAnimation> {
            let source = res_dir.join(rel);
            let text = fs::read_to_string(&source)?;
            let clip = perro_animation::parse_panim(&text).map_err(io::Error::other)?;
            let clip = optimize_animation_clip(clip);
            Ok(ParsedAnimation {
                lookup_key: format!("res://{rel}"),
                clip,
            })
        })
        .collect::<io::Result<Vec<_>>>()?;
    parsed.sort_by(|a, b| a.lookup_key.cmp(&b.lookup_key));
    ensure_unique_hashes("animation", parsed.iter().map(|anim| anim.lookup_key.as_str()))?;

    let mut src = String::new();
    src.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    src.push_str("#![allow(unused_imports)]\n#![allow(dead_code)]\n\n");
    src.push_str("use perro_animation::*;\n");
    src.push_str("use perro_scene::*;\n");
    src.push_str("use perro_structs::*;\n");
    src.push_str("use std::borrow::Cow;\n\n");
    src.push_str("const EMPTY_ANIMATION_OBJECTS: &[AnimationObject] = &[];\n");
    src.push_str("const EMPTY_ANIMATION_TRACKS: &[AnimationObjectTrack] = &[];\n");
    src.push_str("const EMPTY_ANIMATION_KEYS: &[AnimationObjectKey] = &[];\n");
    src.push_str("const EMPTY_ANIMATION_PARAMS: &[AnimationParam] = &[];\n");
    src.push_str("const EMPTY_ANIMATION_EVENTS: &[AnimationFrameEvent] = &[];\n\n");

    let mut lookup = String::new();
    lookup.push_str("pub fn lookup_animation(path_hash: u64) -> Option<&'static AnimationClip> {\n");
    lookup.push_str("    match path_hash {\n");

    for anim in &parsed {
        src.push_str(&emit_static_animation_const(&anim.lookup_key, &anim.clip)?);
        let _ = writeln!(
            lookup,
            "        {}u64 => Some(&CLIP_{}),",
            perro_ids::string_to_u64(&anim.lookup_key),
            sanitize_ident(&anim.lookup_key)
        );
    }
    lookup.push_str("        _ => None,\n");
    lookup.push_str("    }\n");
    lookup.push_str("}\n");

    src.push('\n');
    src.push_str(&lookup);
    fs::write(static_dir.join("animations.rs"), src)?;
    Ok(())
}

fn optimize_animation_clip(mut clip: perro_animation::AnimationClip) -> perro_animation::AnimationClip {
    let mut tracks = clip.object_tracks.into_owned();
    for track in &mut tracks {
        optimize_animation_track_keys(track);
    }
    clip.object_tracks = Cow::Owned(tracks);
    clip
}

fn optimize_animation_track_keys(track: &mut AnimationObjectTrack) {
    if track.keys.len() < 3 {
        return;
    }

    let mut keys = track.keys.to_vec();
    let mut index = 1usize;
    while index + 1 < keys.len() {
        let prev = &keys[index - 1];
        let middle = &keys[index];
        let next = &keys[index + 1];
        if is_redundant_middle_key(prev, middle, next) {
            keys.remove(index);
            index = index.saturating_sub(1).max(1);
        } else {
            index += 1;
        }
    }
    track.keys = Cow::Owned(keys);
}

fn is_redundant_middle_key(
    prev: &AnimationObjectKey,
    middle: &AnimationObjectKey,
    next: &AnimationObjectKey,
) -> bool {
    if prev.frame >= middle.frame || middle.frame >= next.frame {
        return false;
    }

    let trio = [prev.clone(), middle.clone(), next.clone()];
    let pair = [prev.clone(), next.clone()];
    for frame in prev.frame..=next.frame {
        let Some(a) = sample_track_value_from_keys(&trio, frame) else {
            return false;
        };
        let Some(b) = sample_track_value_from_keys(&pair, frame) else {
            return false;
        };
        if !track_value_exact_eq(&a, &b) {
            return false;
        }
    }
    true
}

fn sample_track_value_from_keys(keys: &[AnimationObjectKey], frame: u32) -> Option<AnimationTrackValue> {
    if keys.is_empty() {
        return None;
    }

    let mut prev_index = None::<usize>;
    let mut next_index = None::<usize>;
    for (index, key) in keys.iter().enumerate() {
        if key.frame <= frame {
            prev_index = Some(index);
        } else {
            next_index = Some(index);
            break;
        }
    }

    let prev_index = prev_index.or(Some(0))?;
    let prev_key = &keys[prev_index];
    let prev = &prev_key.value;
    match prev_key.interpolation {
        AnimationInterpolation::Step => Some(prev.clone()),
        AnimationInterpolation::Linear => {
            let Some(next_index) = next_index else {
                return Some(prev.clone());
            };
            let next_key = &keys[next_index];
            let frame_span = next_key.frame.saturating_sub(prev_key.frame);
            if frame_span == 0 {
                return Some(prev.clone());
            }
            let local = frame.saturating_sub(prev_key.frame);
            let t = (local as f32 / frame_span as f32).clamp(0.0, 1.0);
            let t = ease_sample(prev_key.ease, t);
            Some(interpolate_values(prev, &next_key.value, t))
        }
    }
}

#[inline]
fn ease_sample(ease: AnimationEase, t: f32) -> f32 {
    let t = t.clamp(0.0, 1.0);
    match ease {
        AnimationEase::Linear => t,
        AnimationEase::EaseIn => t * t,
        AnimationEase::EaseOut => 1.0 - (1.0 - t) * (1.0 - t),
        AnimationEase::EaseInOut => {
            if t < 0.5 {
                2.0 * t * t
            } else {
                1.0 - ((-2.0 * t + 2.0) * (-2.0 * t + 2.0)) * 0.5
            }
        }
    }
}

fn interpolate_values(a: &AnimationTrackValue, b: &AnimationTrackValue, t: f32) -> AnimationTrackValue {
    match (a, b) {
        (AnimationTrackValue::F32(a), AnimationTrackValue::F32(b)) => {
            AnimationTrackValue::F32(lerp_f32(*a, *b, t))
        }
        (AnimationTrackValue::I32(a), AnimationTrackValue::I32(b)) => {
            AnimationTrackValue::I32(lerp_f32(*a as f32, *b as f32, t).round() as i32)
        }
        (AnimationTrackValue::U32(a), AnimationTrackValue::U32(b)) => {
            AnimationTrackValue::U32(lerp_f32(*a as f32, *b as f32, t).round().max(0.0) as u32)
        }
        (AnimationTrackValue::Vec2(a), AnimationTrackValue::Vec2(b)) => {
            AnimationTrackValue::Vec2([lerp_f32(a[0], b[0], t), lerp_f32(a[1], b[1], t)])
        }
        (AnimationTrackValue::Vec3(a), AnimationTrackValue::Vec3(b)) => AnimationTrackValue::Vec3([
            lerp_f32(a[0], b[0], t),
            lerp_f32(a[1], b[1], t),
            lerp_f32(a[2], b[2], t),
        ]),
        (AnimationTrackValue::Vec4(a), AnimationTrackValue::Vec4(b)) => AnimationTrackValue::Vec4([
            lerp_f32(a[0], b[0], t),
            lerp_f32(a[1], b[1], t),
            lerp_f32(a[2], b[2], t),
            lerp_f32(a[3], b[3], t),
        ]),
        (AnimationTrackValue::Transform2D(a), AnimationTrackValue::Transform2D(b)) => {
            let mut out = *a;
            out.position.x = lerp_f32(a.position.x, b.position.x, t);
            out.position.y = lerp_f32(a.position.y, b.position.y, t);
            out.rotation = lerp_f32(a.rotation, b.rotation, t);
            out.scale.x = lerp_f32(a.scale.x, b.scale.x, t);
            out.scale.y = lerp_f32(a.scale.y, b.scale.y, t);
            AnimationTrackValue::Transform2D(out)
        }
        (AnimationTrackValue::Transform3D(a), AnimationTrackValue::Transform3D(b)) => {
            let mut out = *a;
            out.position.x = lerp_f32(a.position.x, b.position.x, t);
            out.position.y = lerp_f32(a.position.y, b.position.y, t);
            out.position.z = lerp_f32(a.position.z, b.position.z, t);
            out.scale.x = lerp_f32(a.scale.x, b.scale.x, t);
            out.scale.y = lerp_f32(a.scale.y, b.scale.y, t);
            out.scale.z = lerp_f32(a.scale.z, b.scale.z, t);
            out.rotation = a.rotation.to_quat().slerp(b.rotation.to_quat(), t).into();
            AnimationTrackValue::Transform3D(out)
        }
        _ => a.clone(),
    }
}

#[inline]
fn lerp_f32(a: f32, b: f32, t: f32) -> f32 {
    a + (b - a) * t
}

fn track_value_exact_eq(a: &AnimationTrackValue, b: &AnimationTrackValue) -> bool {
    match (a, b) {
        (AnimationTrackValue::Bool(a), AnimationTrackValue::Bool(b)) => a == b,
        (AnimationTrackValue::I32(a), AnimationTrackValue::I32(b)) => a == b,
        (AnimationTrackValue::U32(a), AnimationTrackValue::U32(b)) => a == b,
        (AnimationTrackValue::F32(a), AnimationTrackValue::F32(b)) => f32_cull_eq(*a, *b),
        (AnimationTrackValue::Vec2(a), AnimationTrackValue::Vec2(b)) => {
            f32_cull_eq(a[0], b[0]) && f32_cull_eq(a[1], b[1])
        }
        (AnimationTrackValue::Vec3(a), AnimationTrackValue::Vec3(b)) => {
            f32_cull_eq(a[0], b[0]) && f32_cull_eq(a[1], b[1]) && f32_cull_eq(a[2], b[2])
        }
        (AnimationTrackValue::Vec4(a), AnimationTrackValue::Vec4(b)) => {
            f32_cull_eq(a[0], b[0])
                && f32_cull_eq(a[1], b[1])
                && f32_cull_eq(a[2], b[2])
                && f32_cull_eq(a[3], b[3])
        }
        (AnimationTrackValue::AssetPath(a), AnimationTrackValue::AssetPath(b)) => a == b,
        (AnimationTrackValue::Transform2D(a), AnimationTrackValue::Transform2D(b)) => {
            f32_cull_eq(a.position.x, b.position.x)
                && f32_cull_eq(a.position.y, b.position.y)
                && f32_cull_eq(a.rotation, b.rotation)
                && f32_cull_eq(a.scale.x, b.scale.x)
                && f32_cull_eq(a.scale.y, b.scale.y)
        }
        (AnimationTrackValue::Transform3D(a), AnimationTrackValue::Transform3D(b)) => {
            f32_cull_eq(a.position.x, b.position.x)
                && f32_cull_eq(a.position.y, b.position.y)
                && f32_cull_eq(a.position.z, b.position.z)
                && f32_cull_eq(a.scale.x, b.scale.x)
                && f32_cull_eq(a.scale.y, b.scale.y)
                && f32_cull_eq(a.scale.z, b.scale.z)
                && f32_cull_eq(a.rotation.x, b.rotation.x)
                && f32_cull_eq(a.rotation.y, b.rotation.y)
                && f32_cull_eq(a.rotation.z, b.rotation.z)
                && f32_cull_eq(a.rotation.w, b.rotation.w)
        }
        _ => false,
    }
}

#[inline]
fn f32_cull_eq(a: f32, b: f32) -> bool {
    if a.to_bits() == b.to_bits() {
        return true;
    }
    if !a.is_finite() || !b.is_finite() {
        return false;
    }
    let delta = (a - b).abs();
    let scale = 1.0f32.max(a.abs()).max(b.abs());
    delta <= 1e-6 * scale
}

fn emit_static_animation_const(
    path: &str,
    clip: &perro_animation::AnimationClip,
) -> Result<String, StaticPipelineError> {
    let id = sanitize_ident(path);
    let mut out = String::new();

    let mut tracks_buf = String::new();
    let mut track_entries = String::new();
    for (index, track) in clip.object_tracks.iter().enumerate() {
        let key_const = format!("TRACK_KEYS_{id}_{index}");
        let _ = writeln!(tracks_buf, "const {key_const}: &[AnimationObjectKey] = &[");
        for key in track.keys.as_ref() {
            let _ = writeln!(
                tracks_buf,
                "    AnimationObjectKey {{ frame: {}, interpolation: {}, ease: {}, value: {} }},",
                key.frame,
                emit_interpolation(key.interpolation),
                emit_ease(key.ease),
                emit_track_value(&key.value)
            );
        }
        tracks_buf.push_str("];\n");

        let field_expr = emit_node_field(track.field)?;
        let _ = writeln!(
            track_entries,
            "    AnimationObjectTrack {{ object: Cow::Borrowed(\"{}\"), field: {}, bone_target: {}, interpolation: {}, ease: {}, keys: Cow::Borrowed({}) }},",
            escape_str(track.object.as_ref()),
            field_expr,
            emit_bone_target(&track.bone_target),
            emit_interpolation(track.interpolation),
            emit_ease(track.ease),
            if track.keys.is_empty() {
                "EMPTY_ANIMATION_KEYS".to_string()
            } else {
                key_const
            }
        );
    }
    out.push_str(&tracks_buf);

    let tracks_const = format!("TRACKS_{id}");
    let _ = writeln!(out, "const {tracks_const}: &[AnimationObjectTrack] = &[");
    out.push_str(&track_entries);
    out.push_str("];\n\n");

    let objects_const = format!("OBJECTS_{id}");
    let _ = writeln!(out, "const {objects_const}: &[AnimationObject] = &[");
    for object in clip.objects.as_ref() {
        let _ = writeln!(
            out,
            "    AnimationObject {{ name: Cow::Borrowed(\"{}\"), node_type: Cow::Borrowed(\"{}\") }},",
            escape_str(object.name.as_ref()),
            escape_str(object.node_type.as_ref())
        );
    }
    out.push_str("];\n\n");

    let mut events_buf = String::new();
    let mut event_entries = String::new();
    for (index, event) in clip.frame_events.iter().enumerate() {
        let params_const = format!("EVENT_PARAMS_{id}_{index}");
        let emitted_event = match &event.event {
            AnimationEvent::EmitSignal { name, params } => {
                if !params.is_empty() {
                    let _ = writeln!(events_buf, "const {params_const}: &[AnimationParam] = &[");
                    for param in params.as_ref() {
                        let _ = writeln!(events_buf, "    {},", emit_param(param));
                    }
                    events_buf.push_str("];\n");
                }
                format!(
                    "AnimationEvent::EmitSignal {{ name: Cow::Borrowed(\"{}\"), params: Cow::Borrowed({}) }}",
                    escape_str(name.as_ref()),
                    if params.is_empty() {
                        "EMPTY_ANIMATION_PARAMS".to_string()
                    } else {
                        params_const
                    }
                )
            }
            AnimationEvent::SetVar { name, value } => format!(
                "AnimationEvent::SetVar {{ name: Cow::Borrowed(\"{}\"), value: {} }}",
                escape_str(name.as_ref()),
                emit_param(value)
            ),
            AnimationEvent::CallMethod { name, params } => {
                if !params.is_empty() {
                    let _ = writeln!(events_buf, "const {params_const}: &[AnimationParam] = &[");
                    for param in params.as_ref() {
                        let _ = writeln!(events_buf, "    {},", emit_param(param));
                    }
                    events_buf.push_str("];\n");
                }
                format!(
                    "AnimationEvent::CallMethod {{ name: Cow::Borrowed(\"{}\"), params: Cow::Borrowed({}) }}",
                    escape_str(name.as_ref()),
                    if params.is_empty() {
                        "EMPTY_ANIMATION_PARAMS".to_string()
                    } else {
                        params_const
                    }
                )
            }
        };
        let _ = writeln!(
            event_entries,
            "    AnimationFrameEvent {{ frame: {}, scope: {}, event: {} }},",
            event.frame,
            emit_event_scope(&event.scope),
            emitted_event
        );
    }
    out.push_str(&events_buf);

    let events_const = format!("FRAME_EVENTS_{id}");
    let _ = writeln!(out, "const {events_const}: &[AnimationFrameEvent] = &[");
    out.push_str(&event_entries);
    out.push_str("];\n\n");

    let _ = writeln!(
        out,
        "pub static CLIP_{id}: AnimationClip = AnimationClip {{ name: Cow::Borrowed(\"{}\"), fps: {}, total_frames: {}, objects: Cow::Borrowed({}), object_tracks: Cow::Borrowed({}), frame_events: Cow::Borrowed({}) }};\n",
        escape_str(clip.name.as_ref()),
        emit_f32(clip.fps),
        clip.total_frames,
        if clip.objects.is_empty() {
            "EMPTY_ANIMATION_OBJECTS".to_string()
        } else {
            objects_const
        },
        if clip.object_tracks.is_empty() {
            "EMPTY_ANIMATION_TRACKS".to_string()
        } else {
            tracks_const
        },
        if clip.frame_events.is_empty() {
            "EMPTY_ANIMATION_EVENTS".to_string()
        } else {
            events_const
        }
    );

    Ok(out)
}

fn emit_node_field(field: NodeField) -> Result<String, StaticPipelineError> {
    let debug = format!("{field:?}");
    let (variant, inner) = debug.split_once('(').ok_or_else(|| {
        StaticPipelineError::SceneParse(format!("unsupported node field: {debug}"))
    })?;
    let inner = inner.strip_suffix(')').ok_or_else(|| {
        StaticPipelineError::SceneParse(format!("unsupported node field variant: {debug}"))
    })?;
    Ok(format!("NodeField::{variant}({variant}Field::{inner})"))
}

fn emit_track_value(value: &AnimationTrackValue) -> String {
    match value {
        AnimationTrackValue::Bool(v) => format!("AnimationTrackValue::Bool({v})"),
        AnimationTrackValue::I32(v) => format!("AnimationTrackValue::I32({v})"),
        AnimationTrackValue::U32(v) => format!("AnimationTrackValue::U32({v})"),
        AnimationTrackValue::F32(v) => format!("AnimationTrackValue::F32({})", emit_f32(*v)),
        AnimationTrackValue::Vec2(v) => format!(
            "AnimationTrackValue::Vec2([{}, {}])",
            emit_f32(v[0]),
            emit_f32(v[1])
        ),
        AnimationTrackValue::Vec3(v) => format!(
            "AnimationTrackValue::Vec3([{}, {}, {}])",
            emit_f32(v[0]),
            emit_f32(v[1]),
            emit_f32(v[2])
        ),
        AnimationTrackValue::Vec4(v) => format!(
            "AnimationTrackValue::Vec4([{}, {}, {}, {}])",
            emit_f32(v[0]),
            emit_f32(v[1]),
            emit_f32(v[2]),
            emit_f32(v[3])
        ),
        AnimationTrackValue::AssetPath(v) => format!(
            "AnimationTrackValue::AssetPath(Cow::Borrowed(\"{}\"))",
            escape_str(v.as_ref())
        ),
        AnimationTrackValue::Transform2D(v) => format!(
            "AnimationTrackValue::Transform2D(Transform2D {{ position: Vector2 {{ x: {}, y: {} }}, scale: Vector2 {{ x: {}, y: {} }}, rotation: {} }})",
            emit_f32(v.position.x),
            emit_f32(v.position.y),
            emit_f32(v.scale.x),
            emit_f32(v.scale.y),
            emit_f32(v.rotation)
        ),
        AnimationTrackValue::Transform3D(v) => format!(
            "AnimationTrackValue::Transform3D(Transform3D {{ position: Vector3 {{ x: {}, y: {}, z: {} }}, scale: Vector3 {{ x: {}, y: {}, z: {} }}, rotation: Quaternion {{ x: {}, y: {}, z: {}, w: {} }} }})",
            emit_f32(v.position.x),
            emit_f32(v.position.y),
            emit_f32(v.position.z),
            emit_f32(v.scale.x),
            emit_f32(v.scale.y),
            emit_f32(v.scale.z),
            emit_f32(v.rotation.x),
            emit_f32(v.rotation.y),
            emit_f32(v.rotation.z),
            emit_f32(v.rotation.w)
        ),
    }
}

fn emit_param(value: &AnimationParam) -> String {
    match value {
        AnimationParam::Bool(v) => format!("AnimationParam::Bool({v})"),
        AnimationParam::I32(v) => format!("AnimationParam::I32({v})"),
        AnimationParam::U32(v) => format!("AnimationParam::U32({v})"),
        AnimationParam::F32(v) => format!("AnimationParam::F32({})", emit_f32(*v)),
        AnimationParam::Vec2(v) => format!(
            "AnimationParam::Vec2([{}, {}])",
            emit_f32(v[0]),
            emit_f32(v[1])
        ),
        AnimationParam::Vec3(v) => format!(
            "AnimationParam::Vec3([{}, {}, {}])",
            emit_f32(v[0]),
            emit_f32(v[1]),
            emit_f32(v[2])
        ),
        AnimationParam::Vec4(v) => format!(
            "AnimationParam::Vec4([{}, {}, {}, {}])",
            emit_f32(v[0]),
            emit_f32(v[1]),
            emit_f32(v[2]),
            emit_f32(v[3])
        ),
        AnimationParam::String(v) => format!(
            "AnimationParam::String(Cow::Borrowed(\"{}\"))",
            escape_str(v.as_ref())
        ),
        AnimationParam::Transform2D(v) => format!(
            "AnimationParam::Transform2D(Transform2D {{ position: Vector2 {{ x: {}, y: {} }}, scale: Vector2 {{ x: {}, y: {} }}, rotation: {} }})",
            emit_f32(v.position.x),
            emit_f32(v.position.y),
            emit_f32(v.scale.x),
            emit_f32(v.scale.y),
            emit_f32(v.rotation)
        ),
        AnimationParam::Transform3D(v) => format!(
            "AnimationParam::Transform3D(Transform3D {{ position: Vector3 {{ x: {}, y: {}, z: {} }}, scale: Vector3 {{ x: {}, y: {}, z: {} }}, rotation: Quaternion {{ x: {}, y: {}, z: {}, w: {} }} }})",
            emit_f32(v.position.x),
            emit_f32(v.position.y),
            emit_f32(v.position.z),
            emit_f32(v.scale.x),
            emit_f32(v.scale.y),
            emit_f32(v.scale.z),
            emit_f32(v.rotation.x),
            emit_f32(v.rotation.y),
            emit_f32(v.rotation.z),
            emit_f32(v.rotation.w)
        ),
        AnimationParam::ObjectNode(v) => format!(
            "AnimationParam::ObjectNode(Cow::Borrowed(\"{}\"))",
            escape_str(v.as_ref())
        ),
        AnimationParam::ObjectField { object, field } => format!(
            "AnimationParam::ObjectField {{ object: Cow::Borrowed(\"{}\"), field: Cow::Borrowed(\"{}\") }}",
            escape_str(object.as_ref()),
            escape_str(field.as_ref())
        ),
    }
}

fn emit_bone_target(target: &Option<perro_animation::AnimationBoneTarget>) -> String {
    match target {
        Some(target) => format!(
            "Some(AnimationBoneTarget {{ selector: {} }})",
            emit_bone_selector(&target.selector)
        ),
        None => "None".to_string(),
    }
}

fn emit_bone_selector(selector: &AnimationBoneSelector) -> String {
    match selector {
        AnimationBoneSelector::Index(v) => format!("AnimationBoneSelector::Index({v})"),
        AnimationBoneSelector::Name(v) => format!(
            "AnimationBoneSelector::Name(Cow::Borrowed(\"{}\"))",
            escape_str(v.as_ref())
        ),
    }
}

fn emit_interpolation(value: perro_animation::AnimationInterpolation) -> String {
    format!("AnimationInterpolation::{value:?}")
}

fn emit_ease(value: perro_animation::AnimationEase) -> String {
    format!("AnimationEase::{value:?}")
}

fn emit_event_scope(scope: &AnimationEventScope) -> String {
    match scope {
        AnimationEventScope::Global => "AnimationEventScope::Global".to_string(),
        AnimationEventScope::Object(object) => format!(
            "AnimationEventScope::Object(Cow::Borrowed(\"{}\"))",
            escape_str(object.as_ref())
        ),
    }
}

fn emit_f32(value: f32) -> String {
    format!("f32::from_bits(0x{:08X})", value.to_bits())
}

fn sanitize_ident(path: &str) -> String {
    let mut out = String::new();
    for c in path.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_uppercase());
        } else {
            out.push('_');
        }
    }
    out
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use perro_animation::{AnimationEase, AnimationInterpolation, AnimationObjectTrack, AnimationTrackValue};
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    const TEST_PANIM_SRC: &str = r#"
[Animation]
name = "PipelineClip"
fps = 24
[/Animation]

[Objects]
@Hero = Node3D
[/Objects]

[Frame0]
@Hero {
    position = (0,0,0)
}
[/Frame0]
"#;

    fn unique_temp_dir(label: &str) -> PathBuf {
        let ts = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        std::env::temp_dir().join(format!("perro_static_pipeline_{label}_{ts}"))
    }

    fn key(
        frame: u32,
        interpolation: AnimationInterpolation,
        ease: AnimationEase,
        value: AnimationTrackValue,
    ) -> AnimationObjectKey {
        AnimationObjectKey {
            frame,
            interpolation,
            ease,
            value,
        }
    }

    fn assert_track_sampling_equal(original: &[AnimationObjectKey], optimized: &[AnimationObjectKey]) {
        let start = original
            .iter()
            .map(|k| k.frame)
            .min()
            .expect("original keys should not be empty");
        let end = original
            .iter()
            .map(|k| k.frame)
            .max()
            .expect("original keys should not be empty");
        for frame in start..=end {
            let a = sample_track_value_from_keys(original, frame).expect("original sample");
            let b = sample_track_value_from_keys(optimized, frame).expect("optimized sample");
            assert!(
                track_value_exact_eq(&a, &b),
                "sample mismatch at frame {frame}: original={a:?} optimized={b:?}"
            );
        }
    }

    #[test]
    fn optimize_track_keys_removes_redundant_linear_midpoint() {
        let mut track = AnimationObjectTrack::default();
        let original = vec![
            key(0, AnimationInterpolation::Linear, AnimationEase::Linear, AnimationTrackValue::F32(0.0)),
            key(50, AnimationInterpolation::Linear, AnimationEase::Linear, AnimationTrackValue::F32(5.0)),
            key(100, AnimationInterpolation::Linear, AnimationEase::Linear, AnimationTrackValue::F32(10.0)),
        ];
        track.keys = Cow::Owned(original.clone());
        optimize_animation_track_keys(&mut track);
        assert_track_sampling_equal(&original, &track.keys);
        assert_eq!(track.keys.len(), 2);
        assert_eq!(track.keys[0].frame, 0);
        assert_eq!(track.keys[1].frame, 100);
    }

    #[test]
    fn optimize_track_keys_removes_redundant_step_key() {
        let mut track = AnimationObjectTrack::default();
        let original = vec![
            key(0, AnimationInterpolation::Step, AnimationEase::Linear, AnimationTrackValue::Bool(false)),
            key(50, AnimationInterpolation::Step, AnimationEase::Linear, AnimationTrackValue::Bool(false)),
            key(100, AnimationInterpolation::Step, AnimationEase::Linear, AnimationTrackValue::Bool(true)),
        ];
        track.keys = Cow::Owned(original.clone());
        optimize_animation_track_keys(&mut track);
        assert_track_sampling_equal(&original, &track.keys);
        assert_eq!(track.keys.len(), 2);
        assert_eq!(track.keys[0].frame, 0);
        assert_eq!(track.keys[1].frame, 100);
    }

    #[test]
    fn optimize_track_keys_keeps_non_redundant_step_change() {
        let mut track = AnimationObjectTrack::default();
        let original = vec![
            key(0, AnimationInterpolation::Step, AnimationEase::Linear, AnimationTrackValue::Bool(false)),
            key(50, AnimationInterpolation::Step, AnimationEase::Linear, AnimationTrackValue::Bool(true)),
            key(100, AnimationInterpolation::Step, AnimationEase::Linear, AnimationTrackValue::Bool(false)),
        ];
        track.keys = Cow::Owned(original.clone());
        optimize_animation_track_keys(&mut track);
        assert_track_sampling_equal(&original, &track.keys);
        assert_eq!(track.keys.len(), 3);
        assert_eq!(track.keys[1].frame, 50);
    }

    #[test]
    fn optimize_track_keys_preserves_samples_with_ease_curve() {
        let mut track = AnimationObjectTrack::default();
        let original = vec![
            key(0, AnimationInterpolation::Linear, AnimationEase::EaseInOut, AnimationTrackValue::Vec3([0.0, 10.0, -4.0])),
            key(25, AnimationInterpolation::Linear, AnimationEase::EaseInOut, AnimationTrackValue::Vec3([2.0, 6.0, -1.0])),
            key(50, AnimationInterpolation::Linear, AnimationEase::EaseInOut, AnimationTrackValue::Vec3([4.0, 2.0, 2.0])),
        ];
        track.keys = Cow::Owned(original.clone());
        optimize_animation_track_keys(&mut track);
        assert_track_sampling_equal(&original, &track.keys);
    }

    #[test]
    fn static_animation_pipeline_generates_fully_static_lookup() {
        let root = unique_temp_dir("animations");
        let source_rel = Path::new("animations").join("hero_run.panim");
        let source_abs = root.join("res").join(&source_rel);
        std::fs::create_dir_all(source_abs.parent().expect("source parent should exist"))
            .expect("failed to create source parent");
        std::fs::write(&source_abs, TEST_PANIM_SRC).expect("failed to write source panim");

        generate_static_animations(&root).expect("static animation generation should succeed");

        let embedded_abs = root
            .join(".perro")
            .join("project")
            .join("embedded")
            .join("animations")
            .join(&source_rel);
        assert!(
            !embedded_abs.exists(),
            "static animation generation should not emit embedded .panim sources"
        );

        let generated_rs = root
            .join(".perro")
            .join("project")
            .join("src")
            .join("static")
            .join("animations.rs");
        let generated_src =
            std::fs::read_to_string(generated_rs).expect("generated animations.rs should exist");
        let expected_hash = perro_ids::string_to_u64("res://animations/hero_run.panim");
        assert!(generated_src.contains("pub fn lookup_animation(path_hash: u64)"));
        assert!(generated_src.contains(&format!(
            "{expected_hash}u64 => Some(&CLIP_RES___ANIMATIONS_HERO_RUN_PANIM)"
        )));
        assert!(generated_src.contains("pub static CLIP_RES___ANIMATIONS_HERO_RUN_PANIM"));
        assert!(!generated_src.contains("parse_panim"));
        assert!(!generated_src.contains("include_str!"));
    }
}
