use crate::{StaticPipelineError, asset_uri, ensure_unique_hashes, res_dir, static_dir};
use perro_io::walkdir::collect_file_paths;
use std::{borrow::Cow, fmt::Write as _, fs, io, path::Path};

struct ParsedAnimationTree {
    lookup_key: String,
    tree: perro_animation::AnimationTreeAsset,
}

pub fn generate_static_animation_trees(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    fs::create_dir_all(&static_dir)?;

    let mut paths = Vec::<String>::new();
    if res_dir.exists() {
        paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| ext.eq_ignore_ascii_case("panimtree"))
            })
            .collect();
    }
    paths.sort();

    let mut parsed = paths
        .iter()
        .map(|rel| -> io::Result<ParsedAnimationTree> {
            let text = fs::read_to_string(res_dir.join(rel))?;
            let tree = perro_animation::parse_panimtree(&text).map_err(io::Error::other)?;
            Ok(ParsedAnimationTree {
                lookup_key: asset_uri(rel),
                tree,
            })
        })
        .collect::<io::Result<Vec<_>>>()?;
    parsed.sort_by(|a, b| a.lookup_key.cmp(&b.lookup_key));
    ensure_unique_hashes(
        "animation tree",
        parsed.iter().map(|v| v.lookup_key.as_str()),
    )?;

    let mut src = String::new();
    src.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    src.push_str("#![allow(unused_imports)]\n#![allow(dead_code)]\n\n");
    src.push_str("use perro_animation::*;\nuse std::borrow::Cow;\n\n");
    src.push_str("const EMPTY_REFS: &[Cow<'static, str>] = &[];\nconst EMPTY_WEIGHTS: &[f32] = &[];\nconst EMPTY_SLOTS: &[AnimationTreeSlot] = &[];\nconst EMPTY_NODES: &[AnimationTreeGraphNode] = &[];\n");
    src.push_str("pub static EMPTY_ANIMATION_TREE: AnimationTreeAsset = AnimationTreeAsset { name: Cow::Borrowed(\"\"), slots: Cow::Borrowed(EMPTY_SLOTS), nodes: Cow::Borrowed(EMPTY_NODES), output: Cow::Borrowed(\"\") };\n\n");

    let mut lookup = String::new();
    lookup.push_str("pub const fn lookup_animation_tree(path_hash: u64) -> &'static AnimationTreeAsset {\n    match path_hash {\n");
    for item in &parsed {
        src.push_str(&emit_tree(&item.lookup_key, &item.tree));
        let id = sanitize_ident(&item.lookup_key);
        let _ = writeln!(
            lookup,
            "        {}u64 => &TREE_{id},",
            perro_ids::string_to_u64(&item.lookup_key)
        );
    }
    lookup.push_str("        _ => &EMPTY_ANIMATION_TREE,\n    }\n}\n");
    src.push_str(&lookup);
    fs::write(static_dir.join("animation_trees.rs"), src)?;
    Ok(())
}

fn emit_tree(path: &str, tree: &perro_animation::AnimationTreeAsset) -> String {
    let id = sanitize_ident(path);
    let mut out = String::new();
    let slots = format!("SLOTS_{id}");
    let nodes = format!("NODES_{id}");
    let _ = writeln!(out, "const {slots}: &[AnimationTreeSlot] = &[");
    for slot in tree.slots.iter() {
        let _ = writeln!(
            out,
            "    AnimationTreeSlot {{ name: Cow::Borrowed(\"{}\") }},",
            esc(slot.name.as_ref())
        );
    }
    out.push_str("];\n");
    let mut aux = String::new();
    let _ = writeln!(out, "const {nodes}: &[AnimationTreeGraphNode] = &[");
    for (idx, node) in tree.nodes.iter().enumerate() {
        let kind = emit_kind(&id, idx, &node.kind, &mut aux);
        let _ = writeln!(
            out,
            "    AnimationTreeGraphNode {{ key: Cow::Borrowed(\"{}\"), kind: {} }},",
            esc(node.key.as_ref()),
            kind
        );
    }
    out.push_str("];\n");
    out.push_str(&aux);
    let _ = writeln!(
        out,
        "pub static TREE_{id}: AnimationTreeAsset = AnimationTreeAsset {{ name: Cow::Borrowed(\"{}\"), slots: Cow::Borrowed({}), nodes: Cow::Borrowed({}), output: Cow::Borrowed(\"{}\") }};\n",
        esc(tree.name.as_ref()),
        if tree.slots.is_empty() {
            "EMPTY_SLOTS".to_string()
        } else {
            slots
        },
        if tree.nodes.is_empty() {
            "EMPTY_NODES".to_string()
        } else {
            nodes
        },
        esc(tree.output.as_ref())
    );
    out
}

fn emit_kind(
    id: &str,
    idx: usize,
    kind: &perro_animation::AnimationTreeNodeKind,
    out: &mut String,
) -> String {
    match kind {
        perro_animation::AnimationTreeNodeKind::Blend {
            inputs,
            weights,
            mask,
        } => format!(
            "AnimationTreeNodeKind::Blend {{ inputs: Cow::Borrowed({}), weights: Cow::Borrowed({}), mask: {} }}",
            refs(id, idx, "INPUTS", inputs, out),
            weights_ref(id, idx, weights, out),
            mask_ref(id, idx, mask, out)
        ),
        perro_animation::AnimationTreeNodeKind::Add {
            base,
            inputs,
            weights,
            mask,
        } => format!(
            "AnimationTreeNodeKind::Add {{ base: Cow::Borrowed(\"{}\"), inputs: Cow::Borrowed({}), weights: Cow::Borrowed({}), mask: {} }}",
            esc(base.as_ref()),
            refs(id, idx, "INPUTS", inputs, out),
            weights_ref(id, idx, weights, out),
            mask_ref(id, idx, mask, out)
        ),
        perro_animation::AnimationTreeNodeKind::Invert { input, mask } => format!(
            "AnimationTreeNodeKind::Invert {{ input: Cow::Borrowed(\"{}\"), mask: {} }}",
            esc(input.as_ref()),
            mask_ref(id, idx, mask, out)
        ),
    }
}

fn refs(
    id: &str,
    idx: usize,
    label: &str,
    values: &[Cow<'static, str>],
    out: &mut String,
) -> String {
    if values.is_empty() {
        return "EMPTY_REFS".to_string();
    }
    let name = format!("{label}_{id}_{idx}");
    let _ = writeln!(out, "const {name}: &[Cow<'static, str>] = &[");
    for value in values {
        let _ = writeln!(out, "    Cow::Borrowed(\"{}\"),", esc(value.as_ref()));
    }
    out.push_str("];\n");
    name
}

fn weights_ref(id: &str, idx: usize, values: &[f32], out: &mut String) -> String {
    if values.is_empty() {
        return "EMPTY_WEIGHTS".to_string();
    }
    let name = format!("WEIGHTS_{id}_{idx}");
    let _ = writeln!(out, "const {name}: &[f32] = &[");
    for value in values {
        let _ = writeln!(out, "    f32::from_bits(0x{:08X}),", value.to_bits());
    }
    out.push_str("];\n");
    name
}

fn mask_ref(
    id: &str,
    idx: usize,
    mask: &perro_animation::AnimationTreeMask,
    out: &mut String,
) -> String {
    format!(
        "AnimationTreeMask {{ objects: Cow::Borrowed({}), fields: Cow::Borrowed({}), bones: Cow::Borrowed({}) }}",
        refs(id, idx, "MASK_OBJECTS", &mask.objects, out),
        refs(id, idx, "MASK_FIELDS", &mask.fields, out),
        refs(id, idx, "MASK_BONES", &mask.bones, out)
    )
}

fn sanitize_ident(path: &str) -> String {
    path.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn esc(input: &str) -> String {
    input.replace('\\', "\\\\").replace('"', "\\\"")
}
