use crate::{StaticPipelineError, res_dir, static_dir};
use perro_animation::{AnimationBoneSelector, AnimationEvent, AnimationEventScope, AnimationParam, AnimationTrackValue};
use perro_io::walkdir::collect_file_paths;
use perro_scene::NodeField;
use rayon::prelude::*;
use std::{fmt::Write as _, fs, io, path::Path};

#[derive(Clone)]
struct ParsedAnimation {
    lookup_key: String,
    clip: perro_animation::AnimationClip,
}

pub fn generate_static_animations(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    fs::create_dir_all(&static_dir)?;

    let mut anim_paths = Vec::<String>::new();
    if res_dir.exists() {
        anim_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| Path::new(rel).extension().and_then(|e| e.to_str()) == Some("panim"))
            .collect();
    }
    anim_paths.sort();

    let mut parsed = anim_paths
        .par_iter()
        .map(|rel| -> io::Result<ParsedAnimation> {
            let source = res_dir.join(rel);
            let text = fs::read_to_string(&source)?;
            let clip = perro_animation::parse_panim(&text).map_err(io::Error::other)?;
            Ok(ParsedAnimation {
                lookup_key: format!("res://{rel}"),
                clip,
            })
        })
        .collect::<io::Result<Vec<_>>>()?;
    parsed.sort_by(|a, b| a.lookup_key.cmp(&b.lookup_key));

    let mut src = String::new();
    src.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    src.push_str("#![allow(unused_imports)]\n#![allow(dead_code)]\n\n");
    src.push_str("use perro_animation::*;\n");
    src.push_str("use perro_scene::*;\n");
    src.push_str("use perro_structs::*;\n");
    src.push_str("use std::borrow::Cow;\n\n");
    src.push_str("const EMPTY_ANIMATION_OBJECTS: &[AnimationObject] = &[];\n");
    src.push_str("const EMPTY_ANIMATION_TRACKS: &[AnimationObjectTrack] = &[];\n");
    src.push_str("const EMPTY_ANIMATION_KEYS: &[AnimationObjectKey] = &[];\n");
    src.push_str("const EMPTY_ANIMATION_PARAMS: &[AnimationParam] = &[];\n");
    src.push_str("const EMPTY_ANIMATION_EVENTS: &[AnimationFrameEvent] = &[];\n\n");

    let mut lookup = String::new();
    lookup.push_str("pub fn lookup_animation(path: &str) -> Option<&'static AnimationClip> {\n");
    lookup.push_str("    match path {\n");

    for anim in &parsed {
        src.push_str(&emit_static_animation_const(&anim.lookup_key, &anim.clip)?);
        let _ = writeln!(
            lookup,
            "        \"{}\" => Some(&CLIP_{}),",
            escape_str(&anim.lookup_key),
            sanitize_ident(&anim.lookup_key)
        );
    }
    lookup.push_str("        _ => None,\n");
    lookup.push_str("    }\n");
    lookup.push_str("}\n");

    src.push('\n');
    src.push_str(&lookup);
    fs::write(static_dir.join("animations.rs"), src)?;
    Ok(())
}

fn emit_static_animation_const(
    path: &str,
    clip: &perro_animation::AnimationClip,
) -> Result<String, StaticPipelineError> {
    let id = sanitize_ident(path);
    let mut out = String::new();

    let mut tracks_buf = String::new();
    let mut track_entries = String::new();
    for (index, track) in clip.object_tracks.iter().enumerate() {
        let key_const = format!("TRACK_KEYS_{id}_{index}");
        let _ = writeln!(tracks_buf, "const {key_const}: &[AnimationObjectKey] = &[");
        for key in track.keys.as_ref() {
            let _ = writeln!(
                tracks_buf,
                "    AnimationObjectKey {{ frame: {}, interpolation: {}, ease: {}, value: {} }},",
                key.frame,
                emit_interpolation(key.interpolation),
                emit_ease(key.ease),
                emit_track_value(&key.value)
            );
        }
        tracks_buf.push_str("];\n");

        let field_expr = emit_node_field(track.field)?;
        let _ = writeln!(
            track_entries,
            "    AnimationObjectTrack {{ object: Cow::Borrowed(\"{}\"), field: {}, bone_target: {}, interpolation: {}, ease: {}, keys: Cow::Borrowed({}) }},",
            escape_str(track.object.as_ref()),
            field_expr,
            emit_bone_target(&track.bone_target),
            emit_interpolation(track.interpolation),
            emit_ease(track.ease),
            if track.keys.is_empty() {
                "EMPTY_ANIMATION_KEYS".to_string()
            } else {
                key_const
            }
        );
    }
    out.push_str(&tracks_buf);

    let tracks_const = format!("TRACKS_{id}");
    let _ = writeln!(out, "const {tracks_const}: &[AnimationObjectTrack] = &[");
    out.push_str(&track_entries);
    out.push_str("];\n\n");

    let objects_const = format!("OBJECTS_{id}");
    let _ = writeln!(out, "const {objects_const}: &[AnimationObject] = &[");
    for object in clip.objects.as_ref() {
        let _ = writeln!(
            out,
            "    AnimationObject {{ name: Cow::Borrowed(\"{}\"), node_type: Cow::Borrowed(\"{}\") }},",
            escape_str(object.name.as_ref()),
            escape_str(object.node_type.as_ref())
        );
    }
    out.push_str("];\n\n");

    let mut events_buf = String::new();
    let mut event_entries = String::new();
    for (index, event) in clip.frame_events.iter().enumerate() {
        let params_const = format!("EVENT_PARAMS_{id}_{index}");
        let emitted_event = match &event.event {
            AnimationEvent::EmitSignal { name, params } => {
                if !params.is_empty() {
                    let _ = writeln!(events_buf, "const {params_const}: &[AnimationParam] = &[");
                    for param in params.as_ref() {
                        let _ = writeln!(events_buf, "    {},", emit_param(param));
                    }
                    events_buf.push_str("];\n");
                }
                format!(
                    "AnimationEvent::EmitSignal {{ name: Cow::Borrowed(\"{}\"), params: Cow::Borrowed({}) }}",
                    escape_str(name.as_ref()),
                    if params.is_empty() {
                        "EMPTY_ANIMATION_PARAMS".to_string()
                    } else {
                        params_const
                    }
                )
            }
            AnimationEvent::SetVar { name, value } => format!(
                "AnimationEvent::SetVar {{ name: Cow::Borrowed(\"{}\"), value: {} }}",
                escape_str(name.as_ref()),
                emit_param(value)
            ),
            AnimationEvent::CallMethod { name, params } => {
                if !params.is_empty() {
                    let _ = writeln!(events_buf, "const {params_const}: &[AnimationParam] = &[");
                    for param in params.as_ref() {
                        let _ = writeln!(events_buf, "    {},", emit_param(param));
                    }
                    events_buf.push_str("];\n");
                }
                format!(
                    "AnimationEvent::CallMethod {{ name: Cow::Borrowed(\"{}\"), params: Cow::Borrowed({}) }}",
                    escape_str(name.as_ref()),
                    if params.is_empty() {
                        "EMPTY_ANIMATION_PARAMS".to_string()
                    } else {
                        params_const
                    }
                )
            }
        };
        let _ = writeln!(
            event_entries,
            "    AnimationFrameEvent {{ frame: {}, scope: {}, event: {} }},",
            event.frame,
            emit_event_scope(&event.scope),
            emitted_event
        );
    }
    out.push_str(&events_buf);

    let events_const = format!("FRAME_EVENTS_{id}");
    let _ = writeln!(out, "const {events_const}: &[AnimationFrameEvent] = &[");
    out.push_str(&event_entries);
    out.push_str("];\n\n");

    let _ = writeln!(
        out,
        "pub static CLIP_{id}: AnimationClip = AnimationClip {{ name: Cow::Borrowed(\"{}\"), fps: {}, total_frames: {}, objects: Cow::Borrowed({}), object_tracks: Cow::Borrowed({}), frame_events: Cow::Borrowed({}) }};\n",
        escape_str(clip.name.as_ref()),
        emit_f32(clip.fps),
        clip.total_frames,
        if clip.objects.is_empty() {
            "EMPTY_ANIMATION_OBJECTS".to_string()
        } else {
            objects_const
        },
        if clip.object_tracks.is_empty() {
            "EMPTY_ANIMATION_TRACKS".to_string()
        } else {
            tracks_const
        },
        if clip.frame_events.is_empty() {
            "EMPTY_ANIMATION_EVENTS".to_string()
        } else {
            events_const
        }
    );

    Ok(out)
}

fn emit_node_field(field: NodeField) -> Result<String, StaticPipelineError> {
    let debug = format!("{field:?}");
    let (variant, inner) = debug
        .split_once('(')
        .ok_or_else(|| StaticPipelineError::SceneParse(format!("unsupported node field: {debug}")))?;
    let inner = inner.strip_suffix(')').ok_or_else(|| {
        StaticPipelineError::SceneParse(format!("unsupported node field variant: {debug}"))
    })?;
    Ok(format!(
        "NodeField::{variant}({variant}Field::{inner})"
    ))
}

fn emit_track_value(value: &AnimationTrackValue) -> String {
    match value {
        AnimationTrackValue::Bool(v) => format!("AnimationTrackValue::Bool({v})"),
        AnimationTrackValue::I32(v) => format!("AnimationTrackValue::I32({v})"),
        AnimationTrackValue::U32(v) => format!("AnimationTrackValue::U32({v})"),
        AnimationTrackValue::F32(v) => format!("AnimationTrackValue::F32({})", emit_f32(*v)),
        AnimationTrackValue::Vec2(v) => format!(
            "AnimationTrackValue::Vec2([{}, {}])",
            emit_f32(v[0]),
            emit_f32(v[1])
        ),
        AnimationTrackValue::Vec3(v) => format!(
            "AnimationTrackValue::Vec3([{}, {}, {}])",
            emit_f32(v[0]),
            emit_f32(v[1]),
            emit_f32(v[2])
        ),
        AnimationTrackValue::Vec4(v) => format!(
            "AnimationTrackValue::Vec4([{}, {}, {}, {}])",
            emit_f32(v[0]),
            emit_f32(v[1]),
            emit_f32(v[2]),
            emit_f32(v[3])
        ),
        AnimationTrackValue::AssetPath(v) => format!(
            "AnimationTrackValue::AssetPath(Cow::Borrowed(\"{}\"))",
            escape_str(v.as_ref())
        ),
        AnimationTrackValue::Transform2D(v) => format!(
            "AnimationTrackValue::Transform2D(Transform2D {{ position: Vector2 {{ x: {}, y: {} }}, scale: Vector2 {{ x: {}, y: {} }}, rotation: {} }})",
            emit_f32(v.position.x),
            emit_f32(v.position.y),
            emit_f32(v.scale.x),
            emit_f32(v.scale.y),
            emit_f32(v.rotation)
        ),
        AnimationTrackValue::Transform3D(v) => format!(
            "AnimationTrackValue::Transform3D(Transform3D {{ position: Vector3 {{ x: {}, y: {}, z: {} }}, scale: Vector3 {{ x: {}, y: {}, z: {} }}, rotation: Quaternion {{ x: {}, y: {}, z: {}, w: {} }} }})",
            emit_f32(v.position.x),
            emit_f32(v.position.y),
            emit_f32(v.position.z),
            emit_f32(v.scale.x),
            emit_f32(v.scale.y),
            emit_f32(v.scale.z),
            emit_f32(v.rotation.x),
            emit_f32(v.rotation.y),
            emit_f32(v.rotation.z),
            emit_f32(v.rotation.w)
        ),
    }
}

fn emit_param(value: &AnimationParam) -> String {
    match value {
        AnimationParam::Bool(v) => format!("AnimationParam::Bool({v})"),
        AnimationParam::I32(v) => format!("AnimationParam::I32({v})"),
        AnimationParam::U32(v) => format!("AnimationParam::U32({v})"),
        AnimationParam::F32(v) => format!("AnimationParam::F32({})", emit_f32(*v)),
        AnimationParam::Vec2(v) => format!(
            "AnimationParam::Vec2([{}, {}])",
            emit_f32(v[0]),
            emit_f32(v[1])
        ),
        AnimationParam::Vec3(v) => format!(
            "AnimationParam::Vec3([{}, {}, {}])",
            emit_f32(v[0]),
            emit_f32(v[1]),
            emit_f32(v[2])
        ),
        AnimationParam::Vec4(v) => format!(
            "AnimationParam::Vec4([{}, {}, {}, {}])",
            emit_f32(v[0]),
            emit_f32(v[1]),
            emit_f32(v[2]),
            emit_f32(v[3])
        ),
        AnimationParam::String(v) => format!(
            "AnimationParam::String(Cow::Borrowed(\"{}\"))",
            escape_str(v.as_ref())
        ),
        AnimationParam::Transform2D(v) => format!(
            "AnimationParam::Transform2D(Transform2D {{ position: Vector2 {{ x: {}, y: {} }}, scale: Vector2 {{ x: {}, y: {} }}, rotation: {} }})",
            emit_f32(v.position.x),
            emit_f32(v.position.y),
            emit_f32(v.scale.x),
            emit_f32(v.scale.y),
            emit_f32(v.rotation)
        ),
        AnimationParam::Transform3D(v) => format!(
            "AnimationParam::Transform3D(Transform3D {{ position: Vector3 {{ x: {}, y: {}, z: {} }}, scale: Vector3 {{ x: {}, y: {}, z: {} }}, rotation: Quaternion {{ x: {}, y: {}, z: {}, w: {} }} }})",
            emit_f32(v.position.x),
            emit_f32(v.position.y),
            emit_f32(v.position.z),
            emit_f32(v.scale.x),
            emit_f32(v.scale.y),
            emit_f32(v.scale.z),
            emit_f32(v.rotation.x),
            emit_f32(v.rotation.y),
            emit_f32(v.rotation.z),
            emit_f32(v.rotation.w)
        ),
        AnimationParam::ObjectNode(v) => format!(
            "AnimationParam::ObjectNode(Cow::Borrowed(\"{}\"))",
            escape_str(v.as_ref())
        ),
        AnimationParam::ObjectField { object, field } => format!(
            "AnimationParam::ObjectField {{ object: Cow::Borrowed(\"{}\"), field: Cow::Borrowed(\"{}\") }}",
            escape_str(object.as_ref()),
            escape_str(field.as_ref())
        ),
    }
}

fn emit_bone_target(target: &Option<perro_animation::AnimationBoneTarget>) -> String {
    match target {
        Some(target) => format!(
            "Some(AnimationBoneTarget {{ selector: {} }})",
            emit_bone_selector(&target.selector)
        ),
        None => "None".to_string(),
    }
}

fn emit_bone_selector(selector: &AnimationBoneSelector) -> String {
    match selector {
        AnimationBoneSelector::Index(v) => format!("AnimationBoneSelector::Index({v})"),
        AnimationBoneSelector::Name(v) => format!(
            "AnimationBoneSelector::Name(Cow::Borrowed(\"{}\"))",
            escape_str(v.as_ref())
        ),
    }
}

fn emit_interpolation(value: perro_animation::AnimationInterpolation) -> String {
    format!("AnimationInterpolation::{value:?}")
}

fn emit_ease(value: perro_animation::AnimationEase) -> String {
    format!("AnimationEase::{value:?}")
}

fn emit_event_scope(scope: &AnimationEventScope) -> String {
    match scope {
        AnimationEventScope::Global => "AnimationEventScope::Global".to_string(),
        AnimationEventScope::Object(object) => format!(
            "AnimationEventScope::Object(Cow::Borrowed(\"{}\"))",
            escape_str(object.as_ref())
        ),
    }
}

fn emit_f32(value: f32) -> String {
    format!("f32::from_bits(0x{:08X})", value.to_bits())
}

fn sanitize_ident(path: &str) -> String {
    let mut out = String::new();
    for c in path.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_uppercase());
        } else {
            out.push('_');
        }
    }
    out
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    const TEST_PANIM_SRC: &str = r#"
[Animation]
name = "PipelineClip"
fps = 24
[/Animation]

[Objects]
@Hero = Node3D
[/Objects]

[Frame0]
@Hero {
    position = (0,0,0)
}
[/Frame0]
"#;

    fn unique_temp_dir(label: &str) -> PathBuf {
        let ts = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        std::env::temp_dir().join(format!("perro_static_pipeline_{label}_{ts}"))
    }

    #[test]
    fn static_animation_pipeline_generates_fully_static_lookup() {
        let root = unique_temp_dir("animations");
        let source_rel = Path::new("animations").join("hero_run.panim");
        let source_abs = root.join("res").join(&source_rel);
        std::fs::create_dir_all(source_abs.parent().expect("source parent should exist"))
            .expect("failed to create source parent");
        std::fs::write(&source_abs, TEST_PANIM_SRC).expect("failed to write source panim");

        generate_static_animations(&root).expect("static animation generation should succeed");

        let embedded_abs = root
            .join(".perro")
            .join("project")
            .join("embedded")
            .join("animations")
            .join(&source_rel);
        assert!(
            !embedded_abs.exists(),
            "static animation generation should not emit embedded .panim sources"
        );

        let generated_rs = root
            .join(".perro")
            .join("project")
            .join("src")
            .join("static")
            .join("animations.rs");
        let generated_src =
            std::fs::read_to_string(generated_rs).expect("generated animations.rs should exist");
        assert!(generated_src.contains("pub fn lookup_animation(path: &str)"));
        assert!(generated_src.contains("\"res://animations/hero_run.panim\""));
        assert!(generated_src.contains("pub static CLIP_RES___ANIMATIONS_HERO_RUN_PANIM"));
        assert!(!generated_src.contains("parse_panim"));
        assert!(!generated_src.contains("include_str!"));
    }
}
