use crate::{
    StaticPipelineError, asset_uri, embedded_dir, ensure_unique_hashes, res_dir, static_dir,
};
use perro_io::{compress_zlib_best, walkdir::collect_file_paths};
use rayon::prelude::*;
use std::{
    fmt::Write as _,
    fs, io,
    path::{Path, PathBuf},
};

const AUDIO_EXTENSIONS: &[&str] = &["mp3", "wav", "ogg", "flac", "aac", "m4a"];
const PAWDIO_MAGIC: &[u8; 6] = b"PAWDIO";
const PAWDIO_VERSION: u32 = 2;
const FLAG_ZLIB: u32 = 1;

pub fn generate_static_audios(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    let embedded_audios_dir = embedded_dir(project_root).join("audios");
    fs::create_dir_all(&static_dir)?;
    fs::create_dir_all(&embedded_audios_dir)?;

    let mut audio_paths = Vec::<String>::new();
    if res_dir.exists() {
        audio_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .map(|ext| ext.to_ascii_lowercase())
                    .is_some_and(|ext| AUDIO_EXTENSIONS.contains(&ext.as_str()))
            })
            .collect();
    }
    audio_paths.sort();

    let mut encoded = audio_paths
        .into_par_iter()
        .map(|rel| -> io::Result<(String, String, Vec<u8>)> {
            let res_path = asset_uri(&rel);
            let full_path = res_dir.join(&rel);
            let raw = fs::read(&full_path)?;
            let (flags, payload) = select_pawdio_payload(&raw)?;

            let mut pawdio = Vec::with_capacity(18 + payload.len());
            pawdio.extend_from_slice(PAWDIO_MAGIC);
            pawdio.extend_from_slice(&PAWDIO_VERSION.to_le_bytes());
            pawdio.extend_from_slice(&flags.to_le_bytes());
            pawdio.extend_from_slice(&(raw.len() as u32).to_le_bytes());
            pawdio.extend_from_slice(&payload);

            let mut rel_pawdio = PathBuf::from(&rel);
            rel_pawdio.set_extension("pawdio");
            let rel_pawdio = rel_pawdio.to_string_lossy().replace('\\', "/");
            Ok((res_path, rel_pawdio, pawdio))
        })
        .collect::<io::Result<Vec<_>>>()?;
    encoded.sort_by(|a, b| a.0.cmp(&b.0));

    let mut audios = Vec::<(String, String)>::with_capacity(encoded.len());
    for (res_path, rel_pawdio, pawdio) in encoded {
        let output_path = embedded_audios_dir.join(&rel_pawdio);
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&output_path, pawdio)?;
        audios.push((res_path, rel_pawdio));
    }
    audios.sort_by(|a, b| a.0.cmp(&b.0));
    ensure_unique_hashes("audio", audios.iter().map(|(path, _)| path.as_str()))?;

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n\n");
    for (index, (_res_path, rel_pawdio)) in audios.iter().enumerate() {
        let include_path = format!("../../embedded/audios/{}", escape_str(rel_pawdio));
        let _ = writeln!(
            out,
            "static AUDIO_{index}: &[u8] = include_bytes!(\"{include_path}\");"
        );
    }
    if !audios.is_empty() {
        out.push('\n');
    }
    out.push_str("static EMPTY_AUDIO: &[u8] = b\"\";\n\n");
    out.push_str("pub const fn lookup_audio(path_hash: u64) -> &'static [u8] {\n");
    out.push_str("    match path_hash {\n");
    for (index, (res_path, _)) in audios.iter().enumerate() {
        let path_hash = perro_ids::string_to_u64(res_path);
        let _ = writeln!(out, "        {path_hash}u64 => AUDIO_{index},");
    }
    out.push_str("        _ => EMPTY_AUDIO,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("audios.rs"), out)?;
    Ok(())
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

fn select_pawdio_payload(raw: &[u8]) -> io::Result<(u32, Vec<u8>)> {
    let compressed = compress_zlib_best(raw)?;
    if compressed.len() < raw.len() {
        Ok((FLAG_ZLIB, compressed))
    } else {
        Ok((0u32, raw.to_vec()))
    }
}

#[cfg(test)]
mod tests {
    use super::{FLAG_ZLIB, select_pawdio_payload};

    #[test]
    fn select_payload_prefers_compressed_when_smaller() {
        let raw = vec![0u8; 8192];
        let (flags, payload) = select_pawdio_payload(&raw).expect("payload selection should work");
        assert_eq!(flags, FLAG_ZLIB);
        assert!(payload.len() < raw.len());
    }

    #[test]
    fn select_payload_prefers_raw_when_compressed_not_smaller() {
        let raw = (0..=255u8).cycle().take(1025).collect::<Vec<_>>();
        let (flags, payload) = select_pawdio_payload(&raw).expect("payload selection should work");
        if flags == FLAG_ZLIB {
            assert!(payload.len() < raw.len());
        } else {
            assert_eq!(flags, 0);
            assert_eq!(payload, raw);
        }
    }
}
