use crate::{StaticPipelineError, ensure_unique_hashes, res_dir, static_dir};
use perro_io::{compress_zlib_best, decompress_zlib, walkdir::collect_file_paths};
use perro_scene::{Parser, SceneNodeData, SceneValue};
use std::{
    collections::{BTreeMap, BTreeSet, HashMap},
    fmt::Write as _,
    fs,
    path::Path,
};

const PMESH_MAGIC: &[u8; 5] = b"PMESH";
const PMESH_VERSION_V6: u32 = 6;
const PMESH_VERSION_V7: u32 = 7;
const PMESH_FLAG_INDEX_U16: u32 = 1 << 4;

pub fn generate_static_collision_trimeshes(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_root = res_dir(project_root);
    let static_root = static_dir(project_root);
    let embedded_dir = crate::embedded_dir(project_root).join("collision_trimeshes");
    fs::create_dir_all(&static_root)?;
    fs::create_dir_all(&embedded_dir)?;

    let sources = collect_collision_trimesh_sources(&res_root)?;
    ensure_unique_hashes("collision_trimesh", sources.iter().map(String::as_str))?;

    let mut packed = Vec::<(String, Vec<u8>)>::new();
    for source in &sources {
        let (verts, tris) = load_trimesh_from_source(&res_root, source)
            .ok_or_else(|| StaticPipelineError::SceneParse(format!("failed to load collision trimesh source `{source}`")))?;
        let (verts, tris) = simplify_trimesh_data(verts, tris)
            .ok_or_else(|| StaticPipelineError::SceneParse(format!("failed to simplify collision trimesh source `{source}`")))?;
        packed.push((source.clone(), encode_collision_pmesh(&verts, &tris)?));
    }
    packed.sort_by(|a, b| a.0.cmp(&b.0));

    let mut file_by_source = BTreeMap::<String, String>::new();
    for (source, bytes) in &packed {
        let hash = perro_ids::string_to_u64(source);
        let rel = format!("{hash}.pmesh");
        fs::write(embedded_dir.join(&rel), bytes)?;
        file_by_source.insert(source.clone(), rel);
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n");
    out.push_str("#![allow(dead_code)]\n\n");

    let mut unique_rel = Vec::<String>::new();
    let mut rel_to_index = BTreeMap::<String, usize>::new();
    for rel in file_by_source.values() {
        if rel_to_index.contains_key(rel) {
            continue;
        }
        let idx = unique_rel.len();
        rel_to_index.insert(rel.clone(), idx);
        unique_rel.push(rel.clone());
    }

    for (idx, rel) in unique_rel.iter().enumerate() {
        let include_path = format!("../../embedded/collision_trimeshes/{}", escape_str(rel));
        let _ = writeln!(
            out,
            "static COLLISION_TRIMESH_{idx}: &[u8] = include_bytes!(\"{include_path}\");"
        );
    }
    if !unique_rel.is_empty() {
        out.push('\n');
    }
    out.push_str("static EMPTY_COLLISION_TRIMESH: &[u8] = b\"\";\n\n");
    out.push_str("pub const fn lookup_collision_trimesh(path_hash: u64) -> &'static [u8] {\n");
    out.push_str("    match path_hash {\n");
    for source in &sources {
        let rel = file_by_source
            .get(source)
            .expect("collision trimesh rel path missing for source");
        let idx = *rel_to_index
            .get(rel)
            .expect("collision trimesh index missing for rel path");
        let hash = perro_ids::string_to_u64(source);
        let _ = writeln!(out, "        {hash}u64 => COLLISION_TRIMESH_{idx},");
    }
    out.push_str("        _ => EMPTY_COLLISION_TRIMESH,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_root.join("collision_trimeshes.rs"), out)?;
    Ok(())
}

fn collect_collision_trimesh_sources(res_root: &Path) -> Result<Vec<String>, StaticPipelineError> {
    let mut out = BTreeSet::<String>::new();
    if !res_root.exists() {
        return Ok(Vec::new());
    }
    let mut scene_paths = collect_file_paths(res_root, res_root)?;
    scene_paths.sort();
    for rel in scene_paths {
        if !Path::new(&rel)
            .extension()
            .and_then(|e| e.to_str())
            .is_some_and(|ext| ext.eq_ignore_ascii_case("scn"))
        {
            continue;
        }
        let src = fs::read_to_string(res_root.join(&rel))?;
        let scene = std::panic::catch_unwind(|| Parser::new(&src).parse_scene())
            .map_err(|_| StaticPipelineError::SceneParse(format!("failed to parse scene: res://{rel}")))?;
        collect_collision_sources_from_scene(&scene, &mut out);
    }
    Ok(out.into_iter().collect())
}

fn collect_collision_sources_from_scene(scene: &perro_scene::Scene, out: &mut BTreeSet<String>) {
    for node in scene.nodes.as_ref() {
        collect_collision_sources_from_node_data(&node.data, out);
    }
}

fn collect_collision_sources_from_node_data(data: &SceneNodeData, out: &mut BTreeSet<String>) {
    if data.ty.as_ref() != "CollisionShape3D" {
        if let Some(base) = &data.base {
            let base_ref = match base {
                perro_scene::SceneNodeDataBase::Borrowed(v) => *v,
                perro_scene::SceneNodeDataBase::Owned(v) => v.as_ref(),
            };
            collect_collision_sources_from_node_data(base_ref, out);
        }
        return;
    }
    for (name, value) in data.fields.as_ref() {
        let name = name.as_ref();
        if name.eq_ignore_ascii_case("trimesh") {
            if let Some(source) = as_res_asset_source(value) {
                out.insert(source);
            }
            continue;
        }
        if name.eq_ignore_ascii_case("shape") {
            if let Some(source) = extract_trimesh_source_from_shape_value(value) {
                out.insert(source);
            }
        }
    }
    if let Some(base) = &data.base {
        let base_ref = match base {
            perro_scene::SceneNodeDataBase::Borrowed(v) => *v,
            perro_scene::SceneNodeDataBase::Owned(v) => v.as_ref(),
        };
        collect_collision_sources_from_node_data(base_ref, out);
    }
}

fn extract_trimesh_source_from_shape_value(value: &SceneValue) -> Option<String> {
    if let Some(source) = as_res_asset_source(value) {
        return Some(source);
    }
    let SceneValue::Object(entries) = value else {
        return None;
    };
    let mut ty = None::<String>;
    let mut source = None::<String>;
    for (k, v) in entries.as_ref() {
        let key = k.as_ref();
        if (key.eq_ignore_ascii_case("type") || key.eq_ignore_ascii_case("kind"))
            && let SceneValue::Str(raw) = v
        {
            ty = Some(raw.to_ascii_lowercase());
        } else if matches!(key, "source" | "mesh" | "trimesh") {
            source = as_res_asset_source(v);
        }
    }
    let ty = ty?;
    if matches!(ty.as_str(), "trimesh" | "tri_mesh") {
        return source;
    }
    None
}

fn as_res_asset_source(value: &SceneValue) -> Option<String> {
    let raw = match value {
        SceneValue::Str(v) => v.as_ref(),
        _ => return None,
    };
    if !raw.starts_with("res://") {
        return None;
    }
    let (path, _) = split_source_fragment(raw);
    let ext = Path::new(path)
        .extension()
        .and_then(|e| e.to_str())
        .map(|v| v.to_ascii_lowercase())?;
    matches!(ext.as_str(), "pmesh" | "glb" | "gltf").then(|| raw.to_string())
}

type TriMeshData = (Vec<[f32; 3]>, Vec<[u32; 3]>);

fn load_trimesh_from_source(res_root: &Path, source: &str) -> Option<TriMeshData> {
    let (path, fragment) = split_source_fragment(source);
    let mesh_index = if fragment.is_some() {
        parse_fragment_index(fragment, "mesh")?
    } else {
        0
    };
    let rel = path.trim_start_matches("res://");
    let full = res_root.join(rel);
    let bytes = fs::read(full).ok()?;
    if path.ends_with(".pmesh") {
        return decode_pmesh_trimesh(&bytes);
    }
    if path.ends_with(".glb") || path.ends_with(".gltf") {
        return load_trimesh_from_gltf_bytes(&bytes, mesh_index);
    }
    None
}

fn decode_pmesh_trimesh(bytes: &[u8]) -> Option<TriMeshData> {
    if bytes.len() < 33 || &bytes[0..5] != PMESH_MAGIC {
        return None;
    }
    let version = u32::from_le_bytes(bytes[5..9].try_into().ok()?);
    if version != PMESH_VERSION_V6 && version != PMESH_VERSION_V7 {
        return None;
    }
    if version == PMESH_VERSION_V7 {
        decode_pmesh_trimesh_v7(bytes)
    } else {
        decode_pmesh_trimesh_v6(bytes)
    }
}

fn decode_pmesh_trimesh_v6(bytes: &[u8]) -> Option<TriMeshData> {
    let flags = u32::from_le_bytes(bytes[9..13].try_into().ok()?);
    let vertex_count = u32::from_le_bytes(bytes[13..17].try_into().ok()?) as usize;
    let index_count = u32::from_le_bytes(bytes[17..21].try_into().ok()?) as usize;
    let raw_len = u32::from_le_bytes(bytes[29..33].try_into().ok()?) as usize;
    let raw = decompress_zlib(&bytes[33..]).ok()?;
    if raw.len() != raw_len {
        return None;
    }
    let has_normal = (flags & (1 << 0)) != 0;
    let has_uv0 = (flags & (1 << 1)) != 0;
    let has_joints = (flags & (1 << 2)) != 0;
    let has_weights = (flags & (1 << 3)) != 0;
    let stride = 12
        + if has_normal { 12 } else { 0 }
        + if has_uv0 { 8 } else { 0 }
        + if has_joints { 8 } else { 0 }
        + if has_weights { 16 } else { 0 };
    let vertex_bytes = vertex_count.checked_mul(stride)?;
    let index_bytes = index_count.checked_mul(4)?;
    decode_pmesh_trimesh_from_raw(
        raw,
        vertex_count,
        index_count,
        stride,
        vertex_bytes,
        index_bytes,
        false,
    )
}

fn decode_pmesh_trimesh_v7(bytes: &[u8]) -> Option<TriMeshData> {
    let flags = u32::from_le_bytes(bytes[9..13].try_into().ok()?);
    let vertex_count = u32::from_le_bytes(bytes[13..17].try_into().ok()?) as usize;
    let index_count = u32::from_le_bytes(bytes[17..21].try_into().ok()?) as usize;
    let raw_len = u32::from_le_bytes(bytes[29..33].try_into().ok()?) as usize;
    let raw = decompress_zlib(&bytes[33..]).ok()?;
    if raw.len() != raw_len {
        return None;
    }
    let index_u16 = (flags & PMESH_FLAG_INDEX_U16) != 0;
    let vertex_stride = 12usize;
    let vertex_bytes = vertex_count.checked_mul(vertex_stride)?;
    let index_bytes = index_count.checked_mul(if index_u16 { 2 } else { 4 })?;
    decode_pmesh_trimesh_from_raw(
        raw,
        vertex_count,
        index_count,
        vertex_stride,
        vertex_bytes,
        index_bytes,
        index_u16,
    )
}

fn decode_pmesh_trimesh_from_raw(
    raw: Vec<u8>,
    vertex_count: usize,
    index_count: usize,
    vertex_stride: usize,
    vertex_bytes: usize,
    index_bytes: usize,
    index_u16: bool,
) -> Option<TriMeshData> {
    if raw.len() < vertex_bytes + index_bytes {
        return None;
    }
    let mut vertices = Vec::with_capacity(vertex_count);
    for i in 0..vertex_count {
        let off = i * vertex_stride;
        let x = f32::from_le_bytes(raw[off..off + 4].try_into().ok()?);
        let y = f32::from_le_bytes(raw[off + 4..off + 8].try_into().ok()?);
        let z = f32::from_le_bytes(raw[off + 8..off + 12].try_into().ok()?);
        vertices.push([x, y, z]);
    }
    let mut triangles = Vec::new();
    let index_start = vertex_bytes;
    for tri in (0..index_count / 3).map(|i| i * 3) {
        let ia = read_index(raw.as_slice(), index_start, tri, index_u16)?;
        let ib = read_index(raw.as_slice(), index_start, tri + 1, index_u16)?;
        let ic = read_index(raw.as_slice(), index_start, tri + 2, index_u16)?;
        let a = ia as usize;
        let b = ib as usize;
        let c = ic as usize;
        if a >= vertices.len()
            || b >= vertices.len()
            || c >= vertices.len()
            || a == b
            || b == c
            || a == c
        {
            continue;
        }
        triangles.push([ia, ib, ic]);
    }
    if vertices.len() < 3 || triangles.is_empty() {
        return None;
    }
    Some((vertices, triangles))
}

fn read_index(raw: &[u8], index_start: usize, index: usize, index_u16: bool) -> Option<u32> {
    if index_u16 {
        let off = index_start + index * 2;
        Some(u16::from_le_bytes(raw[off..off + 2].try_into().ok()?) as u32)
    } else {
        let off = index_start + index * 4;
        Some(u32::from_le_bytes(raw[off..off + 4].try_into().ok()?))
    }
}

fn load_trimesh_from_gltf_bytes(bytes: &[u8], mesh_index: usize) -> Option<TriMeshData> {
    let (doc, buffers, _images) = gltf::import_slice(bytes).ok()?;
    let mesh = doc.meshes().nth(mesh_index)?;
    let mut vertices = Vec::<[f32; 3]>::new();
    let mut triangles = Vec::<[u32; 3]>::new();
    for primitive in mesh.primitives() {
        let reader = primitive.reader(|buffer| buffers.get(buffer.index()).map(|d| d.0.as_slice()));
        let Some(pos_iter) = reader.read_positions() else {
            continue;
        };
        let local_positions: Vec<[f32; 3]> = pos_iter.collect();
        if local_positions.len() < 3 {
            continue;
        }
        let base = u32::try_from(vertices.len()).ok()?;
        vertices.extend(local_positions.iter().copied());
        if let Some(indices_reader) = reader.read_indices() {
            let mut flat: Vec<u32> = indices_reader.into_u32().collect();
            flat.truncate(flat.len() / 3 * 3);
            for tri in flat.chunks_exact(3) {
                let ia = tri[0] as usize;
                let ib = tri[1] as usize;
                let ic = tri[2] as usize;
                if ia >= local_positions.len() || ib >= local_positions.len() || ic >= local_positions.len() {
                    continue;
                }
                let a = base + tri[0];
                let b = base + tri[1];
                let c = base + tri[2];
                if a != b && b != c && a != c {
                    triangles.push([a, b, c]);
                }
            }
        } else {
            for i in (0..local_positions.len() / 3 * 3).step_by(3) {
                triangles.push([base + i as u32, base + i as u32 + 1, base + i as u32 + 2]);
            }
        }
    }
    if vertices.len() < 3 || triangles.is_empty() {
        return None;
    }
    Some((vertices, triangles))
}

fn encode_collision_pmesh(vertices: &[[f32; 3]], triangles: &[[u32; 3]]) -> Result<Vec<u8>, StaticPipelineError> {
    let use_u16_indices = vertices.len() <= u16::MAX as usize;
    let mut raw = Vec::<u8>::with_capacity(
        vertices.len() * 12 + triangles.len() * if use_u16_indices { 6 } else { 12 },
    );
    for p in vertices {
        raw.extend_from_slice(&p[0].to_le_bytes());
        raw.extend_from_slice(&p[1].to_le_bytes());
        raw.extend_from_slice(&p[2].to_le_bytes());
    }
    for tri in triangles {
        if use_u16_indices {
            raw.extend_from_slice(&(tri[0] as u16).to_le_bytes());
            raw.extend_from_slice(&(tri[1] as u16).to_le_bytes());
            raw.extend_from_slice(&(tri[2] as u16).to_le_bytes());
        } else {
            raw.extend_from_slice(&tri[0].to_le_bytes());
            raw.extend_from_slice(&tri[1].to_le_bytes());
            raw.extend_from_slice(&tri[2].to_le_bytes());
        }
    }
    let compressed = compress_zlib_best(&raw)
        .map_err(|e| StaticPipelineError::SceneParse(format!("collision trimesh compress fail: {e}")))?;
    let mut out = Vec::<u8>::with_capacity(33 + compressed.len());
    out.extend_from_slice(PMESH_MAGIC);
    out.extend_from_slice(&PMESH_VERSION_V7.to_le_bytes());
    let mut flags = 0u32;
    if use_u16_indices {
        flags |= PMESH_FLAG_INDEX_U16;
    }
    out.extend_from_slice(&flags.to_le_bytes());
    out.extend_from_slice(&(vertices.len() as u32).to_le_bytes());
    out.extend_from_slice(&((triangles.len() * 3) as u32).to_le_bytes());
    out.extend_from_slice(&0u32.to_le_bytes());
    out.extend_from_slice(&0u32.to_le_bytes());
    out.extend_from_slice(&(raw.len() as u32).to_le_bytes());
    out.extend_from_slice(&compressed);
    Ok(out)
}

fn simplify_trimesh_data(vertices: Vec<[f32; 3]>, triangles: Vec<[u32; 3]>) -> Option<TriMeshData> {
    let (vertices, triangles) = weld_and_filter_mesh(vertices, triangles)?;
    if let Some(reduced) = simplify_coplanar_mesh(&vertices, &triangles) {
        return weld_and_filter_mesh(reduced.0, reduced.1);
    }
    Some((vertices, triangles))
}

fn weld_and_filter_mesh(vertices: Vec<[f32; 3]>, triangles: Vec<[u32; 3]>) -> Option<TriMeshData> {
    let mut remap = vec![0u32; vertices.len()];
    let mut map = HashMap::<(i64, i64, i64), u32>::new();
    let mut out_vertices = Vec::<[f32; 3]>::new();
    let eps = 0.0001f32;
    for (idx, v) in vertices.iter().enumerate() {
        let key = (
            (v[0] / eps).round() as i64,
            (v[1] / eps).round() as i64,
            (v[2] / eps).round() as i64,
        );
        let out_idx = if let Some(existing) = map.get(&key) {
            *existing
        } else {
            let next = out_vertices.len() as u32;
            map.insert(key, next);
            out_vertices.push(*v);
            next
        };
        remap[idx] = out_idx;
    }

    let mut unique = BTreeSet::<(u32, u32, u32)>::new();
    let mut out_tris = Vec::<[u32; 3]>::new();
    for tri in triangles {
        let a = remap.get(tri[0] as usize).copied()?;
        let b = remap.get(tri[1] as usize).copied()?;
        let c = remap.get(tri[2] as usize).copied()?;
        if a == b || b == c || a == c {
            continue;
        }
        if triangle_area_sq(out_vertices[a as usize], out_vertices[b as usize], out_vertices[c as usize]) <= 1.0e-12 {
            continue;
        }
        let mut ord = [a, b, c];
        ord.sort_unstable();
        if !unique.insert((ord[0], ord[1], ord[2])) {
            continue;
        }
        out_tris.push([a, b, c]);
    }

    if out_vertices.len() < 3 || out_tris.is_empty() {
        return None;
    }
    Some((out_vertices, out_tris))
}

fn simplify_coplanar_mesh(vertices: &[[f32; 3]], triangles: &[[u32; 3]]) -> Option<TriMeshData> {
    if triangles.len() < 16 {
        return None;
    }
    let first = triangles[0];
    let p0 = vertices[first[0] as usize];
    let p1 = vertices[first[1] as usize];
    let p2 = vertices[first[2] as usize];
    let n = cross(sub(p1, p0), sub(p2, p0));
    let n_len = len(n);
    if n_len <= 1.0e-6 {
        return None;
    }
    let n = mul(n, 1.0 / n_len);
    let plane_d = dot(n, p0);
    let plane_eps = 0.0025f32;
    for p in vertices {
        let dist = (dot(n, *p) - plane_d).abs();
        if dist > plane_eps {
            return None;
        }
    }

    let axis = dominant_axis(n);
    let mut pts2d = Vec::<[f32; 2]>::with_capacity(vertices.len());
    for p in vertices {
        pts2d.push(project_axis(*p, axis));
    }

    let mut unique_2d = pts2d.clone();
    unique_2d.sort_by(|a, b| a[0].partial_cmp(&b[0]).unwrap_or(std::cmp::Ordering::Equal).then_with(|| a[1].partial_cmp(&b[1]).unwrap_or(std::cmp::Ordering::Equal)));
    unique_2d.dedup_by(|a, b| (a[0] - b[0]).abs() <= 1.0e-5 && (a[1] - b[1]).abs() <= 1.0e-5);
    if unique_2d.len() < 3 {
        return None;
    }

    let hull = convex_hull_2d(&unique_2d);
    if hull.len() < 3 {
        return None;
    }
    let hull_area = polygon_area_abs(&hull);
    if hull_area <= 1.0e-6 {
        return None;
    }

    let mut tri_area_sum = 0.0f32;
    for tri in triangles {
        let a = pts2d[tri[0] as usize];
        let b = pts2d[tri[1] as usize];
        let c = pts2d[tri[2] as usize];
        tri_area_sum += ((b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0])).abs() * 0.5;
    }
    if tri_area_sum <= 1.0e-6 {
        return None;
    }
    if hull_area > tri_area_sum * 1.1 {
        return None;
    }

    let mut new_vertices = Vec::<[f32; 3]>::with_capacity(hull.len());
    for p in &hull {
        new_vertices.push(unproject_axis_on_plane(*p, axis, n, plane_d));
    }
    let mut new_tris = Vec::<[u32; 3]>::new();
    for i in 1..hull.len() - 1 {
        new_tris.push([0, i as u32, (i + 1) as u32]);
    }
    Some((new_vertices, new_tris))
}

fn dominant_axis(n: [f32; 3]) -> usize {
    let ax = n[0].abs();
    let ay = n[1].abs();
    let az = n[2].abs();
    if ax >= ay && ax >= az {
        0
    } else if ay >= az {
        1
    } else {
        2
    }
}

fn project_axis(p: [f32; 3], axis: usize) -> [f32; 2] {
    match axis {
        0 => [p[1], p[2]],
        1 => [p[0], p[2]],
        _ => [p[0], p[1]],
    }
}

fn convex_hull_2d(points: &[[f32; 2]]) -> Vec<[f32; 2]> {
    let mut pts = points.to_vec();
    pts.sort_by(|a, b| {
        a[0]
            .partial_cmp(&b[0])
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a[1].partial_cmp(&b[1]).unwrap_or(std::cmp::Ordering::Equal))
    });
    if pts.len() <= 3 {
        return pts;
    }
    let mut lower = Vec::<[f32; 2]>::new();
    for p in &pts {
        while lower.len() >= 2
            && cross2(
                sub2(lower[lower.len() - 1], lower[lower.len() - 2]),
                sub2(*p, lower[lower.len() - 1]),
            ) <= 0.0
        {
            lower.pop();
        }
        lower.push(*p);
    }
    let mut upper = Vec::<[f32; 2]>::new();
    for p in pts.iter().rev() {
        while upper.len() >= 2
            && cross2(
                sub2(upper[upper.len() - 1], upper[upper.len() - 2]),
                sub2(*p, upper[upper.len() - 1]),
            ) <= 0.0
        {
            upper.pop();
        }
        upper.push(*p);
    }
    lower.pop();
    upper.pop();
    lower.extend(upper);
    lower
}

fn polygon_area_abs(poly: &[[f32; 2]]) -> f32 {
    if poly.len() < 3 {
        return 0.0;
    }
    let mut area = 0.0f32;
    for i in 0..poly.len() {
        let a = poly[i];
        let b = poly[(i + 1) % poly.len()];
        area += a[0] * b[1] - a[1] * b[0];
    }
    area.abs() * 0.5
}

fn unproject_axis_on_plane(p: [f32; 2], axis: usize, n: [f32; 3], d: f32) -> [f32; 3] {
    match axis {
        0 => {
            let y = p[0];
            let z = p[1];
            let x = (d - n[1] * y - n[2] * z) / n[0].max(1.0e-6).copysign(n[0]);
            [x, y, z]
        }
        1 => {
            let x = p[0];
            let z = p[1];
            let y = (d - n[0] * x - n[2] * z) / n[1].max(1.0e-6).copysign(n[1]);
            [x, y, z]
        }
        _ => {
            let x = p[0];
            let y = p[1];
            let z = (d - n[0] * x - n[1] * y) / n[2].max(1.0e-6).copysign(n[2]);
            [x, y, z]
        }
    }
}

fn triangle_area_sq(a: [f32; 3], b: [f32; 3], c: [f32; 3]) -> f32 {
    let ab = sub(b, a);
    let ac = sub(c, a);
    let cr = cross(ab, ac);
    dot(cr, cr) * 0.25
}

fn sub(a: [f32; 3], b: [f32; 3]) -> [f32; 3] {
    [a[0] - b[0], a[1] - b[1], a[2] - b[2]]
}
fn mul(a: [f32; 3], s: f32) -> [f32; 3] {
    [a[0] * s, a[1] * s, a[2] * s]
}
fn dot(a: [f32; 3], b: [f32; 3]) -> f32 {
    a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
}
fn cross(a: [f32; 3], b: [f32; 3]) -> [f32; 3] {
    [
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    ]
}
fn len(v: [f32; 3]) -> f32 {
    dot(v, v).sqrt()
}
fn sub2(a: [f32; 2], b: [f32; 2]) -> [f32; 2] {
    [a[0] - b[0], a[1] - b[1]]
}
fn cross2(a: [f32; 2], b: [f32; 2]) -> f32 {
    a[0] * b[1] - a[1] * b[0]
}

fn split_source_fragment(source: &str) -> (&str, Option<&str>) {
    let Some((path, selector)) = source.rsplit_once(':') else {
        return (source, None);
    };
    if path.is_empty() || selector.contains('/') || selector.contains('\\') {
        return (source, None);
    }
    if selector.contains('[') && selector.ends_with(']') {
        return (path, Some(selector));
    }
    (source, None)
}

fn parse_fragment_index(fragment: Option<&str>, key: &str) -> Option<usize> {
    let fragment = fragment?;
    let (name, rest) = fragment.split_once('[')?;
    if name.trim() != key {
        return None;
    }
    let value = rest.strip_suffix(']')?.trim();
    value.parse::<usize>().ok()
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}
