use crate::{
    StaticPipelineError, asset_uri, ensure_unique_hashes, escape_rust_str, res_dir, static_dir,
    write_hash_const,
};
use perro_ids::string_to_u64;
use std::{
    collections::HashMap,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

#[derive(Debug)]
struct StaticCsvTable {
    asset_path: String,
    headers: Vec<String>,
    rows: Vec<Vec<String>>,
}

#[derive(Default)]
struct CsvStringPool {
    values: Vec<String>,
    by_value: HashMap<String, usize>,
}

impl CsvStringPool {
    fn intern(&mut self, value: &str) -> usize {
        if let Some(existing) = self.by_value.get(value) {
            return *existing;
        }
        let index = self.values.len();
        self.by_value.insert(value.to_string(), index);
        self.values.push(value.to_string());
        index
    }
}

pub fn generate_static_csvs(project_root: &Path) -> Result<(), StaticPipelineError> {
    let static_dir = static_dir(project_root);
    fs::create_dir_all(&static_dir)?;

    let root = res_dir(project_root);
    let mut paths = Vec::<(String, PathBuf)>::new();
    collect_csv_paths(&root, &root, &mut paths)?;
    paths.sort_by(|a, b| a.0.cmp(&b.0));
    ensure_unique_hashes("csv", paths.iter().map(|(path, _)| path.as_str()))?;

    let mut tables = Vec::with_capacity(paths.len());
    for (asset_path, disk_path) in &paths {
        tables.push(parse_csv_table(asset_path, disk_path)?);
    }

    let mut string_pool = CsvStringPool::default();
    for table in &tables {
        for value in &table.headers {
            string_pool.intern(value);
        }
        for row in &table.rows {
            for value in row {
                string_pool.intern(value);
            }
        }
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n\n");
    out.push_str("use perro_csv::{CsvCell, CsvRow, CsvRowIndex, Csv};\n\n");
    out.push_str("static EMPTY_CSV: Csv = Csv::empty();\n\n");
    emit_string_pool(&mut out, &string_pool);

    for (table_index, table) in tables.iter().enumerate() {
        write_hash_const(
            &mut out,
            &format!("CSV_HASH_{table_index}"),
            &table.asset_path,
        );
        emit_csv_table(&mut out, table_index, table, &string_pool);
    }

    out.push_str("pub const fn lookup_csv(path_hash: u64) -> &'static Csv {\n");
    out.push_str("    match path_hash {\n");
    for (table_index, _) in tables.iter().enumerate() {
        let _ = writeln!(out, "        CSV_HASH_{table_index} => &CSV_{table_index},");
    }
    out.push_str("        _ => &EMPTY_CSV,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("csvs.rs"), out)?;
    Ok(())
}

fn collect_csv_paths(
    root: &Path,
    dir: &Path,
    out: &mut Vec<(String, PathBuf)>,
) -> Result<(), StaticPipelineError> {
    if !dir.exists() {
        return Ok(());
    }
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_csv_paths(root, &path, out)?;
            continue;
        }
        if path.extension().and_then(|ext| ext.to_str()) != Some("csv") {
            continue;
        }
        let rel = path
            .strip_prefix(root)
            .map_err(|err| StaticPipelineError::SceneParse(err.to_string()))?
            .to_string_lossy()
            .replace('\\', "/");
        out.push((asset_uri(&rel), path));
    }
    Ok(())
}

fn parse_csv_table(
    asset_path: &str,
    disk_path: &Path,
) -> Result<StaticCsvTable, StaticPipelineError> {
    let bytes = fs::read(disk_path)?;
    let mut reader = csv::ReaderBuilder::new()
        .has_headers(true)
        .from_reader(bytes.as_slice());
    let headers = reader.headers().map_err(|err| {
        StaticPipelineError::SceneParse(format!("failed to parse csv `{asset_path}`: {err}"))
    })?;
    let header_values: Vec<String> = headers
        .iter()
        .map(|value| value.trim().to_string())
        .collect();

    let mut rows = Vec::new();
    for row in reader.records() {
        let row = row.map_err(|err| {
            StaticPipelineError::SceneParse(format!("failed to parse csv `{asset_path}`: {err}"))
        })?;
        rows.push(row.iter().map(|value| value.trim().to_string()).collect());
    }

    Ok(StaticCsvTable {
        asset_path: asset_path.to_string(),
        headers: header_values,
        rows,
    })
}

fn emit_csv_table(
    out: &mut String,
    table_index: usize,
    table: &StaticCsvTable,
    string_pool: &CsvStringPool,
) {
    emit_cells(
        out,
        &format!("CSV_{table_index}_HEADERS"),
        &table.headers,
        string_pool,
    );

    let mut row_cell_refs = Vec::<usize>::new();
    let mut unique_rows = Vec::<Vec<String>>::new();
    let mut unique_row_by_values = HashMap::<Vec<String>, usize>::new();
    let mut primary_index = Vec::<(u64, usize, String)>::new();
    let mut seen_primary = std::collections::HashSet::<u64>::new();
    for values in &table.rows {
        let row_count = row_cell_refs.len();
        let row_cell_ref = if let Some(existing) = unique_row_by_values.get(values) {
            *existing
        } else {
            let next = unique_rows.len();
            unique_row_by_values.insert(values.clone(), next);
            unique_rows.push(values.clone());
            next
        };
        row_cell_refs.push(row_cell_ref);
        if let Some(first) = values.first() {
            let hash = string_to_u64(first);
            if seen_primary.insert(hash) {
                primary_index.push((hash, row_count, first.clone()));
            }
        }
    }

    for (row_cell_index, values) in unique_rows.iter().enumerate() {
        emit_cells(
            out,
            &format!("CSV_{table_index}_ROW_CELLS_{row_cell_index}"),
            values,
            string_pool,
        );
    }

    let row_count = row_cell_refs.len();
    let _ = writeln!(
        out,
        "static CSV_{table_index}_ROWS: [CsvRow; {row_count}] = ["
    );
    for row_cell_ref in row_cell_refs {
        let _ = writeln!(
            out,
            "    CsvRow::new(&CSV_{table_index}_ROW_CELLS_{row_cell_ref}),"
        );
    }
    out.push_str("];\n\n");

    primary_index.sort_by_key(|entry| entry.0);
    let _ = writeln!(
        out,
        "static CSV_{table_index}_PRIMARY_INDEX: [CsvRowIndex; {}] = [",
        primary_index.len()
    );
    for (hash, row, _key) in primary_index {
        let _ = writeln!(out, "    CsvRowIndex::new({hash}, {row}),");
    }
    out.push_str("];\n\n");

    let _ = writeln!(
        out,
        "static CSV_{table_index}: Csv = Csv::new(&CSV_{table_index}_HEADERS, &CSV_{table_index}_ROWS, &CSV_{table_index}_PRIMARY_INDEX);\n"
    );
}

fn emit_string_pool(out: &mut String, string_pool: &CsvStringPool) {
    for (index, value) in string_pool.values.iter().enumerate() {
        let escaped = escape_rust_str(value);
        let _ = writeln!(out, "static CSV_STR_{index}: &str = \"{escaped}\";");
    }
    if !string_pool.values.is_empty() {
        out.push('\n');
    }
}

fn emit_cells(out: &mut String, name: &str, values: &[String], string_pool: &CsvStringPool) {
    let _ = writeln!(out, "static {name}: [CsvCell; {}] = [", values.len());
    for value in values {
        let string_index = string_pool
            .by_value
            .get(value)
            .expect("csv string must be interned before emit");
        let hash = string_to_u64(value);
        let _ = writeln!(out, "    CsvCell::new(CSV_STR_{string_index}, {hash}),");
    }
    out.push_str("];\n\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn emit_csv_table_reuses_identical_row_cells() {
        let table = StaticCsvTable {
            asset_path: "res://test.csv".to_string(),
            headers: vec!["name".to_string(), "occ".to_string(), "age".to_string()],
            rows: vec![
                vec![
                    "Tiernan".to_string(),
                    "Self EM".to_string(),
                    "22".to_string(),
                ],
                vec!["Aniya".to_string(), "SAHM".to_string(), "22".to_string()],
                vec![
                    "Tiernan".to_string(),
                    "Self EM".to_string(),
                    "22".to_string(),
                ],
            ],
        };
        let mut string_pool = CsvStringPool::default();
        intern_table_strings(&mut string_pool, &table);

        let mut out = String::new();
        emit_string_pool(&mut out, &string_pool);
        emit_csv_table(&mut out, 0, &table, &string_pool);

        assert_eq!(out.matches("static CSV_0_ROW_CELLS_").count(), 2);
        assert_eq!(out.matches("CsvRow::new(&CSV_0_ROW_CELLS_0),").count(), 2);
        assert_eq!(out.matches("CsvRow::new(&CSV_0_ROW_CELLS_1),").count(), 1);
        assert_eq!(out.matches("static CSV_STR_").count(), 8);
        assert_eq!(out.matches("\"22\"").count(), 1);
        assert_eq!(out.matches("\"Tiernan\"").count(), 1);
        assert!(out.contains("static CSV_0_ROWS: [CsvRow; 3]"));
        assert!(out.contains(&format!(
            "CsvRowIndex::new({}, 0),",
            string_to_u64("Tiernan")
        )));
        assert!(out.contains(&format!("CsvRowIndex::new({}, 1),", string_to_u64("Aniya"))));
    }

    #[test]
    fn string_pool_reuses_values_across_tables() {
        let table_a = StaticCsvTable {
            asset_path: "res://a.csv".to_string(),
            headers: vec!["id".to_string(), "name".to_string()],
            rows: vec![vec!["1".to_string(), "Shared".to_string()]],
        };
        let table_b = StaticCsvTable {
            asset_path: "res://b.csv".to_string(),
            headers: vec!["id".to_string(), "label".to_string()],
            rows: vec![vec!["2".to_string(), "Shared".to_string()]],
        };
        let mut string_pool = CsvStringPool::default();
        intern_table_strings(&mut string_pool, &table_a);
        intern_table_strings(&mut string_pool, &table_b);

        let mut out = String::new();
        emit_string_pool(&mut out, &string_pool);
        emit_csv_table(&mut out, 0, &table_a, &string_pool);
        emit_csv_table(&mut out, 1, &table_b, &string_pool);

        assert_eq!(out.matches("\"Shared\"").count(), 1);
        assert_eq!(out.matches("\"id\"").count(), 1);
        assert_eq!(out.matches("CsvCell::new(CSV_STR_").count(), 8);
    }

    #[test]
    fn parse_csv_table_trims_cells() {
        let suffix = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let path = std::env::temp_dir().join(format!(
            "perro_static_csv_dedup_{}_{}.csv",
            std::process::id(),
            suffix
        ));
        fs::write(&path, "name, occ\n Tiernan , Self EM \n").unwrap();

        let table = parse_csv_table("res://test.csv", &path).unwrap();
        let _ = fs::remove_file(path);

        assert_eq!(table.headers, ["name", "occ"]);
        assert_eq!(
            table.rows,
            [vec!["Tiernan".to_string(), "Self EM".to_string()]]
        );
    }

    fn intern_table_strings(string_pool: &mut CsvStringPool, table: &StaticCsvTable) {
        for value in &table.headers {
            string_pool.intern(value);
        }
        for row in &table.rows {
            for value in row {
                string_pool.intern(value);
            }
        }
    }
}
