use crate::{StaticPipelineError, res_dir, static_dir};
use csv::StringRecord;
use perro_ids::string_to_u64;
use perro_project::ProjectConfig;
use std::{collections::BTreeMap, fmt::Write as _, fs, path::Path};

pub fn generate_static_localizations(
    project_root: &Path,
    config: &ProjectConfig,
) -> Result<(), StaticPipelineError> {
    let static_dir = static_dir(project_root);
    fs::create_dir_all(&static_dir)?;

    let Some(localization) = config.localization.as_ref() else {
        return write_empty_localizations(&static_dir);
    };

    let source_rel = localization
        .source_csv
        .strip_prefix("res://")
        .ok_or_else(|| {
            StaticPipelineError::SceneParse(format!(
                "localization source must start with `res://`: {}",
                localization.source_csv
            ))
        })?
        .replace('\\', "/");
    let source_path = res_dir(project_root).join(&source_rel);
    let bytes = fs::read(&source_path).map_err(|err| {
        StaticPipelineError::SceneParse(format!(
            "failed to read localization source `{}`: {err}",
            localization.source_csv
        ))
    })?;

    let mut reader = csv::ReaderBuilder::new()
        .has_headers(true)
        .from_reader(bytes.as_slice());
    let headers = reader.headers().map_err(|err| {
        StaticPipelineError::SceneParse(format!(
            "failed to read localization csv header `{}`: {err}",
            localization.source_csv
        ))
    })?;

    let key_idx = find_header_index(headers, &localization.key_column).ok_or_else(|| {
        StaticPipelineError::SceneParse(format!(
            "localization csv `{}` missing key column `{}`",
            localization.source_csv, localization.key_column
        ))
    })?;

    let mut locales: Vec<(String, usize)> = headers
        .iter()
        .enumerate()
        .filter_map(|(i, name)| {
            if i == key_idx {
                return None;
            }
            let locale = name.trim().to_ascii_lowercase();
            if locale.is_empty() {
                return None;
            }
            Some((locale, i))
        })
        .collect();
    locales.sort_by(|a, b| a.0.cmp(&b.0));

    let mut per_locale: BTreeMap<String, BTreeMap<u64, (String, String)>> = BTreeMap::new();
    let mut key_hashes: BTreeMap<u64, String> = BTreeMap::new();
    for (locale, _) in &locales {
        per_locale.insert(locale.clone(), BTreeMap::new());
    }

    for row in reader.records() {
        let row = row.map_err(|err| {
            StaticPipelineError::SceneParse(format!(
                "failed to parse localization csv row `{}`: {err}",
                localization.source_csv
            ))
        })?;
        let key = row.get(key_idx).unwrap_or("").trim();
        if key.is_empty() {
            continue;
        }
        let hash = string_to_u64(key);
        if let Some(existing_key) = key_hashes.get(&hash)
            && existing_key != key
        {
            return Err(StaticPipelineError::SceneParse(format!(
                "localization hash collision in `{}` between keys `{existing_key}` and `{key}`",
                localization.source_csv
            )));
        }
        key_hashes.insert(hash, key.to_string());

        for (locale, idx) in &locales {
            let value = row.get(*idx).unwrap_or("").to_string();
            let by_hash = per_locale
                .get_mut(locale)
                .expect("locale map must exist for known header");
            if let Some((existing_key, _)) = by_hash.get(&hash)
                && existing_key != key
            {
                return Err(StaticPipelineError::SceneParse(format!(
                    "localization hash collision in `{}` for locale `{locale}` between keys `{existing_key}` and `{key}`",
                    localization.source_csv
                )));
            }
            by_hash.insert(hash, (key.to_string(), value));
        }
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n\n");

    for (hash, key) in &key_hashes {
        let _ = writeln!(
            out,
            "const {}: u64 = perro::ids::string_to_u64(\"{}\");",
            key_const_name(key, *hash),
            escape_str(key)
        );
    }
    if !key_hashes.is_empty() {
        out.push('\n');
    }

    for (locale, by_hash) in &per_locale {
        let fn_name = format!("lookup_locale_{}", sanitize_ident(locale));
        let _ = writeln!(
            out,
            "const fn {fn_name}(key_hash: u64) -> Option<&'static str> {{"
        );
        out.push_str("    match key_hash {\n");
        for (hash, (key, value)) in by_hash {
            let _ = writeln!(
                out,
                "        {} => Some(\"{}\"),",
                key_const_name(key, *hash),
                escape_str(value)
            );
        }
        out.push_str("        _ => None,\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    for (locale, _) in &locales {
        let const_name = format!("LOCALE_HASH_{}", sanitize_ident(locale).to_ascii_uppercase());
        let _ = writeln!(
            out,
            "const {const_name}: u64 = perro::ids::string_to_u64(\"{locale}\");"
        );
    }
    if !locales.is_empty() {
        out.push('\n');
    }

    out.push_str(
        "pub const fn lookup_localized_string(\n    locale: perro::resource_context::sub_apis::Locale,\n    key_hash: u64,\n) -> Option<&'static str> {\n",
    );
    out.push_str("    let locale_hash = perro::ids::string_to_u64(locale.code());\n");
    out.push_str("    match locale_hash {\n");
    for (locale, _) in &locales {
        let fn_name = format!("lookup_locale_{}", sanitize_ident(locale));
        let const_name = format!("LOCALE_HASH_{}", sanitize_ident(locale).to_ascii_uppercase());
        let _ = writeln!(
            out,
            "        {const_name} => {fn_name}(key_hash),"
        );
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("localizations.rs"), out)?;
    Ok(())
}

fn write_empty_localizations(static_dir: &Path) -> Result<(), StaticPipelineError> {
    fs::write(
        static_dir.join("localizations.rs"),
        "// Auto-generated by Perro Static Pipeline. Do not edit.\n\
#![allow(unused_imports)]\n\n\
pub const fn lookup_localized_string(_locale: perro::resource_context::sub_apis::Locale, _key_hash: u64) -> Option<&'static str> {\n\
    None\n\
}\n",
    )?;
    Ok(())
}

fn find_header_index(headers: &StringRecord, expected: &str) -> Option<usize> {
    headers
        .iter()
        .position(|header| header.trim().eq_ignore_ascii_case(expected))
}

fn sanitize_ident(input: &str) -> String {
    let mut out = String::new();
    for c in input.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        return "x".to_string();
    }
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

fn key_const_name(key: &str, hash: u64) -> String {
    format!(
        "KEY_HASH_{}_{}",
        sanitize_ident(key).to_ascii_uppercase(),
        format!("{hash:016X}")
    )
}
