use crate::{StaticPipelineError, res_dir, static_dir};
use perro_io::walkdir::collect_file_paths;
use perro_render_bridge::{
    CustomMaterialParamValue3D, StandardMaterial3D, ToonMaterial3D, UnlitMaterial3D,
};
use perro_scene::{Parser, RuntimeValue};
use rayon::prelude::*;
use std::{collections::HashMap, fmt::Write as _, fs, io, path::Path};

pub fn generate_static_materials(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    fs::create_dir_all(&static_dir)?;

    let mut material_paths = Vec::<String>::new();
    if res_dir.exists() {
        material_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| matches!(ext, "pmat" | "glb" | "gltf"))
            })
            .collect();
    }
    material_paths.sort();

    let mut materials = material_paths
        .into_par_iter()
        .map(|rel| -> io::Result<Vec<(String, MaterialLiteral)>> {
            let res_path = format!("res://{rel}");
            let full_path = res_dir.join(&rel);
            match Path::new(&rel).extension().and_then(|e| e.to_str()) {
                Some("pmat") => {
                    let src = fs::read_to_string(&full_path)?;
                    let material = load_pmat_literal(&src).ok_or_else(|| {
                        io::Error::other(format!(
                            "material `{res_path}` must be an object with at least one valid field"
                        ))
                    })?;
                    Ok(vec![(res_path, material)])
                }
                Some("glb") | Some("gltf") => materials_from_gltf_file(&full_path, &res_path),
                _ => Ok(Vec::new()),
            }
        })
        .collect::<io::Result<Vec<_>>>()?
        .into_iter()
        .flatten()
        .collect::<Vec<_>>();

    materials.sort_by(|a, b| a.0.cmp(&b.0));

    let mut unique_materials = Vec::<MaterialLiteral>::new();
    let mut unique_by_key = HashMap::<MaterialKey, usize>::new();
    let mut material_refs = Vec::<(String, usize)>::with_capacity(materials.len());
    for (path, material) in materials {
        let key = MaterialKey::from(&material);
        let index = if let Some(existing) = unique_by_key.get(&key).copied() {
            existing
        } else {
            let idx = unique_materials.len();
            unique_materials.push(material);
            unique_by_key.insert(key, idx);
            idx
        };
        material_refs.push((path, index));
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n");
    out.push_str(
        "use perro_render_bridge::{CustomMaterial3D, CustomMaterialParam3D, CustomMaterialParamValue3D, Material3D, StandardMaterial3D, ToonMaterial3D, UnlitMaterial3D};\nuse std::borrow::Cow;\n\n",
    );
    for (index, material) in unique_materials.iter().enumerate() {
        let const_name = format!("MATERIAL_{}", index);
        let _ = writeln!(
            out,
            "static {const_name}: Material3D = {};",
            material_literal_to_code(material)
        );
    }
    out.push('\n');
    out.push_str("pub fn lookup_material(path: &str) -> Option<&'static Material3D> {\n");
    out.push_str("    match path {\n");
    for (path, index) in &material_refs {
        let _ = writeln!(
            out,
            "        \"{}\" => Some(&MATERIAL_{}),",
            escape_str(path),
            index
        );
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("materials.rs"), out)?;
    Ok(())
}

#[derive(Clone)]
enum MaterialLiteral {
    Standard(StandardMaterial3D),
    Unlit(UnlitMaterial3D),
    Toon(ToonMaterial3D),
    Custom(CustomMaterialLiteral),
}

#[derive(Clone)]
struct CustomMaterialLiteral {
    shader_path: String,
    params: Vec<CustomParamLiteral>,
}

#[derive(Clone)]
struct CustomParamLiteral {
    name: Option<String>,
    value: CustomMaterialParamValue3D,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
enum MaterialKey {
    Standard(StandardMaterialKey),
    Unlit(UnlitMaterialKey),
    Toon(ToonMaterialKey),
    Custom(CustomMaterialKey),
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct StandardMaterialKey {
    base_color_factor: [u32; 4],
    roughness_factor: u32,
    metallic_factor: u32,
    occlusion_strength: u32,
    emissive_factor: [u32; 3],
    alpha_mode: u32,
    alpha_cutoff: u32,
    double_sided: bool,
    normal_scale: u32,
    base_color_texture: u32,
    metallic_roughness_texture: u32,
    normal_texture: u32,
    occlusion_texture: u32,
    emissive_texture: u32,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct UnlitMaterialKey {
    base_color_factor: [u32; 4],
    emissive_factor: [u32; 3],
    alpha_mode: u32,
    alpha_cutoff: u32,
    double_sided: bool,
    base_color_texture: u32,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct ToonMaterialKey {
    base_color_factor: [u32; 4],
    emissive_factor: [u32; 3],
    alpha_mode: u32,
    alpha_cutoff: u32,
    double_sided: bool,
    band_count: u32,
    rim_strength: u32,
    outline_width: u32,
    base_color_texture: u32,
    ramp_texture: u32,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct CustomMaterialKey {
    shader_path: String,
    params: Vec<CustomParamKey>,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct CustomParamKey {
    name: Option<String>,
    value: CustomParamValueKey,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
enum CustomParamValueKey {
    F32(u32),
    I32(i32),
    Bool(bool),
    Vec2([u32; 2]),
    Vec3([u32; 3]),
    Vec4([u32; 4]),
}

impl From<&MaterialLiteral> for MaterialKey {
    fn from(value: &MaterialLiteral) -> Self {
        match value {
            MaterialLiteral::Standard(v) => MaterialKey::Standard(StandardMaterialKey {
                base_color_factor: [
                    v.base_color_factor[0].to_bits(),
                    v.base_color_factor[1].to_bits(),
                    v.base_color_factor[2].to_bits(),
                    v.base_color_factor[3].to_bits(),
                ],
                roughness_factor: v.roughness_factor.to_bits(),
                metallic_factor: v.metallic_factor.to_bits(),
                occlusion_strength: v.occlusion_strength.to_bits(),
                emissive_factor: [
                    v.emissive_factor[0].to_bits(),
                    v.emissive_factor[1].to_bits(),
                    v.emissive_factor[2].to_bits(),
                ],
                alpha_mode: v.alpha_mode,
                alpha_cutoff: v.alpha_cutoff.to_bits(),
                double_sided: v.double_sided,
                normal_scale: v.normal_scale.to_bits(),
                base_color_texture: v.base_color_texture,
                metallic_roughness_texture: v.metallic_roughness_texture,
                normal_texture: v.normal_texture,
                occlusion_texture: v.occlusion_texture,
                emissive_texture: v.emissive_texture,
            }),
            MaterialLiteral::Unlit(v) => MaterialKey::Unlit(UnlitMaterialKey {
                base_color_factor: [
                    v.base_color_factor[0].to_bits(),
                    v.base_color_factor[1].to_bits(),
                    v.base_color_factor[2].to_bits(),
                    v.base_color_factor[3].to_bits(),
                ],
                emissive_factor: [
                    v.emissive_factor[0].to_bits(),
                    v.emissive_factor[1].to_bits(),
                    v.emissive_factor[2].to_bits(),
                ],
                alpha_mode: v.alpha_mode,
                alpha_cutoff: v.alpha_cutoff.to_bits(),
                double_sided: v.double_sided,
                base_color_texture: v.base_color_texture,
            }),
            MaterialLiteral::Toon(v) => MaterialKey::Toon(ToonMaterialKey {
                base_color_factor: [
                    v.base_color_factor[0].to_bits(),
                    v.base_color_factor[1].to_bits(),
                    v.base_color_factor[2].to_bits(),
                    v.base_color_factor[3].to_bits(),
                ],
                emissive_factor: [
                    v.emissive_factor[0].to_bits(),
                    v.emissive_factor[1].to_bits(),
                    v.emissive_factor[2].to_bits(),
                ],
                alpha_mode: v.alpha_mode,
                alpha_cutoff: v.alpha_cutoff.to_bits(),
                double_sided: v.double_sided,
                band_count: v.band_count,
                rim_strength: v.rim_strength.to_bits(),
                outline_width: v.outline_width.to_bits(),
                base_color_texture: v.base_color_texture,
                ramp_texture: v.ramp_texture,
            }),
            MaterialLiteral::Custom(v) => MaterialKey::Custom(CustomMaterialKey {
                shader_path: v.shader_path.clone(),
                params: v
                    .params
                    .iter()
                    .map(|p| CustomParamKey {
                        name: p.name.clone(),
                        value: match &p.value {
                            CustomMaterialParamValue3D::F32(x) => {
                                CustomParamValueKey::F32(x.to_bits())
                            }
                            CustomMaterialParamValue3D::I32(x) => CustomParamValueKey::I32(*x),
                            CustomMaterialParamValue3D::Bool(x) => {
                                CustomParamValueKey::Bool(*x)
                            }
                            CustomMaterialParamValue3D::Vec2(v) => {
                                CustomParamValueKey::Vec2([v[0].to_bits(), v[1].to_bits()])
                            }
                            CustomMaterialParamValue3D::Vec3(v) => CustomParamValueKey::Vec3([
                                v[0].to_bits(),
                                v[1].to_bits(),
                                v[2].to_bits(),
                            ]),
                            CustomMaterialParamValue3D::Vec4(v) => CustomParamValueKey::Vec4([
                                v[0].to_bits(),
                                v[1].to_bits(),
                                v[2].to_bits(),
                                v[3].to_bits(),
                            ]),
                        },
                    })
                    .collect(),
            }),
        }
    }
}

fn material_from_runtime_value(value: &RuntimeValue) -> Option<MaterialLiteral> {
    let RuntimeValue::Object(entries) = value else {
        return None;
    };
    material_from_runtime_entries(entries)
}

fn material_from_runtime_entries(entries: &[(String, RuntimeValue)]) -> Option<MaterialLiteral> {
    let mut any = false;
    let kind = material_type_from_first_runtime(entries);
    match kind {
        MaterialType::Standard => {
            let mut out = StandardMaterial3D::default();
            apply_standard_runtime_entries(entries, &mut out, &mut any);
            any.then_some(MaterialLiteral::Standard(out))
        }
        MaterialType::Unlit => {
            let mut out = UnlitMaterial3D::default();
            apply_unlit_runtime_entries(entries, &mut out, &mut any);
            any.then_some(MaterialLiteral::Unlit(out))
        }
        MaterialType::Toon => {
            let mut out = ToonMaterial3D::default();
            apply_toon_runtime_entries(entries, &mut out, &mut any);
            any.then_some(MaterialLiteral::Toon(out))
        }
        MaterialType::Custom => {
            let mut out = CustomMaterialLiteral {
                shader_path: String::new(),
                params: Vec::new(),
            };
            apply_custom_runtime_entries(entries, &mut out, &mut any);
            any.then_some(MaterialLiteral::Custom(out))
        }
    }
}

fn load_pmat_literal(source: &str) -> Option<MaterialLiteral> {
    if pmat_looks_like_object(source) {
        if let Some(parsed) =
            std::panic::catch_unwind(|| Parser::new(source).parse_value_literal()).ok()
            && let Some(material) = material_from_runtime_value(&parsed)
        {
            return Some(material);
        }
        return None;
    }

    let entries = parse_pmat_key_values(source)?;
    material_from_runtime_entries(&entries)
}

fn parse_pmat_key_values(text: &str) -> Option<Vec<(String, RuntimeValue)>> {
    let mut entries = Vec::new();
    for raw_line in text.lines() {
        let line = strip_line_comment(raw_line).trim();
        if line.is_empty() {
            continue;
        }
        let (raw_key, raw_value) = line.split_once('=')?;
        let key = raw_key.trim().to_string();
        if key.is_empty() {
            continue;
        }
        let value_text = raw_value.trim().trim_end_matches(',');
        if value_text.is_empty() {
            continue;
        }
        let value = parse_kv_value(value_text)?;
        entries.push((key, value));
    }
    (!entries.is_empty()).then_some(entries)
}

fn strip_line_comment(line: &str) -> &str {
    let bytes = line.as_bytes();
    let mut in_string = false;
    let mut escape = false;
    let mut i = 0usize;
    while i < bytes.len() {
        let b = bytes[i];
        if in_string {
            if escape {
                escape = false;
            } else if b == b'\\' {
                escape = true;
            } else if b == b'"' {
                in_string = false;
            }
            i += 1;
            continue;
        }
        if b == b'"' {
            in_string = true;
            i += 1;
            continue;
        }
        if b == b'#' {
            return &line[..i];
        }
        if b == b'/' && i + 1 < bytes.len() && bytes[i + 1] == b'/' {
            return &line[..i];
        }
        i += 1;
    }
    line
}


fn pmat_looks_like_object(text: &str) -> bool {
    text.lines()
        .map(strip_line_comment)
        .map(str::trim)
        .find(|line| !line.is_empty())
        .is_some_and(|line| line.starts_with('{'))
}

fn parse_kv_value(text: &str) -> Option<RuntimeValue> {
    let text = text.trim();
    if let Some(value) = parse_vec_value(text) {
        return Some(value);
    }
    if text.eq_ignore_ascii_case("true") {
        return Some(RuntimeValue::Bool(true));
    }
    if text.eq_ignore_ascii_case("false") {
        return Some(RuntimeValue::Bool(false));
    }
    if let Some(inner) = text.strip_prefix('"').and_then(|v| v.strip_suffix('"')) {
        return Some(RuntimeValue::Str(inner.to_string()));
    }
    if let Ok(v) = text.parse::<i32>() {
        return Some(RuntimeValue::I32(v));
    }
    if let Ok(v) = text.parse::<f32>() {
        return Some(RuntimeValue::F32(v));
    }
    Some(RuntimeValue::Str(text.to_string()))
}

fn parse_vec_value(text: &str) -> Option<RuntimeValue> {
    let inner = text.strip_prefix('(')?.strip_suffix(')')?;
    let numbers = inner
        .split(',')
        .map(|token| token.trim().parse::<f32>().ok())
        .collect::<Option<Vec<_>>>()?;
    match numbers.as_slice() {
        [x, y] => Some(RuntimeValue::Vec2 { x: *x, y: *y }),
        [x, y, z] => Some(RuntimeValue::Vec3 {
            x: *x,
            y: *y,
            z: *z,
        }),
        [x, y, z, w] => Some(RuntimeValue::Vec4 {
            x: *x,
            y: *y,
            z: *z,
            w: *w,
        }),
        _ => None,
    }
}

fn material_type_from_first_runtime(entries: &[(String, RuntimeValue)]) -> MaterialType {
    let Some((name, value)) = entries.first() else {
        return MaterialType::Standard;
    };
    if !name.eq_ignore_ascii_case("type") {
        return MaterialType::Standard;
    }
    match value {
        RuntimeValue::Str(v) | RuntimeValue::Key(v) => parse_material_type(v),
        _ => MaterialType::Standard,
    }
}

fn parse_material_type(value: &str) -> MaterialType {
    match value {
        "standard" | "Standard" | "pbr" | "PBR" => MaterialType::Standard,
        "unlit" | "Unlit" => MaterialType::Unlit,
        "toon" | "Toon" | "cel" | "Cel" => MaterialType::Toon,
        "custom" | "Custom" => MaterialType::Custom,
        _ => MaterialType::Standard,
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum MaterialType {
    Standard,
    Unlit,
    Toon,
    Custom,
}

fn apply_standard_runtime_entries(
    entries: &[(String, RuntimeValue)],
    out: &mut StandardMaterial3D,
    any: &mut bool,
) {
    for (name, value) in entries {
        match canonical_standard_key(name) {
            Some("roughnessFactor") => set_f32(value, any, |v| out.roughness_factor = v),
            Some("metallicFactor") => set_f32(value, any, |v| out.metallic_factor = v),
            Some("occlusionStrength") => set_f32(value, any, |v| out.occlusion_strength = v),
            Some("emissiveFactor") => set_color3(value, any, |v| out.emissive_factor = v),
            Some("baseColorFactor") => set_color4(value, any, |v| out.base_color_factor = v),
            Some("normalScale") => set_f32(value, any, |v| out.normal_scale = v),
            Some("alphaCutoff") => set_f32(value, any, |v| out.alpha_cutoff = v),
            Some("alphaMode") => set_alpha_mode(value, any, |v| out.alpha_mode = v),
            Some("doubleSided") => set_bool(value, any, |v| out.double_sided = v),
            Some("baseColorTexture") => set_texture_slot(value, any, |v| out.base_color_texture = v),
            Some("metallicRoughnessTexture") => {
                set_texture_slot(value, any, |v| out.metallic_roughness_texture = v)
            }
            Some("normalTexture") => set_texture_slot(value, any, |v| out.normal_texture = v),
            Some("occlusionTexture") => set_texture_slot(value, any, |v| out.occlusion_texture = v),
            Some("emissiveTexture") => set_texture_slot(value, any, |v| out.emissive_texture = v),
            Some("pbrMetallicRoughness") => {
                if let RuntimeValue::Object(inner) = value {
                    apply_standard_runtime_entries(inner, out, any);
                }
            }
            _ => {}
        }
    }
}

fn apply_unlit_runtime_entries(
    entries: &[(String, RuntimeValue)],
    out: &mut UnlitMaterial3D,
    any: &mut bool,
) {
    for (name, value) in entries {
        match canonical_unlit_key(name) {
            Some("baseColorFactor") => set_color4(value, any, |v| out.base_color_factor = v),
            Some("emissiveFactor") => set_color3(value, any, |v| out.emissive_factor = v),
            Some("alphaCutoff") => set_f32(value, any, |v| out.alpha_cutoff = v),
            Some("alphaMode") => set_alpha_mode(value, any, |v| out.alpha_mode = v),
            Some("doubleSided") => set_bool(value, any, |v| out.double_sided = v),
            Some("baseColorTexture") => set_texture_slot(value, any, |v| out.base_color_texture = v),
            _ => {}
        }
    }
}

fn apply_toon_runtime_entries(
    entries: &[(String, RuntimeValue)],
    out: &mut ToonMaterial3D,
    any: &mut bool,
) {
    for (name, value) in entries {
        match canonical_toon_key(name) {
            Some("baseColorFactor") => set_color4(value, any, |v| out.base_color_factor = v),
            Some("emissiveFactor") => set_color3(value, any, |v| out.emissive_factor = v),
            Some("alphaCutoff") => set_f32(value, any, |v| out.alpha_cutoff = v),
            Some("alphaMode") => set_alpha_mode(value, any, |v| out.alpha_mode = v),
            Some("doubleSided") => set_bool(value, any, |v| out.double_sided = v),
            Some("baseColorTexture") => set_texture_slot(value, any, |v| out.base_color_texture = v),
            Some("rampTexture") => set_texture_slot(value, any, |v| out.ramp_texture = v),
            Some("bandCount") => set_u32(value, any, |v| out.band_count = v),
            Some("rimStrength") => set_f32(value, any, |v| out.rim_strength = v),
            Some("outlineWidth") => set_f32(value, any, |v| out.outline_width = v),
            _ => {}
        }
    }
}

fn apply_custom_runtime_entries(
    entries: &[(String, RuntimeValue)],
    out: &mut CustomMaterialLiteral,
    any: &mut bool,
) {
    for (name, value) in entries {
        match canonical_custom_key(name) {
            Some("shaderPath") => {
                if let Some(v) = as_string_value(value) {
                    out.shader_path = v;
                    *any = true;
                }
            }
            Some("params") => {
                if let Some(params) = as_custom_params(value) {
                    out.params = params;
                    *any = true;
                }
            }
            _ => {}
        }
    }
}

fn canonical_standard_key(name: &str) -> Option<&'static str> {
    match name {
        "type" | "Type" => None,
        "roughnessFactor" | "roughness_factor" => Some("roughnessFactor"),
        "metallicFactor" | "metallic_factor" => Some("metallicFactor"),
        "occlusionStrength" | "occlusion_strength" => Some("occlusionStrength"),
        "emissiveFactor" | "emissive_factor" => Some("emissiveFactor"),
        "baseColorFactor" | "base_color_factor" | "color" => Some("baseColorFactor"),
        "normalScale" | "normal_scale" => Some("normalScale"),
        "alphaCutoff" | "alpha_cutoff" => Some("alphaCutoff"),
        "alphaMode" | "alpha_mode" => Some("alphaMode"),
        "doubleSided" | "double_sided" => Some("doubleSided"),
        "baseColorTexture" | "base_color_texture" => Some("baseColorTexture"),
        "metallicRoughnessTexture" | "metallic_roughness_texture" => {
            Some("metallicRoughnessTexture")
        }
        "normalTexture" | "normal_texture" => Some("normalTexture"),
        "occlusionTexture" | "occlusion_texture" => Some("occlusionTexture"),
        "emissiveTexture" | "emissive_texture" => Some("emissiveTexture"),
        "pbrMetallicRoughness" | "pbr_metallic_roughness" => Some("pbrMetallicRoughness"),
        _ => None,
    }
}

fn canonical_unlit_key(name: &str) -> Option<&'static str> {
    match name {
        "type" | "Type" => None,
        "baseColorFactor" | "base_color_factor" | "color" => Some("baseColorFactor"),
        "emissiveFactor" | "emissive_factor" => Some("emissiveFactor"),
        "alphaCutoff" | "alpha_cutoff" => Some("alphaCutoff"),
        "alphaMode" | "alpha_mode" => Some("alphaMode"),
        "doubleSided" | "double_sided" => Some("doubleSided"),
        "baseColorTexture" | "base_color_texture" => Some("baseColorTexture"),
        _ => None,
    }
}

fn canonical_toon_key(name: &str) -> Option<&'static str> {
    match name {
        "type" | "Type" => None,
        "baseColorFactor" | "base_color_factor" | "color" => Some("baseColorFactor"),
        "emissiveFactor" | "emissive_factor" => Some("emissiveFactor"),
        "alphaCutoff" | "alpha_cutoff" => Some("alphaCutoff"),
        "alphaMode" | "alpha_mode" => Some("alphaMode"),
        "doubleSided" | "double_sided" => Some("doubleSided"),
        "baseColorTexture" | "base_color_texture" => Some("baseColorTexture"),
        "rampTexture" | "ramp_texture" => Some("rampTexture"),
        "bandCount" | "band_count" => Some("bandCount"),
        "rimStrength" | "rim_strength" => Some("rimStrength"),
        "outlineWidth" | "outline_width" => Some("outlineWidth"),
        _ => None,
    }
}

fn canonical_custom_key(name: &str) -> Option<&'static str> {
    match name {
        "type" | "Type" => None,
        "shader" | "shaderPath" | "shader_path" | "path" => Some("shaderPath"),
        "params" | "customParams" | "custom_params" => Some("params"),
        _ => None,
    }
}

fn set_f32(value: &RuntimeValue, any: &mut bool, set: impl FnOnce(f32)) {
    if let Some(v) = as_f32(value) {
        set(v);
        *any = true;
    }
}

fn set_u32(value: &RuntimeValue, any: &mut bool, set: impl FnOnce(u32)) {
    if let Some(v) = as_u32(value) {
        set(v);
        *any = true;
    }
}

fn set_bool(value: &RuntimeValue, any: &mut bool, set: impl FnOnce(bool)) {
    if let Some(v) = as_bool(value) {
        set(v);
        *any = true;
    }
}

fn set_alpha_mode(value: &RuntimeValue, any: &mut bool, set: impl FnOnce(u32)) {
    if let Some(v) = as_alpha_mode(value) {
        set(v);
        *any = true;
    }
}

fn set_color4(value: &RuntimeValue, any: &mut bool, set: impl FnOnce([f32; 4])) {
    if let Some(v) = as_color4(value) {
        set(v);
        *any = true;
    }
}

fn set_color3(value: &RuntimeValue, any: &mut bool, set: impl FnOnce([f32; 3])) {
    if let Some(v) = as_color4(value) {
        set([v[0], v[1], v[2]]);
        *any = true;
    }
}

fn set_texture_slot(value: &RuntimeValue, any: &mut bool, set: impl FnOnce(u32)) {
    if let Some(v) = as_texture_slot(value) {
        set(v);
        *any = true;
    }
}

fn as_f32(value: &RuntimeValue) -> Option<f32> {
    match value {
        RuntimeValue::F32(v) => Some(*v),
        RuntimeValue::I32(v) => Some(*v as f32),
        _ => None,
    }
}

fn as_u32(value: &RuntimeValue) -> Option<u32> {
    match value {
        RuntimeValue::I32(v) if *v >= 0 => Some(*v as u32),
        RuntimeValue::F32(v) if *v >= 0.0 => Some(*v as u32),
        _ => None,
    }
}

fn as_bool(value: &RuntimeValue) -> Option<bool> {
    match value {
        RuntimeValue::Bool(v) => Some(*v),
        _ => None,
    }
}

fn as_alpha_mode(value: &RuntimeValue) -> Option<u32> {
    match value {
        RuntimeValue::Str(v) | RuntimeValue::Key(v) => match v.as_str() {
            "OPAQUE" | "opaque" => Some(0),
            "MASK" | "mask" => Some(1),
            "BLEND" | "blend" => Some(2),
            _ => None,
        },
        RuntimeValue::I32(v) if (0..=2).contains(v) => Some(*v as u32),
        _ => None,
    }
}

fn as_color4(value: &RuntimeValue) -> Option<[f32; 4]> {
    match value {
        RuntimeValue::Vec4 { x, y, z, w } => Some([*x, *y, *z, *w]),
        RuntimeValue::Vec3 { x, y, z } => Some([*x, *y, *z, 1.0]),
        _ => None,
    }
}

fn as_texture_slot(value: &RuntimeValue) -> Option<u32> {
    match value {
        RuntimeValue::I32(v) if *v >= 0 => Some(*v as u32),
        RuntimeValue::Object(entries) => {
            entries
                .iter()
                .find_map(|(name, inner)| match name.as_str() {
                    "index" | "slot" => match inner {
                        RuntimeValue::I32(v) if *v >= 0 => Some(*v as u32),
                        _ => None,
                    },
                    _ => None,
                })
        }
        _ => None,
    }
}

fn as_string_value(value: &RuntimeValue) -> Option<String> {
    match value {
        RuntimeValue::Str(v) | RuntimeValue::Key(v) => Some(v.clone()),
        _ => None,
    }
}

fn as_custom_param_value(value: &RuntimeValue) -> Option<CustomMaterialParamValue3D> {
    match value {
        RuntimeValue::Bool(v) => Some(CustomMaterialParamValue3D::Bool(*v)),
        RuntimeValue::I32(v) => Some(CustomMaterialParamValue3D::I32(*v)),
        RuntimeValue::F32(v) => Some(CustomMaterialParamValue3D::F32(*v)),
        RuntimeValue::Vec2 { x, y } => Some(CustomMaterialParamValue3D::Vec2([*x, *y])),
        RuntimeValue::Vec3 { x, y, z } => Some(CustomMaterialParamValue3D::Vec3([*x, *y, *z])),
        RuntimeValue::Vec4 { x, y, z, w } => {
            Some(CustomMaterialParamValue3D::Vec4([*x, *y, *z, *w]))
        }
        _ => None,
    }
}

fn as_custom_params(value: &RuntimeValue) -> Option<Vec<CustomParamLiteral>> {
    match value {
        RuntimeValue::Object(entries) => {
            let mut out = Vec::new();
            for (name, inner) in entries {
                if let Some(val) = as_custom_param_value(inner) {
                    out.push(CustomParamLiteral {
                        name: Some(name.clone()),
                        value: val,
                    });
                }
            }
            Some(out)
        }
        other => as_custom_param_value(other).map(|val| {
            vec![CustomParamLiteral {
                name: None,
                value: val,
            }]
        }),
    }
}

fn material_literal_to_code(material: &MaterialLiteral) -> String {
    match material {
        MaterialLiteral::Standard(m) => format!(
            "Material3D::Standard(StandardMaterial3D {{ base_color_factor: [{:.6}, {:.6}, {:.6}, {:.6}], roughness_factor: {:.6}, metallic_factor: {:.6}, occlusion_strength: {:.6}, emissive_factor: [{:.6}, {:.6}, {:.6}], alpha_mode: {}, alpha_cutoff: {:.6}, double_sided: {}, normal_scale: {:.6}, base_color_texture: {}, metallic_roughness_texture: {}, normal_texture: {}, occlusion_texture: {}, emissive_texture: {} }})",
            m.base_color_factor[0],
            m.base_color_factor[1],
            m.base_color_factor[2],
            m.base_color_factor[3],
            m.roughness_factor,
            m.metallic_factor,
            m.occlusion_strength,
            m.emissive_factor[0],
            m.emissive_factor[1],
            m.emissive_factor[2],
            m.alpha_mode,
            m.alpha_cutoff,
            if m.double_sided { "true" } else { "false" },
            m.normal_scale,
            m.base_color_texture,
            m.metallic_roughness_texture,
            m.normal_texture,
            m.occlusion_texture,
            m.emissive_texture
        ),
        MaterialLiteral::Unlit(m) => format!(
            "Material3D::Unlit(UnlitMaterial3D {{ base_color_factor: [{:.6}, {:.6}, {:.6}, {:.6}], emissive_factor: [{:.6}, {:.6}, {:.6}], alpha_mode: {}, alpha_cutoff: {:.6}, double_sided: {}, base_color_texture: {} }})",
            m.base_color_factor[0],
            m.base_color_factor[1],
            m.base_color_factor[2],
            m.base_color_factor[3],
            m.emissive_factor[0],
            m.emissive_factor[1],
            m.emissive_factor[2],
            m.alpha_mode,
            m.alpha_cutoff,
            if m.double_sided { "true" } else { "false" },
            m.base_color_texture
        ),
        MaterialLiteral::Toon(m) => format!(
            "Material3D::Toon(ToonMaterial3D {{ base_color_factor: [{:.6}, {:.6}, {:.6}, {:.6}], emissive_factor: [{:.6}, {:.6}, {:.6}], alpha_mode: {}, alpha_cutoff: {:.6}, double_sided: {}, band_count: {}, rim_strength: {:.6}, outline_width: {:.6}, base_color_texture: {}, ramp_texture: {} }})",
            m.base_color_factor[0],
            m.base_color_factor[1],
            m.base_color_factor[2],
            m.base_color_factor[3],
            m.emissive_factor[0],
            m.emissive_factor[1],
            m.emissive_factor[2],
            m.alpha_mode,
            m.alpha_cutoff,
            if m.double_sided { "true" } else { "false" },
            m.band_count,
            m.rim_strength,
            m.outline_width,
            m.base_color_texture,
            m.ramp_texture
        ),
        MaterialLiteral::Custom(m) => {
            let params = if m.params.is_empty() {
                "Cow::Borrowed(&[])".to_string()
            } else {
                let mut rendered = String::from("Cow::Borrowed(&[");
                for (i, param) in m.params.iter().enumerate() {
                    if i > 0 {
                        rendered.push_str(", ");
                    }
                    rendered.push_str("CustomMaterialParam3D { name: ");
                    match &param.name {
                        Some(name) => {
                            rendered.push_str(&format!("Some({:?}.into())", name));
                        }
                        None => rendered.push_str("None"),
                    }
                    rendered.push_str(", value: ");
                    rendered.push_str(&custom_param_value_to_code(&param.value));
                    rendered.push_str(" }");
                }
                rendered.push_str("])");
                rendered
            };
            format!(
                "Material3D::Custom(CustomMaterial3D {{ shader_path: Cow::Borrowed({:?}), params: {} }})",
                m.shader_path, params
            )
        }
    }
}

fn custom_param_value_to_code(value: &CustomMaterialParamValue3D) -> String {
    match value {
        CustomMaterialParamValue3D::F32(v) => {
            format!("CustomMaterialParamValue3D::F32({:.6})", v)
        }
        CustomMaterialParamValue3D::I32(v) => format!("CustomMaterialParamValue3D::I32({})", v),
        CustomMaterialParamValue3D::Bool(v) => format!(
            "CustomMaterialParamValue3D::Bool({})",
            if *v { "true" } else { "false" }
        ),
        CustomMaterialParamValue3D::Vec2(v) => format!(
            "CustomMaterialParamValue3D::Vec2([{:.6}, {:.6}])",
            v[0], v[1]
        ),
        CustomMaterialParamValue3D::Vec3(v) => format!(
            "CustomMaterialParamValue3D::Vec3([{:.6}, {:.6}, {:.6}])",
            v[0], v[1], v[2]
        ),
        CustomMaterialParamValue3D::Vec4(v) => format!(
            "CustomMaterialParamValue3D::Vec4([{:.6}, {:.6}, {:.6}, {:.6}])",
            v[0], v[1], v[2], v[3]
        ),
    }
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn materials_from_gltf_file(
    path: &Path,
    res_path: &str,
) -> io::Result<Vec<(String, MaterialLiteral)>> {
    let (doc, _buffers, _images) = gltf::import(path).map_err(|err| {
        io::Error::other(format!(
            "failed to import model `{res_path}` for materials: {err}"
        ))
    })?;

    let mut out = Vec::<(String, MaterialLiteral)>::new();
    for (index, material) in doc.materials().enumerate() {
        let pbr = material.pbr_metallic_roughness();
        let base_color = pbr.base_color_factor();
        let emissive_factor = material.emissive_factor();
        let derived = StandardMaterial3D {
            base_color_factor: base_color,
            roughness_factor: pbr.roughness_factor(),
            metallic_factor: pbr.metallic_factor(),
            occlusion_strength: material
                .occlusion_texture()
                .map(|occ| occ.strength())
                .unwrap_or(1.0),
            emissive_factor,
            alpha_mode: match material.alpha_mode() {
                gltf::material::AlphaMode::Opaque => 0,
                gltf::material::AlphaMode::Mask => 1,
                gltf::material::AlphaMode::Blend => 2,
            },
            alpha_cutoff: material.alpha_cutoff().unwrap_or(0.5),
            double_sided: material.double_sided(),
            normal_scale: material
                .normal_texture()
                .map(|normal| normal.scale())
                .unwrap_or(1.0),
            base_color_texture: pbr
                .base_color_texture()
                .map(|tex| tex.texture().index() as u32)
                .unwrap_or(u32::MAX),
            metallic_roughness_texture: pbr
                .metallic_roughness_texture()
                .map(|tex| tex.texture().index() as u32)
                .unwrap_or(u32::MAX),
            normal_texture: material
                .normal_texture()
                .map(|tex| tex.texture().index() as u32)
                .unwrap_or(u32::MAX),
            occlusion_texture: material
                .occlusion_texture()
                .map(|tex| tex.texture().index() as u32)
                .unwrap_or(u32::MAX),
            emissive_texture: material
                .emissive_texture()
                .map(|tex| tex.texture().index() as u32)
                .unwrap_or(u32::MAX),
        };
        out.push((
            format!("{res_path}:mat[{index}]"),
            MaterialLiteral::Standard(derived),
        ));
    }
    if out.is_empty() {
        out.push((
            format!("{res_path}:mat[0]"),
            MaterialLiteral::Standard(StandardMaterial3D::default()),
        ));
    }
    Ok(out)
}
