use crate::{
    StaticPipelineError, asset_uri, ensure_unique_hashes, res_dir, static_dir, write_hash_const,
    write_static_lookup_fn,
};
use perro_asset_formats::source_ext;
use perro_io::walkdir::collect_file_paths;
use perro_render_bridge::{
    CustomMaterialLighting3D, CustomMaterialParamValue3D, StandardMaterial3D, ToonMaterial3D,
    UnlitMaterial3D,
};
use perro_scene::{Parser, SceneFieldName, SceneObjectField, SceneValue};
use rayon::prelude::*;
use std::{borrow::Cow, collections::HashMap, fmt::Write as _, fs, io, path::Path};

pub fn generate_static_materials(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    fs::create_dir_all(&static_dir)?;

    let mut material_paths = Vec::<String>::new();
    if res_dir.exists() {
        material_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| source_ext::contains(source_ext::MATERIAL_INPUT, ext))
            })
            .collect();
    }
    material_paths.sort();

    let mut materials = material_paths
        .into_par_iter()
        .map(|rel| -> io::Result<Vec<(String, MaterialLiteral, bool)>> {
            let res_path = asset_uri(&rel);
            let full_path = res_dir.join(&rel);
            let ext = Path::new(&rel)
                .extension()
                .and_then(|e| e.to_str())
                .map(|ext| ext.to_ascii_lowercase())
                .unwrap_or_default();
            match ext.as_str() {
                source_ext::MATERIAL => {
                    let src = fs::read_to_string(&full_path)?;
                    let material = load_pmat_literal(&src).ok_or_else(|| {
                        io::Error::other(format!(
                            "material `{res_path}` must be an object with at least one valid field"
                        ))
                    })?;
                    Ok(vec![(res_path, material, false)])
                }
                source_ext::GLB | source_ext::GLTF => {
                    materials_from_gltf_file(&full_path, &res_path)
                }
                _ => Ok(Vec::new()),
            }
        })
        .collect::<io::Result<Vec<_>>>()?
        .into_iter()
        .flatten()
        .collect::<Vec<_>>();

    materials.sort_by(|a, b| a.0.cmp(&b.0));

    let mut unique_materials = Vec::<MaterialLiteral>::new();
    let mut unique_by_key = HashMap::<MaterialKey, usize>::new();
    let mut material_refs = Vec::<(String, usize, bool)>::with_capacity(materials.len());
    for (path, material, synthesized) in materials {
        let key = MaterialKey::from(&material);
        let index = if let Some(existing) = unique_by_key.get(&key).copied() {
            existing
        } else {
            let idx = unique_materials.len();
            unique_materials.push(material);
            unique_by_key.insert(key, idx);
            idx
        };
        material_refs.push((path, index, synthesized));
    }
    ensure_unique_hashes(
        "material",
        material_refs.iter().map(|(path, _, _)| path.as_str()),
    )?;

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n");
    out.push_str(
        "use perro_render_bridge::{CustomMaterial3D, CustomMaterialImage3D, CustomMaterialLighting3D, CustomMaterialParam3D, CustomMaterialParamValue3D, Material3D, StandardMaterial3D, ToonMaterial3D, UnlitMaterial3D};\nuse std::borrow::Cow;\n\n",
    );
    for (index, material) in unique_materials.iter().enumerate() {
        let const_name = format!("MATERIAL_{}", index);
        let _ = writeln!(
            out,
            "static {const_name}: Material3D = {};",
            material_literal_to_code(material)
        );
    }
    out.push('\n');
    out.push_str(
        "static EMPTY_MATERIAL: Material3D = Material3D::Standard(StandardMaterial3D::const_default());\n\n",
    );
    for (index, (path, _, _)) in material_refs.iter().enumerate() {
        write_hash_const(&mut out, &format!("MATERIAL_HASH_{index}"), path);
    }
    if !material_refs.is_empty() {
        out.push('\n');
    }
    let lookup_entries = material_refs
        .iter()
        .enumerate()
        .map(|(hash_index, (path, index, _))| {
            (
                perro_ids::string_to_u64(path),
                format!("MATERIAL_HASH_{hash_index}"),
                format!("&MATERIAL_{index}"),
            )
        })
        .collect::<Vec<_>>();
    write_static_lookup_fn(
        &mut out,
        "lookup_material",
        "MATERIAL_TABLE",
        "MaterialEntry",
        "&'static Material3D",
        "&EMPTY_MATERIAL",
        &lookup_entries,
    );

    crate::write_if_changed(&static_dir.join("materials.rs"), out.as_bytes())?;
    crate::record_static_assets(
        perro_asset_formats::dlc::DlcAssetKind::MATERIAL,
        perro_asset_formats::dlc::DlcAssetAccess::ENGINE_LOCAL,
        material_refs
            .iter()
            .map(|(path, _, synthesized)| (path.as_str(), *synthesized)),
    );
    Ok(())
}

#[derive(Clone)]
enum MaterialLiteral {
    Standard(StandardMaterial3D),
    Unlit(UnlitMaterial3D),
    Toon(ToonMaterial3D),
    Custom(CustomMaterialLiteral),
}

#[derive(Clone)]
struct CustomMaterialLiteral {
    shader_path: String,
    params: Vec<CustomParamLiteral>,
    images: Vec<CustomImageLiteral>,
    lighting: CustomMaterialLighting3D,
    surface: StandardMaterial3D,
}

#[derive(Clone)]
struct CustomParamLiteral {
    name: Option<String>,
    value: CustomMaterialParamValue3D,
}

#[derive(Clone)]
struct CustomImageLiteral {
    name: Option<String>,
    source: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
enum MaterialKey {
    Standard(StandardMaterialKey),
    Unlit(UnlitMaterialKey),
    Toon(ToonMaterialKey),
    Custom(CustomMaterialKey),
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct StandardMaterialKey {
    base_color_factor: [u32; 4],
    roughness_factor: u32,
    metallic_factor: u32,
    occlusion_strength: u32,
    emissive_factor: [u32; 3],
    alpha_mode: u8,
    alpha_cutoff: u32,
    double_sided: bool,
    flat_shading: bool,
    normal_scale: u32,
    base_color_texture: u32,
    metallic_roughness_texture: u32,
    normal_texture: u32,
    occlusion_texture: u32,
    emissive_texture: u32,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct UnlitMaterialKey {
    base_color_factor: [u32; 4],
    emissive_factor: [u32; 3],
    alpha_mode: u8,
    alpha_cutoff: u32,
    double_sided: bool,
    flat_shading: bool,
    base_color_texture: u32,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct ToonMaterialKey {
    base_color_factor: [u32; 4],
    emissive_factor: [u32; 3],
    alpha_mode: u8,
    alpha_cutoff: u32,
    double_sided: bool,
    flat_shading: bool,
    band_count: u32,
    rim_strength: u32,
    outline_width: u32,
    base_color_texture: u32,
    ramp_texture: u32,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct CustomMaterialKey {
    shader_path: String,
    params: Vec<CustomParamKey>,
    images: Vec<CustomImageKey>,
    lighting: CustomMaterialLighting3D,
    surface: StandardMaterialKey,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct CustomParamKey {
    name: Option<String>,
    value: CustomParamValueKey,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct CustomImageKey {
    name: Option<String>,
    source: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
enum CustomParamValueKey {
    F32(u32),
    I32(i32),
    Bool(bool),
    Vec2([u32; 2]),
    Vec3([u32; 3]),
    Vec4([u32; 4]),
}

impl From<&MaterialLiteral> for MaterialKey {
    fn from(value: &MaterialLiteral) -> Self {
        match value {
            MaterialLiteral::Standard(v) => MaterialKey::Standard(standard_material_key(v)),
            MaterialLiteral::Unlit(v) => MaterialKey::Unlit(UnlitMaterialKey {
                base_color_factor: [
                    v.base_color_factor[0].to_bits(),
                    v.base_color_factor[1].to_bits(),
                    v.base_color_factor[2].to_bits(),
                    v.base_color_factor[3].to_bits(),
                ],
                emissive_factor: [
                    v.emissive_factor[0].to_bits(),
                    v.emissive_factor[1].to_bits(),
                    v.emissive_factor[2].to_bits(),
                ],
                alpha_mode: v.alpha_mode,
                alpha_cutoff: v.alpha_cutoff.to_bits(),
                double_sided: v.double_sided,
                flat_shading: v.flat_shading,
                base_color_texture: v.base_color_texture,
            }),
            MaterialLiteral::Toon(v) => MaterialKey::Toon(ToonMaterialKey {
                base_color_factor: [
                    v.base_color_factor[0].to_bits(),
                    v.base_color_factor[1].to_bits(),
                    v.base_color_factor[2].to_bits(),
                    v.base_color_factor[3].to_bits(),
                ],
                emissive_factor: [
                    v.emissive_factor[0].to_bits(),
                    v.emissive_factor[1].to_bits(),
                    v.emissive_factor[2].to_bits(),
                ],
                alpha_mode: v.alpha_mode,
                alpha_cutoff: v.alpha_cutoff.to_bits(),
                double_sided: v.double_sided,
                flat_shading: v.flat_shading,
                band_count: v.band_count,
                rim_strength: v.rim_strength.to_bits(),
                outline_width: v.outline_width.to_bits(),
                base_color_texture: v.base_color_texture,
                ramp_texture: v.ramp_texture,
            }),
            MaterialLiteral::Custom(v) => MaterialKey::Custom(CustomMaterialKey {
                shader_path: v.shader_path.clone(),
                lighting: v.lighting,
                surface: standard_material_key(&v.surface),
                params: v
                    .params
                    .iter()
                    .map(|p| CustomParamKey {
                        name: p.name.clone(),
                        value: match &p.value {
                            CustomMaterialParamValue3D::F32(x) => {
                                CustomParamValueKey::F32(x.to_bits())
                            }
                            CustomMaterialParamValue3D::I32(x) => CustomParamValueKey::I32(*x),
                            CustomMaterialParamValue3D::Bool(x) => CustomParamValueKey::Bool(*x),
                            CustomMaterialParamValue3D::Vec2(v) => {
                                CustomParamValueKey::Vec2([v[0].to_bits(), v[1].to_bits()])
                            }
                            CustomMaterialParamValue3D::Vec3(v) => CustomParamValueKey::Vec3([
                                v[0].to_bits(),
                                v[1].to_bits(),
                                v[2].to_bits(),
                            ]),
                            CustomMaterialParamValue3D::Vec4(v) => CustomParamValueKey::Vec4([
                                v[0].to_bits(),
                                v[1].to_bits(),
                                v[2].to_bits(),
                                v[3].to_bits(),
                            ]),
                        },
                    })
                    .collect(),
                images: v
                    .images
                    .iter()
                    .map(|image| CustomImageKey {
                        name: image.name.clone(),
                        source: image.source.clone(),
                    })
                    .collect(),
            }),
        }
    }
}

fn standard_material_key(v: &StandardMaterial3D) -> StandardMaterialKey {
    StandardMaterialKey {
        base_color_factor: [
            v.base_color_factor[0].to_bits(),
            v.base_color_factor[1].to_bits(),
            v.base_color_factor[2].to_bits(),
            v.base_color_factor[3].to_bits(),
        ],
        roughness_factor: v.roughness_factor.to_bits(),
        metallic_factor: v.metallic_factor.to_bits(),
        occlusion_strength: v.occlusion_strength.to_bits(),
        emissive_factor: [
            v.emissive_factor[0].to_bits(),
            v.emissive_factor[1].to_bits(),
            v.emissive_factor[2].to_bits(),
        ],
        alpha_mode: v.alpha_mode,
        alpha_cutoff: v.alpha_cutoff.to_bits(),
        double_sided: v.double_sided,
        flat_shading: v.flat_shading,
        normal_scale: v.normal_scale.to_bits(),
        base_color_texture: v.base_color_texture,
        metallic_roughness_texture: v.metallic_roughness_texture,
        normal_texture: v.normal_texture,
        occlusion_texture: v.occlusion_texture,
        emissive_texture: v.emissive_texture,
    }
}

fn material_from_runtime_entries(entries: &[SceneObjectField]) -> Option<MaterialLiteral> {
    let mut any = false;
    let kind = material_type_from_first_runtime(entries);
    match kind {
        MaterialType::Standard => {
            let mut out = StandardMaterial3D::default();
            apply_standard_runtime_entries(entries, &mut out, &mut any);
            any.then_some(MaterialLiteral::Standard(out))
        }
        MaterialType::Unlit => {
            let mut out = UnlitMaterial3D::default();
            apply_unlit_runtime_entries(entries, &mut out, &mut any);
            any.then_some(MaterialLiteral::Unlit(out))
        }
        MaterialType::Toon => {
            let mut out = ToonMaterial3D::default();
            apply_toon_runtime_entries(entries, &mut out, &mut any);
            any.then_some(MaterialLiteral::Toon(out))
        }
        MaterialType::Custom => {
            let mut out = CustomMaterialLiteral {
                shader_path: String::new(),
                params: Vec::new(),
                images: Vec::new(),
                lighting: CustomMaterialLighting3D::Standard,
                surface: StandardMaterial3D::default(),
            };
            apply_custom_runtime_entries(entries, &mut out, &mut any);
            any.then_some(MaterialLiteral::Custom(out))
        }
    }
}

fn load_pmat_literal(source: &str) -> Option<MaterialLiteral> {
    if pmat_looks_like_object(source) {
        if let Some(entries) = parse_pmat_object(source)
            && let Some(material) = material_from_runtime_entries(entries.as_ref())
        {
            return Some(material);
        }
        return None;
    }

    if let Some(entries) = parse_pmat_top_level_object(source)
        && let Some(material) = material_from_runtime_entries(entries.as_ref())
    {
        return Some(material);
    }

    let entries = parse_pmat_key_values(source)?;
    material_from_runtime_entries(&entries)
}

fn parse_pmat_object(text: &str) -> Option<Vec<SceneObjectField>> {
    let value = std::panic::catch_unwind(|| Parser::new(text).parse_value_literal()).ok()?;
    match value {
        SceneValue::Object(entries) => Some(entries.into_owned()),
        _ => None,
    }
}

fn parse_pmat_top_level_object(text: &str) -> Option<Vec<SceneObjectField>> {
    let wrapped = format!("{{\n{text}\n}}");
    parse_pmat_object(&wrapped)
}

fn parse_pmat_key_values(text: &str) -> Option<Vec<SceneObjectField>> {
    let mut entries = Vec::new();
    for raw_line in text.lines() {
        let line = strip_line_comment(raw_line).trim();
        if line.is_empty() {
            continue;
        }
        let (raw_key, raw_value) = line.split_once('=')?;
        let key = SceneFieldName::from(raw_key.trim().to_string());
        if key.is_empty() {
            continue;
        }
        let value_text = raw_value.trim().trim_end_matches(',');
        if value_text.is_empty() {
            continue;
        }
        let value = parse_kv_value(value_text)?;
        entries.push((key, value));
    }
    (!entries.is_empty()).then_some(entries)
}

fn strip_line_comment(line: &str) -> &str {
    let bytes = line.as_bytes();
    let mut in_string = false;
    let mut escape = false;
    let mut i = 0usize;
    while i < bytes.len() {
        let b = bytes[i];
        if in_string {
            if escape {
                escape = false;
            } else if b == b'\\' {
                escape = true;
            } else if b == b'"' {
                in_string = false;
            }
            i += 1;
            continue;
        }
        if b == b'"' {
            in_string = true;
            i += 1;
            continue;
        }
        if b == b'#' {
            return &line[..i];
        }
        if b == b'/' && i + 1 < bytes.len() && bytes[i + 1] == b'/' {
            return &line[..i];
        }
        i += 1;
    }
    line
}

fn pmat_looks_like_object(text: &str) -> bool {
    text.lines()
        .map(strip_line_comment)
        .map(str::trim)
        .find(|line| !line.is_empty())
        .is_some_and(|line| line.starts_with('{'))
}

fn parse_kv_value(text: &str) -> Option<SceneValue> {
    let text = text.trim();
    if let Some(value) = parse_vec_value(text) {
        return Some(value);
    }
    if text.eq_ignore_ascii_case("true") {
        return Some(SceneValue::Bool(true));
    }
    if text.eq_ignore_ascii_case("false") {
        return Some(SceneValue::Bool(false));
    }
    if let Some(inner) = text.strip_prefix('"').and_then(|v| v.strip_suffix('"')) {
        return Some(SceneValue::Str(Cow::Owned(inner.to_string())));
    }
    if let Ok(v) = text.parse::<i32>() {
        return Some(SceneValue::I32(v));
    }
    if let Ok(v) = text.parse::<f32>() {
        return Some(SceneValue::F32(v));
    }
    Some(SceneValue::Str(Cow::Owned(text.to_string())))
}

fn parse_vec_value(text: &str) -> Option<SceneValue> {
    let inner = text.strip_prefix('(')?.strip_suffix(')')?;
    let numbers = inner
        .split(',')
        .map(|token| token.trim().parse::<f32>().ok())
        .collect::<Option<Vec<_>>>()?;
    match numbers.as_slice() {
        [x, y] => Some(SceneValue::Vec2 { x: *x, y: *y }),
        [x, y, z] => Some(SceneValue::Vec3 {
            x: *x,
            y: *y,
            z: *z,
        }),
        [x, y, z, w] => Some(SceneValue::Vec4 {
            x: *x,
            y: *y,
            z: *z,
            w: *w,
        }),
        _ => None,
    }
}

fn material_type_from_first_runtime(entries: &[SceneObjectField]) -> MaterialType {
    let Some((name, value)) = entries.first() else {
        return MaterialType::Standard;
    };
    if !name.as_ref().eq_ignore_ascii_case("type") {
        return MaterialType::Standard;
    }
    match value {
        SceneValue::Str(v) => parse_material_type(v.as_ref()),
        SceneValue::Key(v) => parse_material_type(v.as_ref()),
        _ => MaterialType::Standard,
    }
}

fn parse_material_type(value: &str) -> MaterialType {
    match value {
        "standard" | "Standard" | "pbr" | "PBR" => MaterialType::Standard,
        "unlit" | "Unlit" => MaterialType::Unlit,
        "toon" | "Toon" | "cel" | "Cel" => MaterialType::Toon,
        "custom" | "Custom" => MaterialType::Custom,
        _ => MaterialType::Standard,
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum MaterialType {
    Standard,
    Unlit,
    Toon,
    Custom,
}

fn apply_standard_runtime_entries(
    entries: &[SceneObjectField],
    out: &mut StandardMaterial3D,
    any: &mut bool,
) {
    for (name, value) in entries {
        match canonical_standard_key(name.as_ref()) {
            Some("roughnessFactor") => set_f32(value, any, |v| out.roughness_factor = v),
            Some("metallicFactor") => set_f32(value, any, |v| out.metallic_factor = v),
            Some("occlusionStrength") => set_f32(value, any, |v| out.occlusion_strength = v),
            Some("emissiveFactor") => set_color3(value, any, |v| out.emissive_factor = v),
            Some("baseColorFactor") => set_color4(value, any, |v| out.base_color_factor = v),
            Some("normalScale") => set_f32(value, any, |v| out.normal_scale = v),
            Some("alphaCutoff") => set_f32(value, any, |v| out.alpha_cutoff = v),
            Some("alphaMode") => set_alpha_mode(value, any, |v| out.alpha_mode = v),
            Some("doubleSided") => set_bool(value, any, |v| out.double_sided = v),
            Some("flatShading") => set_bool(value, any, |v| out.flat_shading = v),
            Some("baseColorTexture") => {
                set_texture_slot(value, any, |v| out.base_color_texture = v)
            }
            Some("metallicRoughnessTexture") => {
                set_texture_slot(value, any, |v| out.metallic_roughness_texture = v)
            }
            Some("normalTexture") => set_texture_slot(value, any, |v| out.normal_texture = v),
            Some("occlusionTexture") => set_texture_slot(value, any, |v| out.occlusion_texture = v),
            Some("emissiveTexture") => set_texture_slot(value, any, |v| out.emissive_texture = v),
            Some("pbrMetallicRoughness") => {
                if let SceneValue::Object(inner) = value {
                    apply_standard_runtime_entries(inner.as_ref(), out, any);
                }
            }
            _ => {}
        }
    }
}

fn apply_unlit_runtime_entries(
    entries: &[SceneObjectField],
    out: &mut UnlitMaterial3D,
    any: &mut bool,
) {
    for (name, value) in entries {
        match canonical_unlit_key(name.as_ref()) {
            Some("baseColorFactor") => set_color4(value, any, |v| out.base_color_factor = v),
            Some("emissiveFactor") => set_color3(value, any, |v| out.emissive_factor = v),
            Some("alphaCutoff") => set_f32(value, any, |v| out.alpha_cutoff = v),
            Some("alphaMode") => set_alpha_mode(value, any, |v| out.alpha_mode = v),
            Some("doubleSided") => set_bool(value, any, |v| out.double_sided = v),
            Some("flatShading") => set_bool(value, any, |v| out.flat_shading = v),
            Some("baseColorTexture") => {
                set_texture_slot(value, any, |v| out.base_color_texture = v)
            }
            _ => {}
        }
    }
}

fn apply_toon_runtime_entries(
    entries: &[SceneObjectField],
    out: &mut ToonMaterial3D,
    any: &mut bool,
) {
    for (name, value) in entries {
        match canonical_toon_key(name.as_ref()) {
            Some("baseColorFactor") => set_color4(value, any, |v| out.base_color_factor = v),
            Some("emissiveFactor") => set_color3(value, any, |v| out.emissive_factor = v),
            Some("alphaCutoff") => set_f32(value, any, |v| out.alpha_cutoff = v),
            Some("alphaMode") => set_alpha_mode(value, any, |v| out.alpha_mode = v),
            Some("doubleSided") => set_bool(value, any, |v| out.double_sided = v),
            Some("flatShading") => set_bool(value, any, |v| out.flat_shading = v),
            Some("baseColorTexture") => {
                set_texture_slot(value, any, |v| out.base_color_texture = v)
            }
            Some("rampTexture") => set_texture_slot(value, any, |v| out.ramp_texture = v),
            Some("bandCount") => set_u32(value, any, |v| out.band_count = v),
            Some("rimStrength") => set_f32(value, any, |v| out.rim_strength = v),
            Some("outlineWidth") => set_f32(value, any, |v| out.outline_width = v),
            _ => {}
        }
    }
}

fn apply_custom_runtime_entries(
    entries: &[SceneObjectField],
    out: &mut CustomMaterialLiteral,
    any: &mut bool,
) {
    apply_standard_runtime_entries(entries, &mut out.surface, any);
    for (name, value) in entries {
        match canonical_custom_key(name.as_ref()) {
            Some("shaderPath") => {
                if let Some(v) = as_string_value(value) {
                    out.shader_path = v;
                    *any = true;
                }
            }
            Some("params") => {
                if let Some(params) = as_custom_params(value) {
                    out.params = params;
                    *any = true;
                }
            }
            Some("images") => {
                if let Some(images) = as_custom_images(value) {
                    out.images = images;
                    *any = true;
                }
            }
            Some("lighting") => {
                if let Some(lighting) = as_custom_lighting(value) {
                    out.lighting = lighting;
                    *any = true;
                }
            }
            _ => {}
        }
    }
}

fn canonical_standard_key(name: &str) -> Option<&'static str> {
    match name {
        "type" | "Type" => None,
        "roughnessFactor" | "roughness_factor" => Some("roughnessFactor"),
        "metallicFactor" | "metallic_factor" => Some("metallicFactor"),
        "occlusionStrength" | "occlusion_strength" => Some("occlusionStrength"),
        "emissiveFactor" | "emissive_factor" => Some("emissiveFactor"),
        "baseColorFactor" | "base_color_factor" | "color" => Some("baseColorFactor"),
        "normalScale" | "normal_scale" => Some("normalScale"),
        "alphaCutoff" | "alpha_cutoff" => Some("alphaCutoff"),
        "alphaMode" | "alpha_mode" => Some("alphaMode"),
        "doubleSided" | "double_sided" => Some("doubleSided"),
        "flatShading" | "flat_shading" => Some("flatShading"),
        "baseColorTexture" | "base_color_texture" => Some("baseColorTexture"),
        "metallicRoughnessTexture" | "metallic_roughness_texture" => {
            Some("metallicRoughnessTexture")
        }
        "normalTexture" | "normal_texture" => Some("normalTexture"),
        "occlusionTexture" | "occlusion_texture" => Some("occlusionTexture"),
        "emissiveTexture" | "emissive_texture" => Some("emissiveTexture"),
        "pbrMetallicRoughness" | "pbr_metallic_roughness" => Some("pbrMetallicRoughness"),
        _ => None,
    }
}

fn canonical_unlit_key(name: &str) -> Option<&'static str> {
    match name {
        "type" | "Type" => None,
        "baseColorFactor" | "base_color_factor" | "color" => Some("baseColorFactor"),
        "emissiveFactor" | "emissive_factor" => Some("emissiveFactor"),
        "alphaCutoff" | "alpha_cutoff" => Some("alphaCutoff"),
        "alphaMode" | "alpha_mode" => Some("alphaMode"),
        "doubleSided" | "double_sided" => Some("doubleSided"),
        "flatShading" | "flat_shading" => Some("flatShading"),
        "baseColorTexture" | "base_color_texture" => Some("baseColorTexture"),
        _ => None,
    }
}

fn canonical_toon_key(name: &str) -> Option<&'static str> {
    match name {
        "type" | "Type" => None,
        "baseColorFactor" | "base_color_factor" | "color" => Some("baseColorFactor"),
        "emissiveFactor" | "emissive_factor" => Some("emissiveFactor"),
        "alphaCutoff" | "alpha_cutoff" => Some("alphaCutoff"),
        "alphaMode" | "alpha_mode" => Some("alphaMode"),
        "doubleSided" | "double_sided" => Some("doubleSided"),
        "flatShading" | "flat_shading" => Some("flatShading"),
        "baseColorTexture" | "base_color_texture" => Some("baseColorTexture"),
        "rampTexture" | "ramp_texture" => Some("rampTexture"),
        "bandCount" | "band_count" => Some("bandCount"),
        "rimStrength" | "rim_strength" => Some("rimStrength"),
        "outlineWidth" | "outline_width" => Some("outlineWidth"),
        _ => None,
    }
}

fn canonical_custom_key(name: &str) -> Option<&'static str> {
    match name {
        "type" | "Type" => None,
        "shader" | "shaderPath" | "shader_path" | "path" => Some("shaderPath"),
        "params" | "customParams" | "custom_params" => Some("params"),
        "images" | "imageParams" | "image_params" | "textures" => Some("images"),
        "lighting" | "light" | "lit" => Some("lighting"),
        _ => None,
    }
}

fn set_f32(value: &SceneValue, any: &mut bool, set: impl FnOnce(f32)) {
    if let Some(v) = as_f32(value) {
        set(v);
        *any = true;
    }
}

fn set_u32(value: &SceneValue, any: &mut bool, set: impl FnOnce(u32)) {
    if let Some(v) = as_u32(value) {
        set(v);
        *any = true;
    }
}

fn set_bool(value: &SceneValue, any: &mut bool, set: impl FnOnce(bool)) {
    if let Some(v) = as_bool(value) {
        set(v);
        *any = true;
    }
}

fn set_alpha_mode(value: &SceneValue, any: &mut bool, set: impl FnOnce(u8)) {
    if let Some(v) = as_alpha_mode(value) {
        set(v);
        *any = true;
    }
}

fn set_color4(value: &SceneValue, any: &mut bool, set: impl FnOnce([f32; 4])) {
    if let Some(v) = as_color4(value) {
        set(v);
        *any = true;
    }
}

fn set_color3(value: &SceneValue, any: &mut bool, set: impl FnOnce([f32; 3])) {
    if let Some(v) = as_color4(value) {
        set([v[0], v[1], v[2]]);
        *any = true;
    }
}

fn set_texture_slot(value: &SceneValue, any: &mut bool, set: impl FnOnce(u32)) {
    if let Some(v) = as_texture_slot(value) {
        set(v);
        *any = true;
    }
}

fn as_f32(value: &SceneValue) -> Option<f32> {
    match value {
        SceneValue::F32(v) => Some(*v),
        SceneValue::I32(v) => Some(*v as f32),
        _ => None,
    }
}

fn as_u32(value: &SceneValue) -> Option<u32> {
    match value {
        SceneValue::I32(v) if *v >= 0 => Some(*v as u32),
        SceneValue::F32(v) if *v >= 0.0 => Some(*v as u32),
        _ => None,
    }
}

fn as_bool(value: &SceneValue) -> Option<bool> {
    match value {
        SceneValue::Bool(v) => Some(*v),
        _ => None,
    }
}

fn as_alpha_mode(value: &SceneValue) -> Option<u8> {
    match value {
        SceneValue::Str(v) => match v.as_ref() {
            "OPAQUE" | "opaque" => Some(0),
            "MASK" | "mask" => Some(1),
            "BLEND" | "blend" => Some(2),
            _ => None,
        },
        SceneValue::Key(v) => match v.as_ref() {
            "OPAQUE" | "opaque" => Some(0),
            "MASK" | "mask" => Some(1),
            "BLEND" | "blend" => Some(2),
            _ => None,
        },
        SceneValue::I32(v) if (0..=2).contains(v) => Some(*v as u8),
        _ => None,
    }
}

fn as_color4(value: &SceneValue) -> Option<[f32; 4]> {
    match value {
        SceneValue::Vec4 { x, y, z, w } => Some([*x, *y, *z, *w]),
        SceneValue::Vec3 { x, y, z } => Some([*x, *y, *z, 1.0]),
        _ => None,
    }
}

fn as_texture_slot(value: &SceneValue) -> Option<u32> {
    match value {
        SceneValue::I32(v) if *v >= 0 => Some(*v as u32),
        SceneValue::Object(entries) => {
            entries
                .iter()
                .find_map(|(name, inner)| match name.as_ref() {
                    "index" | "slot" => match inner {
                        SceneValue::I32(v) if *v >= 0 => Some(*v as u32),
                        _ => None,
                    },
                    _ => None,
                })
        }
        _ => None,
    }
}

fn as_string_value(value: &SceneValue) -> Option<String> {
    match value {
        SceneValue::Str(v) => Some(v.to_string()),
        SceneValue::Key(v) => Some(v.to_string()),
        _ => None,
    }
}

fn as_custom_param_value(value: &SceneValue) -> Option<CustomMaterialParamValue3D> {
    value.as_const_param()
}

fn as_custom_lighting(value: &SceneValue) -> Option<CustomMaterialLighting3D> {
    match value {
        SceneValue::Str(v) => parse_custom_lighting_token(v.as_ref()),
        SceneValue::Key(v) => parse_custom_lighting_token(v.as_ref()),
        SceneValue::Bool(v) => Some(if *v {
            CustomMaterialLighting3D::Standard
        } else {
            CustomMaterialLighting3D::Raw
        }),
        _ => None,
    }
}

fn parse_custom_lighting_token(value: &str) -> Option<CustomMaterialLighting3D> {
    match value {
        "standard" | "Standard" | "lit" | "Lit" | "pbr" | "PBR" => {
            Some(CustomMaterialLighting3D::Standard)
        }
        "raw" | "Raw" | "unlit" | "Unlit" | "none" | "None" => Some(CustomMaterialLighting3D::Raw),
        _ => None,
    }
}

fn as_custom_params(value: &SceneValue) -> Option<Vec<CustomParamLiteral>> {
    match value {
        SceneValue::Object(entries) => {
            let mut out = Vec::new();
            for (name, inner) in entries.as_ref() {
                if let Some(val) = as_custom_param_value(inner) {
                    out.push(CustomParamLiteral {
                        name: Some(name.to_string()),
                        value: val,
                    });
                }
            }
            Some(out)
        }
        other => as_custom_param_value(other).map(|val| {
            vec![CustomParamLiteral {
                name: None,
                value: val,
            }]
        }),
    }
}

fn as_custom_images(value: &SceneValue) -> Option<Vec<CustomImageLiteral>> {
    match value {
        SceneValue::Object(entries) => {
            let mut out = Vec::new();
            for (name, inner) in entries.as_ref() {
                if let Some(source) = as_string_value(inner) {
                    out.push(CustomImageLiteral {
                        name: Some(name.to_string()),
                        source,
                    });
                }
            }
            Some(out)
        }
        other => {
            as_string_value(other).map(|source| vec![CustomImageLiteral { name: None, source }])
        }
    }
}

fn material_literal_to_code(material: &MaterialLiteral) -> String {
    match material {
        MaterialLiteral::Standard(m) => {
            let d = StandardMaterial3D::default();
            let mut fields = Vec::<String>::new();
            if m.base_color_factor != d.base_color_factor {
                fields.push(format!(
                    "base_color_factor: {}",
                    f32x4_to_code(m.base_color_factor)
                ));
            }
            if m.roughness_factor != d.roughness_factor {
                fields.push(format!(
                    "roughness_factor: {}",
                    f32_to_code(m.roughness_factor)
                ));
            }
            if m.metallic_factor != d.metallic_factor {
                fields.push(format!(
                    "metallic_factor: {}",
                    f32_to_code(m.metallic_factor)
                ));
            }
            if m.occlusion_strength != d.occlusion_strength {
                fields.push(format!(
                    "occlusion_strength: {}",
                    f32_to_code(m.occlusion_strength)
                ));
            }
            if m.emissive_factor != d.emissive_factor {
                fields.push(format!(
                    "emissive_factor: {}",
                    f32x3_to_code(m.emissive_factor)
                ));
            }
            if m.alpha_mode != d.alpha_mode {
                fields.push(format!("alpha_mode: {}", m.alpha_mode));
            }
            if m.alpha_cutoff != d.alpha_cutoff {
                fields.push(format!("alpha_cutoff: {}", f32_to_code(m.alpha_cutoff)));
            }
            if m.double_sided != d.double_sided {
                fields.push(format!(
                    "double_sided: {}",
                    if m.double_sided { "true" } else { "false" }
                ));
            }
            if m.flat_shading != d.flat_shading {
                fields.push(format!(
                    "flat_shading: {}",
                    if m.flat_shading { "true" } else { "false" }
                ));
            }
            if m.normal_scale != d.normal_scale {
                fields.push(format!("normal_scale: {}", f32_to_code(m.normal_scale)));
            }
            if m.base_color_texture != d.base_color_texture {
                fields.push(format!("base_color_texture: {}", m.base_color_texture));
            }
            if m.metallic_roughness_texture != d.metallic_roughness_texture {
                fields.push(format!(
                    "metallic_roughness_texture: {}",
                    m.metallic_roughness_texture
                ));
            }
            if m.normal_texture != d.normal_texture {
                fields.push(format!("normal_texture: {}", m.normal_texture));
            }
            if m.occlusion_texture != d.occlusion_texture {
                fields.push(format!("occlusion_texture: {}", m.occlusion_texture));
            }
            if m.emissive_texture != d.emissive_texture {
                fields.push(format!("emissive_texture: {}", m.emissive_texture));
            }
            if fields.is_empty() {
                "Material3D::Standard(StandardMaterial3D::const_default())".to_string()
            } else {
                format!(
                    "Material3D::Standard(StandardMaterial3D {{ {}, ..StandardMaterial3D::const_default() }})",
                    fields.join(", ")
                )
            }
        }
        MaterialLiteral::Unlit(m) => {
            let d = UnlitMaterial3D::default();
            let mut fields = Vec::<String>::new();
            if m.base_color_factor != d.base_color_factor {
                fields.push(format!(
                    "base_color_factor: {}",
                    f32x4_to_code(m.base_color_factor)
                ));
            }
            if m.emissive_factor != d.emissive_factor {
                fields.push(format!(
                    "emissive_factor: {}",
                    f32x3_to_code(m.emissive_factor)
                ));
            }
            if m.alpha_mode != d.alpha_mode {
                fields.push(format!("alpha_mode: {}", m.alpha_mode));
            }
            if m.alpha_cutoff != d.alpha_cutoff {
                fields.push(format!("alpha_cutoff: {}", f32_to_code(m.alpha_cutoff)));
            }
            if m.double_sided != d.double_sided {
                fields.push(format!(
                    "double_sided: {}",
                    if m.double_sided { "true" } else { "false" }
                ));
            }
            if m.flat_shading != d.flat_shading {
                fields.push(format!(
                    "flat_shading: {}",
                    if m.flat_shading { "true" } else { "false" }
                ));
            }
            if m.base_color_texture != d.base_color_texture {
                fields.push(format!("base_color_texture: {}", m.base_color_texture));
            }
            if fields.is_empty() {
                "Material3D::Unlit(UnlitMaterial3D::const_default())".to_string()
            } else {
                format!(
                    "Material3D::Unlit(UnlitMaterial3D {{ {}, ..UnlitMaterial3D::const_default() }})",
                    fields.join(", ")
                )
            }
        }
        MaterialLiteral::Toon(m) => {
            let d = ToonMaterial3D::default();
            let mut fields = Vec::<String>::new();
            if m.base_color_factor != d.base_color_factor {
                fields.push(format!(
                    "base_color_factor: {}",
                    f32x4_to_code(m.base_color_factor)
                ));
            }
            if m.emissive_factor != d.emissive_factor {
                fields.push(format!(
                    "emissive_factor: {}",
                    f32x3_to_code(m.emissive_factor)
                ));
            }
            if m.alpha_mode != d.alpha_mode {
                fields.push(format!("alpha_mode: {}", m.alpha_mode));
            }
            if m.alpha_cutoff != d.alpha_cutoff {
                fields.push(format!("alpha_cutoff: {}", f32_to_code(m.alpha_cutoff)));
            }
            if m.double_sided != d.double_sided {
                fields.push(format!(
                    "double_sided: {}",
                    if m.double_sided { "true" } else { "false" }
                ));
            }
            if m.flat_shading != d.flat_shading {
                fields.push(format!(
                    "flat_shading: {}",
                    if m.flat_shading { "true" } else { "false" }
                ));
            }
            if m.band_count != d.band_count {
                fields.push(format!("band_count: {}", m.band_count));
            }
            if m.rim_strength != d.rim_strength {
                fields.push(format!("rim_strength: {}", f32_to_code(m.rim_strength)));
            }
            if m.outline_width != d.outline_width {
                fields.push(format!("outline_width: {}", f32_to_code(m.outline_width)));
            }
            if m.base_color_texture != d.base_color_texture {
                fields.push(format!("base_color_texture: {}", m.base_color_texture));
            }
            if m.ramp_texture != d.ramp_texture {
                fields.push(format!("ramp_texture: {}", m.ramp_texture));
            }
            if fields.is_empty() {
                "Material3D::Toon(ToonMaterial3D::const_default())".to_string()
            } else {
                format!(
                    "Material3D::Toon(ToonMaterial3D {{ {}, ..ToonMaterial3D::const_default() }})",
                    fields.join(", ")
                )
            }
        }
        MaterialLiteral::Custom(m) => {
            let params = if m.params.is_empty() {
                "Cow::Borrowed(&[])".to_string()
            } else {
                let mut rendered = String::from("Cow::Borrowed(&[");
                for (i, param) in m.params.iter().enumerate() {
                    if i > 0 {
                        rendered.push_str(", ");
                    }
                    rendered.push_str("CustomMaterialParam3D { name: ");
                    match &param.name {
                        Some(name) => {
                            rendered.push_str(&format!("Some(Cow::Borrowed({:?}))", name));
                        }
                        None => rendered.push_str("None"),
                    }
                    rendered.push_str(", value: ");
                    rendered.push_str(&custom_param_value_to_code(&param.value));
                    rendered.push_str(" }");
                }
                rendered.push_str("])");
                rendered
            };
            let images = if m.images.is_empty() {
                "Cow::Borrowed(&[])".to_string()
            } else {
                let mut rendered = String::from("Cow::Borrowed(&[");
                for (i, image) in m.images.iter().enumerate() {
                    if i > 0 {
                        rendered.push_str(", ");
                    }
                    rendered.push_str("CustomMaterialImage3D { name: ");
                    match &image.name {
                        Some(name) => {
                            rendered.push_str(&format!("Some(Cow::Borrowed({:?}))", name));
                        }
                        None => rendered.push_str("None"),
                    }
                    rendered.push_str(", source: ");
                    rendered.push_str(&format!("Cow::Borrowed({:?})", image.source));
                    rendered.push_str(" }");
                }
                rendered.push_str("])");
                rendered
            };
            format!(
                "Material3D::Custom(CustomMaterial3D {{ shader_path: Cow::Borrowed({:?}), params: {}, images: {}, lighting: {}, surface: {} }})",
                m.shader_path,
                params,
                images,
                custom_lighting_to_code(m.lighting),
                standard_material_struct_to_code(&m.surface)
            )
        }
    }
}

fn standard_material_struct_to_code(m: &StandardMaterial3D) -> String {
    let d = StandardMaterial3D::default();
    let mut fields = Vec::<String>::new();
    if m.base_color_factor != d.base_color_factor {
        fields.push(format!(
            "base_color_factor: {}",
            f32x4_to_code(m.base_color_factor)
        ));
    }
    if m.roughness_factor != d.roughness_factor {
        fields.push(format!(
            "roughness_factor: {}",
            f32_to_code(m.roughness_factor)
        ));
    }
    if m.metallic_factor != d.metallic_factor {
        fields.push(format!(
            "metallic_factor: {}",
            f32_to_code(m.metallic_factor)
        ));
    }
    if m.occlusion_strength != d.occlusion_strength {
        fields.push(format!(
            "occlusion_strength: {}",
            f32_to_code(m.occlusion_strength)
        ));
    }
    if m.emissive_factor != d.emissive_factor {
        fields.push(format!(
            "emissive_factor: {}",
            f32x3_to_code(m.emissive_factor)
        ));
    }
    if m.alpha_mode != d.alpha_mode {
        fields.push(format!("alpha_mode: {}", m.alpha_mode));
    }
    if m.alpha_cutoff != d.alpha_cutoff {
        fields.push(format!("alpha_cutoff: {}", f32_to_code(m.alpha_cutoff)));
    }
    if m.double_sided != d.double_sided {
        fields.push(format!(
            "double_sided: {}",
            if m.double_sided { "true" } else { "false" }
        ));
    }
    if m.flat_shading != d.flat_shading {
        fields.push(format!(
            "flat_shading: {}",
            if m.flat_shading { "true" } else { "false" }
        ));
    }
    if m.normal_scale != d.normal_scale {
        fields.push(format!("normal_scale: {}", f32_to_code(m.normal_scale)));
    }
    if m.base_color_texture != d.base_color_texture {
        fields.push(format!("base_color_texture: {}", m.base_color_texture));
    }
    if m.metallic_roughness_texture != d.metallic_roughness_texture {
        fields.push(format!(
            "metallic_roughness_texture: {}",
            m.metallic_roughness_texture
        ));
    }
    if m.normal_texture != d.normal_texture {
        fields.push(format!("normal_texture: {}", m.normal_texture));
    }
    if m.occlusion_texture != d.occlusion_texture {
        fields.push(format!("occlusion_texture: {}", m.occlusion_texture));
    }
    if m.emissive_texture != d.emissive_texture {
        fields.push(format!("emissive_texture: {}", m.emissive_texture));
    }
    if fields.is_empty() {
        "StandardMaterial3D::const_default()".to_string()
    } else {
        format!(
            "StandardMaterial3D {{ {}, ..StandardMaterial3D::const_default() }}",
            fields.join(", ")
        )
    }
}

fn custom_lighting_to_code(lighting: CustomMaterialLighting3D) -> &'static str {
    match lighting {
        CustomMaterialLighting3D::Standard => "CustomMaterialLighting3D::Standard",
        CustomMaterialLighting3D::Raw => "CustomMaterialLighting3D::Raw",
    }
}

fn custom_param_value_to_code(value: &CustomMaterialParamValue3D) -> String {
    match value {
        CustomMaterialParamValue3D::F32(v) => {
            format!("CustomMaterialParamValue3D::F32({})", f32_to_code(*v))
        }
        CustomMaterialParamValue3D::I32(v) => format!("CustomMaterialParamValue3D::I32({})", v),
        CustomMaterialParamValue3D::Bool(v) => format!(
            "CustomMaterialParamValue3D::Bool({})",
            if *v { "true" } else { "false" }
        ),
        CustomMaterialParamValue3D::Vec2(v) => {
            format!("CustomMaterialParamValue3D::Vec2({})", f32x2_to_code(*v))
        }
        CustomMaterialParamValue3D::Vec3(v) => {
            format!("CustomMaterialParamValue3D::Vec3({})", f32x3_to_code(*v))
        }
        CustomMaterialParamValue3D::Vec4(v) => {
            format!("CustomMaterialParamValue3D::Vec4({})", f32x4_to_code(*v))
        }
    }
}

fn f32_to_code(value: f32) -> String {
    format!("f32::from_bits({:#010x})", value.to_bits())
}

fn f32x2_to_code(value: [f32; 2]) -> String {
    format!("[{}, {}]", f32_to_code(value[0]), f32_to_code(value[1]))
}

fn f32x3_to_code(value: [f32; 3]) -> String {
    format!(
        "[{}, {}, {}]",
        f32_to_code(value[0]),
        f32_to_code(value[1]),
        f32_to_code(value[2])
    )
}

fn f32x4_to_code(value: [f32; 4]) -> String {
    format!(
        "[{}, {}, {}, {}]",
        f32_to_code(value[0]),
        f32_to_code(value[1]),
        f32_to_code(value[2]),
        f32_to_code(value[3])
    )
}

fn materials_from_gltf_file(
    path: &Path,
    res_path: &str,
) -> io::Result<Vec<(String, MaterialLiteral, bool)>> {
    let (doc, _buffers, _images) = gltf::import(path).map_err(|err| {
        io::Error::other(format!(
            "failed to import model `{res_path}` for materials: {err}"
        ))
    })?;

    let mut out = Vec::<(String, MaterialLiteral, bool)>::new();
    for (index, material) in doc.materials().enumerate() {
        let pbr = material.pbr_metallic_roughness();
        let base_color = pbr.base_color_factor();
        let emissive_factor = material.emissive_factor();
        let derived = StandardMaterial3D {
            base_color_factor: base_color,
            roughness_factor: pbr.roughness_factor(),
            metallic_factor: pbr.metallic_factor(),
            occlusion_strength: material
                .occlusion_texture()
                .map(|occ| occ.strength())
                .unwrap_or(1.0),
            emissive_factor,
            alpha_mode: match material.alpha_mode() {
                gltf::material::AlphaMode::Opaque => 0,
                gltf::material::AlphaMode::Mask => 1,
                gltf::material::AlphaMode::Blend => 2,
            },
            alpha_cutoff: material.alpha_cutoff().unwrap_or(0.5),
            double_sided: material.double_sided(),
            flat_shading: false,
            normal_scale: material
                .normal_texture()
                .map(|normal| normal.scale())
                .unwrap_or(1.0),
            base_color_texture: pbr
                .base_color_texture()
                .map(|tex| tex.texture().index() as u32)
                .unwrap_or(u32::MAX),
            metallic_roughness_texture: pbr
                .metallic_roughness_texture()
                .map(|tex| tex.texture().index() as u32)
                .unwrap_or(u32::MAX),
            normal_texture: material
                .normal_texture()
                .map(|tex| tex.texture().index() as u32)
                .unwrap_or(u32::MAX),
            occlusion_texture: material
                .occlusion_texture()
                .map(|tex| tex.texture().index() as u32)
                .unwrap_or(u32::MAX),
            emissive_texture: material
                .emissive_texture()
                .map(|tex| tex.texture().index() as u32)
                .unwrap_or(u32::MAX),
        };
        out.push((
            format!("{res_path}:mat[{index}]"),
            MaterialLiteral::Standard(derived),
            true,
        ));
    }
    if out.is_empty() {
        out.push((
            format!("{res_path}:mat[0]"),
            MaterialLiteral::Standard(StandardMaterial3D::default()),
            true,
        ));
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::{
        CustomImageLiteral, CustomMaterialLiteral, CustomParamLiteral, MaterialLiteral,
        load_pmat_literal, material_literal_to_code, materials_from_gltf_file,
    };
    use perro_render_bridge::{
        CustomMaterial3D, CustomMaterialImage3D, CustomMaterialLighting3D, CustomMaterialParam3D,
        CustomMaterialParamValue3D, Material3D, StandardMaterial3D, ToonMaterial3D,
        UnlitMaterial3D,
    };
    use std::borrow::Cow;

    const GLTF_STANDARD_TEXTURE_FIXTURE: &str = r#"{
        "asset": { "version": "2.0" },
        "images": [{
            "uri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
        }],
        "textures": [
            { "source": 0 }, { "source": 0 }, { "source": 0 },
            { "source": 0 }, { "source": 0 }
        ],
        "materials": [{
            "pbrMetallicRoughness": {
                "metallicFactor": 0.6,
                "roughnessFactor": 0.7,
                "baseColorTexture": { "index": 0 },
                "metallicRoughnessTexture": { "index": 1 }
            },
            "normalTexture": { "index": 2, "scale": 0.8 },
            "occlusionTexture": { "index": 3, "strength": 0.9 },
            "emissiveTexture": { "index": 4 },
            "emissiveFactor": [0.2, 0.3, 0.4]
        }]
    }"#;

    #[test]
    fn material_codegen_uses_default_ctor_for_default_standard() {
        let code =
            material_literal_to_code(&MaterialLiteral::Standard(StandardMaterial3D::default()));
        assert_eq!(
            code,
            "Material3D::Standard(StandardMaterial3D::const_default())"
        );
    }

    #[test]
    fn static_gltf_material_import_keeps_pbr_texture_slots_and_factors() {
        let path = std::env::temp_dir().join(format!(
            "perro_pbr_material_{}_{}.gltf",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .expect("clock after epoch")
                .as_nanos()
        ));
        std::fs::write(&path, GLTF_STANDARD_TEXTURE_FIXTURE).expect("write glTF fixture");
        let materials = materials_from_gltf_file(&path, "res://fixture.gltf")
            .expect("static glTF material imports");
        let _ = std::fs::remove_file(&path);
        let MaterialLiteral::Standard(standard) = &materials[0].1 else {
            panic!("expected standard material");
        };

        assert_eq!(standard.base_color_texture, 0);
        assert_eq!(standard.metallic_roughness_texture, 1);
        assert_eq!(standard.normal_texture, 2);
        assert_eq!(standard.occlusion_texture, 3);
        assert_eq!(standard.emissive_texture, 4);
        assert_eq!(standard.metallic_factor, 0.6);
        assert_eq!(standard.roughness_factor, 0.7);
        assert_eq!(standard.normal_scale, 0.8);
        assert_eq!(standard.occlusion_strength, 0.9);
        assert_eq!(standard.emissive_factor, [0.2, 0.3, 0.4]);
    }

    #[test]
    fn material_codegen_emits_sparse_standard_fields() {
        let m = StandardMaterial3D {
            double_sided: true,
            base_color_texture: 7,
            ..Default::default()
        };
        let code = material_literal_to_code(&MaterialLiteral::Standard(m));
        assert!(code.contains("double_sided: true"));
        assert!(code.contains("base_color_texture: 7"));
        assert!(code.contains("..StandardMaterial3D::const_default()"));
    }

    #[test]
    fn material_codegen_emits_sparse_toon_fields() {
        let m = ToonMaterial3D {
            band_count: 8,
            ramp_texture: 4,
            ..Default::default()
        };
        let code = material_literal_to_code(&MaterialLiteral::Toon(m));
        assert!(code.contains("band_count: 8"));
        assert!(code.contains("ramp_texture: 4"));
        assert!(code.contains("..ToonMaterial3D::const_default()"));
    }

    #[test]
    fn material_codegen_uses_default_ctor_for_default_unlit() {
        let code = material_literal_to_code(&MaterialLiteral::Unlit(UnlitMaterial3D::default()));
        assert_eq!(code, "Material3D::Unlit(UnlitMaterial3D::const_default())");
    }

    #[test]
    fn material_codegen_emits_custom_lighting_mode() {
        let code = material_literal_to_code(&MaterialLiteral::Custom(CustomMaterialLiteral {
            shader_path: "res://shaders/custom.wgsl".to_string(),
            params: Vec::new(),
            images: Vec::new(),
            lighting: CustomMaterialLighting3D::Raw,
            surface: StandardMaterial3D {
                alpha_mode: 2,
                double_sided: true,
                ..Default::default()
            },
        }));
        assert!(code.contains("lighting: CustomMaterialLighting3D::Raw"));
        assert!(code.contains("surface: StandardMaterial3D { alpha_mode: 2"));
        assert!(code.contains("double_sided: true"));
    }

    #[test]
    fn material_codegen_uses_exact_f32_bits() {
        let color = [0.12345679, 0.2345679, 0.345679, 0.45679];
        let code = material_literal_to_code(&MaterialLiteral::Custom(CustomMaterialLiteral {
            shader_path: "res://shaders/custom.wgsl".to_string(),
            params: vec![CustomParamLiteral {
                name: Some("tint".to_string()),
                value: CustomMaterialParamValue3D::Vec4(color),
            }],
            images: Vec::new(),
            lighting: CustomMaterialLighting3D::Raw,
            surface: StandardMaterial3D {
                base_color_factor: color,
                roughness_factor: 0.12345679,
                ..Default::default()
            },
        }));

        for value in color {
            assert!(code.contains(&format!("f32::from_bits({:#010x})", value.to_bits())));
        }
        assert!(code.contains(&format!(
            "roughness_factor: f32::from_bits({:#010x})",
            0.12345679f32.to_bits()
        )));
        assert!(!code.contains("0.123457"));
    }

    #[test]
    fn pmat_literal_accepts_unbraced_multiline_custom_params() {
        let material = load_pmat_literal(
            r#"
type = "custom"
shader_path = "res://shaders/rune_crystal.wgsl"
lighting = "raw"
params = {
    tint = (1.0, 0.24, 0.18, 1.0)
    glow = 0.9
}
"#,
        )
        .expect("material parses");

        let MaterialLiteral::Custom(custom) = material else {
            panic!("expected custom material");
        };

        assert_eq!(custom.shader_path, "res://shaders/rune_crystal.wgsl");
        assert_eq!(custom.lighting, CustomMaterialLighting3D::Raw);
        assert_eq!(custom.params.len(), 2);
        assert_eq!(custom.params[0].name.as_deref(), Some("tint"));
        assert_eq!(
            custom.params[0].value,
            CustomMaterialParamValue3D::Vec4([1.0, 0.24, 0.18, 1.0])
        );
        assert_eq!(custom.params[1].name.as_deref(), Some("glow"));
        assert_eq!(custom.params[1].value, CustomMaterialParamValue3D::F32(0.9));
    }

    #[test]
    fn pmat_literal_accepts_custom_images() {
        let material = load_pmat_literal(
            r#"
type = "custom"
shader_path = "res://shaders/painted.wgsl"
images = {
    mask = "res://textures/mask.png"
    noise = "res://textures/noise.png"
}
"#,
        )
        .expect("material parses");

        let MaterialLiteral::Custom(custom) = material else {
            panic!("expected custom material");
        };

        assert_eq!(custom.images.len(), 2);
        assert_eq!(custom.images[0].name.as_deref(), Some("mask"));
        assert_eq!(custom.images[0].source, "res://textures/mask.png");
        assert_eq!(custom.images[1].name.as_deref(), Some("noise"));
        assert_eq!(custom.images[1].source, "res://textures/noise.png");

        let code = material_literal_to_code(&MaterialLiteral::Custom(custom));
        assert!(code.contains("CustomMaterialImage3D"));
        assert!(code.contains("res://textures/mask.png"));
        assert!(code.contains("res://textures/noise.png"));
    }

    #[test]
    fn static_pmat_parse_matches_runtime_dynamic_parse() {
        for source in [
            r#"
type = "standard"
base_color_factor = (0.2, 0.4, 0.6, 0.8)
roughness_factor = 0.35
metallic_factor = 0.75
alpha_mode = "blend"
double_sided = true
"#,
            r#"
{
    type = "toon",
    color = (0.9, 0.7, 0.1, 1.0),
    alpha_mode = "mask",
    band_count = 6,
    rim_strength = 0.45,
    outline_width = 0.02,
}
"#,
            r#"
type = "custom"
shader_path = "res://shaders/rune_crystal.wgsl"
lighting = "raw"
alpha_mode = "blend"
params = {
    tint = (1.0, 0.24, 0.18, 1.0)
    glow = 0.9
    use_grid = true
}
images = {
    mask = "res://textures/mask.png"
    noise = "res://textures/noise.png"
}
"#,
        ] {
            let static_material =
                literal_to_material(load_pmat_literal(source).expect("static material parses"));
            let runtime_material = perro_runtime::parse_material_text_for_static_parity(source)
                .expect("runtime material parses");
            assert_eq!(static_material, runtime_material, "source:\n{source}");
        }

        let custom = perro_runtime::parse_material_text_for_static_parity(
            r#"
type = "custom"
shader_path = "res://shaders/rune_crystal.wgsl"
alpha_mode = "blend"
alpha_cutoff = 0.25
double_sided = true
"#,
        )
        .expect("runtime material parses");
        let params = custom.standard_params();
        assert_eq!(params.alpha_mode, 2);
        assert_eq!(params.alpha_cutoff, 0.25);
        assert!(params.double_sided);
    }

    fn literal_to_material(literal: MaterialLiteral) -> Material3D {
        match literal {
            MaterialLiteral::Standard(material) => Material3D::Standard(material),
            MaterialLiteral::Unlit(material) => Material3D::Unlit(material),
            MaterialLiteral::Toon(material) => Material3D::Toon(material),
            MaterialLiteral::Custom(material) => {
                Material3D::Custom(custom_literal_to_material(material))
            }
        }
    }

    fn custom_literal_to_material(literal: CustomMaterialLiteral) -> CustomMaterial3D {
        CustomMaterial3D {
            shader_path: Cow::Owned(literal.shader_path),
            params: Cow::Owned(
                literal
                    .params
                    .into_iter()
                    .map(custom_param_literal_to_material)
                    .collect(),
            ),
            images: Cow::Owned(
                literal
                    .images
                    .into_iter()
                    .map(custom_image_literal_to_material)
                    .collect(),
            ),
            lighting: literal.lighting,
            surface: literal.surface,
        }
    }

    fn custom_param_literal_to_material(literal: CustomParamLiteral) -> CustomMaterialParam3D {
        CustomMaterialParam3D {
            name: literal.name.map(Cow::Owned),
            value: literal.value,
        }
    }

    fn custom_image_literal_to_material(literal: CustomImageLiteral) -> CustomMaterialImage3D {
        CustomMaterialImage3D {
            name: literal.name.map(Cow::Owned),
            source: Cow::Owned(literal.source),
        }
    }
}
