use crate::{StaticPipelineError, embedded_dir, res_dir, static_dir};
use perro_io::{compress_zlib_best, walkdir::collect_file_paths};
use rayon::prelude::*;
use std::{
    fmt::Write as _,
    fs, io,
    path::{Path, PathBuf},
};

const PMESH_MAGIC: &[u8; 5] = b"PMESH";
const PMESH_VERSION: u32 = 1;
const MESHLET_TRIANGLES: usize = 64;

#[derive(Clone, Copy)]
struct PackedVertex {
    position: [f32; 3],
    normal: [f32; 3],
}

#[derive(Clone, Copy)]
struct PackedMeshlet {
    index_start: u32,
    index_count: u32,
    center: [f32; 3],
    radius: f32,
}

#[derive(Clone)]
struct MeshRef {
    lookup_key: String,
    embedded_rel_path: String,
}

struct MeshAsset {
    entry: MeshRef,
    bytes: Vec<u8>,
}

pub fn generate_static_meshes(
    project_root: &Path,
    bake_meshlets: bool,
) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    let embedded_meshes_dir = embedded_dir(project_root).join("meshes");
    fs::create_dir_all(&static_dir)?;
    fs::create_dir_all(&embedded_meshes_dir)?;

    let mut mesh_paths = Vec::<String>::new();
    if res_dir.exists() {
        mesh_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| {
                        matches!(ext.to_ascii_lowercase().as_str(), "pmesh" | "glb" | "gltf")
                    })
            })
            .collect();
    }
    mesh_paths.sort();

    let processed = mesh_paths
        .into_par_iter()
        .map(|rel| -> io::Result<Vec<MeshAsset>> {
            let res_path = format!("res://{rel}");
            let full_path = res_dir.join(&rel);
            let ext = Path::new(&rel)
                .extension()
                .and_then(|e| e.to_str())
                .map(|s| s.to_ascii_lowercase())
                .unwrap_or_default();
            match ext.as_str() {
                "pmesh" => {
                    let bytes = fs::read(&full_path)?;
                    Ok(vec![MeshAsset {
                        entry: MeshRef {
                            lookup_key: res_path,
                            embedded_rel_path: rel,
                        },
                        bytes,
                    }])
                }
                "glb" | "gltf" => {
                    build_gltf_mesh_entries(&full_path, &res_path, &rel, bake_meshlets).map(
                        |entries| {
                            entries
                                .into_iter()
                                .map(|(entry, bytes)| MeshAsset { entry, bytes })
                                .collect()
                        },
                    )
                }
                _ => Ok(Vec::new()),
            }
        })
        .collect::<io::Result<Vec<_>>>()?;

    let mut mesh_assets = processed.into_iter().flatten().collect::<Vec<_>>();
    mesh_assets.sort_by(|a, b| a.entry.embedded_rel_path.cmp(&b.entry.embedded_rel_path));

    let mut mesh_refs = Vec::<MeshRef>::with_capacity(mesh_assets.len());
    for asset in mesh_assets {
        let output_path = embedded_meshes_dir.join(&asset.entry.embedded_rel_path);
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&output_path, asset.bytes)?;
        mesh_refs.push(asset.entry);
    }

    mesh_refs.sort_by(|a, b| a.lookup_key.cmp(&b.lookup_key));
    mesh_refs.dedup_by(|a, b| a.lookup_key == b.lookup_key);

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(dead_code)]\n\n");
    for (index, mesh_ref) in mesh_refs.iter().enumerate() {
        let include_path = format!(
            "../../embedded/meshes/{}",
            escape_str(&mesh_ref.embedded_rel_path)
        );
        let _ = writeln!(
            out,
            "static MESH_{index}: &[u8] = include_bytes!(\"{include_path}\");"
        );
    }
    if !mesh_refs.is_empty() {
        out.push('\n');
    }
    out.push_str("pub fn lookup_mesh(path: &str) -> Option<&'static [u8]> {\n");
    out.push_str("    match path {\n");
    for (index, mesh_ref) in mesh_refs.iter().enumerate() {
        let _ = writeln!(
            out,
            "        \"{}\" => Some(MESH_{index}),",
            escape_str(&mesh_ref.lookup_key)
        );
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("meshes.rs"), out)?;
    Ok(())
}

fn build_gltf_mesh_entries(
    path: &Path,
    res_path: &str,
    rel: &str,
    bake_meshlets: bool,
) -> io::Result<Vec<(MeshRef, Vec<u8>)>> {
    let (doc, buffers, _images) = gltf::import(path)
        .map_err(|err| io::Error::other(format!("failed to import model `{res_path}`: {err}")))?;

    let mut entries = Vec::<(MeshRef, Vec<u8>)>::new();
    let mut rel_base = PathBuf::from(rel);
    rel_base.set_extension("");
    let rel_base = rel_base.to_string_lossy().replace('\\', "/");

    for (mesh_index, mesh) in doc.meshes().enumerate() {
        let Some(primitive) = mesh.primitives().next() else {
            continue;
        };
        let reader =
            primitive.reader(|buffer| buffers.get(buffer.index()).map(|data| data.0.as_slice()));

        let Some(positions) = reader.read_positions() else {
            continue;
        };
        let mut vertices = Vec::<PackedVertex>::new();
        let normals: Vec<[f32; 3]> = reader
            .read_normals()
            .map(|iter| iter.collect())
            .unwrap_or_default();
        for (index, position) in positions.enumerate() {
            let normal = normals.get(index).copied().unwrap_or([0.0, 1.0, 0.0]);
            vertices.push(PackedVertex { position, normal });
        }
        if vertices.is_empty() {
            continue;
        }

        let indices: Vec<u32> = if let Some(read_indices) = reader.read_indices() {
            read_indices.into_u32().collect()
        } else {
            (0..vertices.len() as u32).collect()
        };

        let (indices, meshlets) = if bake_meshlets {
            pack_meshlets(&vertices, &indices)
        } else {
            (indices, Vec::new())
        };
        let pmesh = encode_pmesh(&vertices, &indices, &meshlets)?;

        let embedded_rel_path = format!("{rel_base}_mesh{mesh_index}.pmesh");
        let key_bracket = format!("{res_path}:mesh[{mesh_index}]");
        entries.push((
            MeshRef {
                lookup_key: key_bracket,
                embedded_rel_path,
            },
            pmesh,
        ));
    }

    Ok(entries)
}

fn encode_pmesh(
    vertices: &[PackedVertex],
    indices: &[u32],
    meshlets: &[PackedMeshlet],
) -> io::Result<Vec<u8>> {
    let mut raw = Vec::<u8>::with_capacity(
        vertices.len() * (6 * std::mem::size_of::<f32>())
            + std::mem::size_of_val(indices)
            + meshlets.len() * (2 * std::mem::size_of::<u32>() + 4 * std::mem::size_of::<f32>()),
    );

    for vertex in vertices {
        write_f32(&mut raw, vertex.position[0]);
        write_f32(&mut raw, vertex.position[1]);
        write_f32(&mut raw, vertex.position[2]);
        write_f32(&mut raw, vertex.normal[0]);
        write_f32(&mut raw, vertex.normal[1]);
        write_f32(&mut raw, vertex.normal[2]);
    }
    for &index in indices {
        raw.extend_from_slice(&index.to_le_bytes());
    }
    for meshlet in meshlets {
        raw.extend_from_slice(&meshlet.index_start.to_le_bytes());
        raw.extend_from_slice(&meshlet.index_count.to_le_bytes());
        write_f32(&mut raw, meshlet.center[0]);
        write_f32(&mut raw, meshlet.center[1]);
        write_f32(&mut raw, meshlet.center[2]);
        write_f32(&mut raw, meshlet.radius);
    }

    let compressed = compress_zlib_best(&raw)?;
    let mut out = Vec::with_capacity(5 + 5 * std::mem::size_of::<u32>() + compressed.len());
    out.extend_from_slice(PMESH_MAGIC);
    out.extend_from_slice(&PMESH_VERSION.to_le_bytes());
    out.extend_from_slice(&(vertices.len() as u32).to_le_bytes());
    out.extend_from_slice(&(indices.len() as u32).to_le_bytes());
    out.extend_from_slice(&(meshlets.len() as u32).to_le_bytes());
    out.extend_from_slice(&(raw.len() as u32).to_le_bytes());
    out.extend_from_slice(&compressed);
    Ok(out)
}

fn pack_meshlets(vertices: &[PackedVertex], indices: &[u32]) -> (Vec<u32>, Vec<PackedMeshlet>) {
    if indices.len() < 3 {
        return (indices.to_vec(), Vec::new());
    }
    let packed = pack_indices_spatial(vertices, indices);
    let mut out = Vec::new();
    let tri_index_len = (packed.len() / 3) * 3;
    let chunk = MESHLET_TRIANGLES * 3;
    let mut start = 0usize;
    while start < tri_index_len {
        let end = (start + chunk).min(tri_index_len);
        if let Some((center, radius)) = meshlet_bounds(vertices, &packed[start..end]) {
            out.push(PackedMeshlet {
                index_start: start as u32,
                index_count: (end - start) as u32,
                center,
                radius,
            });
        }
        start = end;
    }
    (packed, out)
}

fn pack_indices_spatial(vertices: &[PackedVertex], indices: &[u32]) -> Vec<u32> {
    let tri_len = (indices.len() / 3) * 3;
    if tri_len == 0 {
        return indices.to_vec();
    }

    let mut centroids = Vec::with_capacity(tri_len / 3);
    let mut cmin = [f32::INFINITY; 3];
    let mut cmax = [f32::NEG_INFINITY; 3];
    for tri in indices[..tri_len].chunks_exact(3) {
        let Some(a) = vertices.get(tri[0] as usize) else {
            return indices.to_vec();
        };
        let Some(b) = vertices.get(tri[1] as usize) else {
            return indices.to_vec();
        };
        let Some(c) = vertices.get(tri[2] as usize) else {
            return indices.to_vec();
        };
        let centroid = [
            (a.position[0] + b.position[0] + c.position[0]) / 3.0,
            (a.position[1] + b.position[1] + c.position[1]) / 3.0,
            (a.position[2] + b.position[2] + c.position[2]) / 3.0,
        ];
        cmin[0] = cmin[0].min(centroid[0]);
        cmin[1] = cmin[1].min(centroid[1]);
        cmin[2] = cmin[2].min(centroid[2]);
        cmax[0] = cmax[0].max(centroid[0]);
        cmax[1] = cmax[1].max(centroid[1]);
        cmax[2] = cmax[2].max(centroid[2]);
        centroids.push((tri, centroid));
    }

    let span = [
        (cmax[0] - cmin[0]).max(1.0e-6),
        (cmax[1] - cmin[1]).max(1.0e-6),
        (cmax[2] - cmin[2]).max(1.0e-6),
    ];
    let mut keyed = Vec::with_capacity(centroids.len());
    for (tri, c) in centroids {
        let nx = ((c[0] - cmin[0]) / span[0]).clamp(0.0, 1.0);
        let ny = ((c[1] - cmin[1]) / span[1]).clamp(0.0, 1.0);
        let nz = ((c[2] - cmin[2]) / span[2]).clamp(0.0, 1.0);
        keyed.push((morton3(nx, ny, nz), [tri[0], tri[1], tri[2]]));
    }
    keyed.sort_unstable_by_key(|(key, _)| *key);

    let mut packed = Vec::with_capacity(indices.len());
    for (_, tri) in keyed {
        packed.extend_from_slice(&tri);
    }
    if tri_len < indices.len() {
        packed.extend_from_slice(&indices[tri_len..]);
    }
    packed
}

#[inline]
fn morton3(nx: f32, ny: f32, nz: f32) -> u64 {
    let qx = (nx * 1023.0).round() as u32;
    let qy = (ny * 1023.0).round() as u32;
    let qz = (nz * 1023.0).round() as u32;
    interleave10(qx) | (interleave10(qy) << 1) | (interleave10(qz) << 2)
}

#[inline]
fn interleave10(v: u32) -> u64 {
    let mut x = (v & 0x3ff) as u64;
    x = (x | (x << 16)) & 0x30000ff;
    x = (x | (x << 8)) & 0x300f00f;
    x = (x | (x << 4)) & 0x30c30c3;
    x = (x | (x << 2)) & 0x9249249;
    x
}

fn meshlet_bounds(vertices: &[PackedVertex], indices: &[u32]) -> Option<([f32; 3], f32)> {
    let mut min = [f32::INFINITY; 3];
    let mut max = [f32::NEG_INFINITY; 3];
    for &idx in indices {
        let pos = vertices.get(idx as usize)?.position;
        min[0] = min[0].min(pos[0]);
        min[1] = min[1].min(pos[1]);
        min[2] = min[2].min(pos[2]);
        max[0] = max[0].max(pos[0]);
        max[1] = max[1].max(pos[1]);
        max[2] = max[2].max(pos[2]);
    }
    if !min.iter().all(|v| v.is_finite()) || !max.iter().all(|v| v.is_finite()) {
        return None;
    }
    let center = [
        (min[0] + max[0]) * 0.5,
        (min[1] + max[1]) * 0.5,
        (min[2] + max[2]) * 0.5,
    ];
    let mut radius_sq = 0.0f32;
    for &idx in indices {
        let pos = vertices.get(idx as usize)?.position;
        let dx = pos[0] - center[0];
        let dy = pos[1] - center[1];
        let dz = pos[2] - center[2];
        radius_sq = radius_sq.max(dx * dx + dy * dy + dz * dz);
    }
    Some((center, radius_sq.sqrt()))
}

fn write_f32(out: &mut Vec<u8>, value: f32) {
    out.extend_from_slice(&value.to_le_bytes());
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}
