use crate::{StaticPipelineError, asset_uri, embedded_dir, ensure_unique_hashes, res_dir, static_dir};
use perro_io::{compress_zlib_best, walkdir::collect_file_paths};
use rayon::prelude::*;
use std::{
    collections::BTreeMap,
    fmt::Write as _,
    fs, io,
    path::{Path, PathBuf},
};

const PMESH_MAGIC: &[u8; 5] = b"PMESH";
const PMESH_VERSION: u32 = 6;
const PMESH_FLAG_HAS_NORMAL: u32 = 1 << 0;
const PMESH_FLAG_HAS_UV0: u32 = 1 << 1;
const PMESH_FLAG_HAS_JOINTS: u32 = 1 << 2;
const PMESH_FLAG_HAS_WEIGHTS: u32 = 1 << 3;
const MESHLET_TRIANGLES: usize = 64;

#[derive(Clone, Copy, Debug, PartialEq)]
struct PackedVertex {
    position: [f32; 3],
    normal: [f32; 3],
    uv: [f32; 2],
    joints: [u16; 4],
    weights: [f32; 4],
}

#[derive(Clone, Copy)]
struct PackedMeshlet {
    index_start: u32,
    index_count: u32,
    center: [f32; 3],
    radius: f32,
}

#[derive(Clone, Copy)]
struct PackedSurfaceRange {
    index_start: u32,
    index_count: u32,
}

#[derive(Clone)]
struct MeshRef {
    lookup_key: String,
    embedded_rel_path: String,
}

struct MeshAsset {
    entry: MeshRef,
    bytes: Vec<u8>,
}

pub fn generate_static_meshes(
    project_root: &Path,
    bake_meshlets: bool,
) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    let embedded_meshes_dir = embedded_dir(project_root).join("meshes");
    fs::create_dir_all(&static_dir)?;
    fs::create_dir_all(&embedded_meshes_dir)?;

    let mut mesh_paths = Vec::<String>::new();
    if res_dir.exists() {
        mesh_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| {
                        matches!(ext.to_ascii_lowercase().as_str(), "pmesh" | "glb" | "gltf")
                    })
            })
            .collect();
    }
    mesh_paths.sort();

    let processed = mesh_paths
        .into_par_iter()
        .map(|rel| -> io::Result<Vec<MeshAsset>> {
            let res_path = asset_uri(&rel);
            let full_path = res_dir.join(&rel);
            let ext = Path::new(&rel)
                .extension()
                .and_then(|e| e.to_str())
                .map(|s| s.to_ascii_lowercase())
                .unwrap_or_default();
            match ext.as_str() {
                "pmesh" => {
                    let bytes = fs::read(&full_path)?;
                    Ok(vec![MeshAsset {
                        entry: MeshRef {
                            lookup_key: res_path,
                            embedded_rel_path: rel,
                        },
                        bytes,
                    }])
                }
                "glb" | "gltf" => {
                    build_gltf_mesh_entries(&full_path, &res_path, &rel, bake_meshlets).map(
                        |entries| {
                            entries
                                .into_iter()
                                .map(|(entry, bytes)| MeshAsset { entry, bytes })
                                .collect()
                        },
                    )
                }
                _ => Ok(Vec::new()),
            }
        })
        .collect::<io::Result<Vec<_>>>()?;

    let mut mesh_assets = processed.into_iter().flatten().collect::<Vec<_>>();
    mesh_assets.sort_by(|a, b| a.entry.embedded_rel_path.cmp(&b.entry.embedded_rel_path));

    let mut mesh_refs = Vec::<MeshRef>::with_capacity(mesh_assets.len());
    for asset in mesh_assets {
        let output_path = embedded_meshes_dir.join(&asset.entry.embedded_rel_path);
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&output_path, asset.bytes)?;
        mesh_refs.push(asset.entry);
    }

    mesh_refs.sort_by(|a, b| a.lookup_key.cmp(&b.lookup_key));
    mesh_refs.dedup_by(|a, b| a.lookup_key == b.lookup_key);
    ensure_unique_hashes(
        "mesh",
        mesh_refs.iter().map(|mesh| mesh.lookup_key.as_str()),
    )?;

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n");
    out.push_str("#![allow(dead_code)]\n\n");
    let mut static_index_by_embedded = BTreeMap::<String, usize>::new();
    let mut static_embedded_paths = Vec::<String>::new();
    for mesh_ref in &mesh_refs {
        if static_index_by_embedded.contains_key(&mesh_ref.embedded_rel_path) {
            continue;
        }
        let index = static_embedded_paths.len();
        static_index_by_embedded.insert(mesh_ref.embedded_rel_path.clone(), index);
        static_embedded_paths.push(mesh_ref.embedded_rel_path.clone());
    }

    for (index, embedded_rel_path) in static_embedded_paths.iter().enumerate() {
        let include_path = format!("../../embedded/meshes/{}", escape_str(embedded_rel_path));
        let _ = writeln!(
            out,
            "static MESH_{index}: &[u8] = include_bytes!(\"{include_path}\");"
        );
    }
    if !mesh_refs.is_empty() {
        out.push('\n');
    }
    out.push_str("static EMPTY_MESH: &[u8] = b\"\";\n\n");
    out.push_str("pub const fn lookup_mesh(path_hash: u64) -> &'static [u8] {\n");
    out.push_str("    match path_hash {\n");
    for mesh_ref in &mesh_refs {
        let index = *static_index_by_embedded
            .get(&mesh_ref.embedded_rel_path)
            .expect("static mesh index missing for embedded rel path");
        let path_hash = perro_ids::string_to_u64(&mesh_ref.lookup_key);
        let _ = writeln!(out, "        {path_hash}u64 => MESH_{index},");
    }
    out.push_str("        _ => EMPTY_MESH,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("meshes.rs"), out)?;
    Ok(())
}

fn build_gltf_mesh_entries(
    path: &Path,
    res_path: &str,
    rel: &str,
    bake_meshlets: bool,
) -> io::Result<Vec<(MeshRef, Vec<u8>)>> {
    let (doc, buffers, _images) = gltf::import(path)
        .map_err(|err| io::Error::other(format!("failed to import model `{res_path}`: {err}")))?;

    let mut entries = Vec::<(MeshRef, Vec<u8>)>::new();
    let mut rel_base = PathBuf::from(rel);
    rel_base.set_extension("");
    let rel_base = rel_base.to_string_lossy().replace('\\', "/");

    for (mesh_index, mesh) in doc.meshes().enumerate() {
        let mut vertices = Vec::<PackedVertex>::new();
        let mut indices = Vec::<u32>::new();
        let mut surface_ranges = Vec::<PackedSurfaceRange>::new();
        let mut has_normals_any = false;
        let mut has_uv_any = false;
        let mut has_joints_any = false;
        let mut has_weights_any = false;

        for primitive in mesh.primitives() {
            let reader = primitive
                .reader(|buffer| buffers.get(buffer.index()).map(|data| data.0.as_slice()));
            let Some(positions_iter) = reader.read_positions() else {
                continue;
            };
            let positions: Vec<[f32; 3]> = positions_iter.collect();
            if positions.is_empty() {
                continue;
            }

            let normals: Vec<[f32; 3]> = reader
                .read_normals()
                .map(|iter| iter.collect())
                .unwrap_or_default();
            if !normals.is_empty() {
                has_normals_any = true;
            }
            let tex_coords: Vec<[f32; 2]> = reader
                .read_tex_coords(0)
                .map(|iter| iter.into_f32().collect())
                .unwrap_or_default();
            if !tex_coords.is_empty() {
                has_uv_any = true;
            }
            let joints: Vec<[u16; 4]> = reader
                .read_joints(0)
                .map(|iter| iter.into_u16().collect())
                .unwrap_or_default();
            if !joints.is_empty() {
                has_joints_any = true;
            }
            let mut weights: Vec<[f32; 4]> = reader
                .read_weights(0)
                .map(|iter| iter.into_f32().collect())
                .unwrap_or_default();
            if !weights.is_empty() {
                has_weights_any = true;
            }
            if weights.is_empty() && !joints.is_empty() {
                weights = vec![[1.0, 0.0, 0.0, 0.0]; joints.len()];
                has_weights_any = true;
            }

            let base_vertex = vertices.len() as u32;
            for (index, position) in positions.iter().copied().enumerate() {
                let normal = normals.get(index).copied().unwrap_or([0.0, 1.0, 0.0]);
                let uv = tex_coords.get(index).copied().unwrap_or([0.0, 0.0]);
                let joint = joints.get(index).copied().unwrap_or([0, 0, 0, 0]);
                let mut weight = weights.get(index).copied().unwrap_or([1.0, 0.0, 0.0, 0.0]);
                let sum = weight.iter().copied().sum::<f32>();
                if sum > 0.0 {
                    let inv = sum.recip();
                    weight.iter_mut().for_each(|w| *w *= inv);
                } else {
                    weight = [1.0, 0.0, 0.0, 0.0];
                }
                vertices.push(PackedVertex {
                    position,
                    normal,
                    uv,
                    joints: joint,
                    weights: weight,
                });
            }

            let surface_start = indices.len() as u32;
            if let Some(read_indices) = reader.read_indices() {
                indices.extend(read_indices.into_u32().map(|i| i + base_vertex));
            } else {
                indices.extend((0..positions.len() as u32).map(|i| i + base_vertex));
            }
            let surface_count = (indices.len() as u32).saturating_sub(surface_start);
            if surface_count > 0 {
                surface_ranges.push(PackedSurfaceRange {
                    index_start: surface_start,
                    index_count: surface_count,
                });
            }
        }

        if vertices.is_empty() || indices.is_empty() {
            continue;
        }

        let (indices, surface_ranges, meshlets) = if bake_meshlets {
            pack_meshlets_with_surfaces(&vertices, &indices, &surface_ranges)
        } else {
            (indices, surface_ranges, Vec::new())
        };
        let pmesh = encode_pmesh_tightest_layout(
            &vertices,
            &indices,
            &surface_ranges,
            &meshlets,
            PackedMeshLayoutFlags {
                has_normals: has_normals_any,
                has_uv0: has_uv_any,
                has_joints: has_joints_any,
                has_weights: has_weights_any,
            },
        )?;

        let embedded_rel_path = format!("{rel_base}_mesh{mesh_index}.pmesh");
        let key_bracket = format!("{res_path}:mesh[{mesh_index}]");
        entries.push((
            MeshRef {
                lookup_key: key_bracket,
                embedded_rel_path,
            },
            pmesh,
        ));
    }

    Ok(entries)
}

#[derive(Clone, Copy)]
struct PackedMeshLayoutFlags {
    has_normals: bool,
    has_uv0: bool,
    has_joints: bool,
    has_weights: bool,
}

fn encode_pmesh_tightest_layout(
    vertices: &[PackedVertex],
    indices: &[u32],
    surface_ranges: &[PackedSurfaceRange],
    meshlets: &[PackedMeshlet],
    layout_flags: PackedMeshLayoutFlags,
) -> io::Result<Vec<u8>> {
    let baseline = encode_pmesh(
        vertices,
        indices,
        surface_ranges,
        meshlets,
        layout_flags,
    )?;
    let (reordered_vertices, reordered_indices) = reorder_vertices_by_first_use(vertices, indices);
    if reordered_vertices == vertices && reordered_indices == indices {
        return Ok(baseline);
    }
    let reordered = encode_pmesh(
        &reordered_vertices,
        &reordered_indices,
        surface_ranges,
        meshlets,
        layout_flags,
    )?;
    if reordered.len() < baseline.len() {
        Ok(reordered)
    } else {
        Ok(baseline)
    }
}

fn reorder_vertices_by_first_use(
    vertices: &[PackedVertex],
    indices: &[u32],
) -> (Vec<PackedVertex>, Vec<u32>) {
    if vertices.is_empty() || indices.is_empty() {
        return (vertices.to_vec(), indices.to_vec());
    }

    let mut old_to_new = vec![u32::MAX; vertices.len()];
    let mut reordered_vertices = Vec::with_capacity(vertices.len());
    let mut reordered_indices = Vec::with_capacity(indices.len());

    for &idx in indices {
        let old_index = idx as usize;
        let Some(vertex) = vertices.get(old_index).copied() else {
            return (vertices.to_vec(), indices.to_vec());
        };
        let mapped = if old_to_new[old_index] == u32::MAX {
            let new_index = reordered_vertices.len() as u32;
            old_to_new[old_index] = new_index;
            reordered_vertices.push(vertex);
            new_index
        } else {
            old_to_new[old_index]
        };
        reordered_indices.push(mapped);
    }

    for (old_index, vertex) in vertices.iter().copied().enumerate() {
        if old_to_new[old_index] == u32::MAX {
            old_to_new[old_index] = reordered_vertices.len() as u32;
            reordered_vertices.push(vertex);
        }
    }

    (reordered_vertices, reordered_indices)
}

fn encode_pmesh(
    vertices: &[PackedVertex],
    indices: &[u32],
    surface_ranges: &[PackedSurfaceRange],
    meshlets: &[PackedMeshlet],
    layout_flags: PackedMeshLayoutFlags,
) -> io::Result<Vec<u8>> {
    let PackedMeshLayoutFlags {
        has_normals,
        has_uv0,
        has_joints,
        has_weights,
    } = layout_flags;
    let vertex_stride_bytes = (3 * std::mem::size_of::<f32>())
        + if has_normals {
            3 * std::mem::size_of::<f32>()
        } else {
            0
        }
        + if has_uv0 {
            2 * std::mem::size_of::<f32>()
        } else {
            0
        }
        + if has_joints {
            4 * std::mem::size_of::<u16>()
        } else {
            0
        }
        + if has_weights {
            4 * std::mem::size_of::<f32>()
        } else {
            0
        };
    let mut raw = Vec::<u8>::with_capacity(
        vertices.len() * vertex_stride_bytes
            + std::mem::size_of_val(indices)
            + surface_ranges.len() * (2 * std::mem::size_of::<u32>())
            + meshlets.len() * (2 * std::mem::size_of::<u32>() + 4 * std::mem::size_of::<f32>()),
    );

    for vertex in vertices {
        write_f32(&mut raw, vertex.position[0]);
        write_f32(&mut raw, vertex.position[1]);
        write_f32(&mut raw, vertex.position[2]);
        if has_normals {
            write_f32(&mut raw, vertex.normal[0]);
            write_f32(&mut raw, vertex.normal[1]);
            write_f32(&mut raw, vertex.normal[2]);
        }
        if has_uv0 {
            write_f32(&mut raw, vertex.uv[0]);
            write_f32(&mut raw, vertex.uv[1]);
        }
        if has_joints {
            write_u16(&mut raw, vertex.joints[0]);
            write_u16(&mut raw, vertex.joints[1]);
            write_u16(&mut raw, vertex.joints[2]);
            write_u16(&mut raw, vertex.joints[3]);
        }
        if has_weights {
            write_f32(&mut raw, vertex.weights[0]);
            write_f32(&mut raw, vertex.weights[1]);
            write_f32(&mut raw, vertex.weights[2]);
            write_f32(&mut raw, vertex.weights[3]);
        }
    }
    for &index in indices {
        raw.extend_from_slice(&index.to_le_bytes());
    }
    for range in surface_ranges {
        raw.extend_from_slice(&range.index_start.to_le_bytes());
        raw.extend_from_slice(&range.index_count.to_le_bytes());
    }
    for meshlet in meshlets {
        raw.extend_from_slice(&meshlet.index_start.to_le_bytes());
        raw.extend_from_slice(&meshlet.index_count.to_le_bytes());
        write_f32(&mut raw, meshlet.center[0]);
        write_f32(&mut raw, meshlet.center[1]);
        write_f32(&mut raw, meshlet.center[2]);
        write_f32(&mut raw, meshlet.radius);
    }

    let compressed = compress_zlib_best(&raw)?;
    let mut out = Vec::with_capacity(5 + 7 * std::mem::size_of::<u32>() + compressed.len());
    out.extend_from_slice(PMESH_MAGIC);
    out.extend_from_slice(&PMESH_VERSION.to_le_bytes());
    let mut flags = 0u32;
    if has_normals {
        flags |= PMESH_FLAG_HAS_NORMAL;
    }
    if has_uv0 {
        flags |= PMESH_FLAG_HAS_UV0;
    }
    if has_joints {
        flags |= PMESH_FLAG_HAS_JOINTS;
    }
    if has_weights {
        flags |= PMESH_FLAG_HAS_WEIGHTS;
    }
    out.extend_from_slice(&flags.to_le_bytes());
    out.extend_from_slice(&(vertices.len() as u32).to_le_bytes());
    out.extend_from_slice(&(indices.len() as u32).to_le_bytes());
    out.extend_from_slice(&(surface_ranges.len() as u32).to_le_bytes());
    out.extend_from_slice(&(meshlets.len() as u32).to_le_bytes());
    out.extend_from_slice(&(raw.len() as u32).to_le_bytes());
    out.extend_from_slice(&compressed);
    Ok(out)
}

fn pack_meshlets_with_surfaces(
    vertices: &[PackedVertex],
    indices: &[u32],
    surface_ranges: &[PackedSurfaceRange],
) -> (Vec<u32>, Vec<PackedSurfaceRange>, Vec<PackedMeshlet>) {
    if surface_ranges.is_empty() {
        let (packed_indices, meshlets) = pack_meshlets(vertices, indices);
        return (
            packed_indices,
            vec![PackedSurfaceRange {
                index_start: 0,
                index_count: indices.len() as u32,
            }],
            meshlets,
        );
    }

    let mut packed_indices = Vec::with_capacity(indices.len());
    let mut packed_ranges = Vec::with_capacity(surface_ranges.len());
    let mut meshlets = Vec::new();

    for range in surface_ranges {
        let start = range.index_start as usize;
        let end = start
            .saturating_add(range.index_count as usize)
            .min(indices.len());
        if start >= end {
            continue;
        }
        let (surface_indices, mut surface_meshlets) = pack_meshlets(vertices, &indices[start..end]);
        if surface_indices.is_empty() {
            continue;
        }
        let packed_start = packed_indices.len() as u32;
        let packed_count = surface_indices.len() as u32;
        packed_indices.extend(surface_indices);
        for meshlet in &mut surface_meshlets {
            meshlet.index_start += packed_start;
        }
        meshlets.extend(surface_meshlets);
        packed_ranges.push(PackedSurfaceRange {
            index_start: packed_start,
            index_count: packed_count,
        });
    }

    if packed_indices.is_empty() {
        let (fallback_indices, fallback_meshlets) = pack_meshlets(vertices, indices);
        return (
            fallback_indices,
            vec![PackedSurfaceRange {
                index_start: 0,
                index_count: indices.len() as u32,
            }],
            fallback_meshlets,
        );
    }

    (packed_indices, packed_ranges, meshlets)
}

fn pack_meshlets(vertices: &[PackedVertex], indices: &[u32]) -> (Vec<u32>, Vec<PackedMeshlet>) {
    if indices.len() < 3 {
        return (indices.to_vec(), Vec::new());
    }
    let packed = indices.to_vec();
    let mut out = Vec::new();
    let tri_index_len = (packed.len() / 3) * 3;
    let chunk = MESHLET_TRIANGLES * 3;
    let mut start = 0usize;
    while start < tri_index_len {
        let end = (start + chunk).min(tri_index_len);
        if let Some((center, radius)) = meshlet_bounds(vertices, &packed[start..end]) {
            out.push(PackedMeshlet {
                index_start: start as u32,
                index_count: (end - start) as u32,
                center,
                radius,
            });
        }
        start = end;
    }
    (packed, out)
}

fn meshlet_bounds(vertices: &[PackedVertex], indices: &[u32]) -> Option<([f32; 3], f32)> {
    let mut min = [f32::INFINITY; 3];
    let mut max = [f32::NEG_INFINITY; 3];
    for &idx in indices {
        let pos = vertices.get(idx as usize)?.position;
        min[0] = min[0].min(pos[0]);
        min[1] = min[1].min(pos[1]);
        min[2] = min[2].min(pos[2]);
        max[0] = max[0].max(pos[0]);
        max[1] = max[1].max(pos[1]);
        max[2] = max[2].max(pos[2]);
    }
    if !min.iter().all(|v| v.is_finite()) || !max.iter().all(|v| v.is_finite()) {
        return None;
    }
    let center = [
        (min[0] + max[0]) * 0.5,
        (min[1] + max[1]) * 0.5,
        (min[2] + max[2]) * 0.5,
    ];
    let mut radius_sq = 0.0f32;
    for &idx in indices {
        let pos = vertices.get(idx as usize)?.position;
        let dx = pos[0] - center[0];
        let dy = pos[1] - center[1];
        let dz = pos[2] - center[2];
        radius_sq = radius_sq.max(dx * dx + dy * dy + dz * dz);
    }
    Some((center, radius_sq.sqrt()))
}

fn write_f32(out: &mut Vec<u8>, value: f32) {
    out.extend_from_slice(&value.to_le_bytes());
}

fn write_u16(out: &mut Vec<u8>, value: u16) {
    out.extend_from_slice(&value.to_le_bytes());
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::{
        PackedSurfaceRange, PackedVertex, encode_pmesh, encode_pmesh_tightest_layout,
        pack_meshlets, pack_meshlets_with_surfaces, reorder_vertices_by_first_use,
    };

    fn test_vertices() -> Vec<PackedVertex> {
        vec![
            PackedVertex {
                position: [0.0, 0.0, 0.0],
                normal: [0.0, 1.0, 0.0],
                uv: [0.0, 0.0],
                joints: [0, 0, 0, 0],
                weights: [1.0, 0.0, 0.0, 0.0],
            },
            PackedVertex {
                position: [1.0, 0.0, 0.0],
                normal: [0.0, 1.0, 0.0],
                uv: [1.0, 0.0],
                joints: [0, 0, 0, 0],
                weights: [1.0, 0.0, 0.0, 0.0],
            },
            PackedVertex {
                position: [1.0, 1.0, 0.0],
                normal: [0.0, 1.0, 0.0],
                uv: [1.0, 1.0],
                joints: [0, 0, 0, 0],
                weights: [1.0, 0.0, 0.0, 0.0],
            },
            PackedVertex {
                position: [0.0, 1.0, 0.0],
                normal: [0.0, 1.0, 0.0],
                uv: [0.0, 1.0],
                joints: [0, 0, 0, 0],
                weights: [1.0, 0.0, 0.0, 0.0],
            },
        ]
    }

    #[test]
    fn pack_meshlets_keeps_index_order() {
        let vertices = test_vertices();
        let indices = vec![2, 1, 0, 0, 3, 2];
        let (packed_indices, meshlets) = pack_meshlets(&vertices, &indices);
        assert_eq!(packed_indices, indices);
        assert_eq!(meshlets.len(), 1);
        assert_eq!(meshlets[0].index_start, 0);
        assert_eq!(meshlets[0].index_count, 6);
    }

    #[test]
    fn pack_meshlets_with_surfaces_keeps_surface_order() {
        let vertices = test_vertices();
        let indices = vec![2, 1, 0, 0, 3, 2, 1, 2, 3];
        let surfaces = vec![
            PackedSurfaceRange {
                index_start: 0,
                index_count: 6,
            },
            PackedSurfaceRange {
                index_start: 6,
                index_count: 3,
            },
        ];
        let (packed_indices, packed_surfaces, _meshlets) =
            pack_meshlets_with_surfaces(&vertices, &indices, &surfaces);
        assert_eq!(packed_indices, indices);
        assert_eq!(packed_surfaces.len(), 2);
        assert_eq!(packed_surfaces[0].index_start, 0);
        assert_eq!(packed_surfaces[0].index_count, 6);
        assert_eq!(packed_surfaces[1].index_start, 6);
        assert_eq!(packed_surfaces[1].index_count, 3);
    }

    #[test]
    fn reorder_vertices_keeps_bindings_for_indices() {
        let vertices = vec![
            PackedVertex {
                position: [10.0, 0.0, 0.0],
                normal: [0.0, 1.0, 0.0],
                uv: [0.1, 0.2],
                joints: [1, 2, 3, 4],
                weights: [0.4, 0.3, 0.2, 0.1],
            },
            PackedVertex {
                position: [11.0, 0.0, 0.0],
                normal: [0.0, 0.0, 1.0],
                uv: [0.3, 0.4],
                joints: [5, 6, 7, 8],
                weights: [0.25, 0.25, 0.25, 0.25],
            },
            PackedVertex {
                position: [12.0, 0.0, 0.0],
                normal: [1.0, 0.0, 0.0],
                uv: [0.5, 0.6],
                joints: [9, 10, 11, 12],
                weights: [1.0, 0.0, 0.0, 0.0],
            },
        ];
        let indices = vec![2, 0, 2, 1, 0, 1];
        let (reordered_vertices, remapped_indices) =
            reorder_vertices_by_first_use(&vertices, &indices);
        for (position, &old_idx) in indices.iter().enumerate() {
            let new_idx = remapped_indices[position] as usize;
            assert_eq!(reordered_vertices[new_idx], vertices[old_idx as usize]);
        }
    }

    #[test]
    fn tighter_layout_selection_reduces_payload_when_better_order_exists() {
        let mut vertices = Vec::new();
        for i in 0..120 {
            let even = i % 2 == 0;
            vertices.push(PackedVertex {
                position: if even {
                    [1.0, 2.0, 3.0]
                } else {
                    [9.0, 8.0, 7.0]
                },
                normal: if even {
                    [0.0, 1.0, 0.0]
                } else {
                    [0.0, 0.0, 1.0]
                },
                uv: if even { [0.2, 0.8] } else { [0.6, 0.4] },
                joints: if even { [1, 1, 1, 1] } else { [2, 2, 2, 2] },
                weights: if even {
                    [1.0, 0.0, 0.0, 0.0]
                } else {
                    [0.0, 1.0, 0.0, 0.0]
                },
            });
        }
        let indices = (0..120u32)
            .step_by(2)
            .chain((1..120u32).step_by(2))
            .collect::<Vec<_>>();
        let surfaces = vec![PackedSurfaceRange {
            index_start: 0,
            index_count: indices.len() as u32,
        }];
        let meshlets = Vec::new();

        let full_layout = PackedMeshLayoutFlags {
            has_normals: true,
            has_uv0: true,
            has_joints: true,
            has_weights: true,
        };
        let baseline =
            encode_pmesh(&vertices, &indices, &surfaces, &meshlets, full_layout)
                .expect("baseline encode");
        let selected = encode_pmesh_tightest_layout(
            &vertices,
            &indices,
            &surfaces,
            &meshlets,
            full_layout,
        )
        .expect("tightest encode");
        assert!(selected.len() <= baseline.len());
        assert!(selected.len() < baseline.len());
    }
}
