use crate::{
    StaticPipelineError, asset_uri, embedded_dir, ensure_unique_hashes, res_dir, static_dir,
    write_hash_const, write_static_lookup_fn,
};
use perro_asset_formats::pnav;
use perro_io::walkdir::collect_file_paths;
use perro_resource_api::sub_apis::parse_pnav_bytes;
use std::{fmt::Write as _, fs, path::Path};

pub fn generate_static_navmeshes(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    let embedded_navmeshes_dir = embedded_dir(project_root).join("navmeshes");
    fs::create_dir_all(&static_dir)?;
    fs::create_dir_all(&embedded_navmeshes_dir)?;

    let mut navmesh_paths = Vec::<String>::new();
    if res_dir.exists() {
        navmesh_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| ext.eq_ignore_ascii_case(pnav::EXTENSION))
            })
            .collect();
    }
    navmesh_paths.sort();

    let mut navmeshes = Vec::<(String, String)>::with_capacity(navmesh_paths.len());
    for rel in navmesh_paths {
        let res_path = asset_uri(&rel);
        let full_path = res_dir.join(&rel);
        let bytes = fs::read(&full_path)?;
        parse_pnav_bytes(&bytes).map_err(|err| {
            StaticPipelineError::SceneParse(format!("navmesh parse failed `{res_path}`: {err}"))
        })?;

        let output_path = embedded_navmeshes_dir.join(&rel);
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&output_path, bytes)?;
        navmeshes.push((res_path, rel));
    }

    navmeshes.sort_by(|a, b| a.0.cmp(&b.0));
    ensure_unique_hashes("navmesh", navmeshes.iter().map(|(path, _)| path.as_str()))?;

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n\n");
    for (index, (_res_path, rel)) in navmeshes.iter().enumerate() {
        let include_path = format!("../../embedded/navmeshes/{}", escape_str(rel));
        let _ = writeln!(
            out,
            "static NAVMESH_{index}: &[u8] = include_bytes!(\"{include_path}\");"
        );
    }
    if !navmeshes.is_empty() {
        out.push('\n');
    }
    out.push_str("static EMPTY_NAVMESH: &[u8] = b\"\";\n\n");
    for (index, (res_path, _)) in navmeshes.iter().enumerate() {
        write_hash_const(&mut out, &format!("NAVMESH_HASH_{index}"), res_path);
    }
    if !navmeshes.is_empty() {
        out.push('\n');
    }
    let lookup_entries = navmeshes
        .iter()
        .enumerate()
        .map(|(index, (res_path, _))| {
            (
                perro_ids::string_to_u64(res_path),
                format!("NAVMESH_HASH_{index}"),
                format!("NAVMESH_{index}"),
            )
        })
        .collect::<Vec<_>>();
    write_static_lookup_fn(
        &mut out,
        "lookup_navmesh",
        "NAVMESH_TABLE",
        "NavMeshEntry",
        "&'static [u8]",
        "EMPTY_NAVMESH",
        &lookup_entries,
    );

    fs::write(static_dir.join("navmeshes.rs"), out)?;
    crate::record_static_assets(
        perro_asset_formats::dlc::DlcAssetKind::NAVMESH,
        perro_asset_formats::dlc::DlcAssetAccess::BYTES,
        navmeshes.iter().map(|(path, _)| (path.as_str(), false)),
    );
    Ok(())
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::generate_static_navmeshes;
    use crate::{StaticPipelineOverrides, set_static_pipeline_overrides};
    use std::{
        fs,
        path::PathBuf,
        time::{SystemTime, UNIX_EPOCH},
    };

    fn unique_temp_root(name: &str) -> PathBuf {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock")
            .as_nanos();
        std::env::temp_dir().join(format!("{name}_{stamp}"))
    }

    #[test]
    fn static_navmesh_embeds_valid_pnav() {
        let root = unique_temp_root("perro_static_navmesh");
        let res_dir = root.join("res");
        let embedded_dir = root.join("embedded");
        let static_dir = root.join("static");
        fs::create_dir_all(res_dir.join("nav")).expect("create nav dir");
        let source = "pnav 1\nv 0 0 0\nv 1 0 0\nv 0 0 1\ntri 0 1 2 1\n";
        fs::write(res_dir.join("nav/level.pnav"), source).expect("write pnav");

        set_static_pipeline_overrides(Some(StaticPipelineOverrides {
            res_dir: res_dir.clone(),
            static_dir: static_dir.clone(),
            embedded_dir: embedded_dir.clone(),
            asset_prefix: "res://".to_string(),
        }));
        let result = generate_static_navmeshes(&root);
        set_static_pipeline_overrides(None);
        result.expect("generate static navmeshes");

        let embedded = fs::read_to_string(embedded_dir.join("navmeshes/nav/level.pnav"))
            .expect("read embedded");
        assert_eq!(embedded, source);
        let generated =
            fs::read_to_string(static_dir.join("navmeshes.rs")).expect("read generated lookup");
        assert!(generated.contains("lookup_navmesh"));
        assert!(generated.contains("res://nav/level.pnav"));
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn static_navmesh_rejects_bad_pnav() {
        let root = unique_temp_root("perro_static_navmesh_bad");
        let res_dir = root.join("res");
        let embedded_dir = root.join("embedded");
        let static_dir = root.join("static");
        fs::create_dir_all(&res_dir).expect("create res dir");
        fs::write(res_dir.join("bad.pnav"), "pnav 1\n").expect("write bad pnav");

        set_static_pipeline_overrides(Some(StaticPipelineOverrides {
            res_dir,
            static_dir,
            embedded_dir,
            asset_prefix: "res://".to_string(),
        }));
        let result = generate_static_navmeshes(&root);
        set_static_pipeline_overrides(None);

        assert!(result.is_err());
        let _ = fs::remove_dir_all(root);
    }
}
