use crate::{StaticPipelineError, res_dir, static_dir};
use perro_io::walkdir::collect_file_paths;
use rayon::prelude::*;
use std::{collections::HashMap, fmt::Write as _, fs, io, path::Path};

pub fn generate_static_particles(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    fs::create_dir_all(&static_dir)?;

    let mut particle_paths = Vec::<String>::new();
    if res_dir.exists() {
        particle_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| Path::new(rel).extension().and_then(|e| e.to_str()) == Some("pparticle"))
            .collect();
    }
    particle_paths.sort();

    let mut particles = particle_paths
        .into_par_iter()
        .map(|rel| -> io::Result<(String, ParticleLiteral)> {
            let res_path = format!("res://{rel}");
            let full_path = res_dir.join(&rel);
            let src = fs::read_to_string(&full_path)?;
            let parsed = parse_pparticle_source(&src).ok_or_else(|| {
                io::Error::other(format!("failed to parse particle profile: {res_path}"))
            })?;
            Ok((res_path, parsed))
        })
        .collect::<io::Result<Vec<_>>>()?;

    particles.sort_by(|a, b| a.0.cmp(&b.0));

    let mut unique_particles = Vec::<ParticleLiteral>::new();
    let mut unique_by_key = HashMap::<ParticleKey, usize>::new();
    let mut particle_refs = Vec::<(String, usize)>::with_capacity(particles.len());
    for (path, particle) in particles {
        let key = ParticleKey::from(&particle);
        let index = if let Some(existing) = unique_by_key.get(&key).copied() {
            existing
        } else {
            let idx = unique_particles.len();
            unique_particles.push(particle);
            unique_by_key.insert(key, idx);
            idx
        };
        particle_refs.push((path, index));
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("use perro_render_bridge::{ParticlePath3D, PointParticleProfile3D};\n");
    out.push_str("use std::borrow::Cow;\n\n");

    for (index, particle) in unique_particles.iter().enumerate() {
        let const_name = format!("PARTICLE_{}", index);
        let init = emit_particle_literal(particle);
        let _ = writeln!(
            out,
            "static {const_name}: PointParticleProfile3D = {init};"
        );
    }
    out.push('\n');
    out.push_str("pub fn lookup_particle(path: &str) -> Option<&'static PointParticleProfile3D> {\n");
    out.push_str("    match path {\n");
    for (path, index) in &particle_refs {
        let _ = writeln!(
            out,
            "        \"{}\" => Some(&PARTICLE_{}),",
            escape_str(path),
            index
        );
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("particles.rs"), out)?;
    Ok(())
}

#[derive(Clone)]
struct ParticleLiteral {
    path: ParticlePathLiteral,
}

#[derive(Clone)]
enum ParticlePathLiteral {
    Ballistic,
    Spiral { angular_velocity: f32, radius: f32 },
    OrbitY { angular_velocity: f32, radius: f32 },
    NoiseDrift { amplitude: f32, frequency: f32 },
    Custom {
        expr_x: String,
        expr_y: String,
        expr_z: String,
    },
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
enum ParticlePathKey {
    Ballistic,
    Spiral { angular_velocity: u32, radius: u32 },
    OrbitY { angular_velocity: u32, radius: u32 },
    NoiseDrift { amplitude: u32, frequency: u32 },
    Custom {
        expr_x: String,
        expr_y: String,
        expr_z: String,
    },
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct ParticleKey {
    path: ParticlePathKey,
}

impl From<&ParticleLiteral> for ParticleKey {
    fn from(value: &ParticleLiteral) -> Self {
        let path = match &value.path {
            ParticlePathLiteral::Ballistic => ParticlePathKey::Ballistic,
            ParticlePathLiteral::Spiral {
                angular_velocity,
                radius,
            } => ParticlePathKey::Spiral {
                angular_velocity: angular_velocity.to_bits(),
                radius: radius.to_bits(),
            },
            ParticlePathLiteral::OrbitY {
                angular_velocity,
                radius,
            } => ParticlePathKey::OrbitY {
                angular_velocity: angular_velocity.to_bits(),
                radius: radius.to_bits(),
            },
            ParticlePathLiteral::NoiseDrift {
                amplitude,
                frequency,
            } => ParticlePathKey::NoiseDrift {
                amplitude: amplitude.to_bits(),
                frequency: frequency.to_bits(),
            },
            ParticlePathLiteral::Custom {
                expr_x,
                expr_y,
                expr_z,
            } => ParticlePathKey::Custom {
                expr_x: expr_x.clone(),
                expr_y: expr_y.clone(),
                expr_z: expr_z.clone(),
            },
        };
        Self { path }
    }
}

fn emit_particle_literal(particle: &ParticleLiteral) -> String {
    let path = match &particle.path {
        ParticlePathLiteral::Ballistic => "ParticlePath3D::Ballistic".to_string(),
        ParticlePathLiteral::Spiral {
            angular_velocity,
            radius,
        } => format!(
            "ParticlePath3D::Spiral {{ angular_velocity: {angular_velocity:?}, radius: {radius:?} }}"
        ),
        ParticlePathLiteral::OrbitY {
            angular_velocity,
            radius,
        } => format!(
            "ParticlePath3D::OrbitY {{ angular_velocity: {angular_velocity:?}, radius: {radius:?} }}"
        ),
        ParticlePathLiteral::NoiseDrift {
            amplitude,
            frequency,
        } => format!(
            "ParticlePath3D::NoiseDrift {{ amplitude: {amplitude:?}, frequency: {frequency:?} }}"
        ),
        ParticlePathLiteral::Custom {
            expr_x,
            expr_y,
            expr_z,
        } => format!(
            "ParticlePath3D::Custom {{ expr_x: Cow::Borrowed(\"{}\"), expr_y: Cow::Borrowed(\"{}\"), expr_z: Cow::Borrowed(\"{}\") }}",
            escape_str(expr_x),
            escape_str(expr_y),
            escape_str(expr_z)
        ),
    };
    format!("PointParticleProfile3D {{ path: {path} }}")
}

fn parse_pparticle_source(source: &str) -> Option<ParticleLiteral> {
    let mut path_mode = String::from("ballistic");
    let mut path_a = 1.0f32;
    let mut path_b = 1.0f32;
    let mut expr_x = String::from("0.0");
    let mut expr_y = String::from("0.0");
    let mut expr_z = String::from("0.0");
    for line in source.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with("//") {
            continue;
        }
        let (key, value) = line.split_once('=')?;
        let key = key.trim().to_ascii_lowercase();
        let value = value.trim();
        match key.as_str() {
            "mode" | "path_mode" => {
                path_mode = value.to_ascii_lowercase();
            }
            "param_a" | "angular_velocity" | "amplitude" => {
                path_a = value.parse::<f32>().ok().unwrap_or(path_a);
            }
            "param_b" | "radius" | "frequency" => {
                path_b = value.parse::<f32>().ok().unwrap_or(path_b);
            }
            "expr_x" => expr_x = value.to_string(),
            "expr_y" => expr_y = value.to_string(),
            "expr_z" => expr_z = value.to_string(),
            _ => {}
        }
    }
    let path = match path_mode.as_str() {
        "ballistic" => ParticlePathLiteral::Ballistic,
        "spiral" => ParticlePathLiteral::Spiral {
            angular_velocity: path_a,
            radius: path_b.abs(),
        },
        "orbity" | "orbit_y" | "orbit" => ParticlePathLiteral::OrbitY {
            angular_velocity: path_a,
            radius: path_b.abs(),
        },
        "noisedrift" | "noise_drift" | "noise" => ParticlePathLiteral::NoiseDrift {
            amplitude: path_a.abs(),
            frequency: path_b.abs(),
        },
        "custom" => ParticlePathLiteral::Custom {
            expr_x,
            expr_y,
            expr_z,
        },
        _ => ParticlePathLiteral::Ballistic,
    };
    Some(ParticleLiteral { path })
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
