use crate::{StaticPipelineError, ensure_unique_hashes, res_dir, static_dir};
use perro_io::walkdir::collect_file_paths;
use perro_particle_math::{Op, compile_expression};
use rayon::prelude::*;
use std::{collections::HashMap, fmt::Write as _, fs, io, path::Path};

pub fn generate_static_particles(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    fs::create_dir_all(&static_dir)?;

    let mut particle_paths = Vec::<String>::new();
    if res_dir.exists() {
        particle_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| ext.eq_ignore_ascii_case("ppart"))
            })
            .collect();
    }
    particle_paths.sort();

    let mut particles = particle_paths
        .into_par_iter()
        .map(|rel| -> io::Result<(String, ParticleLiteral)> {
            let res_path = format!("res://{rel}");
            let full_path = res_dir.join(&rel);
            let src = fs::read_to_string(&full_path)?;
            let parsed = parse_pparticle_source(&src).ok_or_else(|| {
                io::Error::other(format!("failed to parse particle profile: {res_path}"))
            })?;
            Ok((res_path, parsed))
        })
        .collect::<io::Result<Vec<_>>>()?;

    particles.sort_by(|a, b| a.0.cmp(&b.0));

    let mut unique_particles = Vec::<ParticleLiteral>::new();
    let mut unique_by_key = HashMap::<ParticleKey, usize>::new();
    let mut particle_refs = Vec::<(String, usize)>::with_capacity(particles.len());
    for (path, particle) in particles {
        let key = ParticleKey::from(&particle);
        let index = if let Some(existing) = unique_by_key.get(&key).copied() {
            existing
        } else {
            let idx = unique_particles.len();
            unique_particles.push(particle);
            unique_by_key.insert(key, idx);
            idx
        };
        particle_refs.push((path, index));
    }
    ensure_unique_hashes("particle", particle_refs.iter().map(|(path, _)| path.as_str()))?;

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n");
    out.push_str(
        "use perro_render_bridge::{ParticleExprOp3D, ParticlePath3D, ParticleProfile3D};\n",
    );
    out.push_str("use std::borrow::Cow;\n\n");

    for (index, particle) in unique_particles.iter().enumerate() {
        let const_name = format!("PARTICLE_{}", index);
        let init = emit_particle_literal(particle);
        let _ = writeln!(out, "static {const_name}: ParticleProfile3D = {init};");
    }
    out.push('\n');
    out.push_str(
        "static EMPTY_PARTICLE: ParticleProfile3D = ParticleProfile3D { path: ParticlePath3D::None, expr_x_ops: None, expr_y_ops: None, expr_z_ops: None, lifetime_min: 0.6, lifetime_max: 1.4, speed_min: 1.0, speed_max: 3.0, spread_radians: core::f32::consts::FRAC_PI_3, size: 6.0, size_min: 0.65, size_max: 1.35, force: [0.0, 0.0, 0.0], color_start: [1.0, 1.0, 1.0, 1.0], color_end: [1.0, 0.4, 0.1, 0.0], emissive: [0.0, 0.0, 0.0], spin_angular_velocity: 0.0 };\n\n",
    );
    out.push_str("pub const fn lookup_particle(path_hash: u64) -> &'static ParticleProfile3D {\n");
    out.push_str("    match path_hash {\n");
    for (path, index) in &particle_refs {
        let path_hash = perro_ids::string_to_u64(path);
        let _ = writeln!(
            out,
            "        {path_hash}u64 => &PARTICLE_{},",
            index,
        );
    }
    out.push_str("        _ => &EMPTY_PARTICLE,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("particles.rs"), out)?;
    Ok(())
}

#[derive(Clone)]
struct ParticleLiteral {
    path: ParticlePathLiteral,
    expr_x_ops: Option<Vec<Op>>,
    expr_y_ops: Option<Vec<Op>>,
    expr_z_ops: Option<Vec<Op>>,
    lifetime_min: f32,
    lifetime_max: f32,
    speed_min: f32,
    speed_max: f32,
    spread_radians: f32,
    size: f32,
    size_min: f32,
    size_max: f32,
    force: [f32; 3],
    color_start: [f32; 4],
    color_end: [f32; 4],
    emissive: [f32; 3],
    spin_angular_velocity: f32,
}

#[derive(Clone)]
enum ParticlePathLiteral {
    None,
    Ballistic,
    Spiral { angular_velocity: f32, radius: f32 },
    OrbitY { angular_velocity: f32, radius: f32 },
    NoiseDrift { amplitude: f32, frequency: f32 },
    FlatDisk { radius: f32 },
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
enum ParticlePathKey {
    None,
    Ballistic,
    Spiral { angular_velocity: u32, radius: u32 },
    OrbitY { angular_velocity: u32, radius: u32 },
    NoiseDrift { amplitude: u32, frequency: u32 },
    FlatDisk { radius: u32 },
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct ParticleKey {
    path: ParticlePathKey,
    expr_x_ops: Option<String>,
    expr_y_ops: Option<String>,
    expr_z_ops: Option<String>,
    lifetime_min: u32,
    lifetime_max: u32,
    speed_min: u32,
    speed_max: u32,
    spread_radians: u32,
    size: u32,
    size_min: u32,
    size_max: u32,
    force: [u32; 3],
    color_start: [u32; 4],
    color_end: [u32; 4],
    emissive: [u32; 3],
    spin_angular_velocity: u32,
}

impl From<&ParticleLiteral> for ParticleKey {
    fn from(value: &ParticleLiteral) -> Self {
        let path = match &value.path {
            ParticlePathLiteral::None => ParticlePathKey::None,
            ParticlePathLiteral::Ballistic => ParticlePathKey::Ballistic,
            ParticlePathLiteral::Spiral {
                angular_velocity,
                radius,
            } => ParticlePathKey::Spiral {
                angular_velocity: angular_velocity.to_bits(),
                radius: radius.to_bits(),
            },
            ParticlePathLiteral::OrbitY {
                angular_velocity,
                radius,
            } => ParticlePathKey::OrbitY {
                angular_velocity: angular_velocity.to_bits(),
                radius: radius.to_bits(),
            },
            ParticlePathLiteral::NoiseDrift {
                amplitude,
                frequency,
            } => ParticlePathKey::NoiseDrift {
                amplitude: amplitude.to_bits(),
                frequency: frequency.to_bits(),
            },
            ParticlePathLiteral::FlatDisk { radius } => ParticlePathKey::FlatDisk {
                radius: radius.to_bits(),
            },
        };
        let force = [
            value.force[0].to_bits(),
            value.force[1].to_bits(),
            value.force[2].to_bits(),
        ];
        let color_start = [
            value.color_start[0].to_bits(),
            value.color_start[1].to_bits(),
            value.color_start[2].to_bits(),
            value.color_start[3].to_bits(),
        ];
        let color_end = [
            value.color_end[0].to_bits(),
            value.color_end[1].to_bits(),
            value.color_end[2].to_bits(),
            value.color_end[3].to_bits(),
        ];
        let emissive = [
            value.emissive[0].to_bits(),
            value.emissive[1].to_bits(),
            value.emissive[2].to_bits(),
        ];
        Self {
            path,
            expr_x_ops: value.expr_x_ops.as_ref().map(|ops| emit_ops_literal(ops)),
            expr_y_ops: value.expr_y_ops.as_ref().map(|ops| emit_ops_literal(ops)),
            expr_z_ops: value.expr_z_ops.as_ref().map(|ops| emit_ops_literal(ops)),
            lifetime_min: value.lifetime_min.to_bits(),
            lifetime_max: value.lifetime_max.to_bits(),
            speed_min: value.speed_min.to_bits(),
            speed_max: value.speed_max.to_bits(),
            spread_radians: value.spread_radians.to_bits(),
            size: value.size.to_bits(),
            size_min: value.size_min.to_bits(),
            size_max: value.size_max.to_bits(),
            force,
            color_start,
            color_end,
            emissive,
            spin_angular_velocity: value.spin_angular_velocity.to_bits(),
        }
    }
}

fn emit_particle_literal(particle: &ParticleLiteral) -> String {
    let path = match &particle.path {
        ParticlePathLiteral::None => "ParticlePath3D::None".to_string(),
        ParticlePathLiteral::Ballistic => "ParticlePath3D::Ballistic".to_string(),
        ParticlePathLiteral::Spiral {
            angular_velocity,
            radius,
        } => format!(
            "ParticlePath3D::Spiral {{ angular_velocity: {angular_velocity:?}, radius: {radius:?} }}"
        ),
        ParticlePathLiteral::OrbitY {
            angular_velocity,
            radius,
        } => format!(
            "ParticlePath3D::OrbitY {{ angular_velocity: {angular_velocity:?}, radius: {radius:?} }}"
        ),
        ParticlePathLiteral::NoiseDrift {
            amplitude,
            frequency,
        } => format!(
            "ParticlePath3D::NoiseDrift {{ amplitude: {amplitude:?}, frequency: {frequency:?} }}"
        ),
        ParticlePathLiteral::FlatDisk { radius } => {
            format!("ParticlePath3D::FlatDisk {{ radius: {radius:?} }}")
        }
    };
    let expr_x_ops = particle
        .expr_x_ops
        .as_ref()
        .map(|ops| format!("Some(Cow::Borrowed(&[{}]))", emit_ops_literal(ops)))
        .unwrap_or_else(|| "None".to_string());
    let expr_y_ops = particle
        .expr_y_ops
        .as_ref()
        .map(|ops| format!("Some(Cow::Borrowed(&[{}]))", emit_ops_literal(ops)))
        .unwrap_or_else(|| "None".to_string());
    let expr_z_ops = particle
        .expr_z_ops
        .as_ref()
        .map(|ops| format!("Some(Cow::Borrowed(&[{}]))", emit_ops_literal(ops)))
        .unwrap_or_else(|| "None".to_string());
    format!(
        "ParticleProfile3D {{ path: {path}, expr_x_ops: {expr_x_ops}, expr_y_ops: {expr_y_ops}, expr_z_ops: {expr_z_ops}, lifetime_min: {:?}, lifetime_max: {:?}, speed_min: {:?}, speed_max: {:?}, spread_radians: {:?}, size: {:?}, size_min: {:?}, size_max: {:?}, force: [{:?}, {:?}, {:?}], color_start: [{:?}, {:?}, {:?}, {:?}], color_end: [{:?}, {:?}, {:?}, {:?}], emissive: [{:?}, {:?}, {:?}], spin_angular_velocity: {:?} }}",
        particle.lifetime_min,
        particle.lifetime_max,
        particle.speed_min,
        particle.speed_max,
        particle.spread_radians,
        particle.size,
        particle.size_min,
        particle.size_max,
        particle.force[0],
        particle.force[1],
        particle.force[2],
        particle.color_start[0],
        particle.color_start[1],
        particle.color_start[2],
        particle.color_start[3],
        particle.color_end[0],
        particle.color_end[1],
        particle.color_end[2],
        particle.color_end[3],
        particle.emissive[0],
        particle.emissive[1],
        particle.emissive[2],
        particle.spin_angular_velocity,
    )
}

fn parse_pparticle_source(source: &str) -> Option<ParticleLiteral> {
    let mut literal = ParticleLiteral {
        path: ParticlePathLiteral::Ballistic,
        lifetime_min: 0.6,
        lifetime_max: 1.4,
        speed_min: 1.0,
        speed_max: 3.0,
        spread_radians: std::f32::consts::FRAC_PI_3,
        size: 6.0,
        size_min: 0.65,
        size_max: 1.35,
        force: [0.0, 0.0, 0.0],
        color_start: [1.0, 1.0, 1.0, 1.0],
        color_end: [1.0, 0.4, 0.1, 0.0],
        emissive: [0.0, 0.0, 0.0],
        expr_x_ops: None,
        expr_y_ops: None,
        expr_z_ops: None,
        spin_angular_velocity: 0.0,
    };
    let mut preset: Option<String> = None;
    let mut preset_param_a = 1.0f32;
    let mut preset_param_b = 1.0f32;
    let mut preset_param_c = 0.0f32;
    let mut preset_param_d = 0.0f32;
    let mut expr_x = String::from("0.0");
    let mut expr_y = String::from("0.0");
    let mut expr_z = String::from("0.0");
    let mut has_expr_x = false;
    let mut has_expr_y = false;
    let mut has_expr_z = false;
    for line in source.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with("//") {
            continue;
        }
        let (key, value) = line.split_once('=')?;
        let key = key.trim().to_ascii_lowercase();
        let value = value.trim();
        match key.as_str() {
            "preset" => {
                preset = Some(value.to_ascii_lowercase());
            }
            "preset_param_a" => {
                preset_param_a = value.parse::<f32>().ok().unwrap_or(preset_param_a);
            }
            "preset_param_b" => {
                preset_param_b = value.parse::<f32>().ok().unwrap_or(preset_param_b);
            }
            "preset_param_c" => {
                preset_param_c = value.parse::<f32>().ok().unwrap_or(preset_param_c);
            }
            "preset_param_d" => {
                preset_param_d = value.parse::<f32>().ok().unwrap_or(preset_param_d);
            }
            "x" => expr_x = value.to_string(),
            "y" => expr_y = value.to_string(),
            "z" => expr_z = value.to_string(),
            "force" => {
                if let Some(v) = parse_vec3_literal(value) {
                    literal.force = v;
                }
            }
            "force_x" => {
                let v = value.parse::<f32>().ok()?;
                literal.force[0] = v;
            }
            "force_y" => {
                let v = value.parse::<f32>().ok()?;
                literal.force[1] = v;
            }
            "force_z" => {
                let v = value.parse::<f32>().ok()?;
                literal.force[2] = v;
            }
            "lifetime_min" => {
                literal.lifetime_min = value.parse::<f32>().ok().unwrap_or(literal.lifetime_min);
            }
            "lifetime_max" => {
                literal.lifetime_max = value.parse::<f32>().ok().unwrap_or(literal.lifetime_max);
            }
            "speed_min" => {
                literal.speed_min = value.parse::<f32>().ok().unwrap_or(literal.speed_min);
            }
            "speed_max" => {
                literal.speed_max = value.parse::<f32>().ok().unwrap_or(literal.speed_max);
            }
            "spread_radians" => {
                literal.spread_radians =
                    value.parse::<f32>().ok().unwrap_or(literal.spread_radians);
            }
            "size" => {
                literal.size = value.parse::<f32>().ok().unwrap_or(literal.size);
            }
            "size_min" => {
                literal.size_min = value.parse::<f32>().ok().unwrap_or(literal.size_min);
            }
            "size_max" => {
                literal.size_max = value.parse::<f32>().ok().unwrap_or(literal.size_max);
            }
            "color_start" => {
                if let Some(v) = parse_vec4_literal(value) {
                    literal.color_start = v;
                }
            }
            "color_end" => {
                if let Some(v) = parse_vec4_literal(value) {
                    literal.color_end = v;
                }
            }
            "emissive" => {
                if let Some(v) = parse_vec3_literal(value) {
                    literal.emissive = v;
                }
            }
            "spin" => {
                literal.spin_angular_velocity = value
                    .parse::<f32>()
                    .ok()
                    .unwrap_or(literal.spin_angular_velocity);
            }
            _ => {}
        }
        match key.as_str() {
            "x" => has_expr_x = true,
            "y" => has_expr_y = true,
            "z" => has_expr_z = true,
            _ => {}
        }
    }
    literal.path = match preset.as_deref() {
        None => ParticlePathLiteral::None,
        Some("ballistic") => ParticlePathLiteral::Ballistic,
        Some("spiral") => ParticlePathLiteral::Spiral {
            angular_velocity: preset_param_a,
            radius: preset_param_b.abs(),
        },
        Some("orbit_y") => ParticlePathLiteral::OrbitY {
            angular_velocity: preset_param_a,
            radius: preset_param_b.abs(),
        },
        Some("noise_drift") => ParticlePathLiteral::NoiseDrift {
            amplitude: preset_param_a.abs(),
            frequency: preset_param_b.abs(),
        },
        Some("flat_disk") => ParticlePathLiteral::FlatDisk {
            radius: preset_param_a.abs(),
        },
        Some(_) => ParticlePathLiteral::None,
    };
    let _ = (preset_param_c, preset_param_d);
    if has_expr_x || has_expr_y || has_expr_z {
        literal.expr_x_ops = Some(compile_expression(&expr_x).ok()?.ops().to_vec());
        literal.expr_y_ops = Some(compile_expression(&expr_y).ok()?.ops().to_vec());
        literal.expr_z_ops = Some(compile_expression(&expr_z).ok()?.ops().to_vec());
    }
    Some(literal)
}

fn emit_ops_literal(ops: &[Op]) -> String {
    ops.iter()
        .map(emit_op_literal)
        .collect::<Vec<_>>()
        .join(", ")
}

fn emit_op_literal(op: &Op) -> String {
    match op {
        Op::Const(v) => format!("ParticleExprOp3D::Const({v:?})"),
        Op::T => "ParticleExprOp3D::T".to_string(),
        Op::Life => "ParticleExprOp3D::Life".to_string(),
        Op::Lifetime => "ParticleExprOp3D::Lifetime".to_string(),
        Op::AgeLeft => "ParticleExprOp3D::AgeLeft".to_string(),
        Op::Age01 => "ParticleExprOp3D::Age01".to_string(),
        Op::SpawnTime => "ParticleExprOp3D::SpawnTime".to_string(),
        Op::EmitterTime => "ParticleExprOp3D::EmitterTime".to_string(),
        Op::Speed => "ParticleExprOp3D::Speed".to_string(),
        Op::Id => "ParticleExprOp3D::Id".to_string(),
        Op::DirX => "ParticleExprOp3D::DirX".to_string(),
        Op::DirY => "ParticleExprOp3D::DirY".to_string(),
        Op::DirZ => "ParticleExprOp3D::DirZ".to_string(),
        Op::VelX => "ParticleExprOp3D::VelX".to_string(),
        Op::VelY => "ParticleExprOp3D::VelY".to_string(),
        Op::VelZ => "ParticleExprOp3D::VelZ".to_string(),
        Op::Rand => "ParticleExprOp3D::Rand".to_string(),
        Op::Rand2 => "ParticleExprOp3D::Rand2".to_string(),
        Op::Rand3 => "ParticleExprOp3D::Rand3".to_string(),
        Op::Seed => "ParticleExprOp3D::Seed".to_string(),
        Op::RingU => "ParticleExprOp3D::RingU".to_string(),
        Op::Index01 => "ParticleExprOp3D::Index01".to_string(),
        Op::EmitterX => "ParticleExprOp3D::EmitterX".to_string(),
        Op::EmitterY => "ParticleExprOp3D::EmitterY".to_string(),
        Op::EmitterZ => "ParticleExprOp3D::EmitterZ".to_string(),
        Op::Param => "ParticleExprOp3D::Param".to_string(),
        Op::Add => "ParticleExprOp3D::Add".to_string(),
        Op::Sub => "ParticleExprOp3D::Sub".to_string(),
        Op::Mul => "ParticleExprOp3D::Mul".to_string(),
        Op::Div => "ParticleExprOp3D::Div".to_string(),
        Op::Pow => "ParticleExprOp3D::Pow".to_string(),
        Op::Neg => "ParticleExprOp3D::Neg".to_string(),
        Op::Sin => "ParticleExprOp3D::Sin".to_string(),
        Op::Cos => "ParticleExprOp3D::Cos".to_string(),
        Op::Tan => "ParticleExprOp3D::Tan".to_string(),
        Op::Abs => "ParticleExprOp3D::Abs".to_string(),
        Op::Sqrt => "ParticleExprOp3D::Sqrt".to_string(),
        Op::Min => "ParticleExprOp3D::Min".to_string(),
        Op::Max => "ParticleExprOp3D::Max".to_string(),
        Op::Clamp => "ParticleExprOp3D::Clamp".to_string(),
        Op::Hash => "ParticleExprOp3D::Hash".to_string(),
    }
}

fn parse_vec3_literal(raw: &str) -> Option<[f32; 3]> {
    let raw = raw.trim();
    let inner = raw.strip_prefix('(')?.strip_suffix(')')?;
    let mut it = inner.split(',').map(|v| v.trim().parse::<f32>().ok());
    Some([it.next()??, it.next()??, it.next()??])
}

fn parse_vec4_literal(raw: &str) -> Option<[f32; 4]> {
    let raw = raw.trim();
    let inner = raw.strip_prefix('(')?.strip_suffix(')')?;
    let mut it = inner.split(',').map(|v| v.trim().parse::<f32>().ok());
    Some([it.next()??, it.next()??, it.next()??, it.next()??])
}
