use crate::{
    StaticPipelineError, asset_prefix, asset_uri, ensure_unique_hashes, res_dir, static_dir,
    strip_asset_prefix,
};
use perro_io::walkdir::collect_file_paths;
use perro_scene::{Parser, SceneNodeData, SceneNodeDataBase, SceneValue};
use perro_structs::Color;
use rayon::prelude::*;
use std::{borrow::Cow, collections::HashMap, fmt::Write as _, fs, io, path::Path};

pub fn generate_static_scenes(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    fs::create_dir_all(&static_dir)?;

    let mut scene_paths = Vec::<String>::new();

    if res_dir.exists() {
        scene_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| ext.eq_ignore_ascii_case("scn"))
            })
            .map(|rel| asset_uri(&rel))
            .collect();
    }
    scene_paths.sort();
    ensure_unique_hashes("scene", scene_paths.iter().map(String::as_str))?;

    let mut emitted_scenes = scene_paths
        .par_iter()
        .map(|res_path| -> io::Result<(String, EmittedScene)> {
            let rel = strip_asset_prefix(res_path).ok_or_else(|| {
                io::Error::other(format!("scene path not in asset space: {res_path}"))
            })?;
            let full_path = res_dir.join(rel);
            let src = fs::read_to_string(&full_path)?;
            let mut parsed = std::panic::catch_unwind(|| Parser::new(&src).parse_scene())
                .map_err(|_| io::Error::other(format!("failed to parse scene: {res_path}")))?;
            if let Some(mount_name) = static_dlc_mount_name() {
                resolve_scene_dlc_self_paths(&mut parsed, &mount_name);
            }
            let emitted = emit_static_scene_const(res_path, &parsed)
                .map_err(|err| io::Error::other(err.to_string()))?;
            Ok((res_path.clone(), emitted))
        })
        .collect::<io::Result<Vec<_>>>()?;
    emitted_scenes.sort_by(|a, b| a.0.cmp(&b.0));

    let mut scene_defs = String::new();
    let mut any_uses_empty_keys = false;
    let mut any_uses_empty_tags = false;
    let mut any_uses_empty_fields = false;
    for (_res_path, emitted) in emitted_scenes {
        scene_defs.push_str(&emitted.code);
        any_uses_empty_keys |= emitted.uses_empty_keys;
        any_uses_empty_tags |= emitted.uses_empty_tags;
        any_uses_empty_fields |= emitted.uses_empty_fields;
    }

    let mut lookup = String::new();
    lookup.push_str("pub const fn lookup_scene(path_hash: u64) -> &'static Scene {\n");
    lookup.push_str("    match path_hash {\n");
    for p in &scene_paths {
        let id = sanitize_ident(p);
        let path_hash = perro_ids::string_to_u64(p);
        let _ = writeln!(lookup, "        {path_hash}u64 => &SCENE_{},", id,);
    }
    lookup.push_str("        _ => &EMPTY_SCENE,\n");
    lookup.push_str("    }\n");
    lookup.push_str("}\n");

    let mut shared_consts = String::new();
    if any_uses_empty_keys {
        shared_consts.push_str("const EMPTY_SCENE_KEYS: &[SceneKey] = &[];\n");
    }
    if any_uses_empty_tags {
        shared_consts.push_str("const EMPTY_SCENE_TAGS: &[Cow<'static, str>] = &[];\n");
    }
    if any_uses_empty_fields {
        shared_consts.push_str("const EMPTY_SCENE_FIELDS: &[SceneObjectField] = &[];\n");
    }
    shared_consts.push_str("const EMPTY_SCENE_NODES: &[SceneNodeEntry] = &[];\n");
    shared_consts.push_str("const EMPTY_SCENE: Scene = Scene { nodes: Cow::Borrowed(EMPTY_SCENE_NODES), root: None };\n");
    if !shared_consts.is_empty() {
        shared_consts.push('\n');
    }

    let scenes_src = format!(
        "// Auto-generated by Perro Static Pipeline. Do not edit.\n\
#![allow(unused_imports)]\n\
use perro_scene::{{SceneNodeDataBase, SceneObjectField, SceneValue, SceneValueKey, SceneNodeData, SceneNodeEntry, Scene, SceneKey}};\n\
use std::borrow::Cow;\n\n\
{shared_consts}\
{scene_defs}\n\
{lookup}",
        shared_consts = shared_consts
    );
    fs::write(static_dir.join("scenes.rs"), scenes_src)?;
    Ok(())
}

struct EmittedScene {
    code: String,
    uses_empty_keys: bool,
    uses_empty_tags: bool,
    uses_empty_fields: bool,
}

fn emit_static_scene_const(
    path: &str,
    scene: &perro_scene::Scene,
) -> Result<EmittedScene, StaticPipelineError> {
    let scene_ident = sanitize_ident(path);
    let mut out = String::new();
    let mut counter = 0usize;
    let mut node_entries = String::new();
    let mut uses_empty_keys = false;
    let mut uses_empty_tags = false;
    let mut uses_empty_fields = false;
    let mut children_by_parent: HashMap<String, Vec<usize>> = HashMap::new();
    for (child_index, node) in scene.nodes.iter().enumerate() {
        if let Some(parent) = &node.parent {
            children_by_parent
                .entry(parent.as_ref().to_string())
                .or_default()
                .push(child_index);
        }
    }

    for (index, node) in scene.nodes.iter().enumerate() {
        let children_ref = if let Some(children) = children_by_parent.get(node.key.as_ref()) {
            if children.is_empty() {
                uses_empty_keys = true;
                "EMPTY_SCENE_KEYS".to_string()
            } else {
                let children_name = format!("CHILDREN_{}_{}", scene_ident, index);
                let _ = writeln!(out, "const {children_name}: &[SceneKey] = &[");
                for &child_index in children {
                    let child_key = &scene.nodes[child_index].key;
                    let _ = writeln!(
                        out,
                        "    SceneKey(Cow::Borrowed(\"{}\")),",
                        escape_str(child_key.as_ref())
                    );
                }
                out.push_str("];\n");
                children_name
            }
        } else {
            uses_empty_keys = true;
            "EMPTY_SCENE_KEYS".to_string()
        };

        let data_const = emit_node_data_consts(
            &mut out,
            &scene_ident,
            &node.data,
            &mut counter,
            &mut uses_empty_fields,
        )?;
        let tags_ref = if node.tags.is_empty() {
            uses_empty_tags = true;
            "EMPTY_SCENE_TAGS".to_string()
        } else {
            let tags_name = format!("TAGS_{}_{}", scene_ident, index);
            let _ = writeln!(out, "const {tags_name}: &[Cow<'static, str>] = &[");
            for tag in node.tags.as_ref() {
                let _ = writeln!(out, "    Cow::Borrowed(\"{}\"),", escape_str(tag.as_ref()));
            }
            out.push_str("];\n");
            tags_name
        };
        node_entries.push_str(&format!(
            "    SceneNodeEntry {{ data: {data}, has_data_override: {has_data_override}, key: SceneKey(Cow::Borrowed(\"{key}\")), name: {name}, tags: Cow::Borrowed({tags}), children: Cow::Borrowed({children}), parent: {parent}, script: {script}, script_hash: {script_hash}, clear_script: {clear_script}, root_of: {root_of}, root_of_hash: {root_of_hash}, script_vars: Cow::Borrowed({script_vars}) }},\n",
            data = data_const,
            has_data_override = node.has_data_override,
            key = escape_str(node.key.as_ref()),
            name = opt_static_str(&node.name),
            tags = tags_ref,
            children = children_ref,
            parent = match &node.parent {
                Some(p) => format!(
                    "Some(SceneKey(Cow::Borrowed(\"{}\")))",
                    escape_str(p.as_ref())
                ),
                None => "None".to_string(),
            },
            script = opt_static_script_str(&node.script),
            script_hash = opt_static_script_hash(&node.script),
            clear_script = node.clear_script,
            root_of = opt_static_root_of_str(&node.root_of),
            root_of_hash = opt_static_root_of_hash(&node.root_of),
            script_vars = if node.script_vars.is_empty() {
                uses_empty_fields = true;
                "EMPTY_SCENE_FIELDS".to_string()
            } else {
                let script_vars_name = format!("SCRIPT_VARS_{}_{}", scene_ident, index);
                let mut nested_consts = String::new();
                let mut script_var_entries = String::new();
                for (name, value) in node.script_vars.as_ref() {
                    let emitted = emit_value_with_consts(
                        &mut nested_consts,
                        &scene_ident,
                        value,
                        &mut counter,
                        None,
                        None,
                    );
                    let _ = writeln!(
                        script_var_entries,
                        "    (Cow::Borrowed(\"{}\"), {}),",
                        escape_str(name.as_ref()),
                        emitted
                    );
                }
                out.push_str(&nested_consts);
                let _ = writeln!(out, "const {script_vars_name}: &[SceneObjectField] = &[");
                out.push_str(&script_var_entries);
                out.push_str("];\n");
                script_vars_name
            },
        ));
    }

    out.push_str(&format!(
        "const NODES_{id}: &[SceneNodeEntry] = &[\n{entries}];\n\n",
        id = scene_ident,
        entries = node_entries
    ));
    out.push_str(&format!(
        "pub static SCENE_{id}: Scene = Scene {{ nodes: Cow::Borrowed(NODES_{id}), root: {root} }};\n\n",
        id = scene_ident,
        root = match &scene.root {
            Some(r) => format!(
                "Some(SceneKey(Cow::Borrowed(\"{}\")))",
                escape_str(r.as_ref())
            ),
            None => "None".to_string(),
        }
    ));

    Ok(EmittedScene {
        code: out,
        uses_empty_keys,
        uses_empty_tags,
        uses_empty_fields,
    })
}

fn emit_node_data_consts(
    out: &mut String,
    scene_ident: &str,
    data: &SceneNodeData,
    counter: &mut usize,
    uses_empty_fields: &mut bool,
) -> Result<String, StaticPipelineError> {
    let idx = *counter;
    *counter += 1;
    let data_name = format!("DATA_{}_{}", scene_ident, idx);
    let ty = emit_static_node_type(data.ty.as_ref())?;
    let fields_ref = if data.fields.is_empty() {
        *uses_empty_fields = true;
        "EMPTY_SCENE_FIELDS".to_string()
    } else {
        let fields_name = format!("FIELDS_{}_{}", scene_ident, idx);
        let mut nested_consts = String::new();
        let mut field_entries = String::new();
        for (name, value) in data.fields.as_ref() {
            let emitted = emit_value_with_consts(
                &mut nested_consts,
                scene_ident,
                value,
                counter,
                Some(data.ty.as_ref()),
                Some(name.as_ref()),
            );
            let _ = writeln!(
                field_entries,
                "    (Cow::Borrowed(\"{}\"), {}),",
                escape_str(name.as_ref()),
                emitted
            );
        }
        out.push_str(&nested_consts);
        let _ = writeln!(out, "const {fields_name}: &[SceneObjectField] = &[");
        out.push_str(&field_entries);
        out.push_str("];\n");
        fields_name
    };

    let base_ref = if let Some(base) = &data.base {
        let base_data = match base {
            SceneNodeDataBase::Borrowed(v) => *v,
            SceneNodeDataBase::Owned(v) => v.as_ref(),
        };
        let base_name =
            emit_node_data_consts(out, scene_ident, base_data, counter, uses_empty_fields)?;
        format!("Some(SceneNodeDataBase::Borrowed(&{base_name}))")
    } else {
        "None".to_string()
    };

    let _ = writeln!(
        out,
        "const {data_name}: SceneNodeData = SceneNodeData {{ ty: Cow::Borrowed(\"{ty}\"), fields: Cow::Borrowed({fields_ref}), base: {base_ref} }};"
    );
    Ok(data_name)
}

fn emit_static_node_type(ty: &str) -> Result<&'static str, StaticPipelineError> {
    match ty {
        "Node" => Ok("Node"),
        "Node2D" => Ok("Node2D"),
        "CollisionShape2D" => Ok("CollisionShape2D"),
        "StaticBody2D" => Ok("StaticBody2D"),
        "Area2D" => Ok("Area2D"),
        "RigidBody2D" => Ok("RigidBody2D"),
        "Sprite2D" => Ok("Sprite2D"),
        "Camera2D" => Ok("Camera2D"),
        "Node3D" => Ok("Node3D"),
        "MeshInstance3D" => Ok("MeshInstance3D"),
        "MultiMeshInstance3D" => Ok("MultiMeshInstance3D"),
        "CollisionShape3D" => Ok("CollisionShape3D"),
        "StaticBody3D" => Ok("StaticBody3D"),
        "Area3D" => Ok("Area3D"),
        "RigidBody3D" => Ok("RigidBody3D"),
        "Skeleton3D" => Ok("Skeleton3D"),
        "Camera3D" => Ok("Camera3D"),
        "AmbientLight3D" => Ok("AmbientLight3D"),
        "Sky3D" => Ok("Sky3D"),
        "RayLight3D" => Ok("RayLight3D"),
        "PointLight3D" => Ok("PointLight3D"),
        "SpotLight3D" => Ok("SpotLight3D"),
        "ParticleEmitter3D" => Ok("ParticleEmitter3D"),
        "UiBox" => Ok("UiBox"),
        "UiPanel" => Ok("UiPanel"),
        "UiButton" => Ok("UiButton"),
        "UiLabel" => Ok("UiLabel"),
        "UiTextBox" => Ok("UiTextBox"),
        "UiTextBlock" => Ok("UiTextBlock"),
        "UiLayout" => Ok("UiLayout"),
        "UiHLayout" => Ok("UiHLayout"),
        "UiHBox" => Ok("UiHBox"),
        "UiVLayout" => Ok("UiVLayout"),
        "UiVBox" => Ok("UiVBox"),
        "UiGrid" => Ok("UiGrid"),
        "AnimationPlayer" => Ok("AnimationPlayer"),
        _ => Err(StaticPipelineError::SceneParse(format!(
            "unsupported static node type `{ty}`"
        ))),
    }
}

fn emit_value_with_consts(
    out: &mut String,
    scene_ident: &str,
    value: &SceneValue,
    counter: &mut usize,
    node_type: Option<&str>,
    field_name: Option<&str>,
) -> String {
    match value {
        SceneValue::Bool(v) => format!("SceneValue::Bool({v})"),
        SceneValue::I32(v) => format!("SceneValue::I32({v})"),
        SceneValue::F32(v) => format!("SceneValue::F32({v:?})"),
        SceneValue::Vec2 { x, y } => {
            format!("SceneValue::Vec2 {{ x: {x:?}, y: {y:?} }}")
        }
        SceneValue::Vec3 { x, y, z } => {
            format!("SceneValue::Vec3 {{ x: {x:?}, y: {y:?}, z: {z:?} }}")
        }
        SceneValue::Vec4 { x, y, z, w } => {
            format!("SceneValue::Vec4 {{ x: {x:?}, y: {y:?}, z: {z:?}, w: {w:?} }}")
        }
        SceneValue::Str(s) => {
            emit_static_scene_value_str(node_type, field_name, s.as_ref()).to_string()
        }
        SceneValue::Hashed(v) => format!("SceneValue::Hashed({v}u64)"),
        SceneValue::Key(s) => {
            format!(
                "SceneValue::Key(SceneValueKey(Cow::Borrowed(\"{}\")))",
                escape_str(s.as_ref())
            )
        }
        SceneValue::Object(entries) => {
            let idx = *counter;
            *counter += 1;
            let object_name = format!("OBJECT_{}_{}", scene_ident, idx);
            let mut nested_consts = String::new();
            let mut object_entries = String::new();
            for (name, value) in entries.as_ref() {
                let nested = emit_value_with_consts(
                    &mut nested_consts,
                    scene_ident,
                    value,
                    counter,
                    node_type,
                    Some(name.as_ref()),
                );
                let _ = writeln!(
                    object_entries,
                    "    (Cow::Borrowed(\"{}\"), {}),",
                    escape_str(name.as_ref()),
                    nested
                );
            }
            out.push_str(&nested_consts);
            let _ = writeln!(out, "const {object_name}: &[SceneObjectField] = &[");
            out.push_str(&object_entries);
            out.push_str("];\n");
            format!("SceneValue::Object(Cow::Borrowed({object_name}))")
        }
        SceneValue::Array(items) => {
            let idx = *counter;
            *counter += 1;
            let array_name = format!("ARRAY_{}_{}", scene_ident, idx);
            let mut nested_consts = String::new();
            let mut array_entries = String::new();
            for value in items.as_ref() {
                let nested = emit_value_with_consts(
                    &mut nested_consts,
                    scene_ident,
                    value,
                    counter,
                    node_type,
                    field_name,
                );
                let _ = writeln!(array_entries, "    {},", nested);
            }
            out.push_str(&nested_consts);
            let _ = writeln!(out, "const {array_name}: &[SceneValue] = &[");
            out.push_str(&array_entries);
            out.push_str("];\n");
            format!("SceneValue::Array(Cow::Borrowed({array_name}))")
        }
    }
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn opt_static_str(v: &Option<Cow<'static, str>>) -> String {
    match v {
        Some(s) => format!("Some(Cow::Borrowed(\"{}\"))", escape_str(s.as_ref())),
        None => "None".to_string(),
    }
}

fn opt_static_script_str(v: &Option<Cow<'static, str>>) -> String {
    match v {
        Some(s) if static_hashable_path(s.as_ref()).is_some() => "None".to_string(),
        Some(s) => format!("Some(Cow::Borrowed(\"{}\"))", escape_str(s.as_ref())),
        None => "None".to_string(),
    }
}

fn opt_static_script_hash(v: &Option<Cow<'static, str>>) -> String {
    match v {
        Some(s) => static_hashable_path(s.as_ref())
            .map(|hash| format!("Some({hash}u64)"))
            .unwrap_or_else(|| "None".to_string()),
        None => "None".to_string(),
    }
}

fn opt_static_root_of_str(v: &Option<Cow<'static, str>>) -> String {
    match v {
        Some(s) if static_hashable_scene_path(s.as_ref()) => "None".to_string(),
        Some(s) => format!("Some(Cow::Borrowed(\"{}\"))", escape_str(s.as_ref())),
        None => "None".to_string(),
    }
}

fn opt_static_root_of_hash(v: &Option<Cow<'static, str>>) -> String {
    match v {
        Some(s) if static_hashable_scene_path(s.as_ref()) => {
            format!("Some({}u64)", perro_ids::string_to_u64(s.as_ref()))
        }
        None => "None".to_string(),
        _ => "None".to_string(),
    }
}

fn emit_static_scene_value_str(
    node_type: Option<&str>,
    field_name: Option<&str>,
    s: &str,
) -> String {
    if field_name.is_some_and(|field_name| is_static_rgba_color_field(node_type, field_name))
        && let Some(color) = Color::from_hex(s)
    {
        return emit_static_scene_color4(color);
    }
    if field_name.is_some_and(is_static_rgb_color_field)
        && let Some(color) = Color::from_hex(s)
    {
        return emit_static_scene_color3(color);
    }
    if let Some(hash) = static_hashable_path(s) {
        format!("SceneValue::Hashed({hash}u64)")
    } else {
        format!("SceneValue::Str(Cow::Borrowed(\"{}\"))", escape_str(s))
    }
}

fn is_static_rgba_color_field(node_type: Option<&str>, field_name: &str) -> bool {
    match field_name {
        "fill" | "stroke" | "text_color" | "placeholder_color" | "hint_color"
        | "selection_color" | "caret_color" | "cursor_color" | "hover_fill" | "hover_stroke"
        | "pressed_fill" | "pressed_stroke" | "focused_fill" | "focused_stroke" | "modulate"
        | "baseColorFactor" | "base_color_factor" => true,
        "color" | "hover_color" | "pressed_color" | "focused_color" => {
            node_type.is_some_and(is_static_ui_node)
        }
        _ => false,
    }
}

fn is_static_rgb_color_field(field_name: &str) -> bool {
    matches!(
        field_name,
        "emissiveFactor" | "emissive_factor" | "day_colors" | "evening_colors" | "night_colors"
    )
}

fn is_static_ui_node(node_type: &str) -> bool {
    matches!(
        node_type,
        "UiBox"
            | "UiPanel"
            | "UiButton"
            | "UiLabel"
            | "UiTextBox"
            | "UiTextBlock"
            | "UiControl"
            | "UiLayout"
            | "UiHLayout"
            | "UiHBox"
            | "UiVLayout"
            | "UiVBox"
            | "UiGrid"
    )
}

fn emit_static_scene_color4(color: Color) -> String {
    format!(
        "SceneValue::Vec4 {{ x: {:?}, y: {:?}, z: {:?}, w: {:?} }}",
        color.r, color.g, color.b, color.a
    )
}

fn emit_static_scene_color3(color: Color) -> String {
    format!(
        "SceneValue::Vec3 {{ x: {:?}, y: {:?}, z: {:?} }}",
        color.r, color.g, color.b
    )
}

fn static_dlc_mount_name() -> Option<String> {
    let prefix = asset_prefix();
    let rest = prefix.strip_prefix("dlc://")?;
    let mount = rest.trim_end_matches('/');
    if mount.is_empty() || mount.eq_ignore_ascii_case("self") {
        return None;
    }
    Some(mount.to_string())
}

fn resolve_scene_dlc_self_paths(scene: &mut perro_scene::Scene, mount_name: &str) {
    let prefix = "dlc://self/";
    let replacement = format!("dlc://{mount_name}/");
    let replacement_ref = replacement.as_str();
    for node in scene.nodes.to_mut() {
        if let Some(script) = node.script.as_ref()
            && script.starts_with(prefix)
        {
            node.script = Some(Cow::Owned(script.replacen(prefix, replacement_ref, 1)));
        }
        if let Some(root_of) = node.root_of.as_ref()
            && root_of.starts_with(prefix)
        {
            node.root_of = Some(Cow::Owned(root_of.replacen(prefix, replacement_ref, 1)));
        }
        resolve_scene_value_fields_dlc_self(node.script_vars.to_mut(), prefix, replacement_ref);
        resolve_scene_node_data_dlc_self(&mut node.data, prefix, replacement_ref);
    }
}

fn resolve_scene_node_data_dlc_self(data: &mut SceneNodeData, prefix: &str, replacement: &str) {
    resolve_scene_value_fields_dlc_self(data.fields.to_mut(), prefix, replacement);
    if let Some(base) = data.base.as_mut()
        && let SceneNodeDataBase::Owned(base_data) = base
    {
        resolve_scene_node_data_dlc_self(base_data.as_mut(), prefix, replacement);
    }
}

fn resolve_scene_value_fields_dlc_self(
    fields: &mut [perro_scene::SceneObjectField],
    prefix: &str,
    replacement: &str,
) {
    for (_, value) in fields {
        resolve_scene_value_dlc_self(value, prefix, replacement);
    }
}

fn resolve_scene_value_dlc_self(value: &mut SceneValue, prefix: &str, replacement: &str) {
    match value {
        SceneValue::Str(v) if v.as_ref().starts_with(prefix) => {
            *v = Cow::Owned(v.replacen(prefix, replacement, 1));
        }
        SceneValue::Object(fields) => {
            for (_, item) in fields.to_mut() {
                resolve_scene_value_dlc_self(item, prefix, replacement);
            }
        }
        SceneValue::Array(values) => {
            for item in values.to_mut() {
                resolve_scene_value_dlc_self(item, prefix, replacement);
            }
        }
        _ => {}
    }
}

fn static_hashable_scene_path(s: &str) -> bool {
    if !is_res_uri(s) {
        return false;
    }
    let (path_part, _) = split_source_fragment(s);
    Path::new(path_part)
        .extension()
        .and_then(|e| e.to_str())
        .is_some_and(|ext| ext.eq_ignore_ascii_case("scn"))
}

fn static_hashable_path(s: &str) -> Option<u64> {
    if !is_res_uri(s) {
        return None;
    }
    let path_part = split_source_fragment(s).0;
    let ext = Path::new(path_part)
        .extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_ascii_lowercase())?;
    let hashable = matches!(
        ext.as_str(),
        "rs" | "scn"
            | "pmat"
            | "panim"
            | "pmesh"
            | "pskel"
            | "pparticle"
            | "png"
            | "jpg"
            | "jpeg"
            | "bmp"
            | "gif"
            | "ico"
            | "tga"
            | "webp"
            | "rgba"
            | "wgsl"
            | "mp3"
            | "wav"
            | "ogg"
            | "flac"
            | "aac"
            | "m4a"
            | "glb"
            | "gltf"
    );
    hashable.then(|| perro_ids::string_to_u64(s))
}

fn is_res_uri(path: &str) -> bool {
    path.starts_with("res://")
}

fn split_source_fragment(source: &str) -> (&str, Option<&str>) {
    let Some((path, selector)) = source.rsplit_once(':') else {
        return (source, None);
    };
    if path.is_empty() || selector.contains('/') || selector.contains('\\') {
        return (source, None);
    }
    if selector.contains('[') && selector.ends_with(']') {
        return (path, Some(selector));
    }
    (source, None)
}

fn sanitize_ident(path: &str) -> String {
    let mut out = String::new();
    for c in path.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_uppercase());
        } else {
            out.push('_');
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::{
        emit_static_node_type, emit_static_scene_value_str, resolve_scene_dlc_self_paths,
        static_hashable_path,
    };
    use perro_scene::Parser;

    #[test]
    fn static_node_type_supports_registry_nodes() {
        let nodes = [
            "Node",
            "Node2D",
            "Camera2D",
            "Sprite2D",
            "CollisionShape2D",
            "StaticBody2D",
            "Area2D",
            "RigidBody2D",
            "Node3D",
            "Camera3D",
            "MeshInstance3D",
            "MultiMeshInstance3D",
            "CollisionShape3D",
            "StaticBody3D",
            "Area3D",
            "RigidBody3D",
            "Skeleton3D",
            "ParticleEmitter3D",
            "AmbientLight3D",
            "Sky3D",
            "RayLight3D",
            "PointLight3D",
            "SpotLight3D",
            "UiBox",
            "UiPanel",
            "UiButton",
            "UiLabel",
            "UiTextBox",
            "UiTextBlock",
            "UiLayout",
            "UiHLayout",
            "UiHBox",
            "UiVLayout",
            "UiVBox",
            "UiGrid",
            "AnimationPlayer",
        ];

        for node in nodes {
            assert_eq!(emit_static_node_type(node).unwrap(), node);
        }
    }

    #[test]
    fn static_hashable_path_hashes_scheme_plus_fragment_paths() {
        let source = "res://terrain.glb:mesh[0]";
        assert_eq!(
            static_hashable_path(source),
            Some(perro_ids::string_to_u64(source))
        );
    }

    #[test]
    fn static_hashable_path_hashes_script_paths() {
        let source = "res://scripts/game_manager.rs";
        assert_eq!(
            static_hashable_path(source),
            Some(perro_ids::string_to_u64(source))
        );
    }

    #[test]
    fn static_hashable_path_does_not_hash_dlc_paths() {
        let source = "dlc://test/models/hero.glb";
        assert_eq!(static_hashable_path(source), None);
    }

    #[test]
    fn static_color_field_hex_emits_vec4() {
        assert_eq!(
            emit_static_scene_value_str(Some("UiPanel"), Some("fill"), "#4C3B55"),
            "SceneValue::Vec4 { x: 0.29803923, y: 0.23137255, z: 0.33333334, w: 1.0 }"
        );
    }

    #[test]
    fn static_ui_text_edit_hex_fields_emit_vec4() {
        assert_eq!(
            emit_static_scene_value_str(Some("UiTextBox"), Some("color"), "#4C3B55"),
            "SceneValue::Vec4 { x: 0.29803923, y: 0.23137255, z: 0.33333334, w: 1.0 }"
        );
        assert_eq!(
            emit_static_scene_value_str(Some("UiTextBlock"), Some("focused_color"), "#4C3B55"),
            "SceneValue::Vec4 { x: 0.29803923, y: 0.23137255, z: 0.33333334, w: 1.0 }"
        );
        assert_eq!(
            emit_static_scene_value_str(Some("UiTextBox"), Some("caret_color"), "#4C3B55"),
            "SceneValue::Vec4 { x: 0.29803923, y: 0.23137255, z: 0.33333334, w: 1.0 }"
        );
    }

    #[test]
    fn static_non_color_field_hex_stays_string() {
        assert_eq!(
            emit_static_scene_value_str(None, Some("text"), "#4C3B55"),
            "SceneValue::Str(Cow::Borrowed(\"#4C3B55\"))"
        );
    }

    #[test]
    fn static_plain_color_hex_stays_string_without_ui_context() {
        assert_eq!(
            emit_static_scene_value_str(Some("RayLight3D"), Some("color"), "#4C3B55"),
            "SceneValue::Str(Cow::Borrowed(\"#4C3B55\"))"
        );
    }

    #[test]
    fn static_material_hex_fields_emit_color_values() {
        assert_eq!(
            emit_static_scene_value_str(None, Some("base_color_factor"), "#4C3B55"),
            "SceneValue::Vec4 { x: 0.29803923, y: 0.23137255, z: 0.33333334, w: 1.0 }"
        );
        assert_eq!(
            emit_static_scene_value_str(None, Some("emissive_factor"), "#4C3B55"),
            "SceneValue::Vec3 { x: 0.29803923, y: 0.23137255, z: 0.33333334 }"
        );
    }

    #[test]
    fn resolve_scene_dlc_self_paths_rewrites_scene_strings() {
        let mut scene = Parser::new(
            r#"
            @root = main
            [main]
            script = "dlc://self/scripts/script.rs"
            script_vars = { mesh = "dlc://self/models/hero.glb" }
            [Node]
            [/Node]
            [/main]
            "#,
        )
        .parse_scene();

        resolve_scene_dlc_self_paths(&mut scene, "test");
        let node = &scene.nodes[0];
        assert_eq!(node.script.as_deref(), Some("dlc://test/scripts/script.rs"));
        let mesh = node
            .script_vars
            .iter()
            .find(|(k, _)| k.as_ref() == "mesh")
            .and_then(|(_, v)| v.as_str());
        assert_eq!(mesh, Some("dlc://test/models/hero.glb"));
    }
}
