use crate::{
    ResFileTree, StaticPipelineError, asset_uri, embedded_dir, ensure_unique_hashes,
    prune_embedded_dir, res_dir, static_dir, write_hash_const, write_if_changed,
    write_static_lookup_fn,
};
use perro_asset_formats::source_ext;
use std::{collections::HashSet, fmt::Write as _, fs, path::Path};

pub fn generate_static_shaders(
    project_root: &Path,
    res_tree: &ResFileTree,
) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    let embedded_shaders_dir = embedded_dir(project_root).join("shaders");
    fs::create_dir_all(&static_dir)?;
    fs::create_dir_all(&embedded_shaders_dir)?;

    let shader_paths = res_tree.filter_ext(|ext| source_ext::contains(source_ext::SHADER, ext));

    let mut shaders = Vec::<(String, String)>::with_capacity(shader_paths.len());
    let mut synthesized_shaders = HashSet::<String>::new();
    for rel in shader_paths {
        let res_path = asset_uri(&rel);
        let full_path = res_dir.join(&rel);
        let source = fs::read_to_string(&full_path)?;
        check_shader_source(&res_path, &source)?;
        let optimized = perro_wgsl::optimize_source(&source);

        let output_path = embedded_shaders_dir.join(&rel);
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)?;
        }
        write_if_changed(&output_path, optimized.as_bytes())?;
        shaders.push((res_path, rel));
    }
    if !crate::materials::collect_shader_bake_jobs(project_root, res_tree)?.is_empty() {
        let res_path = crate::materials::baked_sample_shader_uri();
        synthesized_shaders.insert(res_path.clone());
        let rel = "__perro_baked__/sample_texture.wgsl".to_string();
        let output_path = embedded_shaders_dir.join(&rel);
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)?;
        }
        let source = "fn shade_material(in: FragmentInput) -> vec4<f32> { return custom_image_sample(in, 0u, in.uv); }\n";
        write_if_changed(&output_path, source.as_bytes())?;
        shaders.push((res_path, rel));
    }
    prune_embedded_dir(
        &embedded_shaders_dir,
        &shaders
            .iter()
            .map(|(_, rel)| rel.clone())
            .collect::<HashSet<_>>(),
    )?;

    shaders.sort_by(|a, b| a.0.cmp(&b.0));
    ensure_unique_hashes("shader", shaders.iter().map(|(path, _)| path.as_str()))?;

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n\n");
    for (index, (_res_path, rel)) in shaders.iter().enumerate() {
        let include_path = format!("../../embedded/shaders/{}", escape_str(rel));
        let _ = writeln!(
            out,
            "static SHADER_{index}: &str = include_str!(\"{include_path}\");"
        );
    }
    if !shaders.is_empty() {
        out.push('\n');
    }
    out.push_str("static EMPTY_SHADER: &str = \"\";\n\n");
    for (index, (res_path, _)) in shaders.iter().enumerate() {
        write_hash_const(&mut out, &format!("SHADER_HASH_{index}"), res_path);
    }
    if !shaders.is_empty() {
        out.push('\n');
    }
    let lookup_entries = shaders
        .iter()
        .enumerate()
        .map(|(index, (res_path, _))| {
            (
                perro_ids::string_to_u64(res_path),
                format!("SHADER_HASH_{index}"),
                format!("SHADER_{index}"),
            )
        })
        .collect::<Vec<_>>();
    write_static_lookup_fn(
        &mut out,
        "lookup_shader",
        "SHADER",
        "&'static str",
        "EMPTY_SHADER",
        &lookup_entries,
    );

    write_if_changed(&static_dir.join("shaders.rs"), out.as_bytes())?;
    crate::record_static_assets(
        perro_asset_formats::dlc::DlcAssetKind::SHADER,
        perro_asset_formats::dlc::DlcAssetAccess::BYTES,
        shaders
            .iter()
            .map(|(path, _)| (path.as_str(), synthesized_shaders.contains(path))),
    );
    Ok(())
}

// Same composition + naga pass `perro doctor` runs, so a broken shader fails
// the static build instead of the first frame that draws with it. A file with
// no engine entry fn is left alone: it may be scratch work the game never
// loads, and doctor already warns about it.
fn check_shader_source(res_path: &str, source: &str) -> Result<(), StaticPipelineError> {
    match perro_wgsl::check::check_user_shader_source(source) {
        Ok(_) | Err(perro_wgsl::check::ShaderCheckError::UnknownKind) => Ok(()),
        Err(perro_wgsl::check::ShaderCheckError::Invalid { kind, diagnostics }) => {
            let mut msg = format!("{res_path}: invalid {}", kind.label());
            for diagnostic in &diagnostics {
                msg.push_str(&format!("\n  {res_path}:{diagnostic}"));
            }
            Err(StaticPipelineError::ShaderCheck(msg))
        }
    }
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::generate_static_shaders;
    use crate::{StaticPipelineOverrides, set_static_pipeline_overrides};
    use std::{
        fs,
        path::PathBuf,
        time::{SystemTime, UNIX_EPOCH},
    };

    fn unique_temp_root(name: &str) -> PathBuf {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock")
            .as_nanos();
        std::env::temp_dir().join(format!("{name}_{stamp}"))
    }

    #[test]
    fn static_shader_embed_matches_shared_optimizer() {
        let root = unique_temp_root("perro_static_shader_exact");
        let res_dir = root.join("res");
        let embedded_dir = root.join("embedded");
        let static_dir = root.join("static");
        fs::create_dir_all(res_dir.join("shaders")).expect("create shader dir");
        let source = r#"// keep comments + layout
fn shade_material(in: FragmentInput) -> vec4<f32> {
    let color = unpack_rgba8(in.packed_color); /* inline */
    return vec4<f32>(color.rgb * custom_f_param(in, 0u).rgb, color.a);
}

fn bake_texture(in: BakeInput) -> vec4<f32> {
    return vec4<f32>(in.uv, bake_param(in, 0u).x, 1.0);
}
"#;
        fs::write(res_dir.join("shaders/custom.wgsl"), source).expect("write shader");

        set_static_pipeline_overrides(Some(StaticPipelineOverrides {
            res_dir: res_dir.clone(),
            static_dir,
            embedded_dir: embedded_dir.clone(),
            asset_prefix: "res://".to_string(),
        }));
        let result =
            generate_static_shaders(&root, &crate::ResFileTree::scan(&root).expect("res scan"));
        set_static_pipeline_overrides(None);
        result.expect("generate static shaders");

        let embedded = fs::read_to_string(embedded_dir.join("shaders/shaders/custom.wgsl"))
            .expect("read embedded");
        assert_eq!(embedded, perro_wgsl::optimize_source(source));
        assert!(embedded.len() < source.len());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn static_build_rejects_broken_shader() {
        let root = unique_temp_root("perro_static_shader_broken");
        let res_dir = root.join("res");
        fs::create_dir_all(res_dir.join("shaders")).expect("create shader dir");
        fs::write(
            res_dir.join("shaders/broken.wgsl"),
            "fn shade_material(in: FragmentInput) -> vec4<f32> {\n    return perro_not_a_helper(in);\n}\n",
        )
        .expect("write shader");

        set_static_pipeline_overrides(Some(StaticPipelineOverrides {
            res_dir,
            static_dir: root.join("static"),
            embedded_dir: root.join("embedded"),
            asset_prefix: "res://".to_string(),
        }));
        let result =
            generate_static_shaders(&root, &crate::ResFileTree::scan(&root).expect("res scan"));
        set_static_pipeline_overrides(None);

        let err = result.expect_err("broken shader must fail the static build");
        let msg = err.to_string();
        assert!(msg.contains("res://shaders/broken.wgsl"), "{msg}");
        assert!(msg.contains(":2:"), "{msg}");
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn static_build_keeps_shader_without_entry_fn() {
        let root = unique_temp_root("perro_static_shader_no_entry");
        let res_dir = root.join("res");
        fs::create_dir_all(res_dir.join("shaders")).expect("create shader dir");
        fs::write(
            res_dir.join("shaders/helpers.wgsl"),
            "fn scratch_helper(x: f32) -> f32 { return x * 2.0; }\n",
        )
        .expect("write shader");

        set_static_pipeline_overrides(Some(StaticPipelineOverrides {
            res_dir,
            static_dir: root.join("static"),
            embedded_dir: root.join("embedded"),
            asset_prefix: "res://".to_string(),
        }));
        let result =
            generate_static_shaders(&root, &crate::ResFileTree::scan(&root).expect("res scan"));
        set_static_pipeline_overrides(None);

        result.expect("shader with no engine entry fn must not fail the build");
        let _ = fs::remove_dir_all(root);
    }
}
