use crate::{StaticPipelineError, embedded_dir, res_dir, static_dir};
use perro_io::walkdir::collect_file_paths;
use std::{fmt::Write as _, fs, path::Path};

const SHADER_EXTENSIONS: &[&str] = &["wgsl"];

pub fn generate_static_shaders(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    let embedded_shaders_dir = embedded_dir(project_root).join("shaders");
    fs::create_dir_all(&static_dir)?;
    fs::create_dir_all(&embedded_shaders_dir)?;

    let mut shader_paths = Vec::<String>::new();
    if res_dir.exists() {
        shader_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .map(|ext| ext.to_ascii_lowercase())
                    .is_some_and(|ext| SHADER_EXTENSIONS.contains(&ext.as_str()))
            })
            .collect();
    }
    shader_paths.sort();

    let mut shaders = Vec::<(String, String)>::with_capacity(shader_paths.len());
    for rel in shader_paths {
        let res_path = format!("res://{rel}");
        let full_path = res_dir.join(&rel);
        let data = fs::read(&full_path)?;

        let output_path = embedded_shaders_dir.join(&rel);
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&output_path, data)?;
        shaders.push((res_path, rel));
    }

    shaders.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n\n");
    for (index, (_res_path, rel)) in shaders.iter().enumerate() {
        let include_path = format!("../../embedded/shaders/{}", escape_str(rel));
        let _ = writeln!(
            out,
            "static SHADER_{index}: &str = include_str!(\"{include_path}\");"
        );
    }
    if !shaders.is_empty() {
        out.push('\n');
    }
    out.push_str("pub fn lookup_shader(path: &str) -> Option<&'static str> {\n");
    out.push_str("    match path {\n");
    for (index, (res_path, _)) in shaders.iter().enumerate() {
        let _ = writeln!(
            out,
            "        \"{}\" => Some(SHADER_{index}),",
            escape_str(res_path)
        );
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("shaders.rs"), out)?;
    Ok(())
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}
