use crate::{StaticPipelineError, embedded_dir, ensure_unique_hashes, res_dir, static_dir};
use perro_io::walkdir::collect_file_paths;
use std::{fmt::Write as _, fs, path::Path};

const SHADER_EXTENSIONS: &[&str] = &["wgsl"];

pub fn generate_static_shaders(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    let embedded_shaders_dir = embedded_dir(project_root).join("shaders");
    fs::create_dir_all(&static_dir)?;
    fs::create_dir_all(&embedded_shaders_dir)?;

    let mut shader_paths = Vec::<String>::new();
    if res_dir.exists() {
        shader_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .map(|ext| ext.to_ascii_lowercase())
                    .is_some_and(|ext| SHADER_EXTENSIONS.contains(&ext.as_str()))
            })
            .collect();
    }
    shader_paths.sort();

    let mut shaders = Vec::<(String, String)>::with_capacity(shader_paths.len());
    for rel in shader_paths {
        let res_path = format!("res://{rel}");
        let full_path = res_dir.join(&rel);
        let data = fs::read(&full_path)?;
        let minified = minify_wgsl_for_embed(&String::from_utf8_lossy(&data));

        let output_path = embedded_shaders_dir.join(&rel);
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&output_path, minified)?;
        shaders.push((res_path, rel));
    }

    shaders.sort_by(|a, b| a.0.cmp(&b.0));
    ensure_unique_hashes("shader", shaders.iter().map(|(path, _)| path.as_str()))?;

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n\n");
    for (index, (_res_path, rel)) in shaders.iter().enumerate() {
        let include_path = format!("../../embedded/shaders/{}", escape_str(rel));
        let _ = writeln!(
            out,
            "static SHADER_{index}: &str = include_str!(\"{include_path}\");"
        );
    }
    if !shaders.is_empty() {
        out.push('\n');
    }
    out.push_str("static EMPTY_SHADER: &str = \"\";\n\n");
    out.push_str("pub const fn lookup_shader(path_hash: u64) -> &'static str {\n");
    out.push_str("    match path_hash {\n");
    for (index, (res_path, _)) in shaders.iter().enumerate() {
        let path_hash = perro_ids::string_to_u64(res_path);
        let _ = writeln!(out, "        {path_hash}u64 => SHADER_{index},");
    }
    out.push_str("        _ => EMPTY_SHADER,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("shaders.rs"), out)?;
    Ok(())
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

fn minify_wgsl_for_embed(src: &str) -> String {
    let mut out = String::with_capacity(src.len());
    let mut first = true;
    for raw_line in src.lines() {
        let line = strip_line_comment_preserving_strings(raw_line).trim();
        if line.is_empty() {
            continue;
        }
        if !first {
            out.push(' ');
        }
        out.push_str(line);
        first = false;
    }
    out
}

fn strip_line_comment_preserving_strings(line: &str) -> &str {
    let bytes = line.as_bytes();
    let mut i = 0usize;
    let mut in_string = false;
    let mut escaped = false;
    while i < bytes.len() {
        let b = bytes[i];
        if in_string {
            if escaped {
                escaped = false;
            } else if b == b'\\' {
                escaped = true;
            } else if b == b'"' {
                in_string = false;
            }
            i += 1;
            continue;
        }
        if b == b'"' {
            in_string = true;
            i += 1;
            continue;
        }
        if b == b'/' && i + 1 < bytes.len() && bytes[i + 1] == b'/' {
            return &line[..i];
        }
        i += 1;
    }
    line
}
