use crate::{StaticPipelineError, embedded_dir, ensure_unique_hashes, res_dir, static_dir};
use perro_io::{compress_zlib_best, walkdir::collect_file_paths};
use perro_structs::{Quaternion, Transform3D, Vector3};
use rayon::prelude::*;
use std::{
    fmt::Write as _,
    fs, io,
    path::{Path, PathBuf},
};

const PSKEL_MAGIC: &[u8; 5] = b"PSKEL";
const PSKEL_VERSION: u32 = 2;
const PSKEL_BONE_FLAG_HAS_PARENT: u32 = 1 << 0;
const PSKEL_BONE_FLAG_HAS_REST_POS: u32 = 1 << 1;
const PSKEL_BONE_FLAG_HAS_REST_SCALE: u32 = 1 << 2;
const PSKEL_BONE_FLAG_HAS_REST_ROT: u32 = 1 << 3;
const PSKEL_BONE_FLAG_HAS_INV_POS: u32 = 1 << 4;
const PSKEL_BONE_FLAG_HAS_INV_SCALE: u32 = 1 << 5;
const PSKEL_BONE_FLAG_HAS_INV_ROT: u32 = 1 << 6;

#[derive(Clone)]
struct SkeletonRef {
    lookup_key: String,
    embedded_rel_path: String,
}

struct SkeletonAsset {
    entry: SkeletonRef,
    bytes: Vec<u8>,
}

#[derive(Clone, Debug, PartialEq)]
struct BoneLiteral {
    name: String,
    parent: i32,
    rest: Transform3D,
    inv_bind: Transform3D,
}

pub fn generate_static_skeletons(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    let embedded_skeletons_dir = embedded_dir(project_root).join("skeletons");
    fs::create_dir_all(&static_dir)?;
    fs::create_dir_all(&embedded_skeletons_dir)?;

    let mut skeleton_paths = Vec::<String>::new();
    if res_dir.exists() {
        skeleton_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| {
                        matches!(ext.to_ascii_lowercase().as_str(), "pskel" | "glb" | "gltf")
                    })
            })
            .collect();
    }
    skeleton_paths.sort();

    let processed = skeleton_paths
        .into_par_iter()
        .map(|rel| -> io::Result<Vec<SkeletonAsset>> {
            let res_path = format!("res://{rel}");
            let full_path = res_dir.join(&rel);
            let ext = Path::new(&rel)
                .extension()
                .and_then(|e| e.to_str())
                .map(|s| s.to_ascii_lowercase())
                .unwrap_or_default();
            match ext.as_str() {
                "pskel" => {
                    let bytes = fs::read(&full_path)?;
                    let baked = if bytes.starts_with(PSKEL_MAGIC) {
                        bytes
                    } else {
                        let text = std::str::from_utf8(&bytes).map_err(|err| {
                            io::Error::other(format!(
                                "pskel `{res_path}` is not valid UTF-8: {err}"
                            ))
                        })?;
                        let bones = parse_pskel_text(text).map_err(io::Error::other)?;
                        encode_pskel_tightest(&bones)?
                    };
                    Ok(vec![SkeletonAsset {
                        entry: SkeletonRef {
                            lookup_key: res_path,
                            embedded_rel_path: rel,
                        },
                        bytes: baked,
                    }])
                }
                "glb" | "gltf" => {
                    build_gltf_skeleton_entries(&full_path, &res_path, &rel).map(|entries| {
                        entries
                            .into_iter()
                            .map(|(entry, bytes)| SkeletonAsset { entry, bytes })
                            .collect()
                    })
                }
                _ => Ok(Vec::new()),
            }
        })
        .collect::<io::Result<Vec<_>>>()?;

    let mut skeleton_assets = processed.into_iter().flatten().collect::<Vec<_>>();
    skeleton_assets.sort_by(|a, b| a.entry.embedded_rel_path.cmp(&b.entry.embedded_rel_path));

    let mut skeleton_refs = Vec::<SkeletonRef>::with_capacity(skeleton_assets.len());
    for asset in skeleton_assets {
        let output_path = embedded_skeletons_dir.join(&asset.entry.embedded_rel_path);
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&output_path, asset.bytes)?;
        skeleton_refs.push(asset.entry);
    }

    skeleton_refs.sort_by(|a, b| a.lookup_key.cmp(&b.lookup_key));
    skeleton_refs.dedup_by(|a, b| a.lookup_key == b.lookup_key);
    ensure_unique_hashes(
        "skeleton",
        skeleton_refs.iter().map(|skeleton| skeleton.lookup_key.as_str()),
    )?;

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n");
    out.push_str("#![allow(dead_code)]\n\n");
    for (index, skel_ref) in skeleton_refs.iter().enumerate() {
        let include_path = format!(
            "../../embedded/skeletons/{}",
            escape_str(&skel_ref.embedded_rel_path)
        );
        let _ = writeln!(
            out,
            "static SKELETON_{index}: &[u8] = include_bytes!(\"{include_path}\");"
        );
    }
    if !skeleton_refs.is_empty() {
        out.push('\n');
    }
    out.push_str("static EMPTY_SKELETON: &[u8] = b\"\";\n\n");
    out.push_str("pub const fn lookup_skeleton(path_hash: u64) -> &'static [u8] {\n");
    out.push_str("    match path_hash {\n");
    for (index, skel_ref) in skeleton_refs.iter().enumerate() {
        let path_hash = perro_ids::string_to_u64(&skel_ref.lookup_key);
        let _ = writeln!(
            out,
            "        {path_hash}u64 => SKELETON_{index},"
        );
    }
    out.push_str("        _ => EMPTY_SKELETON,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("skeletons.rs"), out)?;
    Ok(())
}

fn build_gltf_skeleton_entries(
    path: &Path,
    res_path: &str,
    rel: &str,
) -> io::Result<Vec<(SkeletonRef, Vec<u8>)>> {
    let (doc, buffers, _images) = gltf::import(path)
        .map_err(|err| io::Error::other(format!("failed to import model `{res_path}`: {err}")))?;

    let mut entries = Vec::<(SkeletonRef, Vec<u8>)>::new();
    let mut rel_base = PathBuf::from(rel);
    rel_base.set_extension("");
    let rel_base = rel_base.to_string_lossy().replace('\\', "/");

    let mut parent_by_node = vec![None::<usize>; doc.nodes().len()];
    for node in doc.nodes() {
        let parent_index = node.index();
        for child in node.children() {
            parent_by_node[child.index()] = Some(parent_index);
        }
    }

    for (skin_index, skin) in doc.skins().enumerate() {
        let joints: Vec<_> = skin.joints().collect();
        if joints.is_empty() {
            continue;
        }
        let mut joint_index_by_node = std::collections::HashMap::<usize, usize>::new();
        for (index, joint) in joints.iter().enumerate() {
            joint_index_by_node.insert(joint.index(), index);
        }

        let inv_bind_mats = if let Some(accessor) = skin.inverse_bind_matrices() {
            match read_inv_bind_mats(&accessor, &buffers) {
                Ok(mats) => mats
                    .into_iter()
                    .map(transform_from_matrix)
                    .collect::<Vec<_>>(),
                Err(_) => vec![Transform3D::IDENTITY; joints.len()],
            }
        } else {
            vec![Transform3D::IDENTITY; joints.len()]
        };

        let mut bones = Vec::<BoneLiteral>::with_capacity(joints.len());
        for (joint_index, joint) in joints.iter().enumerate() {
            let name = joint
                .name()
                .map(|n| n.to_string())
                .unwrap_or_else(|| format!("Bone{joint_index}"));
            let parent = resolve_joint_parent(joint.index(), &parent_by_node, &joint_index_by_node);
            let rest = transform_from_node(joint);
            let inv_bind = inv_bind_mats
                .get(joint_index)
                .copied()
                .unwrap_or(Transform3D::IDENTITY);
            bones.push(BoneLiteral {
                name,
                parent,
                rest,
                inv_bind,
            });
        }

        let pskel = encode_pskel_tightest(&bones)?;
        let embedded_rel_path = format!("{rel_base}_skeleton{skin_index}.pskel");
        let key_bracket = format!("{res_path}:skeleton[{skin_index}]");
        entries.push((
            SkeletonRef {
                lookup_key: key_bracket,
                embedded_rel_path,
            },
            pskel,
        ));
    }

    Ok(entries)
}

fn resolve_joint_parent(
    joint_node_index: usize,
    parent_by_node: &[Option<usize>],
    joint_index_by_node: &std::collections::HashMap<usize, usize>,
) -> i32 {
    let mut cursor = parent_by_node.get(joint_node_index).copied().flatten();
    while let Some(parent_idx) = cursor {
        if let Some(joint_index) = joint_index_by_node.get(&parent_idx) {
            return *joint_index as i32;
        }
        cursor = parent_by_node.get(parent_idx).copied().flatten();
    }
    -1
}

fn transform_from_node(node: &gltf::Node) -> Transform3D {
    match node.transform() {
        gltf::scene::Transform::Decomposed {
            translation,
            rotation,
            scale,
        } => Transform3D::new(
            Vector3::new(translation[0], translation[1], translation[2]),
            Quaternion::new(rotation[0], rotation[1], rotation[2], rotation[3]),
            Vector3::new(scale[0], scale[1], scale[2]),
        ),
        gltf::scene::Transform::Matrix { matrix } => transform_from_matrix(matrix),
    }
}

fn transform_from_matrix(matrix: [[f32; 4]; 4]) -> Transform3D {
    // glTF matrices are column-major. Basis vectors are columns 0..2, translation is column 3.
    let x = Vector3::new(matrix[0][0], matrix[0][1], matrix[0][2]);
    let y = Vector3::new(matrix[1][0], matrix[1][1], matrix[1][2]);
    let z = Vector3::new(matrix[2][0], matrix[2][1], matrix[2][2]);
    let position = Vector3::new(matrix[3][0], matrix[3][1], matrix[3][2]);

    let sx = x.length();
    let sy = y.length();
    let sz = z.length();
    let scale = Vector3::new(sx, sy, sz);

    let nx = if sx > 0.0 {
        Vector3::new(x.x / sx, x.y / sx, x.z / sx)
    } else {
        Vector3::new(1.0, 0.0, 0.0)
    };
    let ny = if sy > 0.0 {
        Vector3::new(y.x / sy, y.y / sy, y.z / sy)
    } else {
        Vector3::new(0.0, 1.0, 0.0)
    };
    let nz = if sz > 0.0 {
        Vector3::new(z.x / sz, z.y / sz, z.z / sz)
    } else {
        Vector3::new(0.0, 0.0, 1.0)
    };

    let rotation = quat_from_basis(nx, ny, nz);

    Transform3D::new(position, rotation, scale)
}

fn quat_from_basis(x: Vector3, y: Vector3, z: Vector3) -> Quaternion {
    // Rotation matrix (columns are basis vectors)
    let m00 = x.x;
    let m01 = y.x;
    let m02 = z.x;
    let m10 = x.y;
    let m11 = y.y;
    let m12 = z.y;
    let m20 = x.z;
    let m21 = y.z;
    let m22 = z.z;

    let trace = m00 + m11 + m22;
    if trace > 0.0 {
        let s = (trace + 1.0).sqrt() * 2.0;
        let w = 0.25 * s;
        let x = (m21 - m12) / s;
        let y = (m02 - m20) / s;
        let z = (m10 - m01) / s;
        Quaternion::new(x, y, z, w)
    } else if m00 > m11 && m00 > m22 {
        let s = (1.0 + m00 - m11 - m22).sqrt() * 2.0;
        let w = (m21 - m12) / s;
        let x = 0.25 * s;
        let y = (m01 + m10) / s;
        let z = (m02 + m20) / s;
        Quaternion::new(x, y, z, w)
    } else if m11 > m22 {
        let s = (1.0 + m11 - m00 - m22).sqrt() * 2.0;
        let w = (m02 - m20) / s;
        let x = (m01 + m10) / s;
        let y = 0.25 * s;
        let z = (m12 + m21) / s;
        Quaternion::new(x, y, z, w)
    } else {
        let s = (1.0 + m22 - m00 - m11).sqrt() * 2.0;
        let w = (m10 - m01) / s;
        let x = (m02 + m20) / s;
        let y = (m12 + m21) / s;
        let z = 0.25 * s;
        Quaternion::new(x, y, z, w)
    }
}

fn encode_pskel_tightest(bones: &[BoneLiteral]) -> io::Result<Vec<u8>> {
    encode_pskel_v2(bones)
}

fn encode_pskel_v2(bones: &[BoneLiteral]) -> io::Result<Vec<u8>> {
    let mut raw = Vec::<u8>::new();
    for bone in bones {
        let name_bytes = bone.name.as_bytes();
        raw.extend_from_slice(&(name_bytes.len() as u32).to_le_bytes());
        raw.extend_from_slice(name_bytes);

        let mut flags = 0u32;
        if bone.parent != -1 {
            flags |= PSKEL_BONE_FLAG_HAS_PARENT;
        }
        if !is_vec3_default(bone.rest.position, Vector3::ZERO) {
            flags |= PSKEL_BONE_FLAG_HAS_REST_POS;
        }
        if !is_vec3_default(bone.rest.scale, Vector3::ONE) {
            flags |= PSKEL_BONE_FLAG_HAS_REST_SCALE;
        }
        if !is_quat_default(bone.rest.rotation, Quaternion::IDENTITY) {
            flags |= PSKEL_BONE_FLAG_HAS_REST_ROT;
        }
        if !is_vec3_default(bone.inv_bind.position, Vector3::ZERO) {
            flags |= PSKEL_BONE_FLAG_HAS_INV_POS;
        }
        if !is_vec3_default(bone.inv_bind.scale, Vector3::ONE) {
            flags |= PSKEL_BONE_FLAG_HAS_INV_SCALE;
        }
        if !is_quat_default(bone.inv_bind.rotation, Quaternion::IDENTITY) {
            flags |= PSKEL_BONE_FLAG_HAS_INV_ROT;
        }
        raw.extend_from_slice(&flags.to_le_bytes());

        if (flags & PSKEL_BONE_FLAG_HAS_PARENT) != 0 {
            raw.extend_from_slice(&bone.parent.to_le_bytes());
        }
        if (flags & PSKEL_BONE_FLAG_HAS_REST_POS) != 0 {
            write_vec3(&mut raw, bone.rest.position);
        }
        if (flags & PSKEL_BONE_FLAG_HAS_REST_SCALE) != 0 {
            write_vec3(&mut raw, bone.rest.scale);
        }
        if (flags & PSKEL_BONE_FLAG_HAS_REST_ROT) != 0 {
            write_quat(&mut raw, bone.rest.rotation);
        }
        if (flags & PSKEL_BONE_FLAG_HAS_INV_POS) != 0 {
            write_vec3(&mut raw, bone.inv_bind.position);
        }
        if (flags & PSKEL_BONE_FLAG_HAS_INV_SCALE) != 0 {
            write_vec3(&mut raw, bone.inv_bind.scale);
        }
        if (flags & PSKEL_BONE_FLAG_HAS_INV_ROT) != 0 {
            write_quat(&mut raw, bone.inv_bind.rotation);
        }
    }
    encode_pskel_blob(PSKEL_VERSION, bones.len(), &raw)
}

fn encode_pskel_blob(version: u32, bone_count: usize, raw: &[u8]) -> io::Result<Vec<u8>> {
    let compressed = compress_zlib_best(&raw)?;
    let mut out = Vec::with_capacity(5 + 4 * std::mem::size_of::<u32>() + compressed.len());
    out.extend_from_slice(PSKEL_MAGIC);
    out.extend_from_slice(&version.to_le_bytes());
    out.extend_from_slice(&(bone_count as u32).to_le_bytes());
    out.extend_from_slice(&(raw.len() as u32).to_le_bytes());
    out.extend_from_slice(&compressed);
    Ok(out)
}

fn read_inv_bind_mats(
    accessor: &gltf::Accessor,
    buffers: &[gltf::buffer::Data],
) -> Result<Vec<[[f32; 4]; 4]>, String> {
    if accessor.sparse().is_some() {
        return Err("sparse inverse bind matrices not supported".to_string());
    }
    let view = accessor
        .view()
        .ok_or("inverse bind accessor missing view")?;
    let buffer = buffers
        .get(view.buffer().index())
        .ok_or("inverse bind buffer missing")?;
    if accessor.data_type() != gltf::accessor::DataType::F32
        || accessor.dimensions() != gltf::accessor::Dimensions::Mat4
    {
        return Err("inverse bind accessor must be F32 MAT4".to_string());
    }
    let stride = view.stride().unwrap_or(64);
    let base = view.offset() + accessor.offset();
    let count = accessor.count();
    let bytes = buffer.0.as_slice();

    (0..count)
        .map(|i| -> Result<[[f32; 4]; 4], String> {
            let start = base + i * stride;
            if start + 64 > bytes.len() {
                return Err("inverse bind buffer out of bounds".to_string());
            }

            let mut mat = [[0.0f32; 4]; 4];
            // Create all matrix indices using iterator
            let indices = (0..4).flat_map(|col| (0..4).map(move |row| (col, row)));

            for (col, row) in indices {
                let idx = start + (col * 4 + row) * 4;
                let raw = bytes[idx..idx + 4]
                    .try_into()
                    .map_err(|_| "buffer slice error")?;
                mat[col][row] = f32::from_le_bytes(raw);
            }

            Ok(mat)
        })
        .collect()
}

fn parse_pskel_text(source: &str) -> Result<Vec<BoneLiteral>, String> {
    let mut bones = Vec::<BoneLiteral>::new();
    let mut current: Option<BoneLiteral> = None;

    for (line_no, raw_line) in source.lines().enumerate() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with("//") {
            continue;
        }
        if let Some(name) = parse_bone_start(line) {
            if current.is_some() {
                return Err(format!("pskel: nested bone at line {}", line_no + 1));
            }
            current = Some(BoneLiteral {
                name,
                parent: -1,
                rest: Transform3D::IDENTITY,
                inv_bind: Transform3D::IDENTITY,
            });
            continue;
        }
        if line.eq_ignore_ascii_case("[/bone]") {
            if let Some(bone) = current.take() {
                bones.push(bone);
                continue;
            }
            return Err(format!(
                "pskel: closing [/bone] without open at line {}",
                line_no + 1
            ));
        }

        let Some((key, value)) = line.split_once('=') else {
            return Err(format!("pskel: invalid line {}: {line}", line_no + 1));
        };
        let key = key.trim();
        let value = value.trim();

        let Some(bone) = current.as_mut() else {
            return Err(format!("pskel: field outside bone at line {}", line_no + 1));
        };

        match key {
            "parent" => {
                bone.parent = value
                    .parse::<i32>()
                    .map_err(|_| format!("pskel: invalid parent at line {}", line_no + 1))?;
            }
            "rest_pos" => bone.rest.position = parse_vec3(value, line_no + 1)?,
            "rest_scale" => bone.rest.scale = parse_vec3(value, line_no + 1)?,
            "rest_rot" => bone.rest.rotation = parse_quat(value, line_no + 1)?,
            "inv_pos" => bone.inv_bind.position = parse_vec3(value, line_no + 1)?,
            "inv_scale" => bone.inv_bind.scale = parse_vec3(value, line_no + 1)?,
            "inv_rot" => bone.inv_bind.rotation = parse_quat(value, line_no + 1)?,
            _ => {
                return Err(format!(
                    "pskel: unknown field `{key}` at line {}",
                    line_no + 1
                ));
            }
        }
    }

    if current.is_some() {
        return Err("pskel: missing [/bone] at end".to_string());
    }

    Ok(bones)
}

fn parse_bone_start(line: &str) -> Option<String> {
    let line = line.trim();
    if !line.starts_with("[bone") || !line.ends_with(']') {
        return None;
    }
    let inner = line
        .trim_start_matches("[bone")
        .trim_end_matches(']')
        .trim();
    if inner.is_empty() {
        return None;
    }
    if let Some(stripped) = inner.strip_prefix('"').and_then(|s| s.strip_suffix('"')) {
        return Some(stripped.to_string());
    }
    Some(inner.to_string())
}

fn parse_vec3(value: &str, line_no: usize) -> Result<Vector3, String> {
    let nums = parse_tuple(value, 3, line_no)?;
    Ok(Vector3::new(nums[0], nums[1], nums[2]))
}

fn parse_quat(value: &str, line_no: usize) -> Result<Quaternion, String> {
    let nums = parse_tuple(value, 4, line_no)?;
    Ok(Quaternion::new(nums[0], nums[1], nums[2], nums[3]))
}

fn parse_tuple(value: &str, count: usize, line_no: usize) -> Result<Vec<f32>, String> {
    let trimmed = value.trim();
    let inner = trimmed
        .strip_prefix('(')
        .and_then(|s| s.strip_suffix(')'))
        .ok_or_else(|| format!("pskel: expected tuple at line {line_no}"))?;
    let parts: Vec<_> = inner.split(',').map(|s| s.trim()).collect();
    if parts.len() != count {
        return Err(format!("pskel: expected {count} values at line {line_no}"));
    }
    let mut out = Vec::with_capacity(count);
    for part in parts {
        let value = part
            .parse::<f32>()
            .map_err(|_| format!("pskel: invalid number at line {line_no}"))?;
        out.push(value);
    }
    Ok(out)
}

fn write_vec3(out: &mut Vec<u8>, vec: Vector3) {
    write_f32(out, vec.x);
    write_f32(out, vec.y);
    write_f32(out, vec.z);
}

fn write_quat(out: &mut Vec<u8>, quat: Quaternion) {
    write_f32(out, quat.x);
    write_f32(out, quat.y);
    write_f32(out, quat.z);
    write_f32(out, quat.w);
}

fn is_vec3_default(value: Vector3, default: Vector3) -> bool {
    nearly_eq(value.x, default.x) && nearly_eq(value.y, default.y) && nearly_eq(value.z, default.z)
}

fn is_quat_default(value: Quaternion, default: Quaternion) -> bool {
    nearly_eq(value.x, default.x)
        && nearly_eq(value.y, default.y)
        && nearly_eq(value.z, default.z)
        && nearly_eq(value.w, default.w)
}

fn nearly_eq(a: f32, b: f32) -> bool {
    (a - b).abs() <= 1.0e-6
}

fn write_f32(out: &mut Vec<u8>, value: f32) {
    out.extend_from_slice(&value.to_le_bytes());
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::{BoneLiteral, PSKEL_VERSION, encode_pskel_tightest, encode_pskel_v2};
    use perro_structs::{Quaternion, Transform3D, Vector3};

    fn dense_bone() -> BoneLiteral {
        BoneLiteral {
            name: "hip".to_string(),
            parent: 0,
            rest: Transform3D::new(
                Vector3::new(1.1, 2.2, 3.3),
                Quaternion::new(0.1, 0.2, 0.3, 0.9),
                Vector3::new(1.2, 0.8, 1.4),
            ),
            inv_bind: Transform3D::new(
                Vector3::new(4.4, 5.5, 6.6),
                Quaternion::new(0.2, 0.3, 0.4, 0.8),
                Vector3::new(0.7, 1.3, 0.9),
            ),
        }
    }

    fn sparse_bone() -> BoneLiteral {
        BoneLiteral {
            name: "root".to_string(),
            parent: -1,
            rest: Transform3D::IDENTITY,
            inv_bind: Transform3D::IDENTITY,
        }
    }

    fn decode_pskel_for_test(bytes: &[u8]) -> Vec<BoneLiteral> {
        assert!(bytes.len() >= 17);
        assert_eq!(&bytes[0..5], b"PSKEL");
        let version = u32::from_le_bytes(bytes[5..9].try_into().expect("version"));
        assert_eq!(version, PSKEL_VERSION);
        let bone_count = u32::from_le_bytes(bytes[9..13].try_into().expect("count")) as usize;
        let raw_len = u32::from_le_bytes(bytes[13..17].try_into().expect("raw_len")) as usize;
        let raw = perro_io::decompress_zlib(&bytes[17..]).expect("decompress");
        assert_eq!(raw.len(), raw_len);

        let mut cursor = 0usize;
        let mut out = Vec::with_capacity(bone_count);
        for _ in 0..bone_count {
            let name_len =
                u32::from_le_bytes(raw[cursor..cursor + 4].try_into().expect("name_len")) as usize;
            cursor += 4;
            let name = std::str::from_utf8(&raw[cursor..cursor + name_len])
                .expect("name utf8")
                .to_string();
            cursor += name_len;

            let flags = u32::from_le_bytes(raw[cursor..cursor + 4].try_into().expect("flags"));
            cursor += 4;
            let parent = if (flags & (1 << 0)) != 0 {
                let value = i32::from_le_bytes(raw[cursor..cursor + 4].try_into().expect("parent"));
                cursor += 4;
                value
            } else {
                -1
            };
            let mut rest = Transform3D::IDENTITY;
            let mut inv_bind = Transform3D::IDENTITY;
            if (flags & (1 << 1)) != 0 {
                rest.position = read_vec3_from_raw(&raw, &mut cursor);
            }
            if (flags & (1 << 2)) != 0 {
                rest.scale = read_vec3_from_raw(&raw, &mut cursor);
            }
            if (flags & (1 << 3)) != 0 {
                rest.rotation = read_quat_from_raw(&raw, &mut cursor);
            }
            if (flags & (1 << 4)) != 0 {
                inv_bind.position = read_vec3_from_raw(&raw, &mut cursor);
            }
            if (flags & (1 << 5)) != 0 {
                inv_bind.scale = read_vec3_from_raw(&raw, &mut cursor);
            }
            if (flags & (1 << 6)) != 0 {
                inv_bind.rotation = read_quat_from_raw(&raw, &mut cursor);
            }
            out.push(BoneLiteral {
                name,
                parent,
                rest,
                inv_bind,
            });
        }
        out
    }

    fn read_f32_from_raw(raw: &[u8], cursor: &mut usize) -> f32 {
        let value = f32::from_le_bytes(raw[*cursor..*cursor + 4].try_into().expect("f32"));
        *cursor += 4;
        value
    }

    fn read_vec3_from_raw(raw: &[u8], cursor: &mut usize) -> Vector3 {
        Vector3::new(
            read_f32_from_raw(raw, cursor),
            read_f32_from_raw(raw, cursor),
            read_f32_from_raw(raw, cursor),
        )
    }

    fn read_quat_from_raw(raw: &[u8], cursor: &mut usize) -> Quaternion {
        Quaternion::new(
            read_f32_from_raw(raw, cursor),
            read_f32_from_raw(raw, cursor),
            read_f32_from_raw(raw, cursor),
            read_f32_from_raw(raw, cursor),
        )
    }

    #[test]
    fn encode_pskel_tightest_emits_v2() {
        let bones = vec![sparse_bone(); 64];
        let v2 = encode_pskel_v2(&bones).expect("encode v2");
        let selected = encode_pskel_tightest(&bones).expect("encode tightest");
        assert_eq!(selected, v2);
        assert_eq!(u32::from_le_bytes(selected[5..9].try_into().expect("version")), 2);
    }

    #[test]
    fn encode_pskel_versions_decode_to_same_bones() {
        let bones = vec![dense_bone(), sparse_bone()];
        let selected = encode_pskel_tightest(&bones).expect("encode tightest");
        let decoded = decode_pskel_for_test(&selected);
        assert_eq!(decoded, bones);
    }
}
