use crate::{StaticPipelineError, res_dir, static_dir};
use perro_io::walkdir::collect_file_paths;
use rayon::prelude::*;
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::Path;

const GRID_VERTS_PER_SIDE: usize = 65;
const HEIGHT_COUNT: usize = GRID_VERTS_PER_SIDE * GRID_VERTS_PER_SIDE;

#[derive(Clone)]
struct ParsedChunk {
    x: i32,
    z: i32,
    heights: Vec<f32>,
}

struct WorkingChunk {
    x: i32,
    z: i32,
    heights: Vec<f32>,
    assigned: Vec<bool>,
    assigned_count: usize,
}

impl WorkingChunk {
    fn new(x: i32, z: i32) -> Self {
        Self {
            x,
            z,
            heights: vec![0.0; HEIGHT_COUNT],
            assigned: vec![false; HEIGHT_COUNT],
            assigned_count: 0,
        }
    }

    fn set(&mut self, gx: usize, gz: usize, y: f32) {
        let idx = gz * GRID_VERTS_PER_SIDE + gx;
        if !self.assigned[idx] {
            self.assigned[idx] = true;
            self.assigned_count += 1;
        }
        self.heights[idx] = y;
    }

    fn finish(self) -> Option<ParsedChunk> {
        (self.assigned_count == HEIGHT_COUNT).then_some(ParsedChunk {
            x: self.x,
            z: self.z,
            heights: self.heights,
        })
    }
}

pub fn generate_static_terrains(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    fs::create_dir_all(&static_dir)?;

    let mut ptchunk_paths = Vec::<String>::new();
    if res_dir.exists() {
        ptchunk_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| ext.eq_ignore_ascii_case("ptchunk"))
            })
            .collect();
    }
    ptchunk_paths.sort();

    let parsed = ptchunk_paths
        .into_par_iter()
        .map(|rel| -> io::Result<(String, ParsedChunk)> {
            let full = res_dir.join(&rel);
            let src = fs::read_to_string(&full)?;
            let hint = coord_from_ptchunk_stem(Path::new(&rel).file_stem().and_then(|s| s.to_str()));
            let chunk = parse_ptchunk_kv(&src, hint).ok_or_else(|| {
                io::Error::other(format!("failed to parse .ptchunk `res://{rel}`"))
            })?;
            let folder = terrain_source_for_chunk_path(&rel);
            Ok((folder, chunk))
        })
        .collect::<io::Result<Vec<_>>>()?;

    let mut by_folder = BTreeMap::<String, Vec<ParsedChunk>>::new();
    for (folder, chunk) in parsed {
        by_folder.entry(folder).or_default().push(chunk);
    }
    for chunks in by_folder.values_mut() {
        chunks.sort_by_key(|c| (c.x, c.z));
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n\n");

    let mut folders: Vec<_> = by_folder.into_iter().collect();
    folders.sort_by(|a, b| a.0.cmp(&b.0));

    for (i, (_folder, chunks)) in folders.iter().enumerate() {
        let const_name = format!("TERRAIN_{}", i);
        let literal = build_terrain_literal(chunks);
        let _ = writeln!(
            out,
            "static {const_name}: &str = \"{}\";",
            escape_str(&literal)
        );
    }

    out.push('\n');
    out.push_str("pub fn lookup_terrain(path: &str) -> Option<&'static str> {\n");
    out.push_str("    match path {\n");
    for (i, (folder, _)) in folders.iter().enumerate() {
        let _ = writeln!(
            out,
            "        \"{}\" => Some(TERRAIN_{}),",
            escape_str(folder),
            i
        );
        let slash = if folder.ends_with('/') {
            folder.clone()
        } else {
            format!("{folder}/")
        };
        let _ = writeln!(
            out,
            "        \"{}\" => Some(TERRAIN_{}),",
            escape_str(&slash),
            i
        );
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("terrains.rs"), out)?;
    Ok(())
}

fn terrain_source_for_chunk_path(rel_chunk_path: &str) -> String {
    let rel = rel_chunk_path.replace('\\', "/");
    let folder = Path::new(&rel)
        .parent()
        .map(path_to_slash_string)
        .unwrap_or_default();
    if folder.is_empty() {
        "res://".to_string()
    } else {
        format!("res://{folder}")
    }
}

fn path_to_slash_string(path: &Path) -> String {
    path.components()
        .map(|c| c.as_os_str().to_string_lossy().to_string())
        .collect::<Vec<_>>()
        .join("/")
}

fn build_terrain_literal(chunks: &[ParsedChunk]) -> String {
    let mut out = String::new();
    for chunk in chunks {
        let _ = writeln!(out, "chunk = [{}, {}]", chunk.x, chunk.z);
        for z in 0..GRID_VERTS_PER_SIDE {
            for x in 0..GRID_VERTS_PER_SIDE {
                let idx = z * GRID_VERTS_PER_SIDE + x;
                let _ = writeln!(out, "[{x},{z}] = {:.6}", chunk.heights[idx]);
            }
        }
        out.push('\n');
    }
    out
}

fn parse_ptchunk_kv(source: &str, default_coord: Option<(i32, i32)>) -> Option<ParsedChunk> {
    let mut current = default_coord;
    let mut working = if let Some((x, z)) = current {
        Some(WorkingChunk::new(x, z))
    } else {
        None
    };

    for raw in source.lines() {
        let line = strip_line_comment(raw).trim();
        if line.is_empty() {
            continue;
        }

        if let Some((x, z)) = parse_coord_declaration(line) {
            current = Some((x, z));
            if working.is_none() {
                working = Some(WorkingChunk::new(x, z));
            } else {
                // `.ptchunk` should represent exactly one chunk.
                let w = working.as_ref()?;
                if w.x != x || w.z != z {
                    return None;
                }
            }
            continue;
        }

        let (gx, gz, y) = parse_sample_line(line)?;
        let (cx, cz) = current?;
        let chunk = working.get_or_insert_with(|| WorkingChunk::new(cx, cz));
        chunk.set(gx, gz, y);
    }

    working?.finish()
}

fn parse_coord_declaration(line: &str) -> Option<(i32, i32)> {
    let trimmed = line.trim();
    let lower = trimmed.to_ascii_lowercase();
    if !lower.starts_with("coord") && !lower.starts_with("chunk") {
        return None;
    }
    let bracket_start = trimmed.find('[')?;
    let bracket_end = trimmed[bracket_start..].find(']')? + bracket_start;
    parse_pair_i32(&trimmed[(bracket_start + 1)..bracket_end])
}

fn parse_sample_line(line: &str) -> Option<(usize, usize, f32)> {
    let trimmed = line.trim();
    if !trimmed.starts_with('[') {
        return None;
    }
    let close = trimmed.find(']')?;
    let (x_i32, z_i32) = parse_pair_i32(&trimmed[1..close])?;
    let gx = usize::try_from(x_i32).ok()?;
    let gz = usize::try_from(z_i32).ok()?;
    if gx >= GRID_VERTS_PER_SIDE || gz >= GRID_VERTS_PER_SIDE {
        return None;
    }

    let mut rest = trimmed[(close + 1)..].trim();
    if let Some(after_eq) = rest.strip_prefix('=') {
        rest = after_eq.trim();
    }
    if rest.is_empty() {
        return None;
    }
    let y = rest.parse::<f32>().ok()?;
    Some((gx, gz, y))
}

fn parse_pair_i32(text: &str) -> Option<(i32, i32)> {
    let mut parts = text.split(',').map(str::trim);
    let x = parts.next()?.parse::<i32>().ok()?;
    let z = parts.next()?.parse::<i32>().ok()?;
    if parts.next().is_some() {
        return None;
    }
    Some((x, z))
}

fn strip_line_comment(line: &str) -> &str {
    let no_hash = line.split('#').next().unwrap_or(line);
    no_hash.split("//").next().unwrap_or(no_hash)
}

fn coord_from_ptchunk_stem(stem: Option<&str>) -> Option<(i32, i32)> {
    let stem = stem?;
    let nums = extract_i32_tokens(stem);
    if nums.len() < 2 {
        return None;
    }
    Some((nums[0], nums[1]))
}

fn extract_i32_tokens(text: &str) -> Vec<i32> {
    let mut out = Vec::new();
    let mut cur = String::new();
    for ch in text.chars() {
        if ch.is_ascii_digit() || (ch == '-' && cur.is_empty()) {
            cur.push(ch);
        } else if !cur.is_empty() {
            if let Ok(v) = cur.parse::<i32>() {
                out.push(v);
            }
            cur.clear();
        }
    }
    if !cur.is_empty() {
        if let Ok(v) = cur.parse::<i32>() {
            out.push(v);
        }
    }
    out
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\r', "")
        .replace('\n', "\\n")
}
