use crate::{StaticPipelineError, embedded_dir, res_dir, static_dir};
use perro_io::{compress_zlib_best, walkdir::collect_file_paths};
use rayon::prelude::*;
use std::{
    fmt::Write as _,
    fs, io,
    path::{Path, PathBuf},
};

const IMAGE_EXTENSIONS: &[&str] = &[
    "png", "jpg", "jpeg", "bmp", "gif", "ico", "tga", "webp", "rgba",
];

pub fn generate_static_textures(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    let embedded_textures_dir = embedded_dir(project_root).join("textures");
    fs::create_dir_all(&static_dir)?;
    fs::create_dir_all(&embedded_textures_dir)?;

    let mut texture_paths = Vec::<String>::new();
    if res_dir.exists() {
        texture_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .map(|ext| ext.to_ascii_lowercase())
                    .is_some_and(|ext| IMAGE_EXTENSIONS.contains(&ext.as_str()))
            })
            .collect();
    }
    texture_paths.sort();

    let mut encoded = texture_paths
        .into_par_iter()
        .map(|rel| -> io::Result<(String, String, Vec<u8>)> {
            let res_path = format!("res://{rel}");
            let full_path = res_dir.join(&rel);
            let file_bytes = fs::read(&full_path)?;
            let image = image::load_from_memory(&file_bytes).map_err(|err| {
                io::Error::other(format!("failed to decode image `{res_path}`: {err}"))
            })?;
            let rgba = image.to_rgba8();
            let (width, height) = rgba.dimensions();
            let raw = rgba.into_raw();
            let compressed = compress_zlib_best(&raw)?;

            let mut ptex = Vec::with_capacity(20 + compressed.len());
            ptex.extend_from_slice(b"PTEX");
            ptex.extend_from_slice(&1u32.to_le_bytes());
            ptex.extend_from_slice(&width.to_le_bytes());
            ptex.extend_from_slice(&height.to_le_bytes());
            ptex.extend_from_slice(&(raw.len() as u32).to_le_bytes());
            ptex.extend_from_slice(&compressed);

            let mut rel_ptex = PathBuf::from(&rel);
            rel_ptex.set_extension("ptex");
            let rel_ptex = rel_ptex.to_string_lossy().replace('\\', "/");
            Ok((res_path, rel_ptex, ptex))
        })
        .collect::<io::Result<Vec<_>>>()?;
    encoded.sort_by(|a, b| a.0.cmp(&b.0));

    let mut textures = Vec::<(String, String)>::with_capacity(encoded.len());
    for (res_path, rel_ptex, ptex) in encoded {
        let output_path = embedded_textures_dir.join(&rel_ptex);
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&output_path, ptex)?;
        textures.push((res_path, rel_ptex));
    }

    textures.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n\n");
    for (index, (_res_path, rel_ptex)) in textures.iter().enumerate() {
        let include_path = format!("../../embedded/textures/{}", escape_str(rel_ptex));
        let _ = writeln!(
            out,
            "static TEXTURE_{index}: &[u8] = include_bytes!(\"{include_path}\");"
        );
    }
    if !textures.is_empty() {
        out.push('\n');
    }
    out.push_str("pub fn lookup_texture(path: &str) -> Option<&'static [u8]> {\n");
    out.push_str("    match path {\n");
    for (index, (res_path, _)) in textures.iter().enumerate() {
        let _ = writeln!(
            out,
            "        \"{}\" => Some(TEXTURE_{index}),",
            escape_str(res_path)
        );
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("textures.rs"), out)?;
    Ok(())
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}
