use crate::{StaticPipelineError, embedded_dir, ensure_unique_hashes, res_dir, static_dir};
use perro_io::{compress_zlib_best, walkdir::collect_file_paths};
use rayon::prelude::*;
use std::{
    fmt::Write as _,
    fs, io,
    path::{Path, PathBuf},
};

const IMAGE_EXTENSIONS: &[&str] = &[
    "png", "jpg", "jpeg", "bmp", "gif", "ico", "tga", "webp", "rgba",
];
const PTEX_VERSION: u32 = 2;
const PTEX_FLAG_FORMAT_MASK: u32 = 0b11;
const PTEX_FLAG_FORMAT_RGBA8: u32 = 0;
const PTEX_FLAG_FORMAT_RGB8: u32 = 1;
const PTEX_FLAG_FORMAT_R8: u32 = 2;

pub fn generate_static_textures(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    let embedded_textures_dir = embedded_dir(project_root).join("textures");
    fs::create_dir_all(&static_dir)?;
    fs::create_dir_all(&embedded_textures_dir)?;

    let mut texture_inputs = Vec::<(String, PathBuf)>::new();
    if res_dir.exists() {
        texture_inputs = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .map(|ext| ext.to_ascii_lowercase())
                    .is_some_and(|ext| IMAGE_EXTENSIONS.contains(&ext.as_str()))
            })
            .map(|rel| (format!("res://{rel}"), res_dir.join(rel)))
            .collect();
    }
    let mut encoded = texture_inputs
        .into_par_iter()
        .map(|(res_path, full_path)| -> io::Result<(String, Vec<u8>)> {
            let file_bytes = fs::read(&full_path)?;
            let image = image::load_from_memory(&file_bytes).map_err(|err| {
                io::Error::other(format!("failed to decode image `{res_path}`: {err}"))
            })?;
            let rgba = image.to_rgba8();
            let (width, height) = rgba.dimensions();
            let raw_rgba = rgba.into_raw();
            let (flags, packed_raw) = pack_texture_payload(&raw_rgba);
            let compressed = compress_zlib_best(&packed_raw)?;

            let mut ptex = Vec::with_capacity(24 + compressed.len());
            ptex.extend_from_slice(b"PTEX");
            ptex.extend_from_slice(&PTEX_VERSION.to_le_bytes());
            ptex.extend_from_slice(&width.to_le_bytes());
            ptex.extend_from_slice(&height.to_le_bytes());
            ptex.extend_from_slice(&(flags & PTEX_FLAG_FORMAT_MASK).to_le_bytes());
            ptex.extend_from_slice(&(packed_raw.len() as u32).to_le_bytes());
            ptex.extend_from_slice(&compressed);
            Ok((res_path, ptex))
        })
        .collect::<io::Result<Vec<_>>>()?;
    encoded.sort_by(|a, b| a.0.cmp(&b.0));
    encoded.dedup_by(|a, b| a.0 == b.0);

    let mut textures = Vec::<(String, String)>::with_capacity(encoded.len());
    for (index, (res_path, ptex)) in encoded.into_iter().enumerate() {
        let rel_ptex = format!("texture_{index}.ptex");
        let output_path = embedded_textures_dir.join(&rel_ptex);
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&output_path, ptex)?;
        textures.push((res_path, rel_ptex));
    }

    textures.sort_by(|a, b| a.0.cmp(&b.0));
    ensure_unique_hashes("texture", textures.iter().map(|(path, _)| path.as_str()))?;

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n\n");
    for (index, (_res_path, rel_ptex)) in textures.iter().enumerate() {
        let include_path = format!("../../embedded/textures/{}", escape_str(rel_ptex));
        let _ = writeln!(
            out,
            "static TEXTURE_{index}: &[u8] = include_bytes!(\"{include_path}\");"
        );
    }
    if !textures.is_empty() {
        out.push('\n');
    }
    out.push_str("pub fn lookup_texture(path_hash: u64) -> Option<&'static [u8]> {\n");
    out.push_str("    match path_hash {\n");
    for (index, (res_path, _)) in textures.iter().enumerate() {
        let path_hash = perro_ids::string_to_u64(res_path);
        let _ = writeln!(
            out,
            "        {path_hash}u64 => Some(TEXTURE_{index}),"
        );
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("textures.rs"), out)?;
    Ok(())
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

fn pack_texture_payload(raw_rgba: &[u8]) -> (u32, Vec<u8>) {
    let is_opaque = raw_rgba.chunks_exact(4).all(|px| px[3] == 255);
    let is_gray_opaque = is_opaque
        && raw_rgba
            .chunks_exact(4)
            .all(|px| px[0] == px[1] && px[1] == px[2]);

    if is_gray_opaque {
        let mut packed = Vec::with_capacity(raw_rgba.len() / 4);
        for px in raw_rgba.chunks_exact(4) {
            packed.push(px[0]);
        }
        (PTEX_FLAG_FORMAT_R8, packed)
    } else if is_opaque {
        let mut packed = Vec::with_capacity((raw_rgba.len() / 4) * 3);
        for px in raw_rgba.chunks_exact(4) {
            packed.extend_from_slice(&px[..3]);
        }
        (PTEX_FLAG_FORMAT_RGB8, packed)
    } else {
        (PTEX_FLAG_FORMAT_RGBA8, raw_rgba.to_vec())
    }
}
