use crate::{
    StaticPipelineError, asset_uri, embedded_dir, ensure_unique_hashes, prune_embedded_dir,
    res_dir, static_dir, write_hash_const, write_if_changed, write_static_lookup_fn,
};
use perro_asset_formats::ptset::{
    EXTENSION as PTSET_EXTENSION, SOURCE_EXTENSION as PTSET_SOURCE_EXTENSION,
};
use perro_io::walkdir::collect_file_paths;
use perro_render_bridge::{encode_tileset_2d_binary, parse_ptileset_source};
use rayon::prelude::*;
use std::{fmt::Write as _, fs, io, path::Path};

pub fn generate_static_tilesets(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    let embedded_tilesets_dir = embedded_dir(project_root).join("tilesets");
    fs::create_dir_all(&static_dir)?;
    fs::create_dir_all(&embedded_tilesets_dir)?;

    let mut paths = Vec::<String>::new();
    if res_dir.exists() {
        paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| ext.eq_ignore_ascii_case(PTSET_SOURCE_EXTENSION))
            })
            .collect();
    }
    paths.sort();

    let mut tilesets = paths
        .into_par_iter()
        .map(|rel| -> io::Result<(String, String, Vec<u8>)> {
            let res_path = asset_uri(&rel);
            let src = fs::read_to_string(res_dir.join(&rel))?;
            let tileset = parse_ptileset_source(&src).ok_or_else(|| {
                io::Error::other(format!(
                    "tileset `{res_path}` must be valid .{PTSET_SOURCE_EXTENSION}"
                ))
            })?;
            Ok((res_path, rel, encode_tileset_2d_binary(&tileset)))
        })
        .collect::<io::Result<Vec<_>>>()?;
    tilesets.sort_by(|a, b| a.0.cmp(&b.0));
    ensure_unique_hashes("tileset", tilesets.iter().map(|(path, _, _)| path.as_str()))?;

    let mut keep = std::collections::HashSet::new();
    for (_, rel, bytes) in &tilesets {
        let output_rel = encoded_tileset_rel_path(rel);
        let output_path = embedded_tilesets_dir.join(&output_rel);
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)?;
        }
        write_if_changed(&output_path, bytes)?;
        keep.insert(output_rel);
    }
    prune_embedded_dir(&embedded_tilesets_dir, &keep)?;

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n\n");
    out.push_str("static EMPTY_TILESET: &[u8] = b\"\";\n\n");
    for (index, (_, rel, _)) in tilesets.iter().enumerate() {
        let include_path = format!(
            "../../embedded/tilesets/{}",
            escape_str(&encoded_tileset_rel_path(rel))
        );
        let _ = writeln!(
            out,
            "static TILESET_{index}: &[u8] = include_bytes!(\"{include_path}\");"
        );
    }
    if !tilesets.is_empty() {
        out.push('\n');
    }
    for (index, (path, _, _)) in tilesets.iter().enumerate() {
        write_hash_const(&mut out, &format!("TILESET_HASH_{index}"), path);
    }
    if !tilesets.is_empty() {
        out.push('\n');
    }
    let lookup_entries = tilesets
        .iter()
        .enumerate()
        .map(|(index, (path, _, _))| {
            (
                perro_ids::string_to_u64(path),
                format!("TILESET_HASH_{index}"),
                format!("TILESET_{index}"),
            )
        })
        .collect::<Vec<_>>();
    write_static_lookup_fn(
        &mut out,
        "lookup_tileset",
        "TILESET_TABLE",
        "TilesetEntry",
        "&'static [u8]",
        "EMPTY_TILESET",
        &lookup_entries,
    );

    write_if_changed(&static_dir.join("tilesets.rs"), out.as_bytes())?;
    crate::record_static_assets(
        perro_asset_formats::dlc::DlcAssetKind::TILE_SET,
        perro_asset_formats::dlc::DlcAssetAccess::BYTES,
        tilesets.iter().map(|(path, _, _)| (path.as_str(), false)),
    );
    Ok(())
}

fn encoded_tileset_rel_path(rel: &str) -> String {
    format!("{rel}.{PTSET_EXTENSION}")
}

fn escape_str(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{StaticPipelineOverrides, set_static_pipeline_overrides};
    use std::{fs, time::SystemTime};

    #[test]
    fn static_tilesets_generates_lookup() {
        let stamp = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .expect("required value must be present")
            .as_nanos();
        let root = std::env::temp_dir().join(format!("perro_tilesets_{stamp}"));
        let res = root.join("res");
        let static_dir = root.join("static");
        fs::create_dir_all(res.join("tiles")).expect("required value must be present");
        fs::write(
            res.join("tiles/world.ptileset"),
            "texture = \"res://tiles/world.png\"\ntile_size = (16, 16)\ncolumns = 1\nrows = 1\n",
        )
        .expect("required value must be present");

        set_static_pipeline_overrides(Some(StaticPipelineOverrides {
            res_dir: res,
            static_dir: static_dir.clone(),
            embedded_dir: root.join("embedded"),
            asset_prefix: "res://".to_string(),
        }));
        generate_static_tilesets(&root).expect("required value must be present");
        set_static_pipeline_overrides(None);

        let out = fs::read_to_string(static_dir.join("tilesets.rs"))
            .expect("required value must be present");
        assert!(out.contains("lookup_tileset"));
        assert!(out.contains("include_bytes!"));
        assert!(out.contains("world.ptileset.ptset"));
        assert!(
            static_dir
                .parent()
                .expect("required value must be present")
                .join("embedded/tilesets/tiles/world.ptileset.ptset")
                .exists()
        );
        let bytes = fs::read(
            static_dir
                .parent()
                .expect("required value must be present")
                .join("embedded/tilesets/tiles/world.ptileset.ptset"),
        )
        .expect("required value must be present");
        assert_eq!(&bytes[0..5], b"PTSET");
        assert_eq!(
            u32::from_le_bytes(
                bytes[5..9]
                    .try_into()
                    .expect("required value must be present")
            ),
            1
        );
    }
}
