use crate::{StaticPipelineError, asset_uri, ensure_unique_hashes, res_dir, static_dir};
use perro_io::walkdir::collect_file_paths;
use rayon::prelude::*;
use std::{fmt::Write as _, fs, io, path::Path};

pub fn generate_static_tilesets(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    fs::create_dir_all(&static_dir)?;

    let mut paths = Vec::<String>::new();
    if res_dir.exists() {
        paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| ext.eq_ignore_ascii_case("ptileset"))
            })
            .collect();
    }
    paths.sort();

    let mut tilesets = paths
        .into_par_iter()
        .map(|rel| -> io::Result<(String, String)> {
            let res_path = asset_uri(&rel);
            let src = fs::read_to_string(res_dir.join(&rel))?;
            Ok((res_path, src))
        })
        .collect::<io::Result<Vec<_>>>()?;
    tilesets.sort_by(|a, b| a.0.cmp(&b.0));
    ensure_unique_hashes("tileset", tilesets.iter().map(|(path, _)| path.as_str()))?;

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n\n");
    for (index, (_, src)) in tilesets.iter().enumerate() {
        let _ = writeln!(out, "static TILESET_{index}: &str = r##\"{src}\"##;\n");
    }
    out.push_str("pub const fn lookup_tileset(path_hash: u64) -> &'static str {\n");
    out.push_str("    match path_hash {\n");
    for (index, (path, _)) in tilesets.iter().enumerate() {
        let path_hash = perro_ids::string_to_u64(path);
        let _ = writeln!(out, "        {path_hash}u64 => TILESET_{index},");
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("tilesets.rs"), out)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{StaticPipelineOverrides, set_static_pipeline_overrides};
    use std::{fs, time::SystemTime};

    #[test]
    fn static_tilesets_generates_lookup() {
        let stamp = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let root = std::env::temp_dir().join(format!("perro_tilesets_{stamp}"));
        let res = root.join("res");
        let static_dir = root.join("static");
        fs::create_dir_all(res.join("tiles")).unwrap();
        fs::write(
            res.join("tiles/world.ptileset"),
            "texture = \"res://tiles/world.png\"\ntile_size = (16, 16)\ncolumns = 1\nrows = 1\n",
        )
        .unwrap();

        set_static_pipeline_overrides(Some(StaticPipelineOverrides {
            res_dir: res,
            static_dir: static_dir.clone(),
            embedded_dir: root.join("embedded"),
            asset_prefix: "res://".to_string(),
        }));
        generate_static_tilesets(&root).unwrap();
        set_static_pipeline_overrides(None);

        let out = fs::read_to_string(static_dir.join("tilesets.rs")).unwrap();
        assert!(out.contains("lookup_tileset"));
        assert!(out.contains("world.png"));
    }
}
