use crate::{
    StaticPipelineError, asset_uri, ensure_unique_hashes, res_dir, static_dir, write_hash_const,
    write_static_lookup_fn,
};
use perro_asset_formats::source_ext;
use perro_io::walkdir::collect_file_paths;
use perro_scene::{Parser, SceneFieldIterRef, SceneObjectField, SceneValue};
use perro_structs::{Color, Vector2};
use perro_ui::{UiDepthEffect, UiStyle};
use rayon::prelude::*;
use std::{collections::HashMap, fmt::Write as _, fs, io, path::Path};

pub fn generate_static_ui_styles(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    fs::create_dir_all(&static_dir)?;

    let mut style_paths = Vec::<String>::new();
    if res_dir.exists() {
        style_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| ext.eq_ignore_ascii_case(source_ext::UI_STYLE))
            })
            .collect();
    }
    style_paths.sort();

    let mut styles = style_paths
        .into_par_iter()
        .map(|rel| -> io::Result<(String, UiStyle)> {
            let res_path = asset_uri(&rel);
            let src = fs::read_to_string(res_dir.join(&rel))?;
            let style = load_uistyle_literal(&src).ok_or_else(|| {
                io::Error::other(format!(
                    "ui style `{res_path}` must contain at least one valid style field"
                ))
            })?;
            Ok((res_path, style))
        })
        .collect::<io::Result<Vec<_>>>()?;
    styles.sort_by(|a, b| a.0.cmp(&b.0));
    ensure_unique_hashes("ui style", styles.iter().map(|(path, _)| path.as_str()))?;

    let mut unique_styles = Vec::<UiStyle>::new();
    let mut unique_by_key = HashMap::<UiStyleKey, usize>::new();
    let mut style_refs = Vec::<(String, usize)>::with_capacity(styles.len());
    for (path, style) in styles {
        let key = UiStyleKey::from(&style);
        let index = if let Some(existing) = unique_by_key.get(&key).copied() {
            existing
        } else {
            let idx = unique_styles.len();
            unique_styles.push(style);
            unique_by_key.insert(key, idx);
            idx
        };
        style_refs.push((path, index));
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n");
    out.push_str(
        "use perro_api::structs::{Color, Vector2};\nuse perro_api::ui::{UiCornerRadii, UiDepthEffect, UiFillKind, UiLinearGradient, UiStyle};\n\n",
    );
    for (index, style) in unique_styles.iter().enumerate() {
        let _ = writeln!(
            out,
            "static UI_STYLE_{index}: UiStyle = {};",
            ui_style_to_code(style)
        );
    }
    out.push_str("\nstatic EMPTY_UI_STYLE: UiStyle = UiStyle::panel();\n\n");
    for (index, (path, _)) in style_refs.iter().enumerate() {
        write_hash_const(&mut out, &format!("UI_STYLE_HASH_{index}"), path);
    }
    if !style_refs.is_empty() {
        out.push('\n');
    }
    let lookup_entries = style_refs
        .iter()
        .enumerate()
        .map(|(hash_index, (path, index))| {
            (
                perro_ids::string_to_u64(path),
                format!("UI_STYLE_HASH_{hash_index}"),
                format!("&UI_STYLE_{index}"),
            )
        })
        .collect::<Vec<_>>();
    write_static_lookup_fn(
        &mut out,
        "lookup_ui_style",
        "UI_STYLE_TABLE",
        "UiStyleEntry",
        "&'static UiStyle",
        "&EMPTY_UI_STYLE",
        &lookup_entries,
    );

    fs::write(static_dir.join("ui_styles.rs"), out)?;
    Ok(())
}

fn load_uistyle_literal(source: &str) -> Option<UiStyle> {
    let text = source.trim();
    let wrapped;
    let parse_text = if uistyle_looks_like_object(text) {
        text
    } else {
        wrapped = format!("{{\n{text}\n}}");
        wrapped.as_str()
    };
    let parsed = std::panic::catch_unwind(|| Parser::new(parse_text).parse_value_literal()).ok()?;
    let SceneValue::Object(entries) = parsed else {
        return None;
    };
    ui_style_from_entries(entries.as_ref())
}

fn uistyle_looks_like_object(text: &str) -> bool {
    text.lines()
        .map(strip_line_comment)
        .map(str::trim)
        .find(|line| !line.is_empty())
        .is_some_and(|line| line.starts_with('{'))
}

fn strip_line_comment(line: &str) -> &str {
    let bytes = line.as_bytes();
    let mut in_string = false;
    let mut escape = false;
    let mut i = 0usize;
    while i < bytes.len() {
        let b = bytes[i];
        if in_string {
            if escape {
                escape = false;
            } else if b == b'\\' {
                escape = true;
            } else if b == b'"' {
                in_string = false;
            }
            i += 1;
            continue;
        }
        if b == b'"' {
            in_string = true;
            i += 1;
            continue;
        }
        if b == b'#' || (b == b'/' && i + 1 < bytes.len() && bytes[i + 1] == b'/') {
            return &line[..i];
        }
        i += 1;
    }
    line
}

fn ui_style_from_entries(entries: &[SceneObjectField]) -> Option<UiStyle> {
    let mut style = UiStyle::panel();
    let mut any = false;
    SceneFieldIterRef::new(entries).for_each(|name, value| match name {
        "fill" | "color" => set_color(value, &mut any, |v| {
            style.fill = v;
            style.fill_kind = perro_ui::UiFillKind::Solid;
        }),
        "fill_kind" => set_fill_kind(value, &mut any, |v| style.fill_kind = v),
        "gradient" => set_gradient(value, &mut any, |v| {
            style.gradient = v;
            style.fill_kind = perro_ui::UiFillKind::Linear;
        }),
        "gradient_start" | "gradient_start_color" => set_color(value, &mut any, |v| {
            style.gradient.start_color = v;
            style.fill_kind = perro_ui::UiFillKind::Linear;
        }),
        "gradient_end" | "gradient_end_color" => set_color(value, &mut any, |v| {
            style.gradient.end_color = v;
            style.fill_kind = perro_ui::UiFillKind::Linear;
        }),
        "gradient_vector" | "gradient_direction" => set_vec2(value, &mut any, |v| {
            style.gradient.vector = v;
            style.fill_kind = perro_ui::UiFillKind::Linear;
        }),
        "stroke" => set_color(value, &mut any, |v| style.stroke = v),
        "stroke_width" => set_f32(value, &mut any, |v| style.stroke_width = v),
        "corner_radius" | "radius" => {
            set_corner_radius(value, &mut any, |v| style.set_corner_radius(v))
        }
        "corner_radii" => set_corner_radii(value, &mut any, |v| style.corner_radii = v),
        "radius_tl" | "corner_radius_tl" => {
            set_corner_radius(value, &mut any, |v| style.corner_radii.tl = v)
        }
        "radius_tr" | "corner_radius_tr" => {
            set_corner_radius(value, &mut any, |v| style.corner_radii.tr = v)
        }
        "radius_br" | "corner_radius_br" => {
            set_corner_radius(value, &mut any, |v| style.corner_radii.br = v)
        }
        "radius_bl" | "corner_radius_bl" => {
            set_corner_radius(value, &mut any, |v| style.corner_radii.bl = v)
        }
        "shadow" | "outer_shadow" => set_depth_effect(value, &mut any, |v| style.outer_shadow = v),
        "inner_shadow" => set_depth_effect(value, &mut any, |v| style.inner_shadow = v),
        "highlight" | "inner_highlight" => {
            set_depth_effect(value, &mut any, |v| style.inner_highlight = v)
        }
        "outer_highlight" => set_depth_effect(value, &mut any, |v| style.outer_highlight = v),
        "shadow_color" | "outer_shadow_color" => {
            set_color(value, &mut any, |v| style.outer_shadow.color = v)
        }
        "shadow_distance" | "outer_shadow_distance" => set_f32(value, &mut any, |v| {
            style.outer_shadow.distance = v.max(0.0)
        }),
        "shadow_falloff" | "outer_shadow_falloff" => {
            set_f32(value, &mut any, |v| style.outer_shadow.falloff = v.max(0.0))
        }
        "shadow_vector" | "outer_shadow_vector" => {
            set_vec2(value, &mut any, |v| style.outer_shadow.vector = v)
        }
        "shadow_size" | "outer_shadow_size" => {
            set_f32(value, &mut any, |v| style.outer_shadow.size = v.max(0.0))
        }
        "inner_shadow_color" => set_color(value, &mut any, |v| style.inner_shadow.color = v),
        "inner_shadow_distance" => set_f32(value, &mut any, |v| {
            style.inner_shadow.distance = v.max(0.0)
        }),
        "inner_shadow_falloff" => {
            set_f32(value, &mut any, |v| style.inner_shadow.falloff = v.max(0.0))
        }
        "inner_shadow_vector" => set_vec2(value, &mut any, |v| style.inner_shadow.vector = v),
        "inner_shadow_size" => set_f32(value, &mut any, |v| style.inner_shadow.size = v.max(0.0)),
        "highlight_color" | "inner_highlight_color" => {
            set_color(value, &mut any, |v| style.inner_highlight.color = v)
        }
        "highlight_distance" | "inner_highlight_distance" => set_f32(value, &mut any, |v| {
            style.inner_highlight.distance = v.max(0.0)
        }),
        "highlight_falloff" | "inner_highlight_falloff" => set_f32(value, &mut any, |v| {
            style.inner_highlight.falloff = v.max(0.0)
        }),
        "highlight_vector" | "inner_highlight_vector" => {
            set_vec2(value, &mut any, |v| style.inner_highlight.vector = v)
        }
        "highlight_size" | "inner_highlight_size" => {
            set_f32(value, &mut any, |v| style.inner_highlight.size = v.max(0.0))
        }
        "outer_highlight_color" => set_color(value, &mut any, |v| style.outer_highlight.color = v),
        "outer_highlight_distance" => set_f32(value, &mut any, |v| {
            style.outer_highlight.distance = v.max(0.0)
        }),
        "outer_highlight_falloff" => set_f32(value, &mut any, |v| {
            style.outer_highlight.falloff = v.max(0.0)
        }),
        "outer_highlight_vector" => set_vec2(value, &mut any, |v| style.outer_highlight.vector = v),
        "outer_highlight_size" => {
            set_f32(value, &mut any, |v| style.outer_highlight.size = v.max(0.0))
        }
        _ => {}
    });
    any.then_some(style)
}

fn set_f32(value: &SceneValue, any: &mut bool, set: impl FnOnce(f32)) {
    if let Some(v) = as_f32(value) {
        set(v);
        *any = true;
    }
}

fn set_color(value: &SceneValue, any: &mut bool, set: impl FnOnce(Color)) {
    if let Some(v) = as_color(value) {
        set(v);
        *any = true;
    }
}

fn set_vec2(value: &SceneValue, any: &mut bool, set: impl FnOnce(Vector2)) {
    if let Some(v) = as_vec2(value) {
        set(v);
        *any = true;
    }
}

fn set_corner_radius(value: &SceneValue, any: &mut bool, set: impl FnOnce(f32)) {
    if let Some(v) = as_corner_radius(value) {
        set(v);
        *any = true;
    }
}

fn set_depth_effect(value: &SceneValue, any: &mut bool, set: impl FnOnce(UiDepthEffect)) {
    if let Some(v) = as_depth_effect(value) {
        set(v);
        *any = true;
    }
}

fn set_fill_kind(value: &SceneValue, any: &mut bool, set: impl FnOnce(perro_ui::UiFillKind)) {
    if let Some(v) = as_fill_kind(value) {
        set(v);
        *any = true;
    }
}

fn set_gradient(value: &SceneValue, any: &mut bool, set: impl FnOnce(perro_ui::UiLinearGradient)) {
    if let Some(v) = as_gradient(value) {
        set(v);
        *any = true;
    }
}

fn set_corner_radii(value: &SceneValue, any: &mut bool, set: impl FnOnce(perro_ui::UiCornerRadii)) {
    if let Some(v) = as_corner_radii(value) {
        set(v);
        *any = true;
    }
}

fn as_corner_radius(value: &SceneValue) -> Option<f32> {
    if let Some(v) = as_f32(value) {
        return Some(v.clamp(0.0, 1.0));
    }
    match as_string(value)?
        .to_ascii_lowercase()
        .replace([' ', '-', '_'], "")
        .as_str()
    {
        "full" | "pill" | "round" | "rounded" => Some(1.0),
        _ => None,
    }
}

fn as_f32(value: &SceneValue) -> Option<f32> {
    match value {
        SceneValue::F32(v) => Some(*v),
        SceneValue::I32(v) => Some(*v as f32),
        _ => None,
    }
}

fn as_string(value: &SceneValue) -> Option<&str> {
    match value {
        SceneValue::Str(v) => Some(v.as_ref()),
        SceneValue::Key(v) => Some(v.as_ref()),
        _ => None,
    }
}

fn as_color(value: &SceneValue) -> Option<Color> {
    match value {
        SceneValue::Vec4 { x, y, z, w } => Some(Color::new(*x, *y, *z, *w)),
        SceneValue::Vec3 { x, y, z } => Some(Color::rgb(*x, *y, *z)),
        SceneValue::Str(v) => Color::from_hex(v.as_ref()),
        SceneValue::Key(v) => Color::from_hex(v.as_ref()),
        _ => None,
    }
}

fn as_vec2(value: &SceneValue) -> Option<Vector2> {
    match value {
        SceneValue::Vec2 { x, y } => Some(Vector2::new(*x, *y)),
        _ => None,
    }
}

fn as_depth_effect(value: &SceneValue) -> Option<UiDepthEffect> {
    let SceneValue::Object(fields) = value else {
        return None;
    };
    let mut effect = UiDepthEffect::none();
    SceneFieldIterRef::new(fields.as_ref()).for_each(|name, value| match name {
        "color" => {
            if let Some(v) = as_color(value) {
                effect.color = v;
            }
        }
        "distance" | "dist" => {
            if let Some(v) = as_f32(value) {
                effect.distance = v.max(0.0);
            }
        }
        "falloff" | "blur" => {
            if let Some(v) = as_f32(value) {
                effect.falloff = v.max(0.0);
            }
        }
        "vector" | "direction" | "dir" => {
            if let Some(v) = as_vec2(value) {
                effect.vector = v;
            }
        }
        "size" => {
            if let Some(v) = as_f32(value) {
                effect.size = v.max(0.0);
            }
        }
        _ => {}
    });
    Some(effect)
}

fn as_fill_kind(value: &SceneValue) -> Option<perro_ui::UiFillKind> {
    match as_string(value)?
        .to_ascii_lowercase()
        .replace([' ', '-', '_'], "")
        .as_str()
    {
        "solid" => Some(perro_ui::UiFillKind::Solid),
        "linear" | "gradient" | "lineargradient" => Some(perro_ui::UiFillKind::Linear),
        _ => None,
    }
}

fn as_gradient(value: &SceneValue) -> Option<perro_ui::UiLinearGradient> {
    let SceneValue::Object(fields) = value else {
        return None;
    };
    let mut gradient = perro_ui::UiLinearGradient::none();
    SceneFieldIterRef::new(fields.as_ref()).for_each(|name, value| match name {
        "start" | "start_color" | "from" => {
            if let Some(v) = as_color(value) {
                gradient.start_color = v;
            }
        }
        "end" | "end_color" | "to" => {
            if let Some(v) = as_color(value) {
                gradient.end_color = v;
            }
        }
        "vector" | "direction" | "dir" => {
            if let Some(v) = as_vec2(value) {
                gradient.vector = v;
            }
        }
        _ => {}
    });
    Some(gradient)
}

fn as_corner_radii(value: &SceneValue) -> Option<perro_ui::UiCornerRadii> {
    match value {
        SceneValue::Vec4 { x, y, z, w } => Some(perro_ui::UiCornerRadii::new(
            x.clamp(0.0, 1.0),
            y.clamp(0.0, 1.0),
            z.clamp(0.0, 1.0),
            w.clamp(0.0, 1.0),
        )),
        _ => as_corner_radius(value).map(perro_ui::UiCornerRadii::all),
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct UiStyleKey {
    fill: [u32; 4],
    fill_kind: u8,
    gradient: UiLinearGradientKey,
    stroke: [u32; 4],
    stroke_width: u32,
    corner_radii: [u32; 4],
    outer_shadow: UiDepthEffectKey,
    inner_shadow: UiDepthEffectKey,
    outer_highlight: UiDepthEffectKey,
    inner_highlight: UiDepthEffectKey,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct UiLinearGradientKey {
    start_color: [u32; 4],
    end_color: [u32; 4],
    vector: [u32; 2],
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct UiDepthEffectKey {
    color: [u32; 4],
    distance: u32,
    falloff: u32,
    vector: [u32; 2],
    size: u32,
}

impl From<&UiStyle> for UiStyleKey {
    fn from(value: &UiStyle) -> Self {
        Self {
            fill: color_key(value.fill),
            fill_kind: match value.fill_kind {
                perro_ui::UiFillKind::Solid => 0,
                perro_ui::UiFillKind::Linear => 1,
            },
            gradient: UiLinearGradientKey::from(&value.gradient),
            stroke: color_key(value.stroke),
            stroke_width: value.stroke_width.to_bits(),
            corner_radii: [
                value.corner_radii.tl.to_bits(),
                value.corner_radii.tr.to_bits(),
                value.corner_radii.br.to_bits(),
                value.corner_radii.bl.to_bits(),
            ],
            outer_shadow: UiDepthEffectKey::from(&value.outer_shadow),
            inner_shadow: UiDepthEffectKey::from(&value.inner_shadow),
            outer_highlight: UiDepthEffectKey::from(&value.outer_highlight),
            inner_highlight: UiDepthEffectKey::from(&value.inner_highlight),
        }
    }
}

impl From<&perro_ui::UiLinearGradient> for UiLinearGradientKey {
    fn from(value: &perro_ui::UiLinearGradient) -> Self {
        Self {
            start_color: color_key(value.start_color),
            end_color: color_key(value.end_color),
            vector: [value.vector.x.to_bits(), value.vector.y.to_bits()],
        }
    }
}

impl From<&UiDepthEffect> for UiDepthEffectKey {
    fn from(value: &UiDepthEffect) -> Self {
        Self {
            color: color_key(value.color),
            distance: value.distance.to_bits(),
            falloff: value.falloff.to_bits(),
            vector: [value.vector.x.to_bits(), value.vector.y.to_bits()],
            size: value.size.to_bits(),
        }
    }
}

fn color_key(value: Color) -> [u32; 4] {
    value.to_rgba_u8().map(u32::from)
}

fn ui_style_to_code(style: &UiStyle) -> String {
    format!(
        "UiStyle {{ fill: {}, fill_kind: {}, gradient: {}, stroke: {}, stroke_width: {:.6}, corner_radii: UiCornerRadii::new({:.6}, {:.6}, {:.6}, {:.6}), outer_shadow: {}, inner_shadow: {}, outer_highlight: {}, inner_highlight: {} }}",
        color_to_code(style.fill),
        fill_kind_to_code(style.fill_kind),
        gradient_to_code(style.gradient),
        color_to_code(style.stroke),
        style.stroke_width,
        style.corner_radii.tl,
        style.corner_radii.tr,
        style.corner_radii.br,
        style.corner_radii.bl,
        depth_effect_to_code(style.outer_shadow),
        depth_effect_to_code(style.inner_shadow),
        depth_effect_to_code(style.outer_highlight),
        depth_effect_to_code(style.inner_highlight),
    )
}

fn fill_kind_to_code(fill_kind: perro_ui::UiFillKind) -> &'static str {
    match fill_kind {
        perro_ui::UiFillKind::Solid => "UiFillKind::Solid",
        perro_ui::UiFillKind::Linear => "UiFillKind::Linear",
    }
}

fn gradient_to_code(gradient: perro_ui::UiLinearGradient) -> String {
    format!(
        "UiLinearGradient {{ start_color: {}, end_color: {}, vector: Vector2::new({:.6}, {:.6}) }}",
        color_to_code(gradient.start_color),
        color_to_code(gradient.end_color),
        gradient.vector.x,
        gradient.vector.y,
    )
}

fn depth_effect_to_code(effect: UiDepthEffect) -> String {
    format!(
        "UiDepthEffect {{ color: {}, distance: {:.6}, falloff: {:.6}, vector: Vector2::new({:.6}, {:.6}), size: {:.6} }}",
        color_to_code(effect.color),
        effect.distance,
        effect.falloff,
        effect.vector.x,
        effect.vector.y,
        effect.size,
    )
}

fn color_to_code(color: Color) -> String {
    let [r, g, b, a] = color.to_rgba();
    format!("Color::new({:.6}, {:.6}, {:.6}, {:.6})", r, g, b, a)
}

#[cfg(test)]
mod tests {
    use super::load_uistyle_literal;
    use perro_structs::Color;

    #[test]
    fn key_value_uistyle_parses_nested_effects() {
        let style = load_uistyle_literal(
            r##"
            fill = "#222222DD"
            stroke = "#555555FF"
            radius = 0.2
            shadow = { color = "#00000066" distance = 10 falloff = 12 vector = (1, -1) size = 2 }
            "##,
        )
        .expect("style");

        assert_eq!(style.fill, Color::from_hex("#222222DD").unwrap());
        assert_eq!(style.stroke, Color::from_hex("#555555FF").unwrap());
        assert_eq!(style.corner_radius(), 0.2);
        assert_eq!(
            style.outer_shadow.color,
            Color::from_hex("#00000066").unwrap()
        );
        assert_eq!(style.outer_shadow.distance, 10.0);
    }
}
