use crate::{StaticPipelineError, asset_uri, ensure_unique_hashes, res_dir, static_dir};
use perro_io::walkdir::collect_file_paths;
use perro_scene::{Parser, SceneFieldIterRef, SceneObjectField, SceneValue};
use perro_structs::{Color, Vector2};
use perro_ui::{UiDepthEffect, UiStyle};
use rayon::prelude::*;
use std::{collections::HashMap, fmt::Write as _, fs, io, path::Path};

pub fn generate_static_ui_styles(project_root: &Path) -> Result<(), StaticPipelineError> {
    let res_dir = res_dir(project_root);
    let static_dir = static_dir(project_root);
    fs::create_dir_all(&static_dir)?;

    let mut style_paths = Vec::<String>::new();
    if res_dir.exists() {
        style_paths = collect_file_paths(&res_dir, &res_dir)?
            .into_iter()
            .map(|rel| rel.replace('\\', "/"))
            .filter(|rel| {
                Path::new(rel)
                    .extension()
                    .and_then(|e| e.to_str())
                    .is_some_and(|ext| ext.eq_ignore_ascii_case("uistyle"))
            })
            .collect();
    }
    style_paths.sort();

    let mut styles = style_paths
        .into_par_iter()
        .map(|rel| -> io::Result<(String, UiStyle)> {
            let res_path = asset_uri(&rel);
            let src = fs::read_to_string(res_dir.join(&rel))?;
            let style = load_uistyle_literal(&src).ok_or_else(|| {
                io::Error::other(format!(
                    "ui style `{res_path}` must contain at least one valid style field"
                ))
            })?;
            Ok((res_path, style))
        })
        .collect::<io::Result<Vec<_>>>()?;
    styles.sort_by(|a, b| a.0.cmp(&b.0));
    ensure_unique_hashes("ui style", styles.iter().map(|(path, _)| path.as_str()))?;

    let mut unique_styles = Vec::<UiStyle>::new();
    let mut unique_by_key = HashMap::<UiStyleKey, usize>::new();
    let mut style_refs = Vec::<(String, usize)>::with_capacity(styles.len());
    for (path, style) in styles {
        let key = UiStyleKey::from(&style);
        let index = if let Some(existing) = unique_by_key.get(&key).copied() {
            existing
        } else {
            let idx = unique_styles.len();
            unique_styles.push(style);
            unique_by_key.insert(key, idx);
            idx
        };
        style_refs.push((path, index));
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by Perro Static Pipeline. Do not edit.\n");
    out.push_str("#![allow(unused_imports)]\n");
    out.push_str(
        "use perro_structs::{Color, Vector2};\nuse perro_ui::{UiDepthEffect, UiStyle};\n\n",
    );
    for (index, style) in unique_styles.iter().enumerate() {
        let _ = writeln!(
            out,
            "static UI_STYLE_{index}: UiStyle = {};",
            ui_style_to_code(style)
        );
    }
    out.push_str("\nstatic EMPTY_UI_STYLE: UiStyle = UiStyle::panel();\n\n");
    out.push_str("pub const fn lookup_ui_style(path_hash: u64) -> &'static UiStyle {\n");
    out.push_str("    match path_hash {\n");
    for (path, index) in &style_refs {
        let path_hash = perro_ids::string_to_u64(path);
        let _ = writeln!(out, "        {path_hash}u64 => &UI_STYLE_{index},");
    }
    out.push_str("        _ => &EMPTY_UI_STYLE,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(static_dir.join("ui_styles.rs"), out)?;
    Ok(())
}

fn load_uistyle_literal(source: &str) -> Option<UiStyle> {
    let text = source.trim();
    let wrapped;
    let parse_text = if uistyle_looks_like_object(text) {
        text
    } else {
        wrapped = format!("{{\n{text}\n}}");
        wrapped.as_str()
    };
    let parsed = std::panic::catch_unwind(|| Parser::new(parse_text).parse_value_literal()).ok()?;
    let SceneValue::Object(entries) = parsed else {
        return None;
    };
    ui_style_from_entries(entries.as_ref())
}

fn uistyle_looks_like_object(text: &str) -> bool {
    text.lines()
        .map(strip_line_comment)
        .map(str::trim)
        .find(|line| !line.is_empty())
        .is_some_and(|line| line.starts_with('{'))
}

fn strip_line_comment(line: &str) -> &str {
    let bytes = line.as_bytes();
    let mut in_string = false;
    let mut escape = false;
    let mut i = 0usize;
    while i < bytes.len() {
        let b = bytes[i];
        if in_string {
            if escape {
                escape = false;
            } else if b == b'\\' {
                escape = true;
            } else if b == b'"' {
                in_string = false;
            }
            i += 1;
            continue;
        }
        if b == b'"' {
            in_string = true;
            i += 1;
            continue;
        }
        if b == b'#' || (b == b'/' && i + 1 < bytes.len() && bytes[i + 1] == b'/') {
            return &line[..i];
        }
        i += 1;
    }
    line
}

fn ui_style_from_entries(entries: &[SceneObjectField]) -> Option<UiStyle> {
    let mut style = UiStyle::panel();
    let mut any = false;
    SceneFieldIterRef::new(entries).for_each(|name, value| match name {
        "fill" | "color" => set_color(value, &mut any, |v| style.fill = v),
        "stroke" => set_color(value, &mut any, |v| style.stroke = v),
        "stroke_width" => set_f32(value, &mut any, |v| style.stroke_width = v),
        "corner_radius" | "radius" => {
            set_corner_radius(value, &mut any, |v| style.corner_radius = v)
        }
        "shadow" => set_depth_effect(value, &mut any, |v| style.shadow = v),
        "highlight" | "inner_highlight" => {
            set_depth_effect(value, &mut any, |v| style.highlight = v)
        }
        "shadow_color" => set_color(value, &mut any, |v| style.shadow.color = v),
        "shadow_distance" => set_f32(value, &mut any, |v| style.shadow.distance = v.max(0.0)),
        "shadow_falloff" => set_f32(value, &mut any, |v| style.shadow.falloff = v.max(0.0)),
        "shadow_vector" => set_vec2(value, &mut any, |v| style.shadow.vector = v),
        "shadow_size" => set_f32(value, &mut any, |v| style.shadow.size = v.max(0.0)),
        "highlight_color" | "inner_highlight_color" => {
            set_color(value, &mut any, |v| style.highlight.color = v)
        }
        "highlight_distance" | "inner_highlight_distance" => {
            set_f32(value, &mut any, |v| style.highlight.distance = v.max(0.0))
        }
        "highlight_falloff" | "inner_highlight_falloff" => {
            set_f32(value, &mut any, |v| style.highlight.falloff = v.max(0.0))
        }
        "highlight_vector" | "inner_highlight_vector" => {
            set_vec2(value, &mut any, |v| style.highlight.vector = v)
        }
        "highlight_size" | "inner_highlight_size" => {
            set_f32(value, &mut any, |v| style.highlight.size = v.max(0.0))
        }
        _ => {}
    });
    any.then_some(style)
}

fn set_f32(value: &SceneValue, any: &mut bool, set: impl FnOnce(f32)) {
    if let Some(v) = as_f32(value) {
        set(v);
        *any = true;
    }
}

fn set_color(value: &SceneValue, any: &mut bool, set: impl FnOnce(Color)) {
    if let Some(v) = as_color(value) {
        set(v);
        *any = true;
    }
}

fn set_vec2(value: &SceneValue, any: &mut bool, set: impl FnOnce(Vector2)) {
    if let Some(v) = as_vec2(value) {
        set(v);
        *any = true;
    }
}

fn set_corner_radius(value: &SceneValue, any: &mut bool, set: impl FnOnce(f32)) {
    if let Some(v) = as_corner_radius(value) {
        set(v);
        *any = true;
    }
}

fn set_depth_effect(value: &SceneValue, any: &mut bool, set: impl FnOnce(UiDepthEffect)) {
    if let Some(v) = as_depth_effect(value) {
        set(v);
        *any = true;
    }
}

fn as_corner_radius(value: &SceneValue) -> Option<f32> {
    if let Some(v) = as_f32(value) {
        return Some(v.clamp(0.0, 1.0));
    }
    match as_string(value)?
        .to_ascii_lowercase()
        .replace([' ', '-', '_'], "")
        .as_str()
    {
        "full" | "pill" | "round" | "rounded" => Some(1.0),
        _ => None,
    }
}

fn as_f32(value: &SceneValue) -> Option<f32> {
    match value {
        SceneValue::F32(v) => Some(*v),
        SceneValue::I32(v) => Some(*v as f32),
        _ => None,
    }
}

fn as_string(value: &SceneValue) -> Option<&str> {
    match value {
        SceneValue::Str(v) => Some(v.as_ref()),
        SceneValue::Key(v) => Some(v.as_ref()),
        _ => None,
    }
}

fn as_color(value: &SceneValue) -> Option<Color> {
    match value {
        SceneValue::Vec4 { x, y, z, w } => Some(Color::new(*x, *y, *z, *w)),
        SceneValue::Vec3 { x, y, z } => Some(Color::rgb(*x, *y, *z)),
        SceneValue::Str(v) => Color::from_hex(v.as_ref()),
        SceneValue::Key(v) => Color::from_hex(v.as_ref()),
        _ => None,
    }
}

fn as_vec2(value: &SceneValue) -> Option<Vector2> {
    match value {
        SceneValue::Vec2 { x, y } => Some(Vector2::new(*x, *y)),
        _ => None,
    }
}

fn as_depth_effect(value: &SceneValue) -> Option<UiDepthEffect> {
    let SceneValue::Object(fields) = value else {
        return None;
    };
    let mut effect = UiDepthEffect::none();
    SceneFieldIterRef::new(fields.as_ref()).for_each(|name, value| match name {
        "color" => {
            if let Some(v) = as_color(value) {
                effect.color = v;
            }
        }
        "distance" | "dist" => {
            if let Some(v) = as_f32(value) {
                effect.distance = v.max(0.0);
            }
        }
        "falloff" | "blur" => {
            if let Some(v) = as_f32(value) {
                effect.falloff = v.max(0.0);
            }
        }
        "vector" | "direction" | "dir" => {
            if let Some(v) = as_vec2(value) {
                effect.vector = v;
            }
        }
        "size" => {
            if let Some(v) = as_f32(value) {
                effect.size = v.max(0.0);
            }
        }
        _ => {}
    });
    Some(effect)
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct UiStyleKey {
    fill: [u32; 4],
    stroke: [u32; 4],
    stroke_width: u32,
    corner_radius: u32,
    shadow: UiDepthEffectKey,
    highlight: UiDepthEffectKey,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct UiDepthEffectKey {
    color: [u32; 4],
    distance: u32,
    falloff: u32,
    vector: [u32; 2],
    size: u32,
}

impl From<&UiStyle> for UiStyleKey {
    fn from(value: &UiStyle) -> Self {
        Self {
            fill: color_key(value.fill),
            stroke: color_key(value.stroke),
            stroke_width: value.stroke_width.to_bits(),
            corner_radius: value.corner_radius.to_bits(),
            shadow: UiDepthEffectKey::from(&value.shadow),
            highlight: UiDepthEffectKey::from(&value.highlight),
        }
    }
}

impl From<&UiDepthEffect> for UiDepthEffectKey {
    fn from(value: &UiDepthEffect) -> Self {
        Self {
            color: color_key(value.color),
            distance: value.distance.to_bits(),
            falloff: value.falloff.to_bits(),
            vector: [value.vector.x.to_bits(), value.vector.y.to_bits()],
            size: value.size.to_bits(),
        }
    }
}

fn color_key(value: Color) -> [u32; 4] {
    [
        value.r.to_bits(),
        value.g.to_bits(),
        value.b.to_bits(),
        value.a.to_bits(),
    ]
}

fn ui_style_to_code(style: &UiStyle) -> String {
    format!(
        "UiStyle {{ fill: {}, stroke: {}, stroke_width: {:.6}, corner_radius: {:.6}, shadow: {}, highlight: {} }}",
        color_to_code(style.fill),
        color_to_code(style.stroke),
        style.stroke_width,
        style.corner_radius,
        depth_effect_to_code(style.shadow),
        depth_effect_to_code(style.highlight),
    )
}

fn depth_effect_to_code(effect: UiDepthEffect) -> String {
    format!(
        "UiDepthEffect {{ color: {}, distance: {:.6}, falloff: {:.6}, vector: Vector2::new({:.6}, {:.6}), size: {:.6} }}",
        color_to_code(effect.color),
        effect.distance,
        effect.falloff,
        effect.vector.x,
        effect.vector.y,
        effect.size,
    )
}

fn color_to_code(color: Color) -> String {
    format!(
        "Color::new({:.6}, {:.6}, {:.6}, {:.6})",
        color.r, color.g, color.b, color.a
    )
}

#[cfg(test)]
mod tests {
    use super::load_uistyle_literal;
    use perro_structs::Color;

    #[test]
    fn key_value_uistyle_parses_nested_effects() {
        let style = load_uistyle_literal(
            r##"
            fill = "#222222DD"
            stroke = "#555555FF"
            radius = 0.2
            shadow = { color = "#00000066" distance = 10 falloff = 12 vector = (1, -1) size = 2 }
            "##,
        )
        .expect("style");

        assert_eq!(style.fill, Color::from_hex("#222222DD").unwrap());
        assert_eq!(style.stroke, Color::from_hex("#555555FF").unwrap());
        assert_eq!(style.corner_radius, 0.2);
        assert_eq!(style.shadow.color, Color::from_hex("#00000066").unwrap());
        assert_eq!(style.shadow.distance, 10.0);
    }
}
