use std::{env, fs, path::PathBuf};

const SIZES: [usize; 5] = [32, 128, 512, 2048, 4096];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR unset"));
    let path = out_dir.join("static_lookup_scale_generated.rs");
    fs::write(path, generated_code()).expect("write generated lookup bench code");
}

fn generated_code() -> String {
    let mut code = String::from("// generated by perro_io/build.rs\n\n");

    for size in SIZES {
        let mut rows = (0..size)
            .map(|index| (bench_key(index as u64), index as u32))
            .collect::<Vec<_>>();
        rows.sort_unstable_by_key(|(key, _)| *key);

        code.push_str(&format!(
            "static STATIC_TABLE_{size}: [(u64, u32); {size}] = [\n"
        ));
        for (key, value) in &rows {
            code.push_str(&format!("    ({key:#018x}, {value}),\n"));
        }
        code.push_str("];\n\n");

        let probes = [
            bench_key(0),
            bench_key((size / 2) as u64),
            bench_key((size - 1) as u64),
            bench_key((size as u64).wrapping_add(17)),
        ];
        code.push_str(&format!("static PROBES_{size}: [u64; 4] = [\n"));
        for probe in probes {
            code.push_str(&format!("    {probe:#018x},\n"));
        }
        code.push_str("];\n\n");

        code.push_str(&format!(
            "#[inline(never)]\nfn match_lookup_{size}(key: u64) -> Option<u32> {{\n    match key {{\n"
        ));
        for index in 0..size {
            let key = bench_key(index as u64);
            code.push_str(&format!("        {key:#018x} => Some({index}),\n"));
        }
        code.push_str("        _ => None,\n    }\n}\n\n");
    }

    code
}

fn bench_key(index: u64) -> u64 {
    let mut value = index.wrapping_add(0x9e37_79b9_7f4a_7c15);
    value = (value ^ (value >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
    value = (value ^ (value >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
    value ^ (value >> 31)
}
