[package]
name = "perro_meshlets"
version.workspace = true
edition = "2024"

[lints]
workspace = true

[dependencies]
ahash = { version = "0.8.12", default-features = false, features = ["std"] }
glam = "0.31.0"
rayon = "1.10"

[dev-dependencies]
criterion = "0.5"
gltf.workspace = true

[[bench]]
name = "lod_builder"
harness = false
