#![allow(improper_ctypes_definitions)]
#![allow(unused)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]

use std::{
    any::Any,
    borrow::Cow,
    cell::RefCell,
    collections::HashMap,
    ops::{Deref, DerefMut},
    rc::Rc,
    str::FromStr,
};

use num_bigint::BigInt;
use phf::{phf_map, Map};
use rust_decimal::Decimal;
use rust_decimal::prelude::{FromPrimitive, ToPrimitive};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use smallvec::{smallvec, SmallVec};
use perro_core::{TextureID, NodeID, MaterialID, MeshID, LightID, UIElementID, SignalID};

use perro_core::nodes::ui::ui_registry::UIElementType;
use perro_core::nodes::ui::ui_elements::{ui_button, ui_text};

use perro_core::prelude::*;

//=======================================;
// Auto Generated by Perro Transpiler [Any further edits to this file will be overwritten on next transile];
//=======================================;

const __PERRO_SOURCE_FILE: &str = "test_scene_api.pup";

// ========================================================================
// PuptestsResourceTestsTestSceneApiPup - Main Script Structure
// ========================================================================

static MEMBER_TO_ATTRIBUTES_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
    "exposed_scene" => &["Expose"],
};

static ATTRIBUTE_TO_MEMBERS_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
    "Expose" => &["exposed_scene"],
};

pub struct PuptestsResourceTestsTestSceneApiPupScript {
    id: NodeID,
    __t_exposed_scene: SceneRef,
    __t_scene_name: String,
}

// ========================================================================
// PuptestsResourceTestsTestSceneApiPup - Creator Function (FFI Entry Point)
// ========================================================================

#[unsafe(no_mangle)]
pub extern "C" fn puptests_resource_tests_test_scene_api_pup_create_script() -> *mut dyn ScriptObject {
    let id = NodeID::nil(); // Will be set when attached to node
    let exposed_scene = SceneRef::default();
    let scene_name = String::from("res://scenes/example.scn");

    Box::into_raw(Box::new(PuptestsResourceTestsTestSceneApiPupScript {
        id,
        __t_exposed_scene: exposed_scene,
        __t_scene_name: scene_name,
    })) as *mut dyn ScriptObject
}

// ========================================================================
// PuptestsResourceTestsTestSceneApiPup - Script Init & Update Implementation
// ========================================================================

impl Script for PuptestsResourceTestsTestSceneApiPupScript {
}

// ========================================================================
// PuptestsResourceTestsTestSceneApiPup - Script-Defined Methods
// ========================================================================

impl PuptestsResourceTestsTestSceneApiPupScript {
    fn __t_test_scene_load(&mut self, api: &mut ScriptApi<'_>) {
        let mut __t_scene_ref: SceneRef = SceneRef::new("res://scenes/example.scn");
        let mut scene_root_id: Option<NodeID> = api.Scene.instantiate_ref(&__t_scene_ref);
        api.reparent(self.id, scene_root_id.expect("Child node not found"));
    }

    fn __t_test_scene_load_ref(&mut self, api: &mut ScriptApi<'_>) {
        let mut __t_scene_ref: SceneRef = SceneRef::new("res://scenes/example.scn");
        let mut scene_root_id: Option<NodeID> = api.Scene.instantiate_ref(&__t_scene_ref);
        api.reparent(self.id, scene_root_id.expect("Child node not found"));
    }

    fn __t_test_scene_load_string(&mut self, api: &mut ScriptApi<'_>) {
        let mut scene_root_id: Option<NodeID> = api.Scene.instantiate("res://scenes/example.scn");
        api.reparent(self.id, scene_root_id.expect("Child node not found"));
    }

    fn __t_test_scene_load_string_var(&mut self, api: &mut ScriptApi<'_>) {
        let mut __t__scene_name: String = String::from("res://scenes/example.scn");
        let mut scene_root_id: Option<NodeID> = api.Scene.instantiate(&__t__scene_name);
        api.reparent(self.id, scene_root_id.expect("Child node not found"));
        let mut scene_root2_id: Option<NodeID> = api.Scene.instantiate(&self.__t_scene_name);
        api.reparent(self.id, scene_root_id.expect("Child node not found"));
    }

}


impl ScriptObject for PuptestsResourceTestsTestSceneApiPupScript {
    fn set_id(&mut self, id: NodeID) {
        self.id = id;
    }

    fn get_id(&self) -> NodeID {
        self.id
    }

    fn get_var(&self, var_id: u64) -> Option<Value> {
        VAR_GET_TABLE.get(&var_id).and_then(|f| f(self))
    }

    fn set_var(&mut self, var_id: u64, val: Value) -> Option<()> {
        VAR_SET_TABLE.get(&var_id).and_then(|f| f(self, val))
    }

    fn apply_exposed(&mut self, hashmap: &HashMap<u64, Value>, api: &mut ScriptApi<'_>) {
        for (var_id, val) in hashmap.iter() {
            if let Some(f) = VAR_APPLY_TABLE.get(var_id) {
                f(self, val, api);
            }
        }
    }

    fn call_function(
        &mut self,
        id: u64,
        api: &mut ScriptApi<'_>,
        params: &[Value],
    ) -> Value {
        DISPATCH_TABLE.get(&id).map_or(Value::Null, |f| f(self, params, api))
    }

    // Attributes

    fn attributes_of(&self, member: &str) -> Vec<String> {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn members_with(&self, attribute: &str) -> Vec<String> {
        ATTRIBUTE_TO_MEMBERS_MAP
            .get(attribute)
            .map(|members| members.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn has_attribute(&self, member: &str, attribute: &str) -> bool {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().any(|a| *a == attribute))
            .unwrap_or(false)
    }
    
    fn script_flags(&self) -> ScriptFlags {
        ScriptFlags::new(0)
    }
}

// =========================== Static PHF Dispatch Tables ===========================

static VAR_GET_TABLE: phf::Map<u64, fn(&PuptestsResourceTestsTestSceneApiPupScript) -> Option<Value>> =
    phf::phf_map! {
        4189616247739968303u64 => |script: &PuptestsResourceTestsTestSceneApiPupScript| -> Option<Value> {
                        Some(json!(script.__t_exposed_scene))
                    },
        17808286245792156027u64 => |script: &PuptestsResourceTestsTestSceneApiPupScript| -> Option<Value> {
                        Some(json!(script.__t_scene_name))
                    },

    };

static VAR_SET_TABLE: phf::Map<u64, fn(&mut PuptestsResourceTestsTestSceneApiPupScript, Value) -> Option<()>> =
    phf::phf_map! {
        4189616247739968303u64 => |script: &mut PuptestsResourceTestsTestSceneApiPupScript, val: Value| -> Option<()> {
                            if let Ok(v) = serde_json::from_value::<SceneRef>(val) {
                                script.__t_exposed_scene = v;
                                return Some(());
                            }
                            None
                        },
        17808286245792156027u64 => |script: &mut PuptestsResourceTestsTestSceneApiPupScript, val: Value| -> Option<()> {
                            if let Some(v) = val.as_str() {
                                script.__t_scene_name = v.to_string();
                                return Some(());
                            }
                            None
                        },

    };

static VAR_APPLY_TABLE: phf::Map<u64, fn(&mut PuptestsResourceTestsTestSceneApiPupScript, &Value, &mut ScriptApi<'_>)> =
    phf::phf_map! {
        4189616247739968303u64 => |script: &mut PuptestsResourceTestsTestSceneApiPupScript, val: &Value, _api: &mut ScriptApi<'_>| {
                            if let Some(path) = val.as_str() {
                                script.__t_exposed_scene = SceneRef::new(path);
                                return;
                            }
                            if let Ok(v) = serde_json::from_value::<SceneRef>(val.clone()) {
                                script.__t_exposed_scene = v;
                            }
                        },

    };

static DISPATCH_TABLE: phf::Map<
    u64,
    fn(&mut PuptestsResourceTestsTestSceneApiPupScript, &[Value], &mut ScriptApi<'_>) -> Value,
> = phf::phf_map! {
        11722130464045076908u64 => | script: &mut PuptestsResourceTestsTestSceneApiPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_test_scene_load(api);
            Value::Null
        },
        16459745842159336334u64 => | script: &mut PuptestsResourceTestsTestSceneApiPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_test_scene_load_ref(api);
            Value::Null
        },
        14673779109959838144u64 => | script: &mut PuptestsResourceTestsTestSceneApiPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_test_scene_load_string(api);
            Value::Null
        },
        14849211265244976480u64 => | script: &mut PuptestsResourceTestsTestSceneApiPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_test_scene_load_string_var(api);
            Value::Null
        },

    };
