#![allow(improper_ctypes_definitions)]
#![allow(unused)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]

use std::{
    any::Any,
    borrow::Cow,
    cell::RefCell,
    collections::HashMap,
    ops::{Deref, DerefMut},
    rc::Rc,
    str::FromStr,
};

use num_bigint::BigInt;
use phf::{phf_map, Map};
use rust_decimal::Decimal;
use rust_decimal::prelude::{FromPrimitive, ToPrimitive};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use smallvec::{smallvec, SmallVec};
use perro_core::{TextureID, NodeID, MaterialID, MeshID, LightID, UIElementID, SignalID};

use perro_core::nodes::ui::ui_registry::UIElementType;
use perro_core::nodes::ui::ui_elements::{ui_button, ui_text};

use perro_core::prelude::*;

//=======================================;
// Auto Generated by Perro Transpiler [Any further edits to this file will be overwritten on next transile];
//=======================================;

const __PERRO_SOURCE_FILE: &str = "test_camera2d_api.pup";

// ========================================================================
// PuptestsNodeTestsTestCamera2dApiPup - Main Script Structure
// ========================================================================

static MEMBER_TO_ATTRIBUTES_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
};

static ATTRIBUTE_TO_MEMBERS_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
};

pub struct PuptestsNodeTestsTestCamera2dApiPupScript {
    id: NodeID,
}

// ========================================================================
// PuptestsNodeTestsTestCamera2dApiPup - Creator Function (FFI Entry Point)
// ========================================================================

#[unsafe(no_mangle)]
pub extern "C" fn puptests_node_tests_test_camera2d_api_pup_create_script() -> *mut dyn ScriptObject {
    let id = NodeID::nil(); // Will be set when attached to node

    Box::into_raw(Box::new(PuptestsNodeTestsTestCamera2dApiPupScript {
        id,
    })) as *mut dyn ScriptObject
}

// ========================================================================
// PuptestsNodeTestsTestCamera2dApiPup - Script Init & Update Implementation
// ========================================================================

impl Script for PuptestsNodeTestsTestCamera2dApiPupScript {
    fn init(&mut self, api: &mut ScriptApi<'_>) {
        let mut __t_z: f32 = (api.read_node(self.id, |self_node: &Camera2D| self_node.zoom));
        api.mutate_node(self.id, |self_node: &mut Camera2D| { self_node.zoom = 2f32; });
        let mut __t_act: bool = (api.read_node(self.id, |self_node: &Camera2D| self_node.active));
        api.mutate_node(self.id, |self_node: &mut Camera2D| {
            self_node.active = true;
            self_node.transform.position = Vector2::new(0.0f32, 0.0f32);
        });
        let mut __t_n: Cow<'static, str> = api.read_scene_node(self.id, |n| Cow::Owned(n.get_name().to_string()));
    }

}


impl ScriptObject for PuptestsNodeTestsTestCamera2dApiPupScript {
    fn set_id(&mut self, id: NodeID) {
        self.id = id;
    }

    fn get_id(&self) -> NodeID {
        self.id
    }

    fn get_var(&self, var_id: u64) -> Option<Value> {
        VAR_GET_TABLE.get(&var_id).and_then(|f| f(self))
    }

    fn set_var(&mut self, var_id: u64, val: Value) -> Option<()> {
        VAR_SET_TABLE.get(&var_id).and_then(|f| f(self, val))
    }

    fn apply_exposed(&mut self, hashmap: &HashMap<u64, Value>) {
        for (var_id, val) in hashmap.iter() {
            if let Some(f) = VAR_APPLY_TABLE.get(var_id) {
                f(self, val);
            }
        }
    }

    fn call_function(
        &mut self,
        id: u64,
        api: &mut ScriptApi<'_>,
        params: &[Value],
    ) -> Value {
        DISPATCH_TABLE.get(&id).map_or(Value::Null, |f| f(self, params, api))
    }

    // Attributes

    fn attributes_of(&self, member: &str) -> Vec<String> {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn members_with(&self, attribute: &str) -> Vec<String> {
        ATTRIBUTE_TO_MEMBERS_MAP
            .get(attribute)
            .map(|members| members.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn has_attribute(&self, member: &str, attribute: &str) -> bool {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().any(|a| *a == attribute))
            .unwrap_or(false)
    }
    
    fn script_flags(&self) -> ScriptFlags {
        ScriptFlags::new(1)
    }
}

// =========================== Static PHF Dispatch Tables ===========================

static VAR_GET_TABLE: phf::Map<u64, fn(&PuptestsNodeTestsTestCamera2dApiPupScript) -> Option<Value>> =
    phf::phf_map! {

    };

static VAR_SET_TABLE: phf::Map<u64, fn(&mut PuptestsNodeTestsTestCamera2dApiPupScript, Value) -> Option<()>> =
    phf::phf_map! {

    };

static VAR_APPLY_TABLE: phf::Map<u64, fn(&mut PuptestsNodeTestsTestCamera2dApiPupScript, &Value)> =
    phf::phf_map! {

    };

static DISPATCH_TABLE: phf::Map<
    u64,
    fn(&mut PuptestsNodeTestsTestCamera2dApiPupScript, &[Value], &mut ScriptApi<'_>) -> Value,
> = phf::phf_map! {

    };
