#![allow(improper_ctypes_definitions)]
#![allow(unused)]
#![allow(non_snake_case)]

use std::collections::HashMap;
use serde_json::{json, Value};
use perro_core::prelude::*;
use perro_core::scripting::api::ScriptApi;

//=======================================;
// Auto Generated by Perro Transpiler [Any further edits to this file will be overwritten on next transpile];
//=======================================;

const __PERRO_SOURCE_FILE: &str = "math_utils.pup";

pub mod MathUtils {
    use super::*;

    // ========================================================================
    // Module Constants
    // ========================================================================

    pub const __t_PI: f32 = 3.14159265f32;
    pub const __t_TWO: i32 = 2i32;

    // ========================================================================
    // Module Functions
    // ========================================================================

    pub fn __t_add(__t_a: i32, __t_b: i32, api: &mut ScriptApi<'_>) -> i32 {
        return (__t_a + __t_b);
        0i32
    }
    

    pub fn __t_scale(__t_x: f32, __t_s: f32, api: &mut ScriptApi<'_>) -> f32 {
        return ((__t_x as f32) * __t_s);
        0.0f32
    }
    

}
