#![allow(improper_ctypes_definitions)]
#![allow(unused)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]

use std::{
    any::Any,
    borrow::Cow,
    cell::RefCell,
    collections::HashMap,
    ops::{Deref, DerefMut},
    rc::Rc,
    str::FromStr,
};

use num_bigint::BigInt;
use phf::{phf_map, Map};
use rust_decimal::Decimal;
use rust_decimal::prelude::{FromPrimitive, ToPrimitive};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use smallvec::{smallvec, SmallVec};
use perro_core::{TextureID, NodeID, MaterialID, MeshID, LightID, UIElementID, SignalID};

use perro_core::prelude::*;

//=======================================;
// Auto Generated by Perro Transpiler [Any further edits to this file will be overwritten on next transile];
//=======================================;

const __PERRO_SOURCE_FILE: &str = "ui_helper.pup";

// ========================================================================
// PuptestsGlobalTestsUiHelperPup - Main Script Structure
// ========================================================================

static MEMBER_TO_ATTRIBUTES_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
};

static ATTRIBUTE_TO_MEMBERS_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
};

pub struct PuptestsGlobalTestsUiHelperPupScript {
    id: NodeID,
    __t_label_text: String,
}

// ========================================================================
// PuptestsGlobalTestsUiHelperPup - Creator Function (FFI Entry Point)
// ========================================================================

#[unsafe(no_mangle)]
pub extern "C" fn puptests_global_tests_ui_helper_pup_create_script() -> *mut dyn ScriptObject {
    let id = NodeID::nil(); // Will be set when attached to node
    let label_text = String::from("");

    Box::into_raw(Box::new(PuptestsGlobalTestsUiHelperPupScript {
        id,
        __t_label_text: label_text,
    })) as *mut dyn ScriptObject
}

// ========================================================================
// PuptestsGlobalTestsUiHelperPup - Script Init & Update Implementation
// ========================================================================

impl Script for PuptestsGlobalTestsUiHelperPupScript {
    fn init(&mut self, api: &mut ScriptApi<'_>) {
        self.__t_label_text = String::from("UI");
    }

}

// ========================================================================
// PuptestsGlobalTestsUiHelperPup - Script-Defined Methods
// ========================================================================

impl PuptestsGlobalTestsUiHelperPupScript {
    fn __t_get_label(&mut self, api: &mut ScriptApi<'_>) -> String {
return self.__t_label_text.clone();    String::new()
    }

    fn __t_set_label(&mut self, mut __t_t: String, api: &mut ScriptApi<'_>) {
        self.__t_label_text = __t_t.clone().clone();
    }

    fn __t_read_score(&mut self, api: &mut ScriptApi<'_>) -> i32 {
return (api.call_function_id(NodeID::from_u32(2), 7006042117341749029u64, &[]).as_i64().unwrap_or(0) as i32);    0i32
    }

    fn __t_add_to_score(&mut self, mut __t_delta: i32, api: &mut ScriptApi<'_>) {
        let mut __t_s: Value = api.call_function_id(NodeID::from_u32(2), 7006042117341749029u64, &[]);
        api.call_function_id(NodeID::from_u32(2), 13492554068693301597u64, &[json!((((__t_s.as_i64().unwrap_or(0) as i32) as i32) + __t_delta))]);
    }

    fn __t_ui_uses_more_utils(&mut self, api: &mut ScriptApi<'_>) -> i32 {
return crate::puptests_global_tests_more_utils_pup::MoreUtils::__t_double_sum(5i32, 3i32, api);    0i32
    }

}


impl ScriptObject for PuptestsGlobalTestsUiHelperPupScript {
    fn set_id(&mut self, id: NodeID) {
        self.id = id;
    }

    fn get_id(&self) -> NodeID {
        self.id
    }

    fn get_var(&self, var_id: u64) -> Option<Value> {
        VAR_GET_TABLE.get(&var_id).and_then(|f| f(self))
    }

    fn set_var(&mut self, var_id: u64, val: Value) -> Option<()> {
        VAR_SET_TABLE.get(&var_id).and_then(|f| f(self, val))
    }

    fn apply_exposed(&mut self, hashmap: &HashMap<u64, Value>) {
        for (var_id, val) in hashmap.iter() {
            if let Some(f) = VAR_APPLY_TABLE.get(var_id) {
                f(self, val);
            }
        }
    }

    fn call_function(
        &mut self,
        id: u64,
        api: &mut ScriptApi<'_>,
        params: &[Value],
    ) -> Value {
        DISPATCH_TABLE.get(&id).map_or(Value::Null, |f| f(self, params, api))
    }

    // Attributes

    fn attributes_of(&self, member: &str) -> Vec<String> {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn members_with(&self, attribute: &str) -> Vec<String> {
        ATTRIBUTE_TO_MEMBERS_MAP
            .get(attribute)
            .map(|members| members.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn has_attribute(&self, member: &str, attribute: &str) -> bool {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().any(|a| *a == attribute))
            .unwrap_or(false)
    }
    
    fn script_flags(&self) -> ScriptFlags {
        ScriptFlags::new(1)
    }
}

// =========================== Static PHF Dispatch Tables ===========================

static VAR_GET_TABLE: phf::Map<u64, fn(&PuptestsGlobalTestsUiHelperPupScript) -> Option<Value>> =
    phf::phf_map! {
        585902201258101960u64 => |script: &PuptestsGlobalTestsUiHelperPupScript| -> Option<Value> {
                        Some(json!(script.__t_label_text))
                    },

    };

static VAR_SET_TABLE: phf::Map<u64, fn(&mut PuptestsGlobalTestsUiHelperPupScript, Value) -> Option<()>> =
    phf::phf_map! {
        585902201258101960u64 => |script: &mut PuptestsGlobalTestsUiHelperPupScript, val: Value| -> Option<()> {
                            if let Some(v) = val.as_str() {
                                script.__t_label_text = v.to_string();
                                return Some(());
                            }
                            None
                        },

    };

static VAR_APPLY_TABLE: phf::Map<u64, fn(&mut PuptestsGlobalTestsUiHelperPupScript, &Value)> =
    phf::phf_map! {

    };

static DISPATCH_TABLE: phf::Map<
    u64,
    fn(&mut PuptestsGlobalTestsUiHelperPupScript, &[Value], &mut ScriptApi<'_>) -> Value,
> = phf::phf_map! {
        9684964462604268242u64 => | script: &mut PuptestsGlobalTestsUiHelperPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            json!(script.__t_get_label(api))
        },
        17072810594654405796u64 => | script: &mut PuptestsGlobalTestsUiHelperPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
let __t_t = params.get(0)
                            .and_then(|v| v.as_str())
                            .map(|s| s.to_string())
                            .unwrap_or_default();
            script.__t_set_label(__t_t, api);
            Value::Null
        },
        11535882182265529689u64 => | script: &mut PuptestsGlobalTestsUiHelperPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            json!(script.__t_read_score(api))
        },
        13809999789525982264u64 => | script: &mut PuptestsGlobalTestsUiHelperPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
let __t_delta = params.get(0)
                            .and_then(|v| v.as_i64().or_else(|| v.as_f64().map(|f| f as i64)))
                            .unwrap_or_default() as i32;
            script.__t_add_to_score(__t_delta, api);
            Value::Null
        },
        2507764067283617332u64 => | script: &mut PuptestsGlobalTestsUiHelperPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            json!(script.__t_ui_uses_more_utils(api))
        },

    };
