#![allow(improper_ctypes_definitions)]
#![allow(unused)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]

use std::{
    any::Any,
    borrow::Cow,
    cell::RefCell,
    collections::HashMap,
    ops::{Deref, DerefMut},
    rc::Rc,
    str::FromStr,
};

use num_bigint::BigInt;
use phf::{phf_map, Map};
use rust_decimal::Decimal;
use rust_decimal::prelude::{FromPrimitive, ToPrimitive};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use smallvec::{smallvec, SmallVec};
use perro_core::{TextureID, NodeID, MaterialID, MeshID, LightID, UIElementID, SignalID};

use perro_core::nodes::ui::ui_registry::UIElementType;
use perro_core::nodes::ui::ui_elements::{ui_button, ui_text};

use perro_core::prelude::*;

//=======================================;
// Auto Generated by Perro Transpiler [Any further edits to this file will be overwritten on next transile];
//=======================================;

const __PERRO_SOURCE_FILE: &str = "test_globals_modules.pup";

// ========================================================================
// PuptestsGlobalTestsTestGlobalsModulesPup - Main Script Structure
// ========================================================================

static MEMBER_TO_ATTRIBUTES_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
};

static ATTRIBUTE_TO_MEMBERS_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
};

pub struct PuptestsGlobalTestsTestGlobalsModulesPupScript {
    id: NodeID,
}

// ========================================================================
// PuptestsGlobalTestsTestGlobalsModulesPup - Creator Function (FFI Entry Point)
// ========================================================================

#[unsafe(no_mangle)]
pub extern "C" fn puptests_global_tests_test_globals_modules_pup_create_script() -> *mut dyn ScriptObject {
    let id = NodeID::nil(); // Will be set when attached to node

    Box::into_raw(Box::new(PuptestsGlobalTestsTestGlobalsModulesPupScript {
        id,
    })) as *mut dyn ScriptObject
}

// ========================================================================
// PuptestsGlobalTestsTestGlobalsModulesPup - Script Init & Update Implementation
// ========================================================================

impl Script for PuptestsGlobalTestsTestGlobalsModulesPupScript {
    fn init(&mut self, api: &mut ScriptApi<'_>) {
        let mut __t_rv: Value = api.call_function_id(NodeID::from_u32(1), 11967537757100617670u64, &[]);
        let mut __t_rc: Value = api.get_script_var_id(NodeID::from_u32(1), 18206167897987445329u64);
        let mut __t_rmod: Value = api.call_function_id(NodeID::from_u32(1), 15353357115589987819u64, &[]);
        let mut __t_gs: Value = api.call_function_id(NodeID::from_u32(2), 7006042117341749029u64, &[]);
        let mut __t_gmath: Value = api.call_function_id(NodeID::from_u32(2), 18028419204930178484u64, &[]);
        let mut __t_groot: Value = api.call_function_id(NodeID::from_u32(2), 5138814962466354492u64, &[]);
        let mut __t_lbl: Value = api.call_function_id(NodeID::from_u32(3), 9684964462604268242u64, &[]);
        let mut __t_uscore: Value = api.call_function_id(NodeID::from_u32(3), 11535882182265529689u64, &[]);
        api.call_function_id(NodeID::from_u32(3), 13809999789525982264u64, &[json!(json!(10f32))]);
        let mut __t_umore: Value = api.call_function_id(NodeID::from_u32(3), 2507764067283617332u64, &[]);
        let mut __t_pi: f32 = crate::puptests_module_tests_math_utils_pup::MathUtils::__t_PI;
        let mut __t_two: i32 = crate::puptests_module_tests_math_utils_pup::MathUtils::__t_TWO;
        let mut __t_sum: i32 = crate::puptests_module_tests_math_utils_pup::MathUtils::__t_add(1i32, 2i32, api);
        let mut __t_scaled: f32 = crate::puptests_module_tests_math_utils_pup::MathUtils::__t_scale(2.0f32, 3.0f32, api);
        let mut __t_dsum: i32 = crate::puptests_module_tests_more_utils_pup::MoreUtils::__t_double_sum(4i32, 5i32, api);
        let mut __t_spi: f32 = crate::puptests_module_tests_more_utils_pup::MoreUtils::__t_scaled_pi(2.0f32, api);
        let mut __t_cpi: f32 = crate::puptests_module_tests_simple_module_pup::SimpleModule::__t_PI;
        let mut __t_ctwo: i32 = crate::puptests_module_tests_simple_module_pup::SimpleModule::__t_TWO;
        let mut __t_doubled: i32 = crate::puptests_module_tests_simple_module_pup::SimpleModule::__t_double(7i32, api);
        let mut __t_csum: i32 = crate::puptests_module_tests_simple_module_pup::SimpleModule::__t_add(10i32, 20i32, api);
    }

}

// ========================================================================
// PuptestsGlobalTestsTestGlobalsModulesPup - Script-Defined Methods
// ========================================================================

impl PuptestsGlobalTestsTestGlobalsModulesPupScript {
    fn __t_test_root_and_module(&mut self, api: &mut ScriptApi<'_>) -> bool {
        let mut __t_v: Value = api.call_function_id(NodeID::from_u32(1), 11967537757100617670u64, &[]);
        let mut __t_m: Value = api.call_function_id(NodeID::from_u32(1), 15353357115589987819u64, &[]);
return ((((__t_v.as_i64().unwrap_or(0) as i32) as f32) == 100f32) && (((__t_m.as_f64().unwrap_or(0.0) as f32) as f32) > 3.0f32));    false
    }

    fn __t_test_global_calls_global(&mut self, api: &mut ScriptApi<'_>) -> bool {
        let mut __t_from_root: Value = api.call_function_id(NodeID::from_u32(2), 5138814962466354492u64, &[]);
        api.call_function_id(NodeID::from_u32(2), 13492554068693301597u64, &[json!(json!(42f32))]);
        let mut __t_score: Value = api.call_function_id(NodeID::from_u32(3), 11535882182265529689u64, &[]);
return ((((__t_from_root.as_i64().unwrap_or(0) as i32) as f32) == 100f32) && (((__t_score.as_i64().unwrap_or(0) as i32) as f32) == 42f32));    false
    }

    fn __t_test_global_calls_module(&mut self, api: &mut ScriptApi<'_>) -> bool {
        let mut __t_g: Value = api.call_function_id(NodeID::from_u32(2), 18028419204930178484u64, &[]);
        let mut __t_u: Value = api.call_function_id(NodeID::from_u32(3), 2507764067283617332u64, &[]);
return ((((__t_g.as_i64().unwrap_or(0) as i32) as f32) == 30f32) && (((__t_u.as_i64().unwrap_or(0) as i32) as f32) == 16f32));    false
    }

    fn __t_test_module_calls_module(&mut self, api: &mut ScriptApi<'_>) -> bool {
        let mut __t_d: i32 = crate::puptests_module_tests_more_utils_pup::MoreUtils::__t_double_sum(1i32, 2i32, api);
        let mut __t_s: f32 = crate::puptests_module_tests_more_utils_pup::MoreUtils::__t_scaled_pi(1.0f32, api);
return (((__t_d as f32) == 6f32) && ((__t_s as f32) > 3.0f32));    false
    }

    fn __t_test_simple_module(&mut self, api: &mut ScriptApi<'_>) -> bool {
        let mut __t_pi: f32 = crate::puptests_module_tests_simple_module_pup::SimpleModule::__t_PI;
        let mut __t_two: i32 = crate::puptests_module_tests_simple_module_pup::SimpleModule::__t_TWO;
        let mut __t_d: i32 = crate::puptests_module_tests_simple_module_pup::SimpleModule::__t_double(4i32, api);
        let mut __t_sum: i32 = crate::puptests_module_tests_simple_module_pup::SimpleModule::__t_add(1i32, 2i32, api);
return (((((__t_pi as f32) > 3.0f32) && ((__t_two as f32) == 2f32)) && ((__t_d as f32) == 8f32)) && ((__t_sum as f32) == 3f32));    false
    }

}


impl ScriptObject for PuptestsGlobalTestsTestGlobalsModulesPupScript {
    fn set_id(&mut self, id: NodeID) {
        self.id = id;
    }

    fn get_id(&self) -> NodeID {
        self.id
    }

    fn get_var(&self, var_id: u64) -> Option<Value> {
        VAR_GET_TABLE.get(&var_id).and_then(|f| f(self))
    }

    fn set_var(&mut self, var_id: u64, val: Value) -> Option<()> {
        VAR_SET_TABLE.get(&var_id).and_then(|f| f(self, val))
    }

    fn apply_exposed(&mut self, hashmap: &HashMap<u64, Value>, api: &mut ScriptApi<'_>) {
        for (var_id, val) in hashmap.iter() {
            if let Some(f) = VAR_APPLY_TABLE.get(var_id) {
                f(self, val, api);
            }
        }
    }

    fn call_function(
        &mut self,
        id: u64,
        api: &mut ScriptApi<'_>,
        params: &[Value],
    ) -> Value {
        DISPATCH_TABLE.get(&id).map_or(Value::Null, |f| f(self, params, api))
    }

    // Attributes

    fn attributes_of(&self, member: &str) -> Vec<String> {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn members_with(&self, attribute: &str) -> Vec<String> {
        ATTRIBUTE_TO_MEMBERS_MAP
            .get(attribute)
            .map(|members| members.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn has_attribute(&self, member: &str, attribute: &str) -> bool {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().any(|a| *a == attribute))
            .unwrap_or(false)
    }
    
    fn script_flags(&self) -> ScriptFlags {
        ScriptFlags::new(1)
    }
}

// =========================== Static PHF Dispatch Tables ===========================

static VAR_GET_TABLE: phf::Map<u64, fn(&PuptestsGlobalTestsTestGlobalsModulesPupScript) -> Option<Value>> =
    phf::phf_map! {

    };

static VAR_SET_TABLE: phf::Map<u64, fn(&mut PuptestsGlobalTestsTestGlobalsModulesPupScript, Value) -> Option<()>> =
    phf::phf_map! {

    };

static VAR_APPLY_TABLE: phf::Map<u64, fn(&mut PuptestsGlobalTestsTestGlobalsModulesPupScript, &Value, &mut ScriptApi<'_>)> =
    phf::phf_map! {

    };

static DISPATCH_TABLE: phf::Map<
    u64,
    fn(&mut PuptestsGlobalTestsTestGlobalsModulesPupScript, &[Value], &mut ScriptApi<'_>) -> Value,
> = phf::phf_map! {
        14445746277113328926u64 => | script: &mut PuptestsGlobalTestsTestGlobalsModulesPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            json!(script.__t_test_root_and_module(api))
        },
        17453799083196863174u64 => | script: &mut PuptestsGlobalTestsTestGlobalsModulesPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            json!(script.__t_test_global_calls_global(api))
        },
        4700341089340510413u64 => | script: &mut PuptestsGlobalTestsTestGlobalsModulesPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            json!(script.__t_test_global_calls_module(api))
        },
        10660104873886222307u64 => | script: &mut PuptestsGlobalTestsTestGlobalsModulesPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            json!(script.__t_test_module_calls_module(api))
        },
        17342970142095418825u64 => | script: &mut PuptestsGlobalTestsTestGlobalsModulesPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            json!(script.__t_test_simple_module(api))
        },

    };
