#![allow(improper_ctypes_definitions)]
#![allow(unused)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]

use std::{
    any::Any,
    borrow::Cow,
    cell::RefCell,
    collections::HashMap,
    ops::{Deref, DerefMut},
    rc::Rc,
    str::FromStr,
};

use num_bigint::BigInt;
use phf::{phf_map, Map};
use rust_decimal::Decimal;
use rust_decimal::prelude::{FromPrimitive, ToPrimitive};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use smallvec::{smallvec, SmallVec};
use perro_core::{TextureID, NodeID, MaterialID, MeshID, LightID, UIElementID, SignalID};

use perro_core::prelude::*;

//=======================================;
// Auto Generated by Perro Transpiler [Any further edits to this file will be overwritten on next transile];
//=======================================;

const __PERRO_SOURCE_FILE: &str = "test_node_methods.pup";

// ========================================================================
// PuptestsNodeTestsTestNodeMethodsPup - Main Script Structure
// ========================================================================

static MEMBER_TO_ATTRIBUTES_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
};

static ATTRIBUTE_TO_MEMBERS_MAP: Map<&'static str, &'static [&'static str]> = phf_map! {
};

pub struct PuptestsNodeTestsTestNodeMethodsPupScript {
    id: NodeID,
}

// ========================================================================
// PuptestsNodeTestsTestNodeMethodsPup - Creator Function (FFI Entry Point)
// ========================================================================

#[unsafe(no_mangle)]
pub extern "C" fn puptests_node_tests_test_node_methods_pup_create_script() -> *mut dyn ScriptObject {
    let id = NodeID::nil(); // Will be set when attached to node

    Box::into_raw(Box::new(PuptestsNodeTestsTestNodeMethodsPupScript {
        id,
    })) as *mut dyn ScriptObject
}

// ========================================================================
// PuptestsNodeTestsTestNodeMethodsPup - Script Init & Update Implementation
// ========================================================================

impl Script for PuptestsNodeTestsTestNodeMethodsPupScript {
    fn init(&mut self, api: &mut ScriptApi<'_>) {
        self.__t_test_dot_on_other_node(api);
        self.__t_test_shorthand_on_other_node(api);
    }

}

// ========================================================================
// PuptestsNodeTestsTestNodeMethodsPup - Script-Defined Methods
// ========================================================================

impl PuptestsNodeTestsTestNodeMethodsPupScript {
    fn __t_test_dot_on_other_node(&mut self, api: &mut ScriptApi<'_>) {
        let mut other_id: Option<NodeID> = api.get_child_by_name(self.id, String::from("Child").as_str());
        if other_id.is_some() {
            api.set_script_var_id(other_id.expect("Child node not found"), 7482430169653195547u64, json!(json!(json!(10f32))));
            let mut __t_v = api.get_script_var_id(other_id.expect("Child node not found"), 7482430169653195547u64);
            api.set_script_var_id(other_id.expect("Child node not found"), 5742476388973754500u64, json!(json!(json!(true))));
            let mut __t_f = api.get_script_var_id(other_id.expect("Child node not found"), 5742476388973754500u64);
            api.call_function_id(other_id.expect("Child node not found"), 2855574525570710443u64, &[]);
            api.call_function_id(other_id.expect("Child node not found"), 11554598059623192628u64, &[json!(json!(42f32))]);
            api.call_function_id_deferred(other_id.expect("Child node not found"), 2855574525570710443u64, &[]);
            api.call_function_id_deferred(other_id.expect("Child node not found"), 11554598059623192628u64, &[json!(json!(100f32))]);
        }
    }

    fn __t_test_shorthand_on_other_node(&mut self, api: &mut ScriptApi<'_>) {
        let mut other_id: Option<NodeID> = api.get_child_by_name(self.id, String::from("Child").as_str());
        if other_id.is_some() {
            let mut __t_val: Value = api.get_script_var_id(other_id.expect("Child node not found"), 1903775884355078583u64);
            api.set_script_var_id(other_id.expect("Child node not found"), 1903775884355078583u64, json!(json!(json!(1f32))));
            api.call_function_id(other_id.expect("Child node not found"), 14755300711808244577u64, &[json!(json!(2.0f32))]);
        }
    }

}


impl ScriptObject for PuptestsNodeTestsTestNodeMethodsPupScript {
    fn set_id(&mut self, id: NodeID) {
        self.id = id;
    }

    fn get_id(&self) -> NodeID {
        self.id
    }

    fn get_var(&self, var_id: u64) -> Option<Value> {
        VAR_GET_TABLE.get(&var_id).and_then(|f| f(self))
    }

    fn set_var(&mut self, var_id: u64, val: Value) -> Option<()> {
        VAR_SET_TABLE.get(&var_id).and_then(|f| f(self, val))
    }

    fn apply_exposed(&mut self, hashmap: &HashMap<u64, Value>) {
        for (var_id, val) in hashmap.iter() {
            if let Some(f) = VAR_APPLY_TABLE.get(var_id) {
                f(self, val);
            }
        }
    }

    fn call_function(
        &mut self,
        id: u64,
        api: &mut ScriptApi<'_>,
        params: &[Value],
    ) -> Value {
        DISPATCH_TABLE.get(&id).map_or(Value::Null, |f| f(self, params, api))
    }

    // Attributes

    fn attributes_of(&self, member: &str) -> Vec<String> {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn members_with(&self, attribute: &str) -> Vec<String> {
        ATTRIBUTE_TO_MEMBERS_MAP
            .get(attribute)
            .map(|members| members.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    }

    fn has_attribute(&self, member: &str, attribute: &str) -> bool {
        MEMBER_TO_ATTRIBUTES_MAP
            .get(member)
            .map(|attrs| attrs.iter().any(|a| *a == attribute))
            .unwrap_or(false)
    }
    
    fn script_flags(&self) -> ScriptFlags {
        ScriptFlags::new(1)
    }
}

// =========================== Static PHF Dispatch Tables ===========================

static VAR_GET_TABLE: phf::Map<u64, fn(&PuptestsNodeTestsTestNodeMethodsPupScript) -> Option<Value>> =
    phf::phf_map! {

    };

static VAR_SET_TABLE: phf::Map<u64, fn(&mut PuptestsNodeTestsTestNodeMethodsPupScript, Value) -> Option<()>> =
    phf::phf_map! {

    };

static VAR_APPLY_TABLE: phf::Map<u64, fn(&mut PuptestsNodeTestsTestNodeMethodsPupScript, &Value)> =
    phf::phf_map! {

    };

static DISPATCH_TABLE: phf::Map<
    u64,
    fn(&mut PuptestsNodeTestsTestNodeMethodsPupScript, &[Value], &mut ScriptApi<'_>) -> Value,
> = phf::phf_map! {
        10246547028073039092u64 => | script: &mut PuptestsNodeTestsTestNodeMethodsPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_test_dot_on_other_node(api);
            Value::Null
        },
        5028309915299484547u64 => | script: &mut PuptestsNodeTestsTestNodeMethodsPupScript, params: &[Value], api: &mut ScriptApi<'_>| -> Value {
            script.__t_test_shorthand_on_other_node(api);
            Value::Null
        },

    };
