use super::*;

pub(super) fn encode_effect_params(effect: &PostProcessEffect) -> EncodedEffectParams {
    match effect {
        PostProcessEffect::Blur { strength } => EncodedEffectParams {
            effect_type: EFFECT_BLUR,
            params0: [*strength, 0.0, 0.0, 0.0],
            params1: [0.0; 4],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::Pixelate { size } => EncodedEffectParams {
            effect_type: EFFECT_PIXELATE,
            params0: [*size, 0.0, 0.0, 0.0],
            params1: [0.0; 4],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::Warp { waves, strength } => EncodedEffectParams {
            effect_type: EFFECT_WARP,
            params0: [*waves, *strength, 0.0, 0.0],
            params1: [0.0; 4],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::Vignette {
            strength,
            radius,
            softness,
        } => EncodedEffectParams {
            effect_type: EFFECT_VIGNETTE,
            params0: [*strength, *radius, *softness, 0.0],
            params1: [0.0; 4],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::Crt {
            scanline_strength,
            curvature,
            chromatic,
            vignette,
        } => EncodedEffectParams {
            effect_type: EFFECT_CRT,
            params0: [*scanline_strength, *curvature, *chromatic, *vignette],
            params1: [0.0; 4],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::ColorFilter { color, strength } => EncodedEffectParams {
            effect_type: EFFECT_COLOR_FILTER,
            params0: [color[0], color[1], color[2], *strength],
            params1: [0.0; 4],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::ReverseFilter {
            color,
            strength,
            softness,
        } => EncodedEffectParams {
            effect_type: EFFECT_REVERSE_FILTER,
            params0: [color[0], color[1], color[2], *strength],
            params1: [*softness, 0.0, 0.0, 0.0],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::ChromaKey {
            color,
            tolerance,
            softness,
        } => EncodedEffectParams {
            effect_type: EFFECT_CHROMA_KEY,
            params0: [color.r(), color.g(), color.b(), *tolerance],
            params1: [*softness, 0.0, 0.0, 0.0],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::Bloom {
            strength,
            threshold,
            radius,
        } => EncodedEffectParams {
            effect_type: EFFECT_BLOOM,
            params0: [*strength, *threshold, *radius, 0.0],
            params1: [0.0; 4],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::Exposure { .. } => EncodedEffectParams {
            effect_type: EFFECT_CUSTOM,
            params0: [0.0; 4],
            params1: [0.0; 4],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::Saturate { amount } => EncodedEffectParams {
            effect_type: EFFECT_SATURATE,
            params0: [*amount, 0.0, 0.0, 0.0],
            params1: [0.0; 4],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::BlackWhite { amount } => EncodedEffectParams {
            effect_type: EFFECT_BLACK_WHITE,
            params0: [*amount, 0.0, 0.0, 0.0],
            params1: [0.0; 4],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::ColorGrade {
            exposure,
            contrast,
            brightness,
            saturation,
            gamma,
            temperature,
            tint,
            hue_shift,
            vibrance,
            lift,
            gain,
            offset,
        } => EncodedEffectParams {
            effect_type: EFFECT_COLOR_GRADE,
            params0: [*exposure, *contrast, *brightness, *saturation],
            params1: [*gamma, *temperature, *tint, *hue_shift],
            params2: [lift[0], lift[1], lift[2], *vibrance],
            params3: [gain[0], gain[1], gain[2], 0.0],
            params4: [offset[0], offset[1], offset[2], 0.0],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::Lut2D { size, strength, .. } => EncodedEffectParams {
            effect_type: EFFECT_LUT_2D,
            params0: [*strength, *size as f32, 0.0, 0.0],
            params1: [0.0; 4],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::Lut3D { size, strength, .. } => EncodedEffectParams {
            effect_type: EFFECT_LUT_3D,
            params0: [*strength, *size as f32, 0.0, 0.0],
            params1: [0.0; 4],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: Vec::new(),
        },
        PostProcessEffect::Custom { params, .. } => EncodedEffectParams {
            effect_type: EFFECT_CUSTOM,
            params0: [0.0; 4],
            params1: [0.0; 4],
            params2: [0.0; 4],
            params3: [0.0; 4],
            params4: [0.0; 4],
            params5: [0.0; 4],
            custom_params: params.iter().map(encode_custom_param_value).collect(),
        },
    }
}

pub(super) fn encode_custom_param_value(value: &CustomPostParam) -> [f32; 4] {
    match &value.value {
        CustomPostParamValue::F32(v) => [*v, 0.0, 0.0, 0.0],
        CustomPostParamValue::I32(v) => [*v as f32, 0.0, 0.0, 0.0],
        CustomPostParamValue::Bool(v) => [if *v { 1.0 } else { 0.0 }, 0.0, 0.0, 0.0],
        CustomPostParamValue::Vec2(v) => [v[0], v[1], 0.0, 0.0],
        CustomPostParamValue::Vec3(v) => [v[0], v[1], v[2], 0.0],
        CustomPostParamValue::Vec4(v) => *v,
    }
}
