fn write_scripts_lib(
    scripts_src: &Path,
    copied: &[String],
    registrable: &[String],
    script_path_prefix: &str,
) -> Result<bool, CompilerError> {
    let mut out = String::new();
    out.push_str("#![allow(unused_imports, unused_variables, dead_code)]\n");
    out.push_str("// AUTO-GENERATED by Perro Compiler. Do not edit by hand.\n\n");
    out.push_str("use perro_runtime::RuntimeScriptApi;\n");
    out.push_str("use perro_api::scripting::ScriptConstructor;\n\n");

    for rel in copied {
        let module = module_name_from_rel(rel);
        let generated_rel = generated_script_rel(rel);
        out.push_str(&format!("#[path = \"{generated_rel}\"]\n"));
        out.push_str(&format!("pub mod {module};\n\n"));
    }

    if !copied.is_empty() {
        let mut short_name_counts = BTreeMap::<String, usize>::new();
        for rel in copied {
            let short = module_short_name_from_rel(rel);
            *short_name_counts.entry(short).or_insert(0) += 1;
        }

        for rel in copied {
            let module = module_name_from_rel(rel);
            let short = module_short_name_from_rel(rel);
            if short == module {
                continue;
            }
            if short_name_counts.get(&short).copied() == Some(1) {
                out.push_str(&format!("pub use {module} as {short};\n"));
            }
        }
        out.push('\n');

        out.push_str("pub mod script_modules {\n");
        for rel in copied {
            let module = module_name_from_rel(rel);
            out.push_str(&format!("    pub use super::{module};\n"));
            out.push_str(&format!("    pub use super::{module}::*;\n"));
        }
        for rel in copied {
            let module = module_name_from_rel(rel);
            let short = module_short_name_from_rel(rel);
            if short == module {
                continue;
            }
            if short_name_counts.get(&short).copied() == Some(1) {
                out.push_str(&format!("    pub use super::{module} as {short};\n"));
            }
        }
        out.push_str("}\n\n");
    }

    let mut script_entries = Vec::<(String, u64)>::with_capacity(registrable.len());
    let mut hashes = HashMap::<u64, String>::new();
    for rel in registrable {
        let module = module_name_from_rel(rel);
        let path = format!("{script_path_prefix}{rel}");
        let hash = perro_ids::string_to_u64(&path);
        if let Some(prev) = hashes.insert(hash, path.clone()) {
            return Err(CompilerError::SceneParse(format!(
                "script hash collision: `{prev}` + `{path}` => {hash}"
            )));
        }
        script_entries.push((module, hash));
    }

    out.push_str(
        "pub static SCRIPT_REGISTRY: &[(u64, ScriptConstructor<RuntimeScriptApi>)] = &[\n",
    );
    for (module, hash) in &script_entries {
        out.push_str(&format!(
            "    ({hash}u64, {module}::perro_create_script as ScriptConstructor<RuntimeScriptApi>),\n"
        ));
    }
    out.push_str("];\n");
    out.push_str(
        "\n#[unsafe(no_mangle)]\n\
/// # Safety\n\
/// Caller pass valid UTF-8 ptr+len pairs for `root_ptr`/`root_len` + `name_ptr`/`name_len`.\n\
/// Pointers stay valid for full call + null ptr disallow.\n\
pub unsafe extern \"C\" fn perro_scripts_set_project_root(\n\
    root_ptr: *const u8,\n\
    root_len: usize,\n\
    name_ptr: *const u8,\n\
    name_len: usize,\n\
) -> bool {\n\
    if root_ptr.is_null() || name_ptr.is_null() {\n\
        return false;\n\
    }\n\
    let root_bytes = unsafe { std::slice::from_raw_parts(root_ptr, root_len) };\n\
    let name_bytes = unsafe { std::slice::from_raw_parts(name_ptr, name_len) };\n\
    let Ok(root) = std::str::from_utf8(root_bytes) else {\n\
        return false;\n\
    };\n\
    let Ok(name) = std::str::from_utf8(name_bytes) else {\n\
        return false;\n\
    };\n\
    perro_api::modules::file::set_project_root_disk(root, name);\n\
    true\n\
}\n",
    );
    out.push_str(
        "\n#[unsafe(no_mangle)]\n\
pub extern \"C\" fn perro_script_registry_len() -> usize {\n\
    SCRIPT_REGISTRY.len()\n\
}\n",
    );
    out.push_str(
        "\n#[allow(improper_ctypes_definitions)]\n\
#[unsafe(no_mangle)]\n\
/// # Safety\n\
/// Caller pass non-null writable ptrs for `path_hash_out` + `ctor_out`.\n\
/// Output ptrs stay valid for full call.\n\
pub unsafe extern \"C\" fn perro_script_registry_get(\n\
    index: usize,\n\
    path_hash_out: *mut u64,\n\
    ctor_out: *mut ScriptConstructor<RuntimeScriptApi>,\n\
) -> bool {\n\
    if path_hash_out.is_null() || ctor_out.is_null() {\n\
        return false;\n\
    }\n\
    let Some((path_hash, ctor)) = SCRIPT_REGISTRY.get(index) else {\n\
        return false;\n\
    };\n\
    unsafe {\n\
        *path_hash_out = *path_hash;\n\
        *ctor_out = *ctor;\n\
    }\n\
    true\n\
}\n",
    );

    write_string_if_changed(&scripts_src.join("lib.rs"), &out).map_err(CompilerError::Io)
}

fn write_string_if_changed(path: &Path, content: &str) -> std::io::Result<bool> {
    if let Ok(existing) = fs::read_to_string(path)
        && existing == content
    {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(true)
}

fn remove_stale_generated_scripts(
    scripts_src: &Path,
    generated_rel_paths: &HashSet<String>,
) -> Result<bool, CompilerError> {
    if !scripts_src.exists() {
        return Ok(false);
    }

    let mut stale = Vec::<PathBuf>::new();
    walk_dir(scripts_src, &mut |path| {
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            return Ok(());
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            return Ok(());
        };
        if !name.ends_with(".gen.rs") {
            return Ok(());
        }
        let Ok(rel) = path.strip_prefix(scripts_src) else {
            return Ok(());
        };
        let rel_norm = rel.to_string_lossy().replace('\\', "/");
        if !generated_rel_paths.contains(&rel_norm) {
            stale.push(path.to_path_buf());
        }
        Ok(())
    })?;

    let stale_len = stale.len();
    for path in stale {
        fs::remove_file(path)?;
    }

    Ok(stale_len > 0)
}
