fn transpile_frontend_script(source: &str, source_include: &str) -> String {
    let debug_methods = methods_debug_enabled();
    let source = ensure_script_allows(source);
    let source_include = escape_str(&normalize_generated_include_path(source_include));
    if source.contains("impl ScriptBehavior") {
        return format!("include!(\"{source_include}\");\n");
    }
    let stripped_source = strip_transpiler_attributes(&source);

    let state_ty = parse_marked_struct_name(&source, "@State")
        .or_else(|| parse_attributed_struct_name(&source, "state"));
    let has_lifecycle_macro = has_script_macro_invocation(&source, "lifecycle");
    let has_methods_macro = has_script_macro_invocation(&source, "methods");
    if state_ty.is_none() && !has_lifecycle_macro && !has_methods_macro {
        return format!("include!(\"{source_include}\");\n");
    }

    let script_ty = parse_marked_struct_name(&source, "@Script")
        .or_else(|| parse_attributed_struct_name(&source, "script"))
        .or_else(|| parse_script_macro_target(&source, "lifecycle"))
        .or_else(|| parse_script_macro_target(&source, "methods"))
        .or_else(|| parse_named_struct(&stripped_source, "Script"))
        .unwrap_or_else(|| "Script".to_string());
    let needs_implicit_script_struct = parse_marked_struct_name(&source, "@Script").is_none()
        && parse_attributed_struct_name(&source, "script").is_none()
        && parse_named_struct(&stripped_source, &script_ty).is_none()
        && !has_lifecycle_macro;
    let script_ctor_expr =
        if needs_implicit_script_struct || is_unit_struct(&stripped_source, &script_ty) {
            script_ty.clone()
        } else {
            format!("<{script_ty} as Default>::default()")
        };
    let state_ty = state_ty.unwrap_or_else(|| "()".to_string());
    let state_ctor_expr = if state_ty == "()" {
        "()".to_string()
    } else {
        format!("<{state_ty} as Default>::default()")
    };

    let has_init = has_nonempty_lifecycle_method(&source, "on_init");
    let has_start = has_nonempty_lifecycle_method(&source, "on_all_init");
    let has_update = has_nonempty_lifecycle_method(&source, "on_update");
    let has_fixed = has_nonempty_lifecycle_method(&source, "on_fixed_update");
    let has_removal = has_nonempty_lifecycle_method(&source, "on_removal");
    let user_methods = parse_inherent_methods(&source, &script_ty);
    if debug_methods {
        let method_names = user_methods
            .iter()
            .map(|m| m.name.as_str())
            .collect::<Vec<_>>()
            .join(", ");
        eprintln!(
            "[perro][methods] source={} script_ty={} methods_found={} [{}]",
            source_include,
            script_ty,
            user_methods.len(),
            method_names
        );
        if user_methods.is_empty() && source.contains("methods!(") {
            eprintln!(
                "[perro][methods][warn] methods! macro exists but zero methods were parsed for source={}",
                source_include
            );
        }
    }
    let state_fields = if state_ty == "()" {
        Vec::new()
    } else {
        parse_struct_fields(&source, &state_ty)
    };
    let exposed_fields = supported_fields(&state_fields);
    let nested_fields = parse_local_nested_fields(&source, &exposed_fields);

    let mut flags = String::from("ScriptFlags::NONE");
    if has_init {
        flags.push_str(" | ScriptFlags::HAS_INIT");
    }
    if has_start {
        flags.push_str(" | ScriptFlags::HAS_ALL_INIT");
    }
    if has_update {
        flags.push_str(" | ScriptFlags::HAS_UPDATE");
    }
    if has_fixed {
        flags.push_str(" | ScriptFlags::HAS_FIXED_UPDATE");
    }
    if has_removal {
        flags.push_str(" | ScriptFlags::HAS_REMOVAL");
    }

    let member_consts = generate_member_consts(&exposed_fields, &nested_fields, &user_methods);
    let state_cast_helpers = generate_state_cast_helpers(&state_ty, &exposed_fields);
    let get_var_body = generate_get_var_body(&exposed_fields, &nested_fields);
    let set_var_match_fn = generate_set_var_match_fn(&state_ty, &exposed_fields, &nested_fields);
    let set_var_body = generate_set_var_body(&exposed_fields);
    let apply_scene_injected_vars_body = generate_apply_scene_injected_vars_body(&exposed_fields);
    let call_method_body = generate_call_method_body(&user_methods);

    let implicit_script_decl = if needs_implicit_script_struct {
        format!("#[derive(Default)]\nstruct {script_ty};\n\n")
    } else {
        String::new()
    };

    format!(
        r#"{implicit_script_decl}include!("{source_include}");

// ---- AUTO-GENERATED by Perro Compiler ----
{member_consts}
{state_cast_helpers}
{set_var_match_fn}

impl<API: ScriptAPI + ?Sized> ScriptBehavior<API> for {script_ty} {{
    fn script_flags(&self) -> ScriptFlags {{
        ScriptFlags::new({flags})
    }}

    fn create_state(&self) -> Box<dyn std::any::Any> {{
        Box::new({state_ctor_expr})
    }}

    fn get_var(&self, state: &dyn std::any::Any, var: ScriptMemberID) -> Variant {{
{get_var_body}
    }}

    fn set_var(&self, state: &mut dyn std::any::Any, var: ScriptMemberID, value: Variant) {{
{set_var_body}
    }}

    fn apply_scene_injected_vars(
        &self,
        state: &mut dyn std::any::Any,
        vars: Vec<(ScriptMemberID, Variant)>,
        resolver: &mut dyn perro_api::variant::SceneVariantResolver,
    ) {{
{apply_scene_injected_vars_body}
    }}

    fn call_method(
        &self,
        method: ScriptMemberID,
        ctx: &mut ScriptContext<'_, API>,
        params: &[Variant],
    ) -> Variant {{
{call_method_body}
    }}
}}

pub(crate) fn perro_create_script() -> *mut dyn ScriptBehavior<crate::RuntimeScriptApi> {{
    let script: Box<dyn ScriptBehavior<crate::RuntimeScriptApi>> =
        Box::new({script_ctor_expr});
    Box::into_raw(script)
}}

#[cfg(feature = "dynamic-scripts")]
#[allow(improper_ctypes_definitions)]
pub(crate) extern "C" fn perro_create_script_dynamic() -> *mut dyn ScriptBehavior<crate::RuntimeScriptApi> {{
    perro_create_script()
}}
"#
    )
}

fn transpiled_exports_script_ctor(transpiled: &str) -> bool {
    transpiled.contains("fn perro_create_script(")
}

fn ensure_script_allows(source: &str) -> String {
    if source.contains("#![allow(unused_imports")
        || source.contains("#![allow(unused_variables")
        || source.contains("#![allow(dead_code")
    {
        return source.to_string();
    }
    format!("#![allow(unused_imports, unused_variables, dead_code)]\n{source}")
}

fn strip_transpiler_attributes(source: &str) -> String {
    let mut out = String::new();
    for line in source.lines() {
        let trimmed = line.trim_start();
        if is_transpiler_attr_line(trimmed) {
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

fn parse_marked_struct_name(source: &str, marker: &str) -> Option<String> {
    let lines: Vec<&str> = source.lines().collect();
    for i in 0..lines.len() {
        let l = lines[i].trim();
        if !(l == format!("///{marker}") || l == format!("//{marker}")) {
            continue;
        }
        for next in lines.iter().skip(i + 1) {
            let n = next.trim();
            if n.is_empty() {
                continue;
            }
            if let Some(name) = parse_struct_name(n) {
                return Some(name);
            }
        }
    }
    None
}

fn has_nonempty_lifecycle_method(source: &str, method_name: &str) -> bool {
    let needle = format!("fn {method_name}(");
    let mut search_from = 0usize;

    while search_from < source.len() {
        let Some(rel) = source[search_from..].find(&needle) else {
            break;
        };
        let fn_start = search_from + rel;
        let Some(body) = extract_method_body_from_fn_start(source, fn_start) else {
            search_from = fn_start + needle.len();
            continue;
        };

        if method_signature_looks_like_lifecycle(source, fn_start, body.start)
            && block_has_non_comment_tokens(&source[body.start + 1..body.end])
        {
            return true;
        }

        search_from = body.end + 1;
    }

    false
}

fn extract_method_body_from_fn_start(
    source: &str,
    fn_start: usize,
) -> Option<std::ops::Range<usize>> {
    let after_fn = &source[fn_start..];
    let sig_open_rel = after_fn.find('(')?;
    let sig_open = fn_start + sig_open_rel;
    let sig_close = find_matching_delim(source, sig_open, '(', ')')?;
    let body_start_rel = source[sig_close + 1..].find('{')?;
    let body_start = sig_close + 1 + body_start_rel;
    let body_end = find_matching_delim(source, body_start, '{', '}')?;
    Some(body_start..body_end)
}

fn method_signature_looks_like_lifecycle(source: &str, fn_start: usize, body_start: usize) -> bool {
    let sig = &source[fn_start..body_start];
    sig.contains("&self") && sig.contains("ScriptContext")
}

fn block_has_non_comment_tokens(block: &str) -> bool {
    let bytes = block.as_bytes();
    let mut i = 0usize;

    while i < bytes.len() {
        let b = bytes[i];
        if b.is_ascii_whitespace() {
            i += 1;
            continue;
        }

        if b == b'/' && i + 1 < bytes.len() {
            let next = bytes[i + 1];
            if next == b'/' {
                i += 2;
                while i < bytes.len() && bytes[i] != b'\n' {
                    i += 1;
                }
                continue;
            }
            if next == b'*' {
                i += 2;
                let mut depth = 1_i32;
                while i + 1 < bytes.len() && depth > 0 {
                    if bytes[i] == b'/' && bytes[i + 1] == b'*' {
                        depth += 1;
                        i += 2;
                    } else if bytes[i] == b'*' && bytes[i + 1] == b'/' {
                        depth -= 1;
                        i += 2;
                    } else {
                        i += 1;
                    }
                }
                continue;
            }
        }

        return true;
    }

    false
}

fn parse_named_struct(source: &str, expected: &str) -> Option<String> {
    for line in source.lines() {
        if let Some(name) = parse_struct_name(line.trim())
            && name == expected
        {
            return Some(name);
        }
    }
    None
}

fn parse_struct_name(line: &str) -> Option<String> {
    let line = line.trim_start_matches("pub ").trim_start();
    if !line.starts_with("struct ") {
        return None;
    }
    let rest = line.trim_start_matches("struct ").trim_start();
    let mut name = String::new();
    for c in rest.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            name.push(c);
        } else {
            break;
        }
    }
    if name.is_empty() { None } else { Some(name) }
}

fn is_unit_struct(source: &str, struct_name: &str) -> bool {
    source.lines().any(|line| {
        let line = line.trim();
        let line = line.trim_start_matches("pub ").trim_start();
        line == format!("struct {struct_name};")
    })
}

#[derive(Clone, Debug)]
struct ScriptField {
    name: String,
    ty: String,
}

#[derive(Clone, Debug)]
struct NestedScriptField {
    member: String,
    access: String,
    ty: String,
}

fn parse_local_nested_fields(source: &str, state_fields: &[ScriptField]) -> Vec<NestedScriptField> {
    let mut local_structs = HashMap::<String, Vec<ScriptField>>::new();
    for line in source.lines() {
        let Some(name) = parse_struct_name(line.trim()) else {
            continue;
        };
        local_structs
            .entry(name.clone())
            .or_insert_with(|| parse_struct_fields(source, &name));
    }

    let mut out = Vec::new();
    for field in state_fields {
        let mut stack = HashSet::new();
        collect_local_nested_fields(
            &local_structs,
            local_type_name(&field.ty),
            &field.name,
            &field.name,
            &mut stack,
            &mut out,
        );
    }
    out
}

fn collect_local_nested_fields(
    local_structs: &HashMap<String, Vec<ScriptField>>,
    ty: Option<&str>,
    member_prefix: &str,
    access_prefix: &str,
    stack: &mut HashSet<String>,
    out: &mut Vec<NestedScriptField>,
) {
    let Some(ty) = ty else {
        return;
    };
    let Some(fields) = local_structs.get(ty) else {
        return;
    };
    if fields.is_empty() || !stack.insert(ty.to_string()) {
        return;
    }

    for field in fields {
        let member = format!("{member_prefix}.{}", field.name);
        let access = format!("{access_prefix}.{}", field.name);
        let child_ty = local_type_name(&field.ty);
        let child_is_local_struct = child_ty
            .and_then(|name| local_structs.get(name))
            .is_some_and(|fields| !fields.is_empty());
        if child_is_local_struct {
            collect_local_nested_fields(
                local_structs,
                child_ty,
                &member,
                &access,
                stack,
                out,
            );
        } else {
            out.push(NestedScriptField {
                member,
                access,
                ty: normalize_type(&field.ty),
            });
        }
    }

    stack.remove(ty);
}

fn local_type_name(ty: &str) -> Option<&str> {
    let ty = ty.trim();
    if ty.is_empty() || ty.contains(['<', '[', '(', '&']) {
        return None;
    }
    ty.rsplit("::").next()
}
