fn write_scripts_lib(
    scripts_src: &Path,
    copied: &[String],
    registrable: &[String],
    script_path_prefix: &str,
) -> Result<bool, CompilerError> {
    let mut out = String::new();
    out.push_str("#![allow(unused_imports, unused_variables, dead_code)]\n");
    out.push_str("// AUTO-GENERATED by Perro Compiler. Do not edit by hand.\n\n");
    out.push_str("use perro_runtime::RuntimeScriptApi;\n");
    out.push_str("use perro_api::scripting::ScriptConstructor;\n");
    out.push_str(
        "#[cfg(feature = \"dynamic-scripts\")]\nuse perro_runtime::SCRIPT_ABI_BUILD_FINGERPRINT;\n",
    );
    out.push_str(
        "#[cfg(feature = \"dynamic-scripts\")]\nuse perro_api::scripting::{DynamicScriptConstructor, ScriptAbiDescriptor, ScriptAbiDescriptorHeader};\n\n",
    );

    for rel in copied {
        let module = module_name_from_rel(rel);
        let generated_rel = generated_script_rel(rel);
        out.push_str(&format!("#[path = \"{generated_rel}\"]\n"));
        out.push_str(&format!("pub mod {module};\n\n"));
    }

    if !copied.is_empty() {
        let mut short_name_counts = BTreeMap::<String, usize>::new();
        for rel in copied {
            let short = module_short_name_from_rel(rel);
            *short_name_counts.entry(short).or_insert(0) += 1;
        }

        for rel in copied {
            let module = module_name_from_rel(rel);
            let short = module_short_name_from_rel(rel);
            if short == module {
                continue;
            }
            if short_name_counts.get(&short).copied() == Some(1) {
                out.push_str(&format!("pub use {module} as {short};\n"));
            }
        }
        out.push('\n');

        out.push_str("pub mod script_modules {\n");
        for rel in copied {
            let module = module_name_from_rel(rel);
            out.push_str(&format!("    pub use super::{module};\n"));
            out.push_str(&format!("    pub use super::{module}::*;\n"));
        }
        for rel in copied {
            let module = module_name_from_rel(rel);
            let short = module_short_name_from_rel(rel);
            if short == module {
                continue;
            }
            if short_name_counts.get(&short).copied() == Some(1) {
                out.push_str(&format!("    pub use super::{module} as {short};\n"));
            }
        }
        out.push_str("}\n\n");
    }

    let mut script_entries = Vec::<(String, u64)>::with_capacity(registrable.len());
    let mut hashes = HashMap::<u64, String>::new();
    for rel in registrable {
        let module = module_name_from_rel(rel);
        let path = format!("{script_path_prefix}{rel}");
        let hash = perro_ids::string_to_u64(&path);
        if let Some(prev) = hashes.insert(hash, path.clone()) {
            return Err(CompilerError::SceneParse(format!(
                "script hash collision: `{prev}` + `{path}` => {hash}"
            )));
        }
        script_entries.push((module, hash));
    }
    script_entries.sort_unstable_by_key(|(_, hash)| *hash);

    out.push_str(
        "pub static SCRIPT_REGISTRY: &[(u64, ScriptConstructor<RuntimeScriptApi>)] = &[\n",
    );
    for (module, hash) in &script_entries {
        out.push_str(&format!(
            "    ({hash}u64, {module}::perro_create_script as ScriptConstructor<RuntimeScriptApi>),\n"
        ));
    }
    out.push_str("];\n");
    out.push_str(
        "\n#[cfg(feature = \"dynamic-scripts\")]\n\
static DYNAMIC_SCRIPT_REGISTRY: &[(u64, DynamicScriptConstructor<RuntimeScriptApi>)] = &[\n",
    );
    for (module, hash) in &script_entries {
        out.push_str(&format!(
            "    ({hash}u64, {module}::perro_create_script_dynamic as DynamicScriptConstructor<RuntimeScriptApi>),\n"
        ));
    }
    out.push_str("];\n");
    out.push_str(
        "\n#[cfg(feature = \"dynamic-scripts\")]\n\
static PERRO_SCRIPT_ABI_DESCRIPTOR_V2: ScriptAbiDescriptor =\n\
    ScriptAbiDescriptor::v2(SCRIPT_ABI_BUILD_FINGERPRINT);\n\
\n\
#[cfg(feature = \"dynamic-scripts\")]\n\
#[unsafe(no_mangle)]\n\
pub extern \"C\" fn perro_script_abi_descriptor_v2() -> *const ScriptAbiDescriptorHeader {\n\
    std::ptr::addr_of!(PERRO_SCRIPT_ABI_DESCRIPTOR_V2).cast()\n\
}\n",
    );
    out.push_str(
        "\n#[cfg(feature = \"dynamic-scripts\")]\n\
#[unsafe(no_mangle)]\n\
/// # Safety\n\
/// Caller pass valid UTF-8 ptr+len pairs for `root_ptr`/`root_len` + `name_ptr`/`name_len`.\n\
/// Pointers stay valid for full call + null ptr disallow.\n\
pub unsafe extern \"C\" fn perro_scripts_set_project_root(\n\
    root_ptr: *const u8,\n\
    root_len: usize,\n\
    name_ptr: *const u8,\n\
    name_len: usize,\n\
) -> bool {\n\
    if root_ptr.is_null() || name_ptr.is_null() {\n\
        return false;\n\
    }\n\
    // SAFETY: Caller contract + null checks ensure ptr/len pairs cover valid byte slices.\n\
    let root_bytes = unsafe { std::slice::from_raw_parts(root_ptr, root_len) };\n\
    // SAFETY: Caller contract + null checks ensure ptr/len pairs cover valid byte slices.\n\
    let name_bytes = unsafe { std::slice::from_raw_parts(name_ptr, name_len) };\n\
    let Ok(root) = std::str::from_utf8(root_bytes) else {\n\
        return false;\n\
    };\n\
    let Ok(name) = std::str::from_utf8(name_bytes) else {\n\
        return false;\n\
    };\n\
    perro_api::modules::file::set_project_root_disk(root, name);\n\
    true\n\
}\n",
    );
    out.push_str(
        "\n#[cfg(feature = \"dynamic-scripts\")]\n\
#[unsafe(no_mangle)]\n\
pub extern \"C\" fn perro_script_registry_len() -> usize {\n\
    DYNAMIC_SCRIPT_REGISTRY.len()\n\
}\n",
    );
    out.push_str(
        "\n#[cfg(feature = \"dynamic-scripts\")]\n\
#[allow(improper_ctypes_definitions)]\n\
#[unsafe(no_mangle)]\n\
/// # Safety\n\
/// Caller pass non-null writable ptrs for `path_hash_out` + `ctor_out`.\n\
/// Output ptrs stay valid for full call.\n\
pub unsafe extern \"C\" fn perro_script_registry_get(\n\
    index: usize,\n\
    path_hash_out: *mut u64,\n\
    ctor_out: *mut DynamicScriptConstructor<RuntimeScriptApi>,\n\
) -> bool {\n\
    if path_hash_out.is_null() || ctor_out.is_null() {\n\
        return false;\n\
    }\n\
    let Some((path_hash, ctor)) = DYNAMIC_SCRIPT_REGISTRY.get(index) else {\n\
        return false;\n\
    };\n\
    // SAFETY: Null checks above ensure output ptrs are writable for this call.\n\
    unsafe {\n\
        *path_hash_out = *path_hash;\n\
        *ctor_out = *ctor;\n\
    }\n\
    true\n\
}\n",
    );

    write_string_if_changed(&scripts_src.join("lib.rs"), &out).map_err(CompilerError::Io)
}

fn write_string_if_changed(path: &Path, content: &str) -> std::io::Result<bool> {
    if file_text_matches(path, content)? {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let _guard = WriteLock::acquire(path)?;
    if file_text_matches(path, content)? {
        return Ok(false);
    }
    fs::write(path, content)?;
    Ok(true)
}

fn file_text_matches(path: &Path, content: &str) -> std::io::Result<bool> {
    match fs::read_to_string(path) {
        Ok(existing) => Ok(existing == content),
        Err(err)
            if matches!(
                err.kind(),
                std::io::ErrorKind::NotFound | std::io::ErrorKind::InvalidData
            ) =>
        {
            Ok(false)
        }
        Err(err) => Err(err),
    }
}

struct WriteLock {
    path: PathBuf,
}

impl WriteLock {
    fn acquire(path: &Path) -> std::io::Result<Self> {
        Self::acquire_with_policy(
            path,
            std::time::Duration::from_secs(10),
            std::time::Duration::from_secs(60),
        )
    }

    fn acquire_with_policy(
        path: &Path,
        wait_timeout: std::time::Duration,
        stale_after: std::time::Duration,
    ) -> std::io::Result<Self> {
        let lock_path = path.with_extension("write-lock");
        let started = std::time::Instant::now();
        loop {
            match fs::create_dir(&lock_path) {
                Ok(()) => return Ok(Self { path: lock_path }),
                Err(err) if err.kind() == std::io::ErrorKind::AlreadyExists => {
                    if Self::reclaim_if_stale(&lock_path, stale_after)? {
                        continue;
                    }
                    if started.elapsed() >= wait_timeout {
                        return Err(std::io::Error::new(
                            std::io::ErrorKind::TimedOut,
                            format!(
                                "timed out waiting for generated-script write lock: {}",
                                lock_path.display()
                            ),
                        ));
                    }
                    std::thread::sleep(std::time::Duration::from_millis(10));
                }
                Err(err) => return Err(err),
            }
        }
    }

    fn reclaim_if_stale(
        lock_path: &Path,
        stale_after: std::time::Duration,
    ) -> std::io::Result<bool> {
        let modified = match fs::metadata(lock_path).and_then(|metadata| metadata.modified()) {
            Ok(modified) => modified,
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(true),
            Err(err) => return Err(err),
        };
        if modified.elapsed().unwrap_or_default() < stale_after {
            return Ok(false);
        }

        let unique = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let stale_path = lock_path.with_extension(format!(
            "write-lock.stale-{}-{unique}",
            std::process::id()
        ));
        match fs::rename(lock_path, &stale_path) {
            Ok(()) => {
                fs::remove_dir_all(stale_path)?;
                Ok(true)
            }
            Err(err)
                if matches!(
                    err.kind(),
                    std::io::ErrorKind::NotFound | std::io::ErrorKind::AlreadyExists
                ) =>
            {
                Ok(true)
            }
            Err(err) => Err(err),
        }
    }
}

impl Drop for WriteLock {
    fn drop(&mut self) {
        let _ = fs::remove_dir(&self.path);
    }
}

fn remove_stale_generated_scripts(
    scripts_src: &Path,
    generated_rel_paths: &HashSet<String>,
) -> Result<bool, CompilerError> {
    if !scripts_src.exists() {
        return Ok(false);
    }

    let mut stale = Vec::<PathBuf>::new();
    walk_dir(scripts_src, &mut |path| {
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            return Ok(());
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            return Ok(());
        };
        if !name.ends_with(".gen.rs") {
            return Ok(());
        }
        let Ok(rel) = path.strip_prefix(scripts_src) else {
            return Ok(());
        };
        let rel_norm = rel.to_string_lossy().replace('\\', "/");
        if !generated_rel_paths.contains(&rel_norm) {
            stale.push(path.to_path_buf());
        }
        Ok(())
    })?;

    let stale_len = stale.len();
    for path in stale {
        fs::remove_file(path)?;
    }

    Ok(stale_len > 0)
}
