// Auto-generated by Perro compiler
const PART1: [u8; 8] = [0x76, 0xFC, 0x32, 0x56, 0xCB, 0x10, 0x8E, 0xDB];
const PART2: [u8; 8] = [0xC7, 0x19, 0x89, 0x6F, 0xB6, 0x3C, 0x18, 0xE7];
const PART3: [u8; 8] = [0xF5, 0x31, 0x1B, 0x66, 0x11, 0x52, 0xCB, 0xDB];
const PART4: [u8; 8] = [0x03, 0x62, 0x3C, 0xAF, 0x2C, 0x9B, 0xF5, 0x40];
const CONST1: u32 = 0x1FA60C2A;
const CONST2: u32 = 0x4D18393B;
const CONST3: u32 = 0x83592807;
const CONST4: u32 = 0x26EF8152;
const CONST5: u32 = 0x1F08AD39;
const CONST6: u32 = 0x56B9D234;
const CONST7: u32 = 0x634A6376;
const CONST8: u32 = 0x49B41220;
pub fn get_aes_key() -> [u8; 32] {
    let mut key = [0u8; 32];
    for i in 0..8 {
        key[i]      = PART1[i] ^ (((CONST5 as u8) ^ (CONST8 as u8)));
        key[i + 8]  = PART2[i] ^ (((CONST1 as u8).wrapping_sub(CONST2 as u8)));
        key[i + 16] = PART3[i] ^ (((CONST6 as u8).wrapping_add(CONST1 as u8)));
        key[i + 24] = PART4[i] ^ (((CONST6 as u8).wrapping_sub(CONST3 as u8)));
    }
    key
}
