[package]
name = "perro_render_bridge"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bytemuck = { version = "1.24.0", features = ["derive"] }
perro_ids.workspace = true
perro_asset_formats.workspace = true
perro_particle_math.workspace = true
perro_structs.workspace = true
perro_ui.workspace = true
